### ISSUE TITLE
authentication question

### ISSUE THREAD

**Issue by phand00** [Badgerati/Pode#1005]
Hi,

I red the Question:  authentication question #931 and it's really helpfull
I tried it and it works as you said, both auth mechanism are applied.

But what I want to achieve is a bit different.
I want all /api* routes to get authenticate with Bearer
But for one subroute (/api/route1/item1 for example), I would like to add basic auth as an alternative, but do not want both auth mechanism to be applied/required. Is it doable with Pode?

Thanks

**Comment by Badgerati** [comment]
Hi @phand00,

So basically either auth X or auth Y, and if one succeeds invoke the route? That sounds like #588  😄 

At the moment it's not possible to have 2 authentication methods in a `or` scenario - unless you write a custom auth scheme for it. The idea behind #588 is to make this scenario possible.

**Comment by phand00** [comment]
ok thanks.
