### ISSUE TITLE
Hot reloading isn't working correctly in Pode 2.7.1 | Method invocation failed because [System.Collections.Hashtable+KeyCollection] does not contain a method named 'Clone'.

### ISSUE THREAD

**Issue by pcgeek86** [Badgerati/Pode#1008]
### Describe the Bug

When I attempt to make a change to my application, and leverage automatic / hot reloading in Pode, I get an error message.

```
PS /workspaces/pode> . "/workspaces/pode/pode.ps1"
Listening on the following 1 endpoint(s) [1 thread(s)]:
        - http://localhost:8080/
Restarting server...InvalidOperation: /home/codespace/.local/share/powershell/Modules/Pode/2.7.1/Private/Server.ps1:176:9
Line |
 176 |          $PodeContext.Server.Verbs.Keys.Clone() | ForEach-Object {
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Method invocation failed because [System.Collections.Hashtable+KeyCollection] does not contain a method named 'Clone'.
```

### Steps To Reproduce

1. Create GitHub Actions Codespace
2. Install PowerShell
3. Install Pode

#### Pode.ps1

```powershell
Start-PodeServer -ScriptBlock {
  Add-PodeEndpoint -Address 0.0.0.0 -Port 8080 -Protocol Http

  Add-PodeRoute -Method Get -Path / -ScriptBlock {
    Write-PodeHtmlResponse -Value '<h1>Hello!</h1>'
  }
}
```

#### server.psd1 
```powershell
@{
  Server = @{
    FileMonitor = @{
      Enable = $true
      Include = @('*.ps1')
    }
  }
}
```

### Expected Behavior

Automatic reloading works

### Screenshots
![image](https://user-images.githubusercontent.com/466713/188293865-397c22a0-7f7d-441f-89c9-4594f010ea99.png)

### Platform
 - OS: [e.g. iOS, Windows] GitHub Codespaces Ubuntu 20.04
 - Browser: [e.g. Chrome, Safari]
 - Versions:
   - Pode: [e.g. Pode v1.7.3] 2.7.1
   - PowerShell: [e.g. PS6.2.1] 7.2.6

**Comment by Badgerati** [comment]
Hi @pcgeek86,

This one I'm aware of, also reported here #1001
