### ISSUE TITLE
Acessing request body using Custom logging method

### ISSUE THREAD

**Issue by Mxrcon** [Badgerati/Pode#1012]
### Question

Hey there :wave:, I'm currently tweaking a custom log for my API and I've explored the raw hash-table provided by pode for a custom log on terminal.

I've saw the work done on https://github.com/Badgerati/Pode/issues/33,  and it appears to be possible to access all proprieties on the request, but I'm not sure how to do it properly. 

This is my current code:
```powershell
  $method = New-PodeLoggingMethod -Custom -ScriptBlock {
       param($item)
        "[REQUEST] HOST: $($item.Host) - STATUS: $($item.Response.StatusCode) - METHOD: $($item.Request.Method) - PROTOCOL: $($item.Request.Protocol) - AGENT: $($item.Request.Agent)" | Out-Default
    }
   
   $method | Enable-PodeRequestLogging -Raw

``` 

What I'm trying to do is Access one of the parameters on the request body, Is that possible? I'd like to do something like `$($item.Request.Body.Channel)` to access the Channel parameter form the request body. 

Thank you for you attention and the overall development of PODE, it has been very useful on my projects.

**Comment by Badgerati** [comment]
Hey @Mxrcon 👋 

At the moment it's unfortunately not possible, however I love the idea of being able to define custom headers for the request logging - like you can in IIS for example. (maybe even support for custom formats for the log lines outputted 🤔)

The only way to achieve it currently would be: define a custom logger, via `Add-PodeLogger`, and the inbuilt Terminal method which receives the `$WebEvent` and then build the string there and return it. You can then define an `Add-PodeEndware` which just calls `Write-PodeLog` and passes the `$WebEvent`. Something like:

```powershell
New-PodeLoggingMethod -Terminal | Add-PodeLogger -Name ReqLogging -ScriptBlock {
    param($item)

    $_host = $item.Request.RemoteEndPoint.Address.IPAddressToString
    $_code = $item.Response.StatusCode
    $_method = $item.Request.HttpMethod.ToUpperInvariant()
    $_proto = "HTTP/$($item.Request.ProtocolVersion)"
    $_agent = $item.Request.UserAgent

    # i'm assuming "Channel" is a payload value?
    $_channel - $item.Data['Channel']

    return "[REQUEST] HOST: $($_host) - STATUS: $($_code) - METHOD: $($_method) - PROTOCOL: $($_proto) - AGENT: $($_agent) - CHANNEL: $($_channel)"
}

Add-PodeEndware -ScriptBlock {
    Write-PodeLog -Name ReqLogging -InputObject $WebEvent
}
```

**Comment by Mxrcon** [comment]
Thank you @Badgerati That's Exactly what I'm looking for and It will fix my current problem. I'll try to implement that on my API.

**Comment by github-throwaway** [comment]
@Badgerati Is this available with an inbuilt command by now? Or do I still need to build my own custom logger? I would like to write this to file ideally :)
