### ISSUE TITLE
Server will not start if failing to load modules

### ISSUE THREAD

**Issue by madsaune** [Badgerati/Pode#1013]
### Describe the Bug
I've been using oh-my-posh for a while and today I wanted to try out Pode. When I try to start the pode server (`pode start`) it will throw an exception because there is a module it cannot load.

In my case, I found out that this was caused by oh-my-posh dynamically creating a module called "[oh-my-posh-core](https://github.com/JanDeDobbeleer/oh-my-posh/blob/348cacc86056b751261e88ecb019d0a300ee207d/src/shell/scripts/omp.ps1)". The module is listed when running `Get-Module`, but the path reported does not exist and is a guid that is new for each session.

```
PS> (Get-Module -Name oh-my-posh-core).Path
/Users/aa/3360407f-4100-4347-986d-002902c38c87
```

This can be fixed by changing `-ErrorAction Stop` to `-ErrorAction SilentlyContinue` in [src/Private/Helpers.ps1](https://github.com/Badgerati/Pode/blob/5cb542bfdb75c0feaed98ec3131539b6ea1da922/src/Private/Helpers.ps1#L912) on line 912.

Is there a reason you want to use `-ErrorAction Stop` when loading other modules in Pode?

### Steps To Reproduce
1. Use `oh-my-posh` to customize prompt in powershell
2. Create a basic Pode server from docs (`server.ps1`)
3. Run `pode start`

### Platform
 - OS: MacOS 12.6
 - Browser: N/A
 - Versions:
   - Pode: 2.7.1
   - PowerShell: PS7.2.6

### Additional Context

Thrown error:

```pwsh
Import-Module: /Users/aa/.local/share/powershell/Modules/Pode/2.7.1/Private/Helpers.ps1:913
Line |
 913 |  …     $null = Import-Module $path -DisableNameChecking -Scope Global -E …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The specified module '/Users/aa/3360407f-4100-4347-986d-002902c38c87' was not loaded because no valid module file was found in any module directory.

at Import-PodeModules, /Users/aa/.local/share/powershell/Modules/Pode/2.7.1/Private/Helpers.ps1: line 913
at Open-PodeRunspace, /Users/aa/.local/share/powershell/Modules/Pode/2.7.1/Private/Helpers.ps1: line 603
at <ScriptBlock>, <No file>: line 1

Import-Module: /Users/aa/.local/share/powershell/Modules/Pode/2.7.1/Private/Helpers.ps1:913
Line |
 913 |  …     $null = Import-Module $path -DisableNameChecking -Scope Global -E …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The specified module '/Users/aa/3360407f-4100-4347-986d-002902c38c87' was not loaded because no valid module file was found in any module directory.

at Import-PodeModules, /Users/aa/.local/share/powershell/Modules/Pode/2.7.1/Private/Helpers.ps1: line 913
at Open-PodeRunspace, /Users/aa/.local/share/powershell/Modules/Pode/2.7.1/Private/Helpers.ps1: line 603
at <ScriptBlock>, <No file>: line 1
ParentContainsErrorRecordException: /Users/aa/.local/share/powershell/Modules/Pode/2.7.1/Private/Helpers.ps1:723
Line |
 723 |          throw $_.Exception
     |          ~~~~~~~~~~~~~~~~~~
     | Main runspace failed to load: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module
     | '/Users/aa/3360407f-4100-4347-986d-002902c38c87' was not loaded because no valid module file was found in any module directory.
```

**Comment by Badgerati** [comment]
Hi @madsaune,

The `-ErrorAction Stop` is needed so that if there's a module that's needed for the running of Pode routes, Pode can stop immediately when importing the other modules, and inform you quickly rather than much later on - or if some runspaces do import a module successfully, but others don't.

You can disable the loading of other modules: https://badgerati.github.io/Pode/Tutorials/Scoping/#disable, or keep it enabled but specify that you only want Pode to import specifically exported modules rather than the default of everything.

**Comment by madsaune** [comment]
Ah, I see!

I probably should have read the documentation more carefully. I didn't know you could disable autoloading. It works like a charm now.

Thank you for your time answering my issue and the work you've put into Pode. It's an awesome Powershell module!
