### ISSUE TITLE
how to understand this

### ISSUE THREAD

**Issue by ericxin1982** [Badgerati/Pode#1017]
(https://github.com/Badgerati/Pode/blob/develop/examples/web-funcs-to-routes.ps1)

Hi @Badgerati 

Like this, if I have custom command for the route, is it possible?
And like this, how to invoke this api from client by http protocol?

Thanks
Eric Xin

**Comment by Badgerati** [comment]
Hi @ericxin1982,

You can find examples in the docs here: https://badgerati.github.io/Pode/Tutorials/Routes/Utilities/AutomaticFunctionsAndModules/ :)

**Comment by ericxin1982** [comment]
Thanks so much!
