### ISSUE TITLE
Create routes "dynamically" in foreach loop

### ISSUE THREAD

**Issue by SeriousMikeDE** [Badgerati/Pode#1022]
Hello everyone,

I'm setting up Pode to have a web interface to call PowerShell scripts. The usecases vary from Jira executing AD scripts to Jenkins to copy files from a to b.

I expect the usecases to grow enormously when my colleagues understand the potential. Therefore I'd like to make it easy to add new scripts/pages/routes.

Has anyone experimented with this?

I'm thinking of dropping a script in a subfolder as well as a script containing the ScriptBlock for Add-PodeRoute

Additionally some "config file" i.e. JSON which lists all routes, the name of the page, AD groups/users which are allowed to run the script.

In server.ps1 I'd only have the general stuff like port, certificate, etc. and a foreach loop which walks through the JSON and does Add-PodeRoute for each.

Any better idea, feedback, etc? Do you think it's possible like that?

Greetings
Mike

PS: Epic project!

**Comment by RobinBeismann** [comment]
Check #964, there I'm basically doing exactly this, just without an additional JSON.

**Comment by SeriousMikeDE** [comment]
Hey @RobinBeismann 

Thanks for the hint. Your setup looks much more complicated than my idea 😂

I'll give it a try. Maybe I can skip the JSON and put the parameters in the helper script directly (so first it's called with some parameter to return its requirements which are then put in the Add-PodeRoute command to call the script)

**Comment by jbaechtelMT** [comment]
Hey **SeriousMikeDE** - I basically had the same use case needs.  When I was first learning Pode I didn't like how many times I had to go back and forth to the documentation/examples trying to decide what nested inside what other elements and what where the parameters for each element.  My goals were to design our site(s) to be easy for others that come after me to easily understand and trying to help keep them from having to repeat my learning curve pains.

So I built our site "configuration" into a JSON format stored in a file.  Then I wrote our Server.ps1 script to load/execute the needed "elements" from the JSON config.  It is not fully finished (where does the time go?) but it does function for:  **Endpoints**; **Routes**; **Logging**; & **Sessions**.

You could use the "**File Change**" monitoring method of **Restart-PodeServer** command to load your new scripts; routes; etc.

My current "demo" files loads 3 routes (**Ping**; **Hello**; **Restart**) from the JSON config file to give you a couple of examples to follow.

I haven't fully "adopted" the JSON format concept because of its' inability to support comments (I like a lot of comments so others know what is happening).  On day I will adopt another format which does allow comments and convert over to that.

If you (or others) contact me at **BaechtelMT1@gmail.com** I will provide my JSON config and Server.ps1 files.

P.S. I also have scripts for **Jira**; **Jenkins**; and **several other** APIs that I call as **Pode Routes** if you are interested.  **Glad to share**!

**Comment by jbaechtelMT** [comment]
Config.JSON:


{
	"Modules":{

		"Pode":{
			"MaximumVersion":"2.99.99",
			"Force":"True"
		},

		"Pode.Web":{
			"MaximumVersion":"",
			"Force":"True"
		}
	},

	"Start-PodeServer":{

		"Arguments":{
			"Browse":false,
			"CurrentPath":false,
			"DisableTermination":false,
			"EnablePool":false,
			"FilePath":false,
			"Interval":0,
			"ListenerType":false,
			"Name":"default",
			"Quiet":false,
			"Request":false,
			"RootPath":false,
			"ScriptBlock":false,
			"ServerlessType":false,
			"StatusPageExceptions":"Show",
			"Threads":1
		},

		"New-PodeLoggingMethod":{

			"Arguments":{
				"ArgumentList":false,
				"Batch":10,
				"BatchTimeout":5,
				"Custom":false,
				"EventID":false,
				"EventLogName":false,
				"EventViewer":false,
				"File":false,
				"MaxDays":false,
				"MaxSize":false,
				"Name":false,
				"Path":false,
				"ScriptBlock":false,
				"Source":false,
				"Terminal":"True"
			}
		},

		"Enable-PodeSessionMiddleware":{

			"Arguments":{
				"Duration":28800,
				"Extend":"True",
				"Generator":false,
				"HttpOnly":false,
				"Name":false,
				"Secret":"podeSecret",
				"Secure":false,
				"Storage":false,
				"Strict":false,
				"UseHeaders":false
			}
		},

		"Add-PodeEndpoint":{

			"local":{

				"Arguments":{
					"Address":"127.0.0.1",
					"AllowClientCertificate":false,
					"Certificate":false,
					"CertificateKey":false,
					"CertificateName":false,
					"CertificatePassword":false,
					"CertificateStoreLocation":false,
					"CertificateStoreName":false,
					"CertificateThumbprint":false,
					"Default":"True",
					"Description":"Local Endpoint",
					"Force":false,
					"Hostname":false,
					"LookupHostname":false,
					"Name":"local",
					"PassThru":false,
					"Port":8080,
					"Protocol":"Http",
					"RedirectTo":false,
					"SelfSigned":false,
					"X509Certificate":false
				},

				"Set-PodeViewEngine":{

					"Arguments":{
						"Type":"Pode"
					}
				},

				"Enable-PodeSessionMiddleware":{

					"Arguments":{
						"Duration":120,
						"Extend":"True"
					}
				},

				"Routes":{

					"GET:/ping":{

						"Arguments":{
							"ArgumentList":false,
							"Authentication":false,
							"ContentType":false,
							"EndpointName":"local",
							"ErrorContentType":false,
							"FilePath":false,
							"Login":false,
							"Logout":false,
							"Method":"Get",
							"Middleware":false,
							"PassThru":false,
							"Path":"/ping",
							"ScriptBlock":"Write-PodeJsonResponse -Value @{ 'value' = 'pong'; }",
							"TransferEncoding":false
						}
					},

					"GET:/hello":{

						"Arguments":{
							"ArgumentList":false,
							"Authentication":false,
							"ContentType":false,
							"EndpointName":"local",
							"ErrorContentType":false,
							"FilePath":false,
							"Login":false,
							"Logout":false,
							"Method":"Get",
							"Middleware":false,
							"PassThru":false,
							"Path":"/hello",
							"ScriptBlock":"Write-PodeJsonResponse -Value @{ 'value' = 'Hi!  Glad to hear from you...'; }",
							"TransferEncoding":false
						}
					},

					"GET:/restart":{

						"Arguments":{
							"ArgumentList":false,
							"Authentication":false,
							"ContentType":false,
							"EndpointName":"local",
							"ErrorContentType":false,
							"FilePath":false,
							"Login":false,
							"Logout":false,
							"Method":"Get",
							"Middleware":false,
							"PassThru":false,
							"Path":"/restart",
							"ScriptBlock":"Write-PodeJsonResponse -Value @{'response' = 'Restarting Pode Server!'}; Restart-PodeServer",
							"TransferEncoding":false
						}
					}
				}
			}
		},

		"Show-PodeGui":{
			"Arguments":{
				"EndpointName":false,
				"Height":false,
				"HideFromTaskbar":false,
				"Icon":false,
				"ResizeMode":false,
				"Title":"Pode GUI",
				"Width":false,
				"WindowState":false,
				"WindowStyle":false
			}
		}		
	}
}

**Comment by jbaechtelMT** [comment]
Server.ps1:

CLS
# Pode Server Start-up Script (From config.json)

$Version = "3.10-14-2022"									     					# Current Script Version Number

#region Version History
<#

Version 1.01-26-2022	Joe Baechtel - Original coding.

Version 3.03-23-2022	Joe Baechtel - Added "Auto" theme (user's system default) as a selection.

Version 3.10-03-2022	Joe Baechtel - Split out code sections to Code folder.

Version 3.10-14-2022	Joe Baechtel - Split out Load-PodeWebHomePageCode code section to Code folder.

#>
#endregion Version History

#region Set Processing Flags / Customize Script Variables
	#region Set $Debug Flags
	$Invocation = (Get-Variable MyInvocation).Value
	$ScriptPath = Split-Path $Invocation.MyCommand.Path
	$SplitScriptPath = $ScriptPath.Split('\')
	#endregion Set $Debug Flags

	#region Customize Script Variables
	$podeLocation = $ScriptPath														# Get Pode Installation Location
	#endregion Customize Script Variables
#endregion Set Processing Flags / Customize Script Variables

#region Set Up Functions
	#region Build-Command
	Function Build-Command {
		#region Param
		Param	([Parameter(Mandatory=$false, ValueFromPipelineByPropertyName=$true)][alias("command")]
					$PodeCommand,													# Pode Command to Execute
				[Parameter(Mandatory=$false, ValueFromPipelineByPropertyName=$true)][alias("arguments")]
					[HashTable]$PodeArguments)										# Pode Command Arguments
		#endregion Param

		#region Begin
		Begin	{If (($PodeCommand -is [string]) -and $PodeCommand.Length -ge 1) {
				} Else {[hashtable]$PodeCommand = [ordered]@{}}}
		#endregion Begin

		#region Process
		Process	{ForEach ($PodeArgument in $PodeArguments.GetEnumerator()) {
					$key = $PodeArgument.Key; $val = $PodeArgument.Value
					If (($key -eq "ScriptBlock") -and ($val -ne $false)) {				# ScriptBlock?
						$val = [Scriptblock]::Create($val)
						If ($PodeCommand -is [string]) {$PodeCommand = $PodeCommand + " -ScriptBlock {$($val)}"
						} Else {$PodeCommand.Add("ScriptBlock",$val)}
					} Else {If ($PodeCommand -is [string]) {
								If ($val -eq "True") {$PodeCommand = $PodeCommand + ' -' + $key
								} ElseIf ($val -eq "False") {$PodeCommand = $PodeCommand + ' -' + $key + ':$false'
								} ElseIf ($val -eq $false) {
								} Else {$PodeCommand = $PodeCommand + ' -' + $key
									If ($val -is [string]) {$PodeCommand = $PodeCommand + " '$($val)'"
									} Else {$PodeCommand = $PodeCommand + " $($val)"}}
							} Else {If ($val -eq "True") {$PodeCommand.Add($key,$true)
									} ElseIf ($val -eq "False") {$PodeCommand.Add($key,$false)
									} ElseIf ($val -eq $false) {
									} Else {$PodeCommand.Add($key,$val)}}}}}
		#endregion Process

		#region End
		End		{Return $PodeCommand}
		#endregion End
	}    
	#endregion Build-Command

     #region ConvertTo-HashtableFromPsCustomObject
	<#
	.Synopsis
		Converts PsCustomObject into an [ordered]Hashtable.

	.NOTES     
	    Name: 		ConvertTo-HashtableFromPsCustomObject  
	    Author: 		Joe Baechtel   
	    DateCreated: 	3Febuary2022

	.INPUT PARMS
		psCustomObject		REQUIRED		psCustomObject to convert to [ordered]HashTable

		[ref]HT			Optional		[ref] pointer to an existing [ordered]HashTable.  If not provided, one will be created and returned.

	.RETURNS
		Returns/Updates an [ordered]Hashtable.

	.EXAMPLES
		$config = [ordered]@{}
		[Void](ConvertTo-HashtableFromPsCustomObject -psCustomObject $ConfigJSON -Encoding UTF8 -Raw | ConvertFrom-Json) -HashTable ([ref]$config))

	#>

	###########################################################
	#                 Version and History                     #
	###########################################################
	#region Version History
	<#

	Version 2.02-03-2022	Joe Baechtel - Initial coding/conversion to Included Module.

	#>
	#endregion Version History

	     Function ConvertTo-HashtableFromPsCustomObject {
	          #region Param
	          Param	([Parameter(Mandatory=$true,ValueFromPipeline=$true,ValueFromPipelineByPropertyName=$true,Position=0)][alias("object")]
	                        [object]$psCustomObject,
					[Parameter(Mandatory=$false,ValueFromPipeline=$true,ValueFromPipelineByPropertyName=$true,Position=1)][alias("hashtable")]
	                        [ref]$HT)
	          #endregion Param

	          #region Begin
	          Begin	{Write-Verbose "[Start]:: ConvertTo-HashtableFromPsCustomObject"
					$hash = [ordered]@{}											# Prepare HashTable
					$HT_Stack = New-Object System.Collections.Stack						# Build Hashtable Pointer Stack
					$PS_Stack = New-Object System.Collections.Stack						# Build PScustomObject Pointer Stack
					$Level_Stack = New-Object System.Collections.Stack					# Build Nested Level Stack
					$HT_Stack.Push($hash)											# Save Current HashTable
					$PS_Stack.Push($psCustomObject)}									# Save Current PScustomObject Pointer
	          #endregion Begin

	          #region Process
	          Process   {Do	{$PS_Stack.Peek().PSObject.Properties | ForEach-Object {
							If ($_.Value -is [System.Management.Automation.PSCustomObject]) {	# PScustomObject?
								If (!$hash.Item($_.Name)) {$hash.Add($_.Name,[ordered]@{})}	# Yes - New Hashtable Level
								$hash = $hash.Item($_.Name)							# Save New Hashtable Level
								$HT_Stack.Push($hash)								# Save Current HashTable
								$PS_Stack.Push(($PS_Stack.Peek())."$($_.Name)")			# Save Current PScustomObject Pointer
								$Level_Stack.Push($_.Name)							# Save Nested Level Name for Clean-up
								Continue
							} Else {$hash = $HT_Stack.Peek()							# Get Current Hashtable
								If (!$hash.Item($_.Name)) {$hash.Add($_.Name,$_.Value)}	# Save Name/Value Key Pair
								$psCustomObject = $PS_Stack.Peek()						# Get Current PScustomObject Pointer
								$psCustomObject.PSObject.properties.remove("$($_.Name)")	# Dump Processed Object
								If ($PS_Stack.Count -gt 0) {[void]$PS_Stack.Pop()}		# Reposition PScustomObject Pointer
								$PS_Stack.Push($psCustomObject)}}						# Save Current PScustomObject Pointer
						If ($HT_Stack.Count -gt 1) {[void]$HT_Stack.Pop()					# Clean-up on Aisle 4
							$hash = $HT_Stack.Peek()}								# Get Current Hashtable Level
						If ($PS_Stack.Count -gt 0) {[void]$PS_Stack.Pop()}				# Reposition PScustomObject Pointer
						If ($Level_Stack -gt 0) {$CleanUpPScustomObject = $Level_Stack.Pop()	# Need to Cleanup?
							$psCustomObject = $PS_Stack.Peek()							# Get PScustomObject Pointer
							$psCustomObject.PSObject.properties.remove("$($CleanUpPScustomObject)")	# Yes - Dump Processed Object
							If ($PS_Stack.Count -gt 0) {$PS_Stack.Pop()}					# Reposition PScustomObject Pointer
							$PS_Stack.Push($psCustomObject)							# Save Current PScustomObject Pointer
							$CleanUpPScustomObject = $null}							# Reset Switch
						} While ($PS_Stack.Count -gt 0)}
	          #endregion Process

	          #region End
	          End		{Write-Verbose "[Exit]:: ConvertTo-HashtableFromPsCustomObject"
					If ($HT) {$HT.Value = $hash
					} Else {Return $hash}; Return}
	          #endregion End
	     }
	#endregion ConvertTo-HashtableFromPsCustomObject

     #region Process-PodeCommands
     Function Process-PodeCommands {
          #region Param
          Param	([Parameter(Mandatory=$true,ValueFromPipeline=$true,ValueFromPipelineByPropertyName=$true,Position=0)][alias("commands","EndpointCommands")]
                        [ref]$PodeCommands)
          #endregion Param

          #region Begin
          Begin	{Write-Verbose "[Start]:: Process-PodeCommands"}
          #endregion Begin

          #region Process
          Process   {ForEach ($PodeCommand in $PodeCommands.Value.GetEnumerator()) {				# Process Pode Commands
					Switch ($PodeCommand.Key) {
						"Routes"		{If ($route -eq "PodeWeb") {						# Pode.Web?
									} Else {$Routes_Queue = New-Object System.Collections.Queue	# Build Routes Queue
										ForEach ($route in $PodeCommand.Value.GetEnumerator()) {	# Process Routes
											$Routes_Queue.Enqueue($route.Value)}
										Do	{$route = $Routes_Queue.Dequeue()
											If (!$route.Item("Arguments")) {[string]$command = Build-Command -PodeCommand "Add-PodeRoute"
											} Else {[string]$command = Build-Command -PodeCommand "Add-PodeRoute" -PodeArguments $route.Item("Arguments")}
											invoke-expression $command
											} While ($Routes_Queue.Count -gt 0)}; Continue}
						default		{If (!$PodeCommand.Value.Item("Arguments")) {[string]$command = Build-Command -PodeCommand $PodeCommand.Key
									} Else {[string]$command = Build-Command -PodeCommand $PodeCommand.Key -PodeArguments $PodeCommand.Value.Item("Arguments")}
									invoke-expression $command; Continue}}}}
          #endregion Process

          #region End
          End		{Write-Verbose "[Exit]:: Process-PodeCommands"}
          #endregion End
     }
     #endregion Process-PodeCommands
#endregion Set Up Functions

#region House Keeping
cls
$env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
$ThisServer = $env:computername														# Get This Server's Name
#endregion House Keeping

#region Load Config.Json
$config = [ordered]@{}
[Void](ConvertTo-HashtableFromPsCustomObject -psCustomObject (Get-Content $($podeLocation + '\config.json') -Encoding UTF8 -Raw | ConvertFrom-Json) -HashTable ([ref]$config))
#endregion Load Config.Json

#region Load Modules
Write-Host "Loading Modules - Please Wait..."
ForEach ($module in $config.Item("Modules").GetEnumerator()) {								# Load Modules
	[string]$command = Build-Command -PodeCommand "Import-Module -Name '$($module.Key)'" -PodeArguments $module.Value
	Invoke-Expression $Command}
#endregion Load Modules

#region Start Pode Server
Write-Host "     Starting Pode Server - Treads:  $($config.Item("Start-PodeServer").Item("Arguments").Item("Threads")) - Please Wait..."
Sleep -Seconds 2
[hashtable]$arguments = Build-Command -PodeArguments $config.Item("Start-PodeServer").Item("Arguments")	# Get Start-PodeServer Arguments
Start-PodeServer @arguments {
	$podeLocation = Get-PodeServerPath													# Get Script Path

	#region Add Endpoints/Routes
	ForEach ($endpoint in $config.Item("Start-PodeServer").Item("Add-PodeEndpoint").GetEnumerator()) {	# Add Endpoints
		[hashtable]$arguments = Build-Command -PodeArguments $endpoint.Value.Item("Arguments")	# Get Add-PodeEndpoint Arguments
		Add-PodeEndpoint @arguments													# Add Endpoint
		ForEach ($route in $endpoint.Value.Routes.GetEnumerator()) {						# Add Routes
			[hashtable]$arguments = Build-Command -PodeArguments $route.Value.Item("Arguments")	# Get Add-PodeRouteRoute Arguments
			Add-PodeRoute @arguments}}												# Add Route
	#endregion Add Endpoints/Routes

	#region Logging
	If ($config.Item("Start-PodeServer").Item("New-PodeLoggingMethod")) {
		[hashtable]$arguments = Build-Command -PodeArguments $config.Item("Start-PodeServer").Item("New-PodeLoggingMethod").Item("Arguments")	# Get New-PodeLoggingMethod Arguments
		New-PodeLoggingMethod @arguments | Enable-PodeErrorLogging}						# Set New-PodeLoggingMethod
	#endregion Logging

	#region Enable Sessions
		If ($config.Item("Start-PodeServer").Item("Enable-PodeSessionMiddleware")) {
			[hashtable]$arguments = Build-Command -PodeArguments $config.Item("Start-PodeServer").Item("Enable-PodeSessionMiddleware").Item("Arguments")	# Get Enable-PodeSessionMiddleware Arguments
			Enable-PodeSessionMiddleware @arguments}									# Enable-PodeSessionMiddleware
	#endregion Enable Sessions
}
#endregion Start Pode Server

**Comment by jbaechtelMT** [comment]
[config.zip](https://github.com/Badgerati/Pode/files/9795824/config.zip)
[server.zip](https://github.com/Badgerati/Pode/files/9795825/server.zip)

**Comment by jacobswhit-copart** [comment]
Just wanted to add this here as I recently did something similar for an application.

In my main server file, this logic looks within a 'routes' folder for .psd1 files and subfolders (for route groups).
The object in a given .psd1 is splatted as the parameters for a 'Add-PodeRoute' or 'Add-PodeRouteGroup' call.
As a point of convention, I've taken to naming the route data and script files the same.

#### Within server.ps1
```
        # Load routes.
        # https://badgerati.github.io/Pode/Tutorials/Routes/Overview/
        (Get-ChildItem './routes/' -Filter *.psd1)
        | ForEach-Object {
            $Splat = (Import-PowerShellDataFile $_.FullName)
            Add-PodeRoute @Splat
        }
        # Load route groups.
        (Get-ChildItem './routes/' -Directory)
        | ForEach-Object {
            $RouteGroup = $_
            $Splat = (Import-PowerShellDataFile (Join-Path $RouteGroup.Fullname 'group.psd1'))
            Add-PodeRouteGroup @Splat -Routes {
                (Get-ChildItem ($using:RouteGroup) -Filter *.psd1)
                | ForEach-Object {
                    if ($_.BaseName -ne 'group') {
                        $GroupRoute = (Import-PowerShellDataFile $_.FullName)
                        Add-PodeRoute @GroupRoute
                    }
                }
            }
        }
```

#### Example structure
```
-server.ps1
-routes/
    -ping.ps1
    -ping.psd1
    -<route-name>.ps1
    -<route-name>.psd1
    -<group name>/
        -group.psd1
        -<group-route>.ps1
        -<group-route>.psd1
```

#### ping.psd1
```
@{
    Method = 'GET'
    Path = '/ping'
    FilePath = './routes/ping.ps1'
}
```

#### ping.ps1
```
{
    Write-PodeJsonResponse "Pong!"
}
```

I've found this to be extensible so far and I thought the use of psd1/splat felt very "powershell".

**Comment by SeriousMikeDE** [comment]
To finish this here's what I setup now.

In server.ps1 I have the following:
```powershell
$Pages = Get-ChildItem .\pages\ -Filter "*.ps1"

foreach($Page in $Pages) {
    # Gather information from script by calling it with -Info
    $Auth, $Method, $URI = & $Page.FullName -Info
	try {
		# Check, if scheme already exists (i.e. if previous page uses the same)
		Get-PodeAuth -Name $Auth.Name
	}
	catch {
		# Error expected
		# Auth scheme doesn't exist and will be created
		New-PodeAuthScheme -Basic | Add-PodeAuthWindowsAd -KeepCredential -Name $Auth.Name -Groups $Auth.Groups -Users $Auth.Users
	}
    # Create Route
    Add-PodeRoute -Method $Method -Path ("/"+$URI) -Authentication $Auth.Name -FilePath $Page.FullName
}
```
this loops through the subfolder "pages" and searches for all ps1 files

Each ps1 file has the following content:
```powershell
[CmdletBinding()]
param (
    [Switch] $Info # Set to only return information
)

if($Info) {
    $Authentication = @{
        Name = "Welcome"
        Groups = @("some_AD_group")
        Users = @()
    }
    $Method = "Get"
    $URI = "welcome"
    return $Authentication, $Method, $URI
}
{
# the actual code of the routes script block
}
```

With this setup I only need to create a new file in the subfolder, fill in the infos and add the code block. After server restart the new sub page is available
