### ISSUE TITLE
How to retrieve task instances created in another ScriptBlock

### ISSUE THREAD

**Issue by phillippover** [Badgerati/Pode#1034]
### Question
We have a task that runs a script file Asynchronously:

```ps
    Add-PodeTask -Name "executeScript" -ArgumentList  @{script_name = $script_name; data = $data} -ScriptBlock {
         param($Event, $script_name, $data)
            . $script_name -data $data
    }
```

Which is invoked by an endpoint:
```ps
    Add-PodeRoute -Method Post -Path "/test" -ScriptBlock {
        $data = $WebEvent.Data
        $task = Invoke-PodeTask -Name "executeScript" -ArgumentList @{
                script_name=$data.script_name
                data = $data
            }            
            Write-PodeJsonResponse @{ID = $task.ID; status = "In progress"}
    }
```

This script may take some time to run so we don't want to wait for the task to complete before we send a response. However, we would like a way of checking up on the task, which I was intending to do with an endpoint to get the tasks and return their current status, but when I invoke Get-PodeTask from another endpoint, it doesn't return the running task. From what I've been able to figure out, this is due to the ScriptBlocks running in a separate pwsh instance, so are not available to the PodeServer instance.

Is this correct?

Is there any way of retrieving the running tasks?

I tried adding them to a global variable, but this also didn't appear to work. All I've managed to confirm is that the task runs to completion, so we do have a way to call back when the script completes using an Invoke-WebRequest, but not being able to confirm that status of a running task makes the process we're building a little worrysome.

Any suggestions would be appreciated.

**Comment by Badgerati** [comment]
Hi @phillippover,

`Get-PodeTask` will just return the tasks defined by `Add-PodeTask`, rather than any processes invoked for the Task itself.

However, #1037 has some extra functions to be implemented for Tasks that will do what you're after 😃 

At the moment, with the baby, I'm not sure when I'll get round to looking at it. It's not supported, but you might be able to use `$PodeContext.Tasks.Results.Values` which will contain an array of all running tasks.

**Comment by phillippover** [comment]
Hi @Badgerati,

Thanks for capturing the requirements, I understand this isn't your day job, so look forwards to when that's added.

As for using `$PodeContext.Tasks.Results.Values`, that's working perfectly, thanks. I understand it's not supported, but it achieves what I need on an ever-shortening timescale, so I'll take it.

Thanks also for the quick reply.
-Phill
