### ISSUE TITLE
Update UploadFile docs to reference using curl for CLI file upload

### ISSUE THREAD

**Issue by Badgerati** [Badgerati/Pode#1041]
Update the [UploadFIle](https://badgerati.github.io/Pode/Tutorials/Misc/UploadFiles/) docs to reference using `curl` to upload files from the CLI, ie:

```bash
curl http://localhost:8080/upload -F name=john -F avatar=@"C:\path\to\some\picture.png"
```

This will upload the file, as a form, and allow `Save-PodeRequestFile` to work.

Extra:
Investigate doing the same with `Invoke-RestMethod`, but it seems it doesn't work properly.

**Comment by Mxrcon** [comment]
I've been trying to upload files using Invoke-WebRequest method but no success so far... it seems that using `-Form @{avatar =Get-Item avatar.png` fails and gives server error as the avatar key wasn't provided...

**Comment by Badgerati** [comment]
I've updated the UploadFile docs to show how to upload a file using `curl`, but also `Invoke-WebRequest`!

I found a gotcha bug with how `Invoke-WebRequest` sets the form-data boundary, and fixing that now allows it to work 😄

**Comment by Mxrcon** [comment]
Very nice! Thank you for this!! I would like to rely on PS as much as possible instead of using other binaries for tests like curl!

How can I check the dev docs instead of main docs? I'd like to keep watching the edge work that you're doing.

I'm waiting for the next release 🚀
