### ISSUE TITLE
Pode seemingly cannot handle HTML5 Multiple Attribute 

### ISSUE THREAD

**Issue by Warburons** [Badgerati/Pode#1044]
### Describe the Bug
Pode MIddleware errors when using HTML5's multiple Tag on forms:
Attempting to use HTML5's Multiple attribute to upload multiple files per tag; will return a 400 error. On the terminal, internal pode errors occur in the middlewere handling the file parsing, as it cannot handle multiple files per tag.

### Steps To Reproduce
Using this form:

`<form action="/mps/uploadctf" method="post" enctype="multipart/form-data">
            <div>
                <h3>
                <label>CTF:</label>
                <input type="file" id="ctf" name="ctf" multiple="multiple"/>
                </h3>
            </div>
            <div>
            <br>
                <input type="submit" value="Submit" />
            </div>
     </form>`

Try posting two files in the same input box

### Expected Behavior
A hastable or object of files to be accessible using only one input box

### Platform
 - OS: Windows&Linux
 - Browser: Edge,Firefox
 - Versions:
   - Pode: 2.7.2
   - PowerShell: PS7.2-lts

**Comment by Badgerati** [comment]
Hi @Warburons,

I just reproduced this myself, and get the same error:
```
Exception calling "Add" with "2" argument(s): "Item has already been added. Key in dictionary: 'avatar'  Key being added: 'avatar'"
At C:\Projects\Pode\src\Private\Middleware.ps1:283 char:23
+ …   $result = ConvertFrom-PodeRequestContent -Request $WebEvent.Request …
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
at ConvertFrom-PodeRequestContent, C:\Projects\Pode\src\Private\Helpers.ps1: line 1579
at <ScriptBlock>, C:\Projects\Pode\src\Private\Middleware.ps1: line 283
at Invoke-PodeScriptBlock, C:\Projects\Pode\src\Public\Utilities.ps1: line 634
at Invoke-PodeMiddleware, C:\Projects\Pode\src\Private\Middleware.ps1: line 45
at <ScriptBlock>, <No file>: line 81
    + NotSpecified: (:) [ConvertFrom-PodeRequestContent], MethodInvocationException
```

I can see why it's happening, as `multiple` passes the form-data with the same name/id of `ctf` twice! 🙈 

I'll look into fixing it.

**Comment by Badgerati** [comment]
The above commit should fix this now, and it works for me locally. I've also update `Save-PodeRequestFile` to save all the files as once, and to allow saving specific files via `-FileName`.
