### ISSUE TITLE
How to add a File upload based request to Open API Schema?

### ISSUE THREAD

**Issue by Mxrcon** [Badgerati/Pode#1045]
### Question
I'm trying to generate the open API documentation for my API, but I'm not sure about how to add a specification for a File upload based endpoint. 

Here's my current code: 
```Powershell
$Solve = (Join-Path(Join-Path -Path (Join-Path (Split-Path -Path $PSScriptRoot -Parent) -ChildPath "Private")`
               -ChildPath "Api-Versions") -ChildPath "v1Solve.ps1")

      Add-PodeRoute -Method 'Post' -Path '/v1/solve' -FilePath $Solve -PassThru |
      Set-PodeOARouteInfo -PassThru |
      Set-PodeOARequest -Parameters @(
            (New-PodeOARequestBody -ContentSchemas @{ 'application/octet-stream' = (New-PodeOAStringProperty -Name 'Recipe' -Format Binary -Object)}`
             | ConvertTo-PodeOAParameter -In Query))`
         -PassThru |
      Add-PodeOAResponse -StatusCode 200 `
         -ContentSchemas @{ 'application/json' = (New-PodeOAObjectProperty -Properties @(
               (New-PodeOABoolProperty -Name 'Solvable')
            ) )
      }
```

My objective is to receive only a request with a "Recipe" yaml file on Body,
I would like to recreate something very similar to the "Avatar" Example on Pode Upload example.

[Here](https://swagger.io/docs/specification/describing-request-body/file-upload/) is How Open API 3 expects the content to be enconded
```yaml
    requestBody:
      content:
        application/octet-stream:
          schema:
            type: string
            format: binary 
```

Thank you for you attention, 
Kindly, Davi

**Comment by Mxrcon** [comment]
Hmm, I just got it working, but I'm not sure if this is the most correct way to achieve it..

Working code with file upload on docs:
```powershell
Set-PodeOARequest -RequestBody (
            (New-PodeOARequestBody -ContentSchemas @{ 'multipart/form-data' = (New-PodeOAStringProperty -Name 'recipe' -Format Binary -Object)}  -Description 'Yaml recipe for a Conda Environment')) -PassThru |
      Add-PodeOAResponse -StatusCode 200 -Description 'Yaml processed by the server'`
         -ContentSchemas @{ 'application/json' = (New-PodeOAObjectProperty -Properties @(
               (New-PodeOABoolProperty -Name 'Solvable')
            ) )
      }`
         -PassThru 
```

My `Set-PodeOARequest` was wrongly written on the previous comment.

**Comment by Badgerati** [comment]
Hi @Mxrcon,

This is correct for Pode, as it only parses files in requests sent as `multipart/form-data` at the moment - still valid on that [link](https://swagger.io/docs/specification/describing-request-body/file-upload/) 😄 

I've thought about supporting `application/octet-stream`, just needs looking into!

**Comment by Mxrcon** [comment]
Thank you @Badgerati, that addition would be very nice as we could optimize the upload size by using octets 🙏
