### ISSUE TITLE
$MyInvocation.PSScriptRoot for Server Root

### ISSUE THREAD

**Issue by fatherofinvention** [Badgerati/Pode#1062]
### Describe the Change
When trying to access functions I have dot sourced into my `main.ps1`(called `file.ps1` in the docs) using a relative path, I noticed that `$MyInvocation.PSScriptRoot` resolves to the module directory (e.g. `/usr/local/share/powershell/Modules/Pode/2.7.2/Public`) instead of the location of the `server.ps1` as the documentation says: https://github.com/Badgerati/Pode/blob/e16adca3ce76addebfa653a6088168bcd5dc22f8/docs/Tutorials/Misc/ServerRoot.md

Incidentally, I noticed that if I define functions in my `main.ps1` script they are accessible within script blocks, for example a route script block, but if I dot source them into my `main.ps1` they are no longer accessible within script blocks. Is this a scoping issue of some kind? Is it possible to dot source my functions into `main.ps1` and have them be usable within script blocks?

For example:

main.ps1
```powershell

$functionsDir = './functions'
    Get-ChildItem -Path $functionsDir -Recurse -Filter '*.ps1' | ForEach-Object {
     . $_.FullName
    } 

Add-PodeRoute -Method Get -Path '/route/' -ScriptBlock {
   My-DotSourcedFunction
}
```

**Comment by Badgerati** [comment]
Hi @fatherofinvention,

This comes down to terrible wording on my part, oops! 🙈 

What the page should really convey is that the root path of the server *on start-up* is `$MyInvocation.PSScriptRoot` - or `-RootPath` if supplied, or the value from the `server.psd1`. This is the path where Pode retrieving its views, error pages, config file, etc.. Throughout the running of the server `$MyInvocation.PSScriptRoot` will just be the path to Pode. (We can use this issue to track updating the doc's wording)

To retrieve the root path you're expecting you can use `Get-PodeServerPath`.

For the functions you're correct in saying this is a scoping issue; I'd recommend using `Use-PodeScript` instead. This will dot-source the files for you, and then extract those functions into Pode's runspaces for you 😄

**Comment by fatherofinvention** [comment]
Hey @Badgerati ! Thank you for the super helpful answer as always. I'll give `Use-PodeScript` a shot and report back.

**Comment by fatherofinvention** [comment]
@Badgerati that worked perfectly, TY!
