### ISSUE TITLE
 Trigger server state events before closing listeners

### ISSUE THREAD

**Issue by atriumcarceri** [Badgerati/Pode#1082]
### Describe
Hi!
Just discover, that "Register-PodeEvent" script block start to process after closing listeners socket, so its cannot be use with Send-PodeSignal to prepare clients with auto-reconnect websockets to do something with that. Is that real, to trigger it before? For Start/Restart will be absolutely perfect.

### Error text
``` powershell
Category: OperationStopped: (WebSockets have not…end signal messages:String) [], RuntimeException
Message: WebSockets have not been configured to send signal messages
```

Pode Version 2.8.0
PSVersion 7.3.2

**Comment by Badgerati** [comment]
Hi @atriumcarceri,

Which Event are you current using? The `Restart` event should occur before all sockets are closed 🤔

**Comment by Badgerati** [comment]
Linked with #1107, I've created a new Running event which will be triggered soon after the Start one. In the Running event all Runspaces will be open and available.
