### ISSUE TITLE
client side how to invoke specific end point

### ISSUE THREAD

**Issue by ericxin1982** [Badgerati/Pode#1092]
### Question
A clear and concise description of your question.
https://github.com/Badgerati/Pode/blob/develop/examples/tcp-server-multi-endpoint.ps1

Hi @Badgerati 

I am curious how client invoke the specific endpoint, would you please give me brief client side example?

Thanks
Eric Xin

**Comment by Badgerati** [comment]
Hi,

You can see an example of a function that can be used to invoke a TCP endpoint here: https://badgerati.github.io/Pode/Servers/TCP/#test-send

With that you can call the IP of the endpoint you're after.

Hope that helps!

**Comment by ericxin1982** [comment]
I may ask the wrong question, I may ask when this feature can be used, and what you would have this feature on, it is like com port communication.
