### ISSUE TITLE
Increase JSON depth on save/restore to maximums

### ISSUE THREAD

**Issue by plk** [Badgerati/Pode#1093]
### Describe the Bug
A mildly complex state exceeds the hard-coded depth of 10 in the convert-to/from JSON calls in the save/restore state cmdlets. This makes it impossible to save/restore such state. Please increase the depth for these commands to the maximums (1024/100 for from/to in PS core).

### Steps To Reproduce
Create a state variable with a depth > 10 and then save/restore of state fails.

### Expected Behavior
Maximum depth for JSON should be supported or perhaps settable via the save/restore cmdlets.

**Comment by Badgerati** [comment]
Resolved in #1094
