### ISSUE TITLE
pode template engine powershell invoke from Use-PodeScript

### ISSUE THREAD

**Issue by ericxin1982** [Badgerati/Pode#1103]
### Question
A clear and concise description of your question.

HI @Badgerati 

I have a question, if I want to use some custom powershell command from use-podescript inside pode view file, how to make it happen?
I meant I guess I should use-podescript on top of the pode file, and I am not sure what the format is, maybe this way does not work, would you please introduce a feasible way to me?

Thanks
Eric Xin

**Comment by Badgerati** [comment]
Hi @ericxin1982,

Any functions in .ps1 files loaded via `Use-PodeScript` should be accessible to be able to be used in .pode view files.

Is there an error you're seeing trying to use a function? If you have a server.psd1 with AutoImport Functions and ExportOnly set to true, then you'll need to use `Export-PodeFunction` to tell Pode you want to export specific functions (if this is false or not present, all functions will be exported by default).

Thanks :)

**Comment by ericxin1982** [comment]
Thanks so much!
