### ISSUE TITLE
is variable conflict possible in Add-PodeTask?

### ISSUE THREAD

**Issue by behrouzamiri** [Badgerati/Pode#1104]
### Question
ENV:
```
> Pode is hosted using IIS method
> Windows Server 2022
> Get-Module Pode

ModuleType Version    PreRelease Name                      
---------- -------    ---------- ----                      
Script     2.7.2                 Pode                      

> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
I have faced an issue while developing an API using Pode, that is being heavily called.

Let's say some system posts form data to a Pode endpoint using an API call. since the form submission waits until it gets the post response, I had to use the pode task functionality to return HTTP/200 and later process the request.

the form data has file uploads. I get the file attachment URLs within the initial API call, then using the pode task, download the attachments, and add it to the corresponding item in SharePoint.
while most of the items in SharePoint are created correctly with correct attachments, in some cases I see there are attachments related to other form submissions, meaning that either the form has posted the file attachment list incorrectly (rare) or within the pode task, the attachment array variable is global.

kindly, please let me know if is there a chance that this is happening by Pode?

Example:
```
Task1 {
$files = @()
if ($thisEvent.Data.upload1){
$files += $thisEvent.Data.upload1
  }
if ($thisEvent.Data.upload2){
$files += $thisEvent.Data.upload2
  }
# Now download each file in $files and add it to the SharePoint list item.
}
.
.
.

route1: /api/route1 {
Invoke-PodeTask -Name 'Task1' -ArgumentList @{thisEvent = $WebEvent, ...} ...
}
```
and simultaneously or near the same time, two `Invoke-PodeTask -Name 'Task1'` commands are being executed, with one of them having upload1 and the other having upload2.
is there any chance that the variable $files contain both upload1 and upload2?

>Update1:

I've tested on my Mac this morning with the below script:
```
Start-PodeServer -RootPath ~/Desktop/ -ScriptBlock {
    Add-PodeEndpoint -Port 8080 -Protocol Http -Verbose -Address *
    New-PodeLoggingMethod -Terminal | Enable-PodeErrorLogging -Levels Error, Warning

 Add-PodeTask -Name 'task' -ScriptBlock {
        param ($Event, $ThisEvent)
        $sum = @()
        if ($ThisEvent.Data.arg1){$sum+=$ThisEvent.Data.arg1}
        if ($ThisEvent.Data.arg2){$sum+=$ThisEvent.Data.arg2}
        if($sum.count -gt 2) {$sum.count | Out-PodeHost}
    }

    Add-PodeRoute -Method Post -Path /api/task -ScriptBlock {
        Invoke-PodeTask -Name 'task' -ArgumentList @{ThisEvent = $WebEvent}
    }
}
```
and then made two different http requests from two terminals:
```
while ($true) {
    irm -uri http://localhost:8080/api/task -Method Post -Body (@{
            arg1 = "one"
            arg2 = ""
        } | ConvertTo-Json) -ContentType "application/json"
}
```
and
```
while ($true) {
    irm -uri http://localhost:8080/api/task -Method Post -Body (@{
            arg1 = ""
            arg2 = "two"
        } | ConvertTo-Json) -ContentType "application/json"
}
```
then sometimes, I get the below error:
```
Listening on the following 1 endpoint(s) [1 thread(s)]:
        - http://localhost:8080/
        
Date: 2023-06-22 09:11:26
Level: Error
ThreadId: 0
Server: MacBook
Category: InvalidOperation: (System.Collections.…HashtableEnumerator:HashtableEnumerator) [Invoke-PodeScriptBlock], RuntimeException
Message: An error occurred while enumerating through a collection: Collection was modified; enumeration operation may not execute..
StackTrace: at <ScriptBlock>, /Users/behrouz/.local/share/powershell/Modules/Pode/2.6.2/Private/Tasks.ps1: line 19
at Invoke-PodeScriptBlock, /Users/behrouz/.local/share/powershell/Modules/Pode/2.6.2/Public/Utilities.ps1: line 634
at Invoke-PodeInternalTimer, /Users/behrouz/.local/share/powershell/Modules/Pode/2.6.2/Private/Timers.ps1: line 106
at <ScriptBlock>, <No file>: line 35
at <ScriptBlock>, <No file>: line 7
```
the above test was done on:
```
PS /Users/behrouz/Desktop> Get-Module Pode

ModuleType Version    PreRelease Name               
---------- -------    ---------- ----               
Script     2.6.2                 Pode               

PS /Users/behrouz/Desktop> $PSVersionTable     

Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Darwin 22.1.0 Darwin 
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
> Update 2:

tested the same test on the Windows ENV, and the same error was sometimes observed (in rare cases)
Maybe Pode and PowerShell can handle this kind of violation, however, when running with IIS, this happens?

>Update 3:

Just Updated the server with `-Threads 8` and `Set-PodeTaskConcurrency -Maximum 8`, and the issue seems to be gone.

**Comment by behrouzamiri** [comment]
> ### Question
> ENV:
> 
> ```
> > Pode is hosted using IIS method
> > Windows Server 2022
> > Get-Module Pode
> 
> ModuleType Version    PreRelease Name                      
> ---------- -------    ---------- ----                      
> Script     2.7.2                 Pode                      
> 
> > $PSVersionTable
> 
> Name                           Value
> ----                           -----
> PSVersion                      7.3.1
> PSEdition                      Core
> GitCommitId                    7.3.1
> OS                             Microsoft Windows 10.0.20348
> Platform                       Win32NT
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
> PSRemotingProtocolVersion      2.3
> SerializationVersion           1.1.0.1
> WSManStackVersion              3.0
> ```
> 
> I have faced an issue while developing an API using Pode, that is being heavily called.
> 
> Let's say some system posts form data to a Pode endpoint using an API call. since the form submission waits until it gets the post response, I had to use the pode task functionality to return HTTP/200 and later process the request.
> 
> the form data has file uploads. I get the file attachment URLs within the initial API call, then using the pode task, download the attachments, and add it to the corresponding item in SharePoint. while most of the items in SharePoint are created correctly with correct attachments, in some cases I see there are attachments related to other form submissions, meaning that either the form has posted the file attachment list incorrectly (rare) or within the pode task, the attachment array variable is global.
> 
> kindly, please let me know if is there a chance that this is happening by Pode?
> 
> Example:
> 
> ```
> Task1 {
> $files = @()
> if ($thisEvent.Data.upload1){
> $files += $thisEvent.Data.upload1
>   }
> if ($thisEvent.Data.upload2){
> $files += $thisEvent.Data.upload2
>   }
> # Now download each file in $files and add it to the SharePoint list item.
> }
> .
> .
> .
> 
> route1: /api/route1 {
> Invoke-PodeTask -Name 'Task1' -ArgumentList @{thisEvent = $WebEvent, ...} ...
> }
> ```
> 
> and simultaneously or near the same time, two `Invoke-PodeTask -Name 'Task1'` commands are being executed, with one of them having upload1 and the other having upload2. is there any chance that the variable $files contain both upload1 and upload2?
> 
> > Update:
> > I've tested on my Mac this morning with the below script:
> 
> ```
> Start-PodeServer -RootPath ~/Desktop/ -ScriptBlock {
>     Add-PodeEndpoint -Port 8080 -Protocol Http -Verbose -Address *
>     New-PodeLoggingMethod -Terminal | Enable-PodeErrorLogging -Levels Error, Warning
> 
>  Add-PodeTask -Name 'task' -ScriptBlock {
>         param ($Event, $ThisEvent)
>         $sum = @()
>         if ($ThisEvent.Data.arg1){$sum+=$ThisEvent.Data.arg1}
>         if ($ThisEvent.Data.arg2){$sum+=$ThisEvent.Data.arg2}
>         if($sum.count -gt 2) {$sum.count | Out-PodeHost}
>     }
> 
>     Add-PodeRoute -Method Post -Path /api/task -ScriptBlock {
>         Invoke-PodeTask -Name 'task' -ArgumentList @{ThisEvent = $WebEvent}
>     }
> }
> ```
> 
> and then made two different http requests from two terminals:
> 
> ```
> while ($true) {
>     irm -uri http://localhost:8080/api/task -Method Post -Body (@{
>             arg1 = "one"
>             arg2 = ""
>         } | ConvertTo-Json) -ContentType "application/json"
> }
> ```
> 
> and
> 
> ```
> while ($true) {
>     irm -uri http://localhost:8080/api/task -Method Post -Body (@{
>             arg1 = ""
>             arg2 = "two"
>         } | ConvertTo-Json) -ContentType "application/json"
> }
> ```
> 
> then sometimes, I get the below error:
> 
> ```
> Listening on the following 1 endpoint(s) [1 thread(s)]:
>         - http://localhost:8080/
>         
> Date: 2023-06-22 09:11:26
> Level: Error
> ThreadId: 0
> Server: MacBook
> Category: InvalidOperation: (System.Collections.…HashtableEnumerator:HashtableEnumerator) [Invoke-PodeScriptBlock], RuntimeException
> Message: An error occurred while enumerating through a collection: Collection was modified; enumeration operation may not execute..
> StackTrace: at <ScriptBlock>, /Users/behrouz/.local/share/powershell/Modules/Pode/2.6.2/Private/Tasks.ps1: line 19
> at Invoke-PodeScriptBlock, /Users/behrouz/.local/share/powershell/Modules/Pode/2.6.2/Public/Utilities.ps1: line 634
> at Invoke-PodeInternalTimer, /Users/behrouz/.local/share/powershell/Modules/Pode/2.6.2/Private/Timers.ps1: line 106
> at <ScriptBlock>, <No file>: line 35
> at <ScriptBlock>, <No file>: line 7
> ```
> 
> the above test was done on:
> 
> ```
> PS /Users/behrouz/Desktop> Get-Module Pode
> 
> ModuleType Version    PreRelease Name               
> ---------- -------    ---------- ----               
> Script     2.6.2                 Pode               
> 
> PS /Users/behrouz/Desktop> $PSVersionTable     
> 
> Name                           Value
> ----                           -----
> PSVersion                      7.2.4
> PSEdition                      Core
> GitCommitId                    7.2.4
> OS                             Darwin 22.1.0 Darwin 
> Platform                       Unix
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
> PSRemotingProtocolVersion      2.3
> SerializationVersion           1.1.0.1
> WSManStackVersion              3.0
> ```
> 
> > Update 2: tested the same test on the Windows ENV, and the same error was sometimes observed (rare cases)
> > Maybe Pode and PowerShell can handle this kind of violation, however, when running with IIS, this happens?

Just Updated the server with `-Threads 8` and `Set-PodeTaskConcurrency -Maximum 8`, and the issue seems to be gone.

**Comment by Badgerati** [comment]
Hi @behrouzamiri,

The conflict is likely being caused by the direct passing of the `$WebEvent` variable as a Task `-ArgumentList`. The WebEvent is a hashtable defined higher up, and on new requests will be reset - so the conflict could be being caused here.

If you pass just the `.Data` properties you're after as arguments then the conflicts should go.

Bumping the `-Threads` will have a "similar" affect, as it'll be less likely to have the WebEvent get reset - but if the endpoint sees any higher load for some reason, the conflicts will come back.

Hope that helps!

**Comment by behrouzamiri** [comment]
You are absolutely right!
Thanks for your advice 👍
