### ISSUE TITLE
psake error

### ISSUE THREAD

**Issue by ericxin1982** [Badgerati/Pode#1105]
### Question
A clear and concise description of your question.

Hi @Badgerati 

I tried to use pode build, I can skip,  but I am curious.
![image](https://github.com/Badgerati/Pode/assets/9047436/5bf7b434-0fb3-4c42-91af-0dc4275e3fa5)

Do you know why?

Thanks
Eric Xin

**Comment by Badgerati** [comment]
Hi @ericxin1982,

It's a placeholder in the `package.json` file for building your website - it can be replaced by anything; yarn, npm, invoke-build, etc.. It depends on what your site needs to build.

It's not related to building Pode itself, which uses the `InvokeBuild` module :)

**Comment by ericxin1982** [comment]
Oh, ok, thanks.
