### ISSUE TITLE
Hide Web Server Name Tag from response header

### ISSUE THREAD

**Issue by ericxin1982** [Badgerati/Pode#1106]
### Question
A clear and concise description of your question.

Hi @Badgerati 

I used to use nginx, and I would hide the server tag for security reason, if I need to hide the server tag, is it possible?
Right now the server tag is Pode.

![image](https://github.com/Badgerati/Pode/assets/9047436/c14bd587-60df-42e4-836c-db9e78c04287)

Thanks
Eric Xin

**Comment by Badgerati** [comment]
Hi @ericxin1982,

I thought I had implemented this, but must have dreamt it! Yes, I can implement a way to not have the Server header added on responses.

**Comment by ericxin1982** [comment]
Thanks.

**Comment by Badgerati** [comment]
Added two new functions:

* `Hide-PodeSecurityServer`
* `Show-PodeSecurityServer`
