### ISSUE TITLE
Invoke-PodeTask

### ISSUE THREAD

**Issue by ericxin1982** [Badgerati/Pode#1107]
### Question
A clear and concise description of your question.

Register-PodeEvent -Type Start -Name 'ProjInit' -ScriptBlock {
        $connection = GetConnectionString
        Write-Host "$([DateTime]::Now)"
        $dbpipe = New-SqlConnection $connection
        ##global state tree setup, then the whole app can reach the db connection by get-podestate
        Set-PodeState -Name 'db' -Value @{ 't254' = $dbpipe } | Out-Null
        Invoke-PodeTask -name 'xxxxxx' | out-null
    }

Hi @Badgerati 

I put invoke-podetask inside register-podeevent -type start, and it does not work, I am curious why.
invoke-podetask inside add-poderoute, and inside Add-PodeSchedule, it works fine.

I just try to make invoke-podetask can trigger when start.
It does not support?

Thanks
Eric Xin

**Comment by Badgerati** [comment]
Hi @ericxin1982,

This will be because the Start event is triggered before any of the Runspaces are actually created, so you can load anything additional if required.

To have this work, we'll probably need a new Event, something like `Running` perhaps 🤔 I can have a look.

**Comment by ericxin1982** [comment]
Ok, I see. That is not rush, I am using this instead after start trigger event.

![image](https://github.com/Badgerati/Pode/assets/9047436/a9032b1d-359c-4c72-9df5-675bcf3713f8)

But if I can put task on start or running that would be much better.

Thanks
Eric Xin

**Comment by Badgerati** [comment]
I've created a new Running event which will be triggered soon after the Start one. In the Running event all Runspaces will be open and available.
