### ISSUE TITLE
Add-PodeEndpoint does not validate 127.0.0.1 as localhost with ws

### ISSUE THREAD

**Issue by mtimperley** [Badgerati/Pode#1120]
### Describe the Bug
when a client uses address ws://127.0.0.1:51499
and the server is configured as localhost
Add-PodeEndpoint -Protocol ws -Address localhost -Port 51499
the response is:
[Debug] HttpRequestException: Request is not for a WebSocket
   at Pode.PodeContext.SetContextType()
   at Pode.PodeContext.<Receive>d__74.MoveNext()
[Error] HttpRequestException: Invalid request Host: 127.0.0.1:51499
   at Pode.PodeHttpRequest.ParseHeaders(String[] reqLines, String newline)
   at Pode.PodeHttpRequest.Parse(Byte[] bytes)
   at Pode.PodeRequest.<Receive>d__78.MoveNext()
and the client cannot connect.
when a client uses address ws://localhost:51499
it can then connect.

### Steps To Reproduce

Run server server.ps1 (script as follows):
```
param (
    [string]$url = 'ws://localhost:51499/'
)

$uri = $null
if (![System.Uri]::TryCreate($url, [System.UriKind]::RelativeOrAbsolute, [ref]$uri) ) {
    Out-PodeHost "Invalid -url: $url"
    exit
}

Start-PodeServer {
    Add-PodeEndpoint -Protocol $uri.Scheme -Address $uri.Host -Port $uri.Port

    # log requests to the terminal
    New-PodeLoggingMethod -Terminal | Enable-PodeErrorLogging -Level Error, Debug, Verbose

    # SIGNAL route, to return current date
    Add-PodeSignalRoute -Path '/' -ScriptBlock {
        $msg = $SignalEvent.Data.Message

        if ($msg -ieq '[date]') {
            $msg = [datetime]::Now.ToString()
        }

        Send-PodeSignal -Value @{ reply = $msg }
    }
}
```

### Expected Behavior
the client can connect to this server with either 127.0.0.1 or localhost (both refer to the loopback so either should work)

### Screenshots
none

### Platform
 - OS: Windows 10
 - Browser: not used, PowerShell async client using Net.WebSockets.ClientWebSocket as below
 - Pode: 2.8.0
PSVersion                      5.1.19041.3031                                                             
PSEdition                      Desktop                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                    
BuildVersion                   10.0.19041.3031                                                            
CLRVersion                     4.0.30319.42000                                                            
WSManStackVersion              3.0                                                                        
PSRemotingProtocolVersion      2.3                                                                        
SerializationVersion           1.1.0.1  

### Additional Context

```
function Create-Websocket($uri)
{
    $webSocket = New-Object Net.WebSockets.ClientWebSocket
    $cts = New-Object Threading.CancellationTokenSource
    $connectTask = $webSocket.ConnectAsync($uri, $cts.Token)
    do { Sleep(1) }
    until ($connectTask.IsCompleted)
    return $webSocket
}
```

**Comment by Badgerati** [comment]
Hi @mtimperley,

I've just tried this myself but can't reproduce the issue 🤔 The only way code path that throws the error you're seeing is if there's a `-Hostname` being set on `Add-PodeEndpoint`. Are you setting a hostname by chance that wasn't copied into the script above?

**Comment by mtimperley** [comment]
So earlier yes, I was trying different options and -Hostname was one of them, but not at the time that I copied the script and reported this issue (at least that I remember). However, I rebooted my workstation, and now I cannot reproduce the problem either... Sorry for the false alarm, it does not appear to be a Pode issue. I wonder if I had some left-over undisposed objects in my powershell environment...
