### ISSUE TITLE
On restart verbs are not being loaded correctly via Use-PodeVerbs

### ISSUE THREAD

**Issue by sytone** [Badgerati/Pode#1125]
### Describe the Bug
Setup a simpler server, make a verbs folder and add a few files for the verbs you want to support. Add one called restart with something like this in it. 

```
Write-Host "VERB:RESTART"
Add-PodeVerb -Verb 'RESTART' -ScriptBlock {
    Restart-PodeServer
}
```

Here is my hello verb stored in hello.ps1
```
Write-Host "VERB:HELLO"
Add-PodeVerb -Verb 'HELLO' -ScriptBlock {
    Write-Host "VERB:HELLO Called"
    Write-PodeTcpClient -Message 'HI'
}

```

When server starts you can see it loads, when you send RESTART via a TCP call the server does a restart and can be seen via logs. You can see the "VERB:RESTART" message so the file has been . sourced. When you try to send a TCP message for any of the verbs in logs you can see the request received but there is no response. and the contents of the add-podeverb script block is not getting executed at all. Also added logging to wildcard and it is not picking up anything. 

### Steps To Reproduce
1. See description.

### Expected Behavior
On restart the verbs from the path would reload correctly. 

### Screenshots
NA

### Platform
 - OS: Windows 11
 - Browser: NA - TCP
 - Versions:
   - Pode: 2.8.0
   - PowerShell: 7.3.6 - Core

**Comment by Badgerati** [comment]
Hi @sytone,

I've managed to reproduce this locally. The issue is caused by the following line: https://github.com/Badgerati/Pode/blob/b6a97d26587c9384e65ac54e94f38981f17a9184/src/Private/Server.ps1#L176

This should be the following instead:

```powershell
$PodeContext.Server.Verbs.Clear()
```
