### ISSUE TITLE
Runspace error on pode start

### ISSUE THREAD

**Issue by v2kiran** [Badgerati/Pode#1137]
### Describe the Bug
Failed to close RunspacePool: Main error on running pode start

### Steps To Reproduce
create a simple server.ps1 witht he following content:
```ps
Start-PodeServer {
    New-PodeLoggingMethod -Terminal | Enable-PodeErrorLogging
    Write-Host 'hello, world!'
}

```
run `pode start`

### Expected Behavior
hello world is print with no error

### Screenshots
![image](https://github.com/Badgerati/Pode/assets/7691373/47adb397-2a72-40dc-a08c-6a8ba937b5b8)

### Platform
 - Windows
 - Chrome,edge,firefox
 - Versions:
   - Pode 2.8.0
   - Pwsh 7.3.6

### Additional Context
Also tried with an older version of pode, tried another user account, different content in server.ps1

**Comment by v2kiran** [comment]
did some debugging and found there is a conflict with another module called "completionpredictor".
I removed completionpredictor from the session and the error went away.

this is what i found during debugging:

```ps
Exception: C:\Users\Kiran\OneDrive\Documents\PowerShell\Modules\Pode\2.7.2\Private\Context.ps1:714:13
Line |
 714 |              $item.Pool.EndOpen($item.Result) | Out-Default
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "EndOpen" with "1" argument(s): "The implementation with Id '77bb0bd8-2d8b-4210-ad14-79fb91a75eab' was already registered for the
     | subsystem 'CommandPredictor'."

``

**Comment by Badgerati** [comment]
Hi @v2kiran,

The first error appears to be when closing the runspace, while the second error seems to be while trying to open the runspace. Do you know if they're both related to the CommandPredictor module?

If you try disabling the auto-importing of modules, does that resolve the issue? (https://badgerati.github.io/Pode/Tutorials/Scoping/#disable)

**Comment by v2kiran** [comment]
hi @Badgerati  - thanks for replying.
I just ran "remove-module completionpredictor". then pode ran.

I then changed the server.ps1 script slightly then ran into another error about importing modules after which i basically gave up.

```ps
{
    # attach to port 8080 for http
    Add-PodeEndpoint -Address localhost -Port 8085 -Protocol Http

    # a simple page for displaying services
    Add-PodePage -Name 'processes' -ScriptBlock { Get-Process }
}

```

i also have this psd1 file named server.psd1 in the same directory but didnt change do anything:

```ps
@{
    Server = @{
        AutoImport = @{
            Modules = @{
                Enable = $false
            }
        }
    }
}

```

```ps

Import-Module: C:\Users\Kiran\OneDrive\Documents\PowerShell\Modules\Pode\2.8.0\Private\Helpers.ps1:933:17
Line |
 933 |  …     $null = Import-Module $path -DisableNameChecking -Scope Global -E …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The specified module 'C:\gh\learn-pode\31a63532-6abc-443a-8533-7462fe8fe31f' was not loaded because no valid module file was found in any module
     | directory.

at Import-PodeModules, C:\Users\Kiran\OneDrive\Documents\PowerShell\Modules\Pode\2.8.0\Private\Helpers.ps1: line 933
at Open-PodeRunspace, C:\Users\Kiran\OneDrive\Documents\PowerShell\Modules\Pode\2.8.0\Private\Helpers.ps1: line 603
at <ScriptBlock>, <No file>: line 1

Import-Module: C:\Users\Kiran\OneDrive\Documents\PowerShell\Modules\Pode\2.8.0\Private\Helpers.ps1:933:17
Line |
 933 |  …     $null = Import-Module $path -DisableNameChecking -Scope Global -E …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The specified module 'C:\gh\learn-pode\31a63532-6abc-443a-8533-7462fe8fe31f' was not loaded because no valid module file was found in any module
     | directory.

at Import-PodeModules, C:\Users\Kiran\OneDrive\Documents\PowerShell\Modules\Pode\2.8.0\Private\Helpers.ps1: line 933
at Open-PodeRunspace, C:\Users\Kiran\OneDrive\Documents\PowerShell\Modules\Pode\2.8.0\Private\Helpers.ps1: line 603
at <ScriptBlock>, <No file>: line 1
ParentContainsErrorRecordException: C:\Users\Kiran\OneDrive\Documents\PowerShell\Modules\Pode\2.8.0\Private\Helpers.ps1:730:9
Line |
 730 |          throw $_.Exception
     |          ~~~~~~~~~~~~~~~~~~
     | Main runspace failed to load: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop:
     | The specified module 'C:\gh\learn-pode\31a63532-6abc-443a-8533-7462fe8fe31f' was not loaded because no valid module file was found in any module
     | directory.

```

**Comment by Badgerati** [comment]
Hi @v2kiran,

Well I just found a bug with Auto-Importing! Turns out the configuration is actually being ignored, so I'll get that fixed.

What's the module at `C:\gh\learn-pode\31a63532-6abc-443a-8533-7462fe8fe31f` it's trying to load? If it's extension is `.ps1` changing it to `.psm1` should work.

**Comment by v2kiran** [comment]
thats great :) 
31a63532-6abc-443a-8533-7462fe8fe31f - i have no clue what module it is trying to load because there are no files  in the root directory .....basically trying a very simple example.

Note: this string (31a63532-6abc-443a-8533-7462fe8fe31f) changes everytime i restart the ps session..

**Comment by JustinGrote** [comment]
Just a quick bump as I have the same issue as @v2kiran on a fresh Win10 insider system, tried in both 5.1 and 7.3.8. I'll try to build the dev version and see if that fixes it

**Comment by piereligio** [comment]
Met the same issue: was fault of PowerToys CommandNotFound module. You can remove it from Microsoft.Powershell_profile.ps1 in Documents\PowerShell and it should work.

**Comment by opustecnica** [comment]
Run into the same issue today.  Rather than commenting the module out in the $profile, I start the PODE files with:
```powershell
# [2025-09-28 15:13:31] NOTE: PODE fails if this module is loaded. [OT]
if (Get-Module -Name Microsoft.WinGet.CommandNotFound -ListAvailable) {
    Remove-Module -Name Microsoft.WinGet.CommandNotFound -Force -ErrorAction SilentlyContinue
}
```
