### ISSUE TITLE
Add-PodeRoute -FilePath doesn't work as expected 

### ISSUE THREAD

**Issue by mdaneri** [Badgerati/Pode#1140]
The expectation for **Add-PodeRoute -FilePath <file.ps1>** is to be equivalent to 

`Add-PodeRoute -ScriptBlock ([ScriptBlock]::Create( (Get-Content -Path <file.ps1> -Raw)))`

but it's not the way it works 

This is my test file

```
$Id = $WebEvent.Parameters['id'] 
Write-PodeJsonResponse -StatusCode 200 -Value @{'id' = $Id }
```

This one is the route: 
`Add-PodeRoute -PassThru -Method Post -Path '/api/v1/helloFile/:id' -FilePath '.\test.ps1' | Set-PodeOARouteInfo -Summary 'Test' -OperationId 'testScriptBlock' -PassThru | Set-PodeOARequest -Parameters @((New-PodeOAStringProperty -Name 'id' | ConvertTo-PodeOAParameter -In Path) )   `

and this is the error that I get 
```
InvalidOperation: C:\Users\m_dan\Documents\GitLab\cliaccess\test.ps1:1:1
Line |
   1 |  $Id = $WebEvent.Parameters['id']
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot index into a null array.
```

These 2 are working as expected:
 
`Add-PodeRoute -PassThru -Method Get -Path '/api/v1/helloConvertedFile/:id'  -ScriptBlock ([ScriptBlock]::Create( (Get-Content -Path '.\test.ps1' -Raw))) | Set-PodeOARouteInfo -Summary 'Test' -OperationId 'testScriptBlock' -PassThru | Set-PodeOARequest -Parameters @((New-PodeOAStringProperty -Name 'id' | ConvertTo-PodeOAParameter -In Path) ) `

 ` Add-PodeRoute -PassThru -Method Get -Path '/api/v1/helloScript/:id' -ScriptBlock { $Id = $WebEvent.Parameters['id'] ; Write-PodeJsonResponse -StatusCode 200 -Value @{'id' = $Id } } | Set-PodeOARouteInfo -Summary 'Test' -OperationId 'testScriptBlock' -PassThru | Set-PodeOARequest -Parameters @((New-PodeOAStringProperty -Name 'id' | ConvertTo-PodeOAParameter -In Path) )  ` 

I think the easy way to fix this is to simply convert the file content to ScriptBlock but please let me know if I'm doing something wrong. 

Pode Version: Github Develop 
OS Windows 11
Powershell:  7.3.7

**Comment by mdaneri** [comment]
in the meantime, I'm going to workaround the issue using: 
`Add-PodeRoute -PassThru -Method Get -Path '/api/v1/helloConvertedFile/:id'  -ScriptBlock ([ScriptBlock]::Create( (Get-Content -Path '.\test.ps1' -Raw)))`

It's working fine for me.

**Comment by Chris--A** [comment]
I didn't realize there is a `-FilePath` parameter, I've been doing basically the same thing:

```PowerShell
Start-PodeServer -Threads $Script:Threads -RootPath $Script:WebRoot -ScriptBlock { . .\Server.ps1}
```

This is so I can make changes and just restart without having to close the server entirely.

**Comment by Badgerati** [comment]
Hi @mdaneri,

In the file you have to "return" a scriptblock, in Pode the file is dot-sourced rather than the content loaded raw; this lets you create custom functions in the same file as well

For your route above:
```powershell
{
    $Id = $WebEvent.Parameters['id'] 
    Write-PodeJsonResponse -StatusCode 200 -Value @{'id' = $Id }
}
```

or
```powershell
return {
    $Id = $WebEvent.Parameters['id'] 
    Write-PodeJsonResponse -StatusCode 200 -Value @{'id' = $Id }
}
```


(https://badgerati.github.io/Pode/Tutorials/Routes/Overview/#script-from-file)

**Comment by mdaneri** [comment]
I thought it was like   `Add-PodeRoute -PassThru -Method Get -Path '/api/v1/helloConvertedFile/:id'  -ScriptBlock ([ScriptBlock]::Create( (Get-Content -Path '.\test.ps1' -Raw)))`

My bad now it's clear what is the scope of the FilePath parameter

**Comment by mdaneri** [comment]
I think I can close this issue.
