### ISSUE TITLE
Add-PodePage giving error 404 on browser

### ISSUE THREAD

**Issue by peracchi** [Badgerati/Pode#1143]
### Describe the Bug
Example from https://badgerati.github.io/Pode/Tutorials/Basics/ do not work, gives 404 error.

### Steps To Reproduce
1. Go to https://badgerati.github.io/Pode/Tutorials/Basics/
2. Save example code to server.ps1
3. pode start
4. access address on browser
5. See error 404

### Expected Behavior
Processes running on server

### Screenshots
![image](https://github.com/Badgerati/Pode/assets/1372058/b979a99c-7df9-4e37-ab13-98ea9a635eaf)

### Platform
 - OS: Alpine Linux edge x86_64
 - Browser: Firefox 118.0.1
 - Versions:
   - Pode: 2.8.0
   - PowerShell: 7.3.7

### Additional Context
The code giving error 404 on browser is:

```
Start-PodeServer {
    # attach to port 8080 for http
    Add-PodeEndpoint -Address * -Port 8080 -Protocol Http

    # a simple page for displaying services
    Add-PodePage -Name 'processes' -ScriptBlock { Get-Process }
}

```

**Comment by Badgerati** [comment]
Hi @peracchi,

What happens if you navigate to `http://10.4.2.126:8080/processes`? Looking at the image above is appears only `http://10.4.2.126` is being loaded?

**Comment by peracchi** [comment]
> Looking at the image above is appears only `http://10.4.2.126` is being loaded?

Yes, you are right.

Using `http://10.4.2.126:8080/processes` page loads correctly.

Sorry, my fault, I assumed that without the "Path" parameter the route would be '/'.

Now I see that the "Name" parameter acts like the "Path" parameter, right?

**Comment by Badgerati** [comment]
Sort of yes, The `-Path` parameter on `Add-PodePage` is default to `/` and the `-Name` is appended onto the path. So if you set the  path to be `/pages` and the name as `processes` then it would be accessible at `/pages/processes`.

**Comment by Badgerati** [comment]
Hey @fatherofinvention, yes that's correct. It's only meant as a way to create really simple quick named pages, for pages on `/` using `Add-PodeRoute` would be better.
