### ISSUE TITLE
Error: No extension vaults registered when adding secret

### ISSUE THREAD

**Issue by fatherofinvention** [Badgerati/Pode#1180]
### Describe the Bug
Hey @Badgerati . Maybe it's late and I'm just missing something, or maybe this is a bug. I am trying to use Pode's secret functions but am hitting an error. I've installed Microsoft.PowerShell.SecretManagement and Microsoft.PowerShell.SecretStore and they are imported. I ran `Register-PodeSecretVault -Name 'MyVault' -ModuleName 'Microsoft.PowerShell.SecretStore'` to register the vault, and which ostensibly worked without error, but when I run `Get-PodeSecretVault -Name 'MyVault'` I see a number of things that make me question if it succeeded and is fully ready to use but I'm not sure, maybe it is OK that these values are false:

![CleanShot 2023-11-02 at 22 12 05@2x](https://github.com/Badgerati/Pode/assets/24985048/d8358553-fc9c-42c2-8348-5343960d3a3a)

When I run `Test-PodeSecretVault -Name 'MyVault'` it says 'True' so it seems like it should be ready to go, but then when I run `Set-PodeSecret -Key 'path/to/key' -Vault 'MyVault' -InputObject 'test' I get this:

![CleanShot 2023-11-02 at 22 15 27@2x](https://github.com/Badgerati/Pode/assets/24985048/23abb538-1fbf-4719-817b-f06818434233)

So in spite of registering and testing the Vault, and in the docs seeing this I'm confused 🤷‍♂️. Have I done something wrong or missed a step? 

![CleanShot 2023-11-02 at 22 16 40@2x](https://github.com/Badgerati/Pode/assets/24985048/500a02af-feed-4e36-b7f4-6840f60c5dca)

Thank you!

**Comment by Badgerati** [comment]
I wouldn't worry too much about Unlock.Enabled and AutoImported, those are just properties Pode sets to know if the module needs unlocking or if it was automatically imported.

From what you've said it looks like it should be working, as you're correct, Pode will create/register the vault for you 🤔 Do you have a fuller script I could look at, and I'll test on my side to see what happens.

Thanks

**Comment by Badgerati** [comment]
The "Vault not found" is something I need to look into, but for the way to create/access secrets you're looking at a combo of [creating a secret](https://badgerati.github.io/Pode/Tutorials/Secrets/Overview/#create) and then [mounting a secret](https://badgerati.github.io/Pode/Tutorials/Secrets/Overview/#mounting).

In your case, you'll want to create the secret in a vault first (`Set-PodeSecret`), and then mount it into Pode afterwards (`Mount-PodeSecret`) for use as a specific "SecretName". After that, you can use `$secret:SecretName`:

```powershell
Set-PodeSecret -Key 'db/masterKey' -Vault 'MyVault' -InputObject 'test123!'
Mount-PodeSecret -Name 'SomeSecretName' -Vault 'MyVault' -Key 'db/masterKey'
$secret:SomeSecretName
```

**Comment by Badgerati** [comment]
I've added in some better default parameter handling when using SecretStore, but the crux of the issue was that a Password for the vault needed to be supplied, and then unlocked periodically.

I've put together some documentation on how to use SecretStore, but ultimately the `-UnlockSecret` parameter is required and will be properly handled when the commit above is released:

```powershell
Register-PodeSecretVault -Name 'MyVault' -ModuleName 'Microsoft.PowerShell.SecretStore' -UnlockSecret 'My$ecret!'
```

Setting, Mounting, and using `$secret:` all remain unchanged.
