### ISSUE TITLE
Pester issues with PWSH 7.4

### ISSUE THREAD

**Issue by mdaneri** [Badgerati/Pode#1185]
with PWSH 7.4 some of the interop testing are failing.
I created a new DLL for .NET 8.0 and everything start to work as expected.

**Comment by mdaneri** [comment]
Update 
Pester will hung during the restful test.
The only way to leave the test is to use CTRL C

**Comment by mdaneri** [comment]
@Badgerati  milestone 2.10

**Comment by Badgerati** [comment]
Resolved in #1136
