### ISSUE TITLE
Only support netstandard2.0 and net8 builds

### ISSUE THREAD

**Issue by Badgerati** [Badgerati/Pode#1189]
### Describe the Change
To save having to compile the Pode DLL for multiple versions of .NET and PowerShell, it would be simpler to only compile Pode to support Windows PowerShell 5.1 and the latest PowerShell version (7.4 currently) - anything in between would use the same DLL as 5.1.

To achieve this, we can compile Pode using netstandard2.0, which every version of PowerShell will default to using. And then compile Pode using the latest version of .NET (ie: .NET8), and this version will be used by the latest version of PowerShell.

For example:
* PS5.1, 6, 7, 7.1, 7.2 and 7.3: `netstandard2.0`
* PS7.4: `net8.0`

When PS7.5 rolls around, then 7.4 will default to netstandard2.0, and net9.0 used for 7.5.

**Comment by mdaneri** [comment]
My suggestion is to still maintain net7 until 7.2 is eol

![image](https://github.com/Badgerati/Pode/assets/17148649/b1cad29a-7ae3-4fc7-a913-5172b2972e03)

**Comment by Badgerati** [comment]
Agreed, in which case we could just support anything that is currently in support (assuming PS7.3 is unsupported at this point, as it is ~1 month away):

* =PS7.4 uses net8.0
* \>=PS7.2+ uses net6.0
* <=PS7.1 uses netstandard2.0

So when PS7.5 rolls around, and PS7.2's support expires, it would be:

* =PS7.5 uses net9.0
* =PS7.4 uses net8.0
* <=PS7.3 uses netstandard2.0
