### ISSUE TITLE
How to set header like this

### ISSUE THREAD

**Issue by ericxin1982** [Badgerati/Pode#1195]
### Question
A clear and concise description of your question.

Hi @Badgerati 

I want to make all html has no cache, and nginx it seems has this way, and how about pode?
![image](https://github.com/Badgerati/Pode/assets/9047436/e9c0294d-f617-459d-8812-1e0f0634f583)

Thanks
Eric Xin

**Comment by ericxin1982** [comment]
Hi @Badgerati 

Just wondering whether access static html file can be set to must provide jwt or api key.

Thanks
Eric xin

**Comment by Badgerati** [comment]
Hi @ericxin1982,

If you're using `Add-PodeStaticRoute` to serve the static content then yes, this function can be supplied an `-Authentication` method to require JWT/API key.

If you're using the normal `/public` folder for static content then no, static content placed here is publicly available for all and you'll have to switch to using `Add-PodeStaticRoute` instead for anything that requires authentication.

**Comment by ericxin1982** [comment]
Thanks.
