### ISSUE TITLE
Swagger Authentication Options

### ISSUE THREAD

**Issue by port-43** [Badgerati/Pode#1198]
### Question
I am using a modified version of the api authentication scheme. It requires the client to provide an X-API-KEY and X-API-KEY-ID. These values are used to hash and store the key in a backend database. I am unable to use the swagger UI to test authenticated routes because there isn't an option to set the other required header. Is there a method to address this?

**Comment by mdaneri** [comment]
You can create 2 ApiKeys authentication schemas and merge them using     Merge-PodeAuth

**Comment by port-43** [comment]
Thanks for the quick response, I am looking through the docs but there isn't a good example of what is needed to in the -ScriptBlock for merging multiple authenticated users into 1.

**Comment by port-43** [comment]
I was able to figure out how to get it to work, unfortunately swagger only shows the two api key auth options and excludes the merged options. Populating both auth options doesn't work either because swagger doesn't include them when testing the route with merged auth setup.

**Comment by mdaneri** [comment]
I'm working on extending the Open API in Pode. This will be part of Pode 2.10
What you are asking is there. 
The code is completed so I'm not expecting any major changes.

Here is the link
https://github.com/mdaneri/Pode 

What is new : https://github.com/Badgerati/Pode/pull/1136

**Comment by mdaneri** [comment]
use the file https://github.com/mdaneri/Pode/blob/develop/examples/PetStore/Petstore-openApi.ps1 
   and change the lines 180,181 and 182 adding the petstore_auth. 
    Merge-PodeAuth -Name 'merged_auth' -Authentication   'Basic', 'api_key','petstore_auth'  -Valid One
    Merge-PodeAuth -Name 'merged_auth_All' -Authentication   'Basic', 'api_key','petstore_auth'   -Valid All -ScriptBlock {}
    Merge-PodeAuth -Name 'merged_auth_nokey' -Authentication   'Basic','petstore_auth'   -Valid One

After this change no paths are accessible
