### ISSUE TITLE
Not displaying images the easy way.

### ISSUE THREAD

**Issue by LLIT** [Badgerati/Pode#12]
I have been trying to display some images, but it is not working.

The workaround that i found was to base64 encode them in a Pode file.
img src="data:image/png;base64,$([convert]::ToBase64String((Get-Content image.png -Encoding byte)))" alt="png"
It is working, but i have to rewrite some pages.

Do you thing it will be fixed in a newer version?
I am on the newest commit: 9132d7debad57974501a5fa6ae9a55ac860b1ff1

**Comment by Badgerati** [comment]
Just saw this in the nick of time!

I've taken a look and put a fix into the `images` branch; tested it myself and pages still render, but also with png, jpg and gifs using the below (assuming there at the route of the `public` folder):

```
<img src="image.png" />
```

If you want to quickly make sure it works let me know, or i'll just merge and deploy the next release :)

**Comment by LLIT** [comment]
Still no luck,
I am testing on a Windows Server 2012 R2.

By the wat, I am trying to make something simple to add HTTPS support.
It is worknig for now, but it is not pretty.

**Comment by Badgerati** [comment]
Hmm, I've added in a quick fix for powershell core, and tested it on 2016 with PS5.1, and on windows/linux with PSCore (6.0) - each of which work.

I'll spin up a 2012 machine in a bit - which version of PS are you running? If not core, are you able to install core on the server?

**Comment by LLIT** [comment]
The server is running PS 5.1.

**Comment by Badgerati** [comment]
Just tested on a 2012 R2 machine running PS5.1, using the current `images` branch, and the `web-pages.ps1` script in the examples dir loads the image for myself.

Are you able to give me the code for your page, or a mocked example/excerpt?

**Comment by LLIT** [comment]
I have now tested with the new code, and it is working.
Just for the fun of it, I replaced the /scr folder for my own project, and all is working 100% :-)

**Comment by Badgerati** [comment]
Awesome! I'll get that set for the next release then
