### ISSUE TITLE
how to set cache-control per extension type

### ISSUE THREAD

**Issue by ericxin1982** [Badgerati/Pode#1200]
[### Question
A clear and concise description of your question.
]
(https://stackoverflow.com/questions/32987486/iis-setting-cache-control-header-per-file-type)

Is it possible to achieve this as well?

Thanks
Eric Xin

**Comment by Badgerati** [comment]
Hi @ericxin1982,

One way to achieve this would be to use Pode's [Endware](https://badgerati.github.io/Pode/Tutorials/Endware/), assuming this is static content, you could create an Endware which pattern matches against the supplied Path:

```powershell
Add-PodeEndware -ScriptBlock {
    if ($WebEvent.Path -ilike '*.html') {
        Set-PodeHeader -Name 'Cache-Control' -Value '<value>'
    }
}
```

Hope that helps :)

**Comment by ericxin1982** [comment]
That is so great, thanks.

**Comment by ericxin1982** [comment]
Sorry to ask further.
![image](https://github.com/Badgerati/Pode/assets/9047436/36ec2d15-d32a-4aa4-9fd1-9327f7a28ba0)
If the Cache-Control has two rows, how to do?

Thanks
Eric Xin

**Comment by Badgerati** [comment]
Hi @ericxin1982,

Are you able to show a code example of what you have? Called `Set-PodeHeader` should override any previously set and force on one header - unless there's a process higher up than Pode setting the header also?

**Comment by mdaneri** [comment]
Let me modify the sample to include the issue

**Comment by ericxin1982** [comment]
@Badgerati 

I set one cache-control in middleware, and set one in endware, and the endware would overwrite the previous setting. I do not have to have two cache-control, but I just showed you IIS would have two or multiple but pode just can have one only.

Thanks
Eric Xin

**Comment by Badgerati** [comment]
Hi @ericxin1982,

Ah right I see, so you want two. In which case using `Add-PodeHeader` would do this, as it would "add" multiple versions of that header; calling "set" at any point will override any multiple added values and force it back to just one.

**Comment by ericxin1982** [comment]
Got it.
