### ISSUE TITLE
Using Pode instead of electron or tauri

### ISSUE THREAD

**Issue by ericxin1982** [Badgerati/Pode#1227]
Hi @Badgerati 

I remembered Pode has self-server feature? is it possible to replace electron or tauri, just curious how to use the self-server like feature.

Thanks
Eric Xin

**Comment by RobinBeismann** [comment]
Hi @ericxin1982,

check out this page, it describes how to use it: https://badgerati.github.io/Pode/Tutorials/Misc/DesktopApp/
It is not a drop-in replacement for Electron as it still spawns a socket and takes a bit longer to initialize. But depending on the use case, it might be a good fit.

**Comment by ericxin1982** [comment]
Right, right. That is what I remembered, ok, I think I can try to fit there, thanks.
