### ISSUE TITLE
Scheduled Tasks Not Running in Pode PowerShell on IIS

### ISSUE THREAD

**Issue by ThomasPerezBlanco** [Badgerati/Pode#1233]
Hello,

I am experiencing an issue with scheduled tasks in Pode, when hosted on IIS. Despite setting the application pool to AlwaysRunning and preloading enabled, the scheduled tasks in Pode do not seem to initiate unless a web request is made to the server. This behavior suggests that IIS is not initializing the application until it receives the first request, which is interfering with the execution of Pode's scheduled tasks.

Here are the steps I've taken so far:

Set the application pool Start Mode to AlwaysRunning.
Enabled Preload for the application in IIS.
Ensured Idle Time-out is set to 0 for the application pool.
Configured web.config with the appropriate handlers and modules for Pode.
However, the scheduled tasks only start working after the first HTTP request is received. This issue persists even after restarting the application pool. It's as if the application needs a request to kick off the scheduled tasks, which should not be the case as they should run regardless of web traffic.

Has anyone faced a similar issue or can suggest additional configurations that might resolve this problem? Any help or insight would be greatly appreciated.

Thank you!

**Comment by RobinBeismann** [comment]
Do you see pwsh.exe running on the server that is hosting IIS while the tasks are not being executed (before you do the webrequests)?

I'm running multiple instances on IIS, however we have them running on multiple servers at the same time with a load balancer in front, so the healthchecks are keeping our instances alive.
One of them was running without load balancer before and that was executing scheduled tasks just fine, but there I'm also sure that IIS was not recycling the app pool.

**Comment by Badgerati** [comment]
We have a similar setup where I work, with a Pode site being IIS with schedules and timers. Whenever the app-pool recycles IIS needs a minimum of one HTTP request to the site before it actually spins up the pwsh process behind the IIS site.

It's not bothered us too much, as we also have health checks that help to keep the site alive - or start the process up against quickly. So I've never needed to see if there's a way to tell IIS to start the process without that HTTP.

When I was looking originally I didn't see anything, but that might have changed with IIS updates. 🤔

**Comment by Badgerati** [comment]
It depends on your setup, using Windows Scheduled Tasks is one way. For myself we have some that are kept alive via Azure Load Balancer health probes, and some via Kubernetes liveness probes.

**Comment by ThomasPerezBlanco** [comment]
Thanks for your feedback, sorry for the delay in closing the post.
