### ISSUE TITLE
Server Requests Timeout

### ISSUE THREAD

**Issue by jbaechtelMT** [Badgerati/Pode#1235]
### Question
I have set the Requests Timeout value to 600 (10 mins.) for long running script pages.

Yet when running very long script pages, it still times out in 3 mins. and 30 seconds.  Is there a maximum value being reached for Requests Timeout?

See Pode.Web Related Issue: [https://github.com/Badgerati/Pode.Web/issues/529](url)

Pode Version:      2.9.0
Pode.Web Version:  0.8.3

Thanks,

**Comment by jbaechtelMT** [comment]
Pode Version:  2.8.0

**Comment by Badgerati** [comment]
Hi @jbaechtelMT,

Is this timing out after 3mins 30secs when accessing a page via the browser, or via CLI? Does the same timeout occur in a different browser? As it could be a cut-off from the browser itself.

**Comment by Badgerati** [comment]
Hi @jbaechtelMT, see comment over on https://github.com/Badgerati/Pode.Web/issues/529, it's a browser related issue.
