### ISSUE TITLE
Test-PodeTaskCompleted always returns false?

### ISSUE THREAD

**Issue by plk** [Badgerati/Pode#1240]
I am running an async task from one endpoint and getting the status using another endpoint which uses the task name. I want to return the results from the async task when it's finished but Test-PodeTaskCompleted always seems to return false,even when the asynce task scriptblock is finished?

**Comment by Badgerati** [comment]
This is similar to an issue just raised (#1249), the underlying cause is that `Get-PodeTask` returns the base task definition created by `Add-PodeTask`, and not a processing task object like `Invoke-PodeTask` returns.

(linked to #1037)

**Comment by Badgerati** [comment]
In 2.11.0 they'll be a new `Get-PodeTaskProcess` (via #1393) which will enable the retrieving of Task processes which can be used by `Test-PodeTaskCompleted`.
