### ISSUE TITLE
Routes order

### ISSUE THREAD

**Issue by mdaneri** [Badgerati/Pode#1247]
Is there a reason why static routes are checked before any non-static ones?
The question is related to this sample: ( $directoryPath is the PodePath)

```PowerShell
# Start Pode server
Start-PodeServer -ScriptBlock {

    Add-PodeEndpoint -Address localhost -Port 8080 -Protocol Http -Default
   Add-PodeRoute -Method Get -Path '/LICENSE.txt' -ScriptBlock {
        $value=@"
Don't be kidding. Nobody will believe that you want to read this legalise nonsense.
I want to be kind; this is a summary of the content:

Nothing to report :D
"@
        Write-PodeTextResponse -Value $value
    }
    Add-PodeStaticRouteGroup -FileBrowser  -Routes {
        Add-PodeStaticRoute -Path '/' -Source $using:directoryPath -FileBrowser  
    }
}
```

in theory, the code should hide the LICENSE.TXT file, but today, this code is not working because Static routes are checked before  
anything else.

It is a problem if we switch the order `Static->Anything else` to `Anything else ->Static`. Or at least make this configurable.

I did some tests and cannot see any side effects from changing that.

@Badgerati, what are your thoughts? 

Thanks

**Comment by ArieHein** [comment]
The order is static routes first, then normal non-static routes.
It is configurable - https://badgerati.github.io/Pode/Tutorials/Routes/Utilities/StaticContent/#static-routes-order
