### ISSUE TITLE
Pode cannot listen on both ipv6 and ipv4 unspecified addresses at the same time - it should be able to

### ISSUE THREAD

**Issue by araemo** [Badgerati/Pode#1251]
### Describe the Bug
Since #915 was fixed, pode can now listen on an ipv6 unspecified address, but it cannot listen on both ipv6 and ipv4 unspecified addresses at the same time.

### Steps To Reproduce
```Powershell
Start-PodeServer -ScriptBlock {
  Add-PodeEndpoint -Address '::' -Port 8080 -Protocol http
  Add-PodeEndpoint -Address '0.0.0.0' -Port 8080 -Protocol http

  Add-PodeRoute -Method Get -Path /meat -ScriptBlock {
    Write-Host -Object (Get-Random -InputObject @('Bacon', 'Sausage', 'Steak', 'Italian Sausage', 'Beef'))
    Write-PodeTextResponse -Value success
  }
}
```

Result:
```Powershell
> Get-NetTCPConnection -State Listen -LocalPort 8080

LocalAddress                        LocalPort RemoteAddress                       RemotePort State       AppliedSetting
------------                        --------- -------------                       ---------- -----       --------------
::                                  8080      ::                                  0          Listen
```

Or, if you do ipv4 first:
```Powershell
Start-PodeServer -ScriptBlock {
  Add-PodeEndpoint -Address '0.0.0.0' -Port 8080 -Protocol http
  Add-PodeEndpoint -Address '::' -Port 8080 -Protocol http

  Add-PodeRoute -Method Get -Path /meat -ScriptBlock {
    Write-Host -Object (Get-Random -InputObject @('Bacon', 'Sausage', 'Steak', 'Italian Sausage', 'Beef'))
    Write-PodeTextResponse -Value success
  }
}
```

Result:
```Powershell
> Get-NetTCPConnection -State Listen -LocalPort 8080

LocalAddress                        LocalPort RemoteAddress                       RemotePort State       AppliedSetting
------------                        --------- -------------                       ---------- -----       --------------
0.0.0.0                             8080      0.0.0.0                             0          Listen
```

### Expected Behavior
BOTH listen addresses (IPv4 unspecified, aka 0.0.0.0, and IPv6 unspecified, aka '::') should be listening on the same port at the same time.

### Platform
 - OS: Windows Server build 20348.2322
 - Browser: N/A
 - Versions:
   - Pode: Pode 2.9.0
   - PowerShell: 5.1.20348.2227

### Additional Context
I suspect Pode is trying to dedupe the listen address before attempting to listen again.  In the interactive Pode output, both the ipv6 unspecified and ipv4 unspecified show up as:
```Powershell
Listening on the following 1 endpoint(s) [1 thread(s)]:
        - http://localhost:8080/
```

So, I would guess that Pode is resolving the address:port to `localhost:8080`, then seeing that it is already listening on `localhost:8080` and then does not attempt to create another listener.

I think this is the issue here:
https://github.com/Badgerati/Pode/blob/df86e0fb5fb37a30d684d79933b95734e4101286/src/Public/Core.ps1#L1006-L1008

But I am honestly having trouble following the logic of what hostname/friendlyname/address should/shouldn't be as that function progresses up to that point.

**Comment by araemo** [comment]
While implementing a workaround to get all the local addresses and listen on them individually, I am pretty sure this also prevents listening on both IPv4 loopback and IPv6 loopback at the same time.  Probably for the exact same reason.

**Comment by Badgerati** [comment]
Hi @araemo,

A related issue was flagged on the Discord recently, and it was found that .NET Sockets have support for a "DualMode" which should allow a single socket to listen on the IPv4 and v6 for a single address - https://devblogs.microsoft.com/dotnet/dual-mode-sockets-never-create-an-ipv4-socket-again/

I'm going to investigate adding a `-DualMode` switch onto `Add-PodeEndpoint` to enable this, and was also planning on having this support enabled by default for the localhost address.

**Comment by araemo** [comment]
Yep, listening on all both the ipv4 and ipv6 'any' addresses at once would address this nicely.
