### ISSUE TITLE
Add-PodeAccessCustom -route

### ISSUE THREAD

**Issue by ericxin1982** [Badgerati/Pode#1252]
![image](https://github.com/Badgerati/Pode/assets/9047436/c72d1ef3-c8c8-4e4b-9178-79bce5c7b456)

Hi all,

Sorry to ask since I cannot see further example, I am wondering where I can find the real cases to use route parameters.

Thanks
Eric Xin

**Comment by mdaneri** [comment]
I don't have an answer; I have never used it. What are you trying to accomplish?

**Comment by ericxin1982** [comment]
Nevermind, I come up a better question and ask again.
