### ISSUE TITLE
return special message and different 40x code

### ISSUE THREAD

**Issue by ericxin1982** [Badgerati/Pode#1255]
![image](https://github.com/Badgerati/Pode/assets/9047436/4424edbd-0ac5-4dfc-a835-6718885a286f)

Hi,

Like this above, I understand if username is not equal to morty, then would return $null as 40x whatever, but that is default error code and error message. If I return $null and with custom error code and error message, how to do ?
Since I saw documentation mentioned different code and message, but there is no return $null there.
How come, I am always puzzled, please help me verify!

Thanks
Eric Xin

New-PodeAuthScheme -ApiKey -Location $Location -AsJWT | Add-PodeAuth -Name 'Validate' -Sessionless -ScriptBlock {
        param($jwt)

        # here you'd check a real user storage, this is just for example
        if ($jwt.username -ieq 'morty') {
            return @{
                User = @{
                    ID ='M0R7Y302'
                    Name = 'Morty'
                    Type = 'Human'
                }
            }
        }
        ??????????????????????
        return $null
    }

**Comment by mdaneri** [comment]
By default, Add-PodeAuth always returns a 401 code.
But there is a simple workaround.

```PowerShell
if ($jwt.username -ieq 'morty') {
	return @{
		User = @{
			ID ='M0R7Y302'
			Name = 'Morty'
			Type = 'Human'
		}
	}
}else{
	return @{
		User = @{
			errorId=932
			errorMsg='something is wrong'
		}
	}
}

```

Inside your route script, you can check the user content using `$WebEvent.Auth.User` and return the proper error message

**Comment by ericxin1982** [comment]
I see, thanks.
