### ISSUE TITLE
Server stops with errors "Collection was modified after..."

### ISSUE THREAD

**Issue by nightroman** [Badgerati/Pode#1257]
### Describe the Bug

Server stops with the error "Collection was modified after the enumerator was instantiated."

### Steps To Reproduce

[2024-03-25-server-stops.zip](https://github.com/Badgerati/Pode/files/14739006/2024-03-25-server-stops.zip)

(1) Start the attached `server.ps1`, rather trivial one route server.

(2) In the opened browser keep refreshing the page with brief processes details.
Alternatively, run the attached `loop.ps1` which sends similar requests in a loop.

(3) At some point, sometimes soon or after a while, the server stops with errors like:

```
Test-PodeRestartPressed: C:\Program Files\WindowsPowerShell\Modules\Pode\2.9.0\Public\Core.ps1:194
Line |
 194 |  … t.IsCancellationRequested) -or (Test-PodeRestartPressed -Key $key)) {
     |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Collection was modified after the enumerator was instantiated.
```

Errors may be at different locations and about different keys tested.

### Expected Behavior

Ideally, the error should not happen, with its reasons avoided.

If this is not possible errors should be caught and ignored.

### Platform

 - OS: Windows 11
 - Browser: Chrome
 - Versions:
   - Pode: 2.9.0
   - PowerShell: 7.4.1

**Comment by mdaneri** [comment]
It's a bug due to the way Powershell deals with array and piping.

We have to make the `Write-PodeTextResponse` and `Write-PodeHtmlResponse` "piping compliance" 

Try this one 

```PowerShell
Start-PodeServer {
    Add-PodeEndpoint -Address localhost -Port 8081 -Protocol Http
    #working
    Add-PodeRoute -Path '/processes'  -Method Get -ScriptBlock {
        $r = Get-Process | .{ process { if ($_.WS -gt 100mb) { $_ } } } |
            Select-Object Name, @{e = { [int]($_.WS / 1mb) }; n = 'WS' } |
            Sort-Object WS -Descending

        Write-PodeHtmlResponse -Value $r  -StatusCode 200
    }
    #not working
    Add-PodeRoute -Path '/processesPipedNotWorking'  -Method Get -ScriptBlock {
        Get-Process | .{ process { if ($_.WS -gt 100mb) { $_ } } } |
            Select-Object Name, @{e = { [int]($_.WS / 1mb) }; n = 'WS' } |
            Sort-Object WS -Descending | Write-PodeHtmlResponse  -StatusCode 200
    }

    #this is like the previous one
    Add-PodePage -Name NotWorkingProcesses -ScriptBlock {
        Get-Process | .{ process { if ($_.WS -gt 100mb) { $_ } } } |
            Select-Object Name, @{e = { [int]($_.WS / 1mb) }; n = 'WS' } |
            Sort-Object WS -Descending
    }

    Start-Process http://localhost:8081/processes
}
```

**Comment by mdaneri** [comment]
I found the real problem, and it's not related to the piping issue.
 ![image](https://github.com/Badgerati/Pode/assets/17148649/153978b3-6b5b-416b-a58c-18b99cbdffbc)


I'm going to open a bug for the piping issues with arrays
