### ISSUE TITLE
Migration to Pester 5.5

### ISSUE THREAD

**Issue by mdaneri** [Badgerati/Pode#1260]
### Describe the Change
Migrate all tests to Pester 5.5

**Comment by mdaneri** [comment]
I fixed the test for pwsh 7.4 but I broke it for 5.1 🗡️ 

I'm trying to fix it

**Comment by mdaneri** [comment]
I get a strange error with 5.1
https://github.com/mdaneri/Pode/actions/runs/8443196196

I don't know what to do here

**Comment by mdaneri** [comment]
test passed with pwsh 7.3.10, 7.4.1 , 7.5 preview
test failed with 5.1 
```
 PSInvalidOperationException: There is no Runspace available to run scripts in this thread. You can provide one in the DefaultRunspace property of the System.Management.Automation.Runspaces.Runspace type. The script block you attempted to invoke was:  $true 
  WebException: The underlying connection was closed: An unexpected error occurred on a send.
```

**Comment by Badgerati** [comment]
@mdaneri 

It'll be this line, it's not needed:
```powershell
[System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $true }
```

**Comment by mdaneri** [comment]
I forgot to remove it 👯

**Comment by mdaneri** [comment]
done everything is working now

**Comment by Badgerati** [comment]
Awesome, once the jobs on the PR finish I'll get it merged

**Comment by mdaneri** [comment]
still I don't understand why invoke-restmethod doesn't work
