### ISSUE TITLE
Request Header information

### ISSUE THREAD

**Issue by LLIT** [Badgerati/Pode#13]
To get the information from the header, the following code will work.

In the Start-WebServer, right after you define the content type:

[System.Collections.Specialized.NameValueCollection]$headers = $request.Headers
                    $HeadersArray = foreach ($key in $headers.AllKeys){
                        [array]$values = $headers.GetValues($key);
                        if($values.Length -gt 0) {
                            New-Object psobject -Property ([ordered]@{
                                HeaderName  = $key
                                HeaderValue = $values[0]
                            })
}
}

And this to add it for the output.
$PodeSession.Web.Headers = $HeadersArray

**Comment by Badgerati** [comment]
With the request object already in `$PodeSession.Web.Request` and the `$PodeSession.Web` object being passed through to each `route`; you can do `$session.Request.Headers['Host']` to get header values in routes:

```powershell
route 'get' '/' {
        param($session)

        $session.Request.Headers.Keys | %{
            write-host $session.Request.Headers[$_]
        }
}
```

Are you able to use this or is there something that's restricted your over snippet overcomes?

**Comment by LLIT** [comment]
Looks way easier than what i found.
It was some C# rewtritten to Powershell.

I was just playing arround with some authentication, to see what was possible.

**Comment by Badgerati** [comment]
Aah, I see; always more complicated with C# converted to PowerShell 😛
