### ISSUE TITLE
Add-PodeAuthIIS ScriptBlock no param $user

### ISSUE THREAD

**Issue by jsg91** [Badgerati/Pode#1392]
### Describe the Bug
Example https://badgerati.github.io/Pode/Hosting/IIS/#additional-validation doesn't work starting from v2.10.0, because $user is not passed as parameter. Workaround is to use $user = $arguments and then it all works. Seems to be related to the variable scoping changes, as also $session: within that ScriptBlock no longer works (or might not be related at all...).

### Steps To Reproduce
1. Have a Pode instance ready on IIS
2. Add the example to the code and have a route using that Auth
4. Try accessing it

### Expected Behavior
For it to work as before update...

### Platform
 - OS: Windows
 - Browser: Any
 - Versions:
   - Pode: v2.10.0, v2.10.1
   - PowerShell: 7

**Comment by Badgerati** [comment]
Managed to reproduce, and appears to affect some other Authentication methods as well. Fixed both User and Session issues in the above commit :)
