### ISSUE TITLE
Set-PodeOAGlobalAuth failure on launch

### ISSUE THREAD

**Issue by tylrtrst** [Badgerati/Pode#1406]
### Describe the Bug
After upgrading from 2.10.1 to 2.11.0, Pode fails to launch and outputs the following error to console:

```
Pode v2.11.0 (PID: 1)
Set-PodeOAGlobalAuth: /usr/local/share/powershell/Modules/Pode/Public/Authentication.ps1:1645
Line |
1645 |      Set-PodeOAGlobalAuth -DefinitionTag $DefinitionTag -Name $Authent …
     |                                          ~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'DefinitionTag' because it is an empty
     | string.
```
reverting back to 2.10.1 corrects the problem.

### Steps To Reproduce
Update from 2.10.1 to 2.11.0
Run Pode
View console

### Expected Behavior
Expecting Pode to launch without error

### Platform
 - OS: Linux (Docker image badgerati/pode:2.11.0-alpine)
 - Versions:
   - Pode: 2.11.0

### Additional Context
I am not making use of the OpenAPI feature and have not enabled it.
I have defined 2 auth schemes, both of type: API Key. Only one of which is being applied via middleware.

**Comment by mdaneri** [comment]
I’m not able to reproduce the issue can you please give a sample?

**Comment by mdaneri** [comment]
Let me try it

**Comment by mdaneri** [comment]
I'm able to reproduce it.
**Workaround:**
Add a `server.psd1` file with at least this content:

```powershell
@{
    Web    = @{
        OpenApi     = @{
        }
    }
}
```
