### ISSUE TITLE
OpenAPI 3.1 supports Body for DELETE method

### ISSUE THREAD

**Issue by jsg91** [Badgerati/Pode#1432]
### Describe the Bug
OpenAPI 3.1 supports Body for DELETE method, if condition in OpenApi.ps1 doesn't allow it: https://github.com/Badgerati/Pode/blob/f8c51b7f907fd8efd3c43dd97f9a7ed3367c5602/src/Public/OpenApi.ps1#L814

### Steps To Reproduce
1. Set up a DELETE API requiring a body
2. Start server
4. See error in ErrorLog

### Expected Behavior
Should work, especially if Enable-PodeOpenApi -OpenApiVersion is defined as "3.1.0"

**Comment by jsg91** [comment]
From what I've seen, one *should* avoid using a Body for a DELETE. However, I have a requirement where the delete calls need a few more parameters than I want to put in the URL. For that very reason, probably OpenAPI allows it in their latest standard. Thus it's hindering in my case for Pode to not allow it

**Comment by mdaneri** [comment]
You can pass the body content as a JSON/YAML/XML header.
That is supported

**Comment by mdaneri** [comment]
Do you have a link that says Delete body is supported openapi?

**Comment by jsg91** [comment]
> Do you have a link that says Delete body is supported openapi?

https://spec.openapis.org/oas/v3.1.0.html#operation-object under Field Name requestBody
