### ISSUE TITLE
Status code in response

### ISSUE THREAD

**Issue by LLIT** [Badgerati/Pode#16]
Is there a reason wht the function Status is not exported?
Is it posible to add status code in all of the responses?

**Comment by Badgerati** [comment]
Nor is the `Include` function, spooky! 👻 I'll get a hot fix out for them tonight.

To set the status code for the time being you can do it the old way of `$session.Response.StatusCode = 201` from each of the `route` blocks.

**Comment by Badgerati** [comment]
Fixed and released.
