### ISSUE TITLE
Add modules section to package.json file, and save to ps_modules on "pode install"

### ISSUE THREAD

**Issue by Badgerati** [Badgerati/Pode#162]
This is an extension to the `package.json` functionality, by adding a new `modules` section to it. This `modules` section will be like the `dependencies` but for PowerShell modules. Running `pode install` from the terminal will auto-install any modules from the PSGallery to a local `ps_modules` directory (like `pode_modules`).

This allows you to specify which modules your server depends on, and which versions of those modules - and without having to install them globally to the machine.

* Running `pode install` will check if there are any modules in the `package.json`. If they exist, they will be downloaded and saved to a `ps_modules` directory (`Save-Module`).
* Update the `import` function to auto-look in the `ps_modules` directory first for non-path modules

example:
```json
{
    "modules": {
        "EPS": "0.5.0"
    }
}
```

Doing `pode install` will download a local copy of the `EPS` module to `ps_modules/EPS/0.5.0`. Calling `import eps` in your script will first check the `ps_modules`, then check global modules.

> This should make it easier to install dependency modules in docker containers, plus elsewhere.

**Comment by majkinetor** [comment]
Hmm...  not sure what to think about that. Seems like intrusion in another domain and breaking of core Unix principles. You can easily add tone of other options here like proxy, different sources, smart versioning etc... Not sure if its worth it. 

There is PSDepend you could use here, tho I think its not that great. I am making my own one which works with random repositories, not sure when tho...

**Comment by majkinetor** [comment]
So you say its basically more limited form of:

```ps1
Install-Module -Name EPS -Version 0.5.0
./pode.ps1
```

😃

**Comment by Badgerati** [comment]
😂 Pretty much!
