### ISSUE TITLE
The property 'Type' cannot be found on this object

### ISSUE THREAD

**Issue by LLIT** [Badgerati/Pode#173]
I get the following error when i try to start Pode version 0.25.0
The property 'Type' cannot be found on this object. Verify that the property exists and can be set.
At C:\Program Files\WindowsPowerShell\Modules\Pode\0.25.0\Tools\Session.ps1:370 char:13
             $PodeSession.Server.Type = $_type
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : PropertyNotFound

When i run version 0.23.0 everything works.

I have testet on Server 2008 R2 and Server 2012 R2, and i get the same error.

Both modules are installed with "Install-Module" command.

Server 2008 R2:
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Server 2012 R2:
Name                           Value
----                           -----
PSVersion                      5.1.14409.1018
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1018
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by Badgerati** [comment]
That's interesting, because the `Session.ps1` file doesn't exist anymore 🤔 as it was renamed in #160 .

The Chocolatey installer appears to be all right, but for some reason the PowerShell Gallery module still thinks the `Session.ps1` exists.

I'll investigate later, for now installing via Chocolatey or removing the `Session.ps1` file manually should resolve it. (Or dropping back to v0.24.0/v0.23.0)

**Comment by Badgerati** [comment]
@LLIT I've just pushed a v0.25.1 to the PowerShell Gallery with the `Session.ps1` file removed, should resolve your error now

**Comment by LLIT** [comment]
Thanks a lot :)
Everything is working now in 0.25.1
