### ISSUE TITLE
Post/Put data is empty in 0.25.1

### ISSUE THREAD

**Issue by LLIT** [Badgerati/Pode#176]
When posting using body, the server returns an empty value.
Running 0.23.0 $session.Data the posted data.

My Code:
route 'Post' '/WindowsUpdate/RunUpdate' {
    param($session)

    Write-Host "ModulePath: $((Get-Module Pode).Path)"
    Write-host "RequestBody: $($session.Data | ConvertFrom-Json)"
}

0.23.0 result:
0.0.0.0:443 already has a certificate bound
Listening on the following 1 endpoint(s) [1 thread(s)]:
        - https://localhost:443/
ModulePath: C:\Program Files\WindowsPowerShell\Modules\Pode\0.23.0\Pode.psm1
RequestBody: @{Servername=MyServer; user=MyUsername}

0.25.0
0.0.0.0:443 already has a certificate bound
Listening on the following 1 endpoint(s) [1 thread(s)]:
        - https://localhost:443/
ModulePath: C:\Program Files\WindowsPowerShell\Modules\Pode\0.25.1\Pode.psm1
ConvertFrom-Json : Invalid JSON primitive: System.Collections.Hashtable.
At E:\Pode\Plugins\WindowsUpdate\API\routes.ps1:48 char:48
     Write-host "RequestBody: $($session.Data | ConvertFrom-Json)"
                                                ~~~~~~~~~~~~~~~~
     CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
     FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

**Comment by Badgerati** [comment]
Hi @LLIT,

Would you be able to try just `Write-host "RequestBody: $($session.Data)"`? Testing locally this should already be a hashtable. Pode will automatically attempt to convert the body from JSON for you, based on the Content-Type of the request.

As to why dropping back to 0.23.0 works is strange, when I get a moment I'll test with 0.23.0 as well.

**Comment by Badgerati** [comment]
Oh, for both, do you have an example of the requests being made? Mostly just an example of the body and the content type?

**Comment by Badgerati** [comment]
Just managed to test with 0.23.0, and for me this line throws the same error as 0.25.1:

```powershell
Write-host "RequestBody: $($session.Data | ConvertFrom-Json)"
```

Changing to use `$session.Data` as a hashtable works. The call I'm using is:

```powershell
Invoke-WebRequest -Method post -Uri http://localhost:8085/WindowsUpdate/RunUpdate -Body '{"name": "bob"}' -ContentType 'application/json'
```

**Comment by LLIT** [comment]
Adding "ContentType 'application/json'" to my request fixed the request.
Must have been an Error 40 in my Rest client :-)
