### ISSUE TITLE
Module import fails

### ISSUE THREAD

**Issue by datenschieber** [Badgerati/Pode#190]
Trying to import a module via `import 'path/to/module.psd1'`fails with error message:

``` 
You cannot call a method on a null-valued expression.
At /usr/local/share/powershell/Modules/Pode/0.25.1/Tools/Context.ps1:498 char:9
+         $_.InitialSessionState.ImportPSModule($_path)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

The path and file exists. `Import-Module 'path/to/module.psd1'` executes without errors.

My environment:
* pode 0.25.1
* PSVersion 6.1.3
* PSEdition Core
* Mac OS X

**Comment by Badgerati** [comment]
Hi @datenschieber,

I've reproduced this myself on 0.25.1, in 0.26.0 it works - are you able to upgrade?

**Comment by datenschieber** [comment]
You're right. In 0.26.0 it works. Sorry for not checking for the latest version. Thought that 0.25.1 is the latest...
