### ISSUE TITLE
Request for a new release. Matching the documentation and several functions.

### ISSUE THREAD

**Issue by larssb** [Badgerati/Pode#2]
Hi Matthew, 

I really like your Pode repo. I have one challenge though. The documentation and some of the examples does not match the latest release available on DockerHub or/and the PowerShell module. For example the Pode and route functions are not in the latest public release. Will you update soon?

I guess I'll have to clone for now and go from there. But it will lovely to get an official release.

:+1:

**Comment by Badgerati** [comment]
Hey, glad you like it! 😊 

It's one of the things on my to-do list this week since I'm off work; I'll try and get it up for at some point this week.

**Comment by Badgerati** [comment]
Should no longer need to use `-t` any more: https://github.com/Badgerati/Pode#docker 😄 
(it now checks to make sure the console input isn't being redirected)

I've also released 0.10.0 to Docker and Chocolatey (pending moderation); PowerShell Gallery should be at some point tomorrow.

**Comment by Badgerati** [comment]
Up on PowerShell Gallery, too. Had to put out a quick hot-fix of 0.10.1, otherwise all should be good!

**Comment by larssb** [comment]
B-e-autiful. That makes it closeable for me. Thank you very much.
