### ISSUE TITLE
Knowledge request. Watch for changes. Restart Pode.

### ISSUE THREAD

**Issue by larssb** [Badgerati/Pode#20]
Hi @Badgerati,

I have been looking for a way to dynamically reload a running Pode server when 'x' file changes. A la nodemon is able to do. Are you aware of a similar tool for PowerShell and therefore Pode?

Thank you very much.

**Comment by Badgerati** [comment]
Hey @larssb,

I am aware that .NET does have a file watching class - which is available to use in PowerShell and PS Core. An example of using it I managed to fine is here: https://gallery.technet.microsoft.com/scriptcenter/Powershell-FileSystemWatche-dfd7084b

You should be able to use that and monitor for changes to files (maybe exclude the `public/` and `view/` dirs - those should be safe to change and use without a restart) and then stop/start pode.

It could be something I can also try looking into, and integrate into Pode to internally restart the server when a file change is detected.

**Comment by larssb** [comment]
Hi @Badgerati,

Thank you for looking into it. Oh yeah, you are right. There is that filewatcher class. I might look into that myself, why not. I could then provide a proposal for it, to use with Pode. Make a pull request and be your first contributor 👍.
Because, it would be nice to have the option of putting Pode into a mode where it "sniffs" changes to files and restarts. Especially while developing. When in production, maybe not so much. In some scenarios it might be nice. In short. Why it would be great to be able to turn it on and off.

Thank you.

**Comment by Badgerati** [comment]
Closing this while we have #21 open
