### ISSUE TITLE
Ability for Pode to Internally Restart when a File Change is Detected

### ISSUE THREAD

**Issue by Badgerati** [Badgerati/Pode#21]
This feature comes from #20, and a code example via PowerShell can be found here: https://gallery.technet.microsoft.com/scriptcenter/Powershell-FileSystemWatche-dfd7084b

* Pode should be able to monitor for file changes (created, changed, or deleted) and internally restart the server logic.
* On a restart, the current session should be disposed (ie, runspaces, timers and routes) before the server script is restarted.
* When a restart is initiated, it should be logged to the CLI.
* I'm thinking this should be optional, so only enable monitoring if the `Server` block has the `-Monitor` switch supplied?

**Comment by Badgerati** [comment]
So I've been doing some work on this, and having it working perfectly. However, there's a bug in dotnet core 2.0 where HttpListener doesn't re-use addresses after they've been disposed.

This means that the restart logic works fine on machines with dotnet core 2.1. The issue is with the latest `microsoft/powershell` docker image, which only runs with powershell 6.0 and dotnet 2.0 - which means the internal restart fails to re-attach onto the ip:port.

Using the `microsoft/powershell:6.1.0-preview.3-ubuntu-trusty-20180531` docker image, the restart works like a charm.

So I guess, I can prep the work and release now - but it won't work in docker. Or I can wait until the `6.1.0` image is released to `latest` before releasing this work.

**Comment by larssb** [comment]
Thank you very much Matthew.

Looking forward to trying it out. Regarding docker. You could use the release by specifying a specific tag on the “FROM” keyword in the dockerfile.
Actually, just a polite comment, it is not advised to use “latest” as one cannot know — exactly what release you are going to get
— versioning on the dockerfile therefore makes less sense.

Have a great weekend.

--
Mvh. / Kind regards
Lars Bengtsson

- Health is wealth, movement is medicine -

**Comment by Badgerati** [comment]
Nope, makes perfect sense; I've setup #51 to stop using `latest`.
