### ISSUE TITLE
Support - ARM Docker Images

### ISSUE THREAD

**Issue by gazataeon** [Badgerati/Pode#233]
Noticed the default Docker image and Dockerfile doesn't currently build for ARM architectures (specifically Raspberry Pi!)

Could the docker image be updated to support PowerShell Core 6.2.0 for ARM please?

Thanks

**Comment by Badgerati** [comment]
PowerShell Core ARM32 Docker images: https://cloud.docker.com/u/badgerati/repository/docker/badgerati/ps-core

**Comment by jeremymcgee73** [comment]
This is awesome! Thanks @Badgerati! I wish you would have been at Summit this week. Can't wait to play with this and k8s on my Raspberry Pis.

**Comment by Badgerati** [comment]
@jeremymcgee73, I wish I could've been there as well, it looked awesome! I kept up with most of the Summit over Twitter, just gotta wait for the recording to go up now 😄
