### ISSUE TITLE
Add FilePath to Route function

### ISSUE THREAD

**Issue by jeremymcgee73** [Badgerati/Pode#251]
It would be nice if you could define File Paths for routes. It would really clean up code to be able to move routes to their own files. Something like:

`route get '/' (auth check login -o @{ 'failureUrl' = '/login' }) C:\PSWebForms\Routes\Root.ps1`

**Comment by LLIT** [comment]
How about /routes to auto include .ps1 files.

I do it like this:

$RootPath   = $PSScriptRoot
$RouteFiles = @()
$RoutePath  = (Join-Path -Path $RootPath -ChildPath "Routes")
if (Test-Path $RoutePath) {
    Get-ChildItem -Path $RoutePath -Recurse -Filter *.ps1 | ForEach-Object {
        $RouteFiles += $_.FullName
        Write-Host $_.FullName
    }
}
Server -Threads 2 {
    listen *:8085 http
    engine pode
    
    $RouteFiles | ForEach-Object {
        . $_
    }
}

**Comment by Badgerati** [comment]
Basically @LLIT's script; and if we upgrade the `load` function from #250 to mass load scripts then that will make the above script even easier too! (just `load './Routes'` - which will auto-load all `*.ps1`)

I can add a `-FilePath` to the `route` function, as under the hood it would be the same as doing:

```powershell
route get '/' <auth-check> (load 'C:\PSWebForms\Routes\Root.ps1')

# but as:
route get '/' <auth-check> -fp 'C:\PSWebForms\Routes\Root.ps1'
```

and the `C:\PSWebForms\Routes\Root.ps1` script would need to look something like:

```powershell
return {
    view 'index'
}
```
