### ISSUE TITLE
File monitor - Output which file was changed

### ISSUE THREAD

**Issue by Fraham** [Badgerati/Pode#280]
File monitor - Output which file was changed which then caused the server to be restarted.

This could either log out to the console or to a log file.

Suggestion to have this feature switched with a default of off so it doesn't affect current processes.

**Comment by Badgerati** [comment]
@Fraham, I'm thinking for this just the terminal should be enough.

In cases where multiple files are changed that trigger the restart; would you want all the files listed? (guessing so).

**Comment by Badgerati** [comment]
If enabled, the following will be output just before the server restarts:

```plain
The following files have changed:
> [Changed] pode.json
> [Created] views/about.pode
```

To enable, set the `server.fileMonitor.showFiles` property to `true` in `pode.json`.

**Comment by Fraham** [comment]
Yeah, that is exactly what I wanted to have, looks really good, thanks.
