### ISSUE TITLE
Question: Function Syntax - Shorter or PowerShell?

### ISSUE THREAD

**Issue by Badgerati** [Badgerati/Pode#281]
I asked this on Twitter, but I'll ask here as well.

It's something I've thought about before with Pode, do people prefer the following shorter syntax:

* `route`
* `engine`
* `json`
* `csrf middleware`

or would you prefer normal PowerShell syntax:

* `Add-PodeRoute`
* `Set-PodeViewEngine`
* `Set-PodeJsonResponse`
* `Get-PodeCsrfMiddleware`

Since I'm now looking at a v1.0.0 release of Pode, this could be a good time to refactor everything.

**Comment by Badgerati** [comment]
As a note, I'm leaning towards PowerShell syntax.

I kept to the shorter syntax to maintain consistency in v0.X, but it's becoming a bit of a hassle. Especially when I write `Get-PodeFlashMessage`/`Add-PodeFlashMessage` functions, and then have to write a giant `flash` wrapper around it - causing messy Parameters.

It would be nice in PowerShell if you could base `ParameterSets` on `ValidationSet` values 🤔

**Comment by LLIT** [comment]
I would go for the Powershell syntax

**Comment by Fraham** [comment]
I also agree with PowerShell syntax, just so everything feels a bit more normal for PowerShell devs

**Comment by Badgerati** [comment]
Yep, consensus from people so far is for PowerShell Syntax! I'll start looking at what's needed for a refactor.

**Comment by Badgerati** [comment]
Started writing up some issues for the refactor: https://github.com/Badgerati/Pode/projects/1
