### ISSUE TITLE
PowerShell Compatibility Issue 

### ISSUE THREAD

**Issue by Synergy404** [Badgerati/Pode#284]
Params not parsing when server is running under PowerShell 5.1

The following server code running under 5.1.17763. 503
````
server {
    listen localhost:8080 http

    route post '/users' {
        param($s)

        # get the user
        $user = $s.Data['userId']
        $age = "21"

        # return the user
        json @{
            'Username' = $user;
            'Age' = $age;
        }
    }
}
````
Client code 
````
[Net.ServicePointManager]::ServerCertificateValidationCallback = {$true}
$params = @{"userId"="someguy5";
 }
 $Json = $params|ConvertTo-Json
$response = Invoke-WebRequest -Uri 'http://localhost:8080/users' -Method Post -Body $Json -ContentType 'application/json'
Write-Host "Response - $response"
````
Produces this output:
Response {"Username":{},"Age":"21"}

The same server code and client code  running under PowerShell 6.1.2 parses the params correctly and produces this

Response {"Username":"someguy5","Age":"21"}

Documents say
Cross-platform using PowerShell Core (with support for PS4.0+)

**Comment by LLIT** [comment]
Try:

```
server {
    listen localhost:8080 http

    route post '/users' {
        param($s)

        # get the user
        $user = $s.Data.userId
        $age = "21"

        # return the user
        json @{
            'Username' = $user;
            'Age' = $age;
        }
    }
}
```

**Comment by Badgerati** [comment]
I was just about to recommend this!

`ConvertFrom-Json` in PS4/5 uses a `psobject`, so `$data['userId']` doesn't work unfortunately.

A gab in documentation, so if `$s.Data.userId` works, I'll add a note in for PS4/5.

**Comment by Synergy404** [comment]
I tested $s.Data.userId and it does work. Thank you

**Comment by Badgerati** [comment]
Excellent! I'll look at updating the docs.
