### ISSUE TITLE
Write a migration guide for going from v0.X to v1.0

### ISSUE THREAD

**Issue by Badgerati** [Badgerati/Pode#316]
Since v1.0 is going to contain vast changes to syntax, it'll be worth writing a Migration Guide for people going from Pode v0.X to v1.0.

This guide should contain:
* A function map, from old syntax to the new PowerShell syntax.
* Information on migrating from a `pode.json` to the new `server.psd1` settings file.

**Comment by jeremymcgee73** [comment]
Just a thought, would a script that renames the functions to the new syntax be useful?

**Comment by Badgerati** [comment]
@jeremymcgee73 I like the idea, a script could work for some of the simpler functions (`header`, `cookie`, `flash`, etc). For functions like `logger` and `auth` these could be a lot more complicated 🤔 

A script would give a good starting point though.

**Comment by Badgerati** [comment]
Going through the examples and thinking about this migration script, I think what I'm gonna do it move it to a separate issue.

I'm also considering putting the script onto gist (linked to in docs), so it's easier to bug fix and improve much later on. 🤔
