### ISSUE TITLE
Authentication: Form and Basic with Add-PodeAuthWindowsAd

### ISSUE THREAD

**Issue by LLIT** [Badgerati/Pode#324]
Hi,

I am trying to adapt all my code to the new format, and is struggling to get Basic authentication to work...

Form Auth is working, but i dont get any auth on Basic.

```ps1
Write-Host "Adding Authentication" -ForegroundColor Green
Enable-PodeSessionMiddleware -Secret 'schwifty' -Duration 600 -Extend
New-PodeAuthType -Form | Add-PodeAuthWindowsAd `
    -Name 'Login' `
    -Fqdn $Settings.FQDN `
    -Groups $MyListOfGroups `
    -Users $MyListOfUsers
Write-Host "    Form Login"

New-PodeAuthType -Basic -HeaderTag "Authorization"| Add-PodeAuthWindowsAd `
    -Name 'API' `
    -Fqdn $Settings.FQDN `
    -Groups $MyListOfGroups `
    -Users $MyListOfUsers
Write-Host "    Basic Login"

# This one works :)
Add-PodeRoute `
    -Method 'Get' `
    -Path '/login' `
    -Middleware ( `
        Get-PodeAuthMiddleware `
            -Name 'Login' `
	    -AutoLogin `
	    -SuccessUrl '/'
    ) `
    -ScriptBlock {
	param($session)
	Write-Json -Data $session -Depth 1
    }

# Not this one :(
Add-PodeRoute `
    -Method 'Get' `
    -Path '/api/login' `
    -Middleware ( `
        Get-PodeAuthMiddleware `
	    -Name 'API' `
	    -AutoLogin `
	    -SuccessUrl '/api/'
    ) `
    -ScriptBlock {
	param($session)
	Write-Json -Data $session -Depth 1
    }

```

**Comment by Badgerati** [comment]
Hi,

I can have a proper test later, though an idea springs to mind.

For the Basic auth, is this being done via Curl/Invoke-WebRequest/etc? If so, then omitting the `-AutoLogin` and `SuccessUrl` on the `Get-PodeAuthMiddleware` function should succeed (these parameters are mostly for frontend views).

I'd imagine you'd want people to resend the Authorization Header with each Request for the API side? If so, you can use the `-Sessionless` switch on `Get-PodeAuthMiddleware` and it'll check the details every time.

Eg:
```powershell
Add-PodeRoute `
    -Method 'Get' `
    -Path '/api/login' `
    -Middleware ( `
        Get-PodeAuthMiddleware `
            -Name 'API' `
            -Sessionless
    ) `
    -ScriptBlock {
        param($session)
        Write-Json -Data $session -Depth 1
    }
```

In this case, since all your `/api` routes will require authentication every time, you could wire up the check as global route middleware:

```powershell
Get-PodeAuthMiddleware -Name 'API' -Sessionless | Add-PodeMiddleware -Name 'ApiAuth' -Route '/api/*'

Add-PodeRoute `
    -Method 'Get' `
    -Path '/api/login' `
    -ScriptBlock {
        param($session)
        Write-Json -Data $session -Depth 1
    }
```

Hope this helps!

**Comment by Badgerati** [comment]
Yes, it's the `-AutoLogin` switch. Removing that on the Basic Auth check will redirect to the `-SuccessUrl`, but you'll get a 401 response as the session will be in a cookie. Using auth on REST APIs is best with `-Sessionless` 😄

**Comment by LLIT** [comment]
Worked like a charm :)

I will test the global routes ASAP.

**Comment by LLIT** [comment]
I keep recieving a 500 Error with this enabled:

```ps1
Get-PodeAuthMiddleware -Name 'API' -Sessionless | Add-PodeMiddleware -Name 'ApiAuth' -Route '/api/*'

Add-PodeRoute `
	-Method 'Get' `
	-Path '/api/login' `
	-ScriptBlock {
		param($session)
		Write-Json -Data $session.auth -Depth 2
	}
```

**Comment by Badgerati** [comment]
Are you able to see the error being thrown? I've just tried myself and it worked.

**Comment by LLIT** [comment]
It is only when i leave out the /middleware part i get the error.
Is there a feature to easy enable debug logging?

**Comment by LLIT** [comment]
The 500 error was because of $Session.auth was null

If i add the -Middleware part for each route the $Session.auth contains data.

**Comment by Badgerati** [comment]
> If i add the -Middleware part for each route the $Session.auth contains data.

Oooh! That might be a bug, I'll investigate later.

> Is there a feature to easy enable debug logging?

Yes! You should now be able to do `New-PodeLoggingMethod -Terminal | Enable-PodeErrorLogging`, and it'll log the errors to the terminal.

**Comment by Badgerati** [comment]
It was indeed a bug; that commit now works for me.

**Comment by LLIT** [comment]
With the code from #324 i get the correct authentication information :-)
