### ISSUE TITLE
New "ConvertTo-PodeRoute" function to automatically make Routes from Functions/Modules

### ISSUE THREAD

**Issue by Badgerati** [Badgerati/Pode#334]
The idea behind this is to create a new `ConvertTo-PodeRoute` function that takes an array of Commands (functions/aliases) or a Module name and Pode will automatically generate the appropriate Routes.

For example:
```powershell
# will convert all of Pester's exported commands to Routes
ConvertTo-PodeRoute -Module Pester -Verbose

# will convert just Get-ChildItem to a Route
ConvertTo-PodeRoute -Commands @('Get-ChildItem')

# will convert just Invoke-Pester from the Pester module to a Route
ConvertTo-PodeRoute -Commands @('Invoke-Pester') -Module Pester
```

And example route that could be generated is:
```powershell
Add-PodeRoute -Method Post -Path "/Pester/Invoke-Pester" -ArgumentList 'Invoke-Pester' -ScriptBlock {
    param($e, $cmd)
    $parameters = $e.Data
    $result = (. $cmd @parameters)
    Write-PodeJsonResponse -Value $result -Depth 1
}
```

* The HTTP method for the routes should be determined by the command's `Verb`, the default should be `POST`.
** Should be overridable via a parameter (ie, one HTTP method for everything)

* The route's path will be based on any module name, the name of the command, and any optional path supplied: `/pester/invoke-pester` or `/api/pester/invoke-pester`.
** The verb can be optionally skipped: `/pester/pester`.

* The body of the generated route will call the appropriate function (defined by the route's `-ArgumentList`), and the parameters to be supplied will be splatted from either the query string or payload (based on the HTTP method). Any result will then before written back as JSON.

* Should support supplying middleware like normal Routes - for authentication, etc.

**Comment by haidouks** [comment]
Great idea 👍
