### ISSUE TITLE
Support for relative paths on views.

### ISSUE THREAD

**Issue by larssb** [Badgerati/Pode#36]
Hi @Badgerati,

So there I was. Starting the server via PowerShell dot-sourcing. However, not in the folder of the .PS1 being dot-sourced. But from several levels up in the folder hierarchy.

_Issue_

When I do this, Pode cannot locate the "Whatever.html" file I want loaded as this > https://github.com/Badgerati/Pode/blob/52b00ffd2f036789cc5403f4a5fe7bd24304a8e6/src/Tools/Responses.ps1#L388 <-- is not path relative compatible.
I tried with some `$global:MyInvocation.MyCommand.Path` magic inside the Responses.ps1 file. Now my "Whatever.html" file could be located but other files, such as CSS and JS files could still no be loaded (HTTP404 returned). 

_Wish_

It would be nice if it was possible for Pode to support relative paths. So that one does NOT have to be at the correct path when invoking the PS1 file containing Server definitions and so forth.

I hope I made myself understandable. Let me know what you think.

Thank you.

**Comment by Badgerati** [comment]
Yep, think I've go you: so if you have your ps1 at `/a/server.ps1` but you're currently at `/a/b/c`, you shouldn't have to navigate back to `/a` but should be able to call `../../server.ps1`?

In which case, I can definitely look to add in support for that via `$MyInvocation.MyCommand.Path` - for `views` and `public` content.

**Comment by Badgerati** [comment]
Hey @larssb,

I've tested the commit above on relative path calling, and dot-sourcing, and works with PS5.1, PSCore Windows/Linux.

Fix applied to views, public content, and attaching files to a response.

**Comment by larssb** [comment]
Nice! Sounds great. Regarding the path hierarchies for which it should work. It is also when I'm in some top folder say I'm in 'a' if the tree is /a/b/c and c is where the Server declaring PS1 file is in. I should be able to do `. ./a/b/c/SomePs1.ps1` and have it work :-).

Thank you.....and let me know when I can test it out. Kind regards and great work.

**Comment by Badgerati** [comment]
@larssb Just tested it, that also works 😄

**Comment by larssb** [comment]
Great! Ping me when the new version is out and proud :-D

**Comment by Badgerati** [comment]
@larssb released in 0.12.0
