### ISSUE TITLE
Documentation: FirstApp.md bad links

### ISSUE THREAD

**Issue by robinmalik** [Badgerati/Pode#364]
File: [`FirstApp.md`](https://github.com/Badgerati/Pode/blob/develop/docs/Getting-Started/FirstApp.md)

Text at the bottom contains links that don't appear to work:
```
To see how to create web pages using Pode, see here
To see how to do basic login/logout pages, see here
```

**Comment by Badgerati** [comment]
😳 Yep, they're supposed to respectively go to:

* https://badgerati.github.io/Pode/Tutorials/Routes/Examples/WebPages/
* https://badgerati.github.io/Pode/Tutorials/Routes/Examples/LoginPage/

I'll update them later! Thanks

**Comment by Badgerati** [comment]
That's been fixed over at https://badgerati.github.io/Pode/Getting-Started/FirstApp/ now.
