### ISSUE TITLE
Use Sockets in PowerShell to support HTTPS cross-platform

### ISSUE THREAD

**Issue by Badgerati** [Badgerati/Pode#376]
As we know HttpListener only supports HTTPS on Windows, and it's also depreciated. Using Kestrel would be nice, but would require a massive dependency on ASP.NET Core and current features that PowerShell is lacking (tasks, delegates, etc).

So, going down the route of no dependencies, and sticking to PowerShell only for cross-platform support, I thought I'd be mental and look at using Sockets in PowerShell!

Well it works! And so far I have a simple complete server type working, **and** with HTTPS support cross-platform! 🎉 You can find the current implementation in the `pode-listener` branch, with the relevant example being `examples/web-sockets.ps1`.

There are a few things it doesn't support at the moment:
- [x] Threading
- [x] Keep-Alive, which currently acts a little weird on browsers
- [x] Request/Response are not streamed (so multiform doesn't work, and some chars don't render)
- [x] It can only handle 1 endpoint (I think I've got a way to make it support multiple)
- [x] There is a horrible nasty `Start-Sleep` 🤢 
- [x] There's no validation on reading the Request
- [x] Headers in the Response are unique, so you can't have multiple `Set-Cookie` headers
- [x] Content-Type and Content-Length headers are missing
- [x] Under load EOF errors are possible (likely a multi-threading issue)
- [x] Extra tests for Certificates and SSL
- [x] Documentation

If you fancy having a play and spot anything, or want to help out, go a head! 😄

**Comment by Badgerati** [comment]
Getting to a stable point with this now! For simple REST APIs it's really good, for sites in a browser is OK, but could be better - mostly a restriction on PowerShell and Async. Otherwise, it's fairly stable.

Might try and get the Req/Res streamed, some documentation, and poooosssibly release it as an experimental feature 🤔

**Comment by Badgerati** [comment]
Need to run a few more tests on Certs and SSL, but it's mostly down to documentation now!

**Comment by gazataeon** [comment]
SUCCESS
