### ISSUE TITLE
Documentation for using Pode in Heroku

### ISSUE THREAD

**Issue by Badgerati** [Badgerati/Pode#381]
Heroku has support for running containers, so it would be cool to have some documentation in Pode on how to run Pode's container in Heroku.

This will likely go into a `/docs/Tutorials/Providers/Heroku.md`.

**Comment by anshulxyz** [comment]
Hi, Matthew

I'd like to work on this. I have deployed stuff (A Python bot) on Heroku before.

Things I'd like to learn from this issue:
- Docker
- Quality Documentation

**Comment by anshulxyz** [comment]
I'll get started on this. Can you give me a few examples on what stuff you want to be written on the page, from other projects?

Also, your website is giving 403

![Screenshot from 2019-09-27 18-52-11](https://user-images.githubusercontent.com/6121530/65772600-270c4d00-e158-11e9-9ad4-946b35abc7ba.png)

**Comment by Badgerati** [comment]
So my thinking is that it could follow a similar-ish style to the current [AWS Lambda](https://badgerati.github.io/Pode/Tutorials/Serverless/Types/AwsLambda/) and [Azure Functions](https://badgerati.github.io/Pode/Tutorials/Serverless/Types/AzureFunctions/) docs. Something that details a simple Pode server, how to containerise it, and then how to host that on Heroku.

Some examples I managed to find could be like [Running Docker on Heroku](https://medium.com/travis-on-docker/how-to-run-dockerized-apps-on-heroku-and-its-pretty-great-76e07e610e22) or [Running .NET on Heroku](https://codersblock.com/blog/how-to-run-net-on-heroku/).

Pode does also have documentation on containerising Pode servers [here](https://badgerati.github.io/Pode/Getting-Started/Docker/).

Hope that helps!

---

For the badgerati.com website, yeah I'm aware. I stopped using the provider a while back, and I've been meaning to re-host it on GitHub, just haven't gotten around to doing it yet 😂 (it was pretty outdated anyway - and hideous)

**Comment by anshulxyz** [comment]
I noticed how you've named some branches after issue number. Want me to follow that protocol?

**Comment by Badgerati** [comment]
Hey,

For branch names you can either use `Issue-xxx` or something descriptive. The branch to make yours from is `develop`.

The former can be [found here](https://github.com/Badgerati/Pode/blob/develop/.github/CONTRIBUTING.md#branch-names), though I just realised which branch to branch from isn't - so i'll add this!
