### ISSUE TITLE
Trying to return an Excel file

### ISSUE THREAD

**Issue by dfinke** [Badgerati/Pode#384]
I guessed wrong.

```powershell
Start-PodeServer {
    Add-PodeEndpoint -Address localhost -Port 8080 -Protocol Http

    Add-PodeRoute -Method Get -Path '/GetXl' -ContentType "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" -ScriptBlock {
        Set-PodeResponseAttachment -Path "C:\Temp\test.xlsx"
    }
}
```

**Comment by Badgerati** [comment]
Hi @dfinke,

So for `Set-PodeResponseAttachment`, this currently only attaches files from within the `/public` directory at the root of your Pode server ([see docs](https://badgerati.github.io/Pode/Functions/Responses/Set-PodeResponseAttachment/)).

For the `-ContentType` on `Add-PodeRoute` this is only really for the Request payload.

However! In testing this just to make sure the Response's content type was correct, I did stumble across a bug. The Response's content length is actually being set to 0, as it's trying to reference the FileStream too early; once this is set appropriately, the file is attached and downloaded.

I can also add in support on `-Path` so it can support files outside of the static content directories 🤔.

**Comment by dfinke** [comment]
Thanks, works like a charm.
