### ISSUE TITLE
How to perform the Active Directory Auth with Invoke-WebRequest

### ISSUE THREAD

**Issue by ClissonFlorian** [Badgerati/Pode#398]
Hi,

I would like to perform an active directory authentification from Invoke-WebRequest (client side). It's works well from the web form but not when i'm using Invoke-WebRequest. 

In server side, I set this config :    New-PodeAuthType -Form | Add-PodeAuthWindowsAd -Name 'Login' -Fqdn $env:USERDNSDOMAIN -Groups @() -Users @()
[server.txt](https://github.com/Badgerati/Pode/files/3805355/server.txt)

I'm trying to do this from the bellow way but it's not working...What am I doing wrong?

$username = "<username>"
$password = "<password>"

# Step 1. Create a username:password pair
$credPair = "$($username):$($password)"
 
# Step 2. Encode the pair to Base64 string
$encodedCredentials = [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes($credPair))

# Step 3. Form the header and add the Authorization attribute to it
$headers = @{ Authorization = "Basic $encodedCredentials" }
 
Invoke-WebRequest -Uri "http://localhost:8085/" -Method Get -Body $headers -SessionVariable s
Invoke-WebRequest -Uri "http://localhost:8085/Get-ChildItem" -WebSession $s -Method Post

Thanks.

**Comment by Badgerati** [comment]
Hi @ClissonFlorian,

At a glance the only issues I can see are that for basic authentication you need to use `New-PodeAuthType -Basic` instead of `New-PodeAuthType -Form`.

Also, maybe a typo? But on the first `Invoke-WebRequest` you have `-Body $headers` instead of `-Headers $headers`

Hope that helps!

**Comment by ClissonFlorian** [comment]
Thank you for your help and for your quick answer

It's works like a charm like that : 
`Invoke-WebRequest -Uri "http://localhost:8085/" -Method Get -Headers $headers -SessionVariable s`

`Invoke-WebRequest -Uri "http://localhost:8085/Get-ChildItem" -Method get -WebSession $s`

There is any way to use the option `-UseDefaultCredentials` to avoid to request the credentials to the user?

**Comment by Badgerati** [comment]
Hey, glad it worked.

For `-UseDefaultCredentials` I'm afraid that currently won't work. I took a quick look at how it works, and it looks like it should be fairly simple to implement NTLM 🤔 - as it works very much like Basic auth.

I'll raise a feature to add in support for NTLM authentication.
