### ISSUE TITLE
Log directly to user terminal

### ISSUE THREAD

**Issue by Fraham** [Badgerati/Pode#400]
### Related Issues
As each feature runs in its own run space, like schedules, when logging to console it doesn't go to the right host

### Describe the Change
Have a Pode method that will log a message directly to the users terminal

**Comment by Badgerati** [comment]
Normally just using `Out-Default` does the trick. I can make a wrapper around it though, something like:

```powershell
Write-PodeHost -Message "Hello, world!"
```
