### ISSUE TITLE
How Can I get Auth Data Outside scriptblock

### ISSUE THREAD

**Issue by ClissonFlorian** [Badgerati/Pode#413]
Hi!

I'm trying to get the username authentified but without success.

According your exemple, i'm getting well the username:

```powershell
    $auth_check = Get-PodeAuthMiddleware -Name 'Login' -FailureUrl '/login'
    Add-PodeRoute -Method Get -Path '/' -Middleware $auth_check -ScriptBlock {
        param($e)

        $e.Session.Data.Views++
       
        Write-PodeViewResponse -Path 'auth-home' -Data @{
            'Username' = $e.Auth.User.Name;
            'Views' = $e.Session.Data.Views;
        }
    }
```

But I would like to get the username from this bellow route but it doesn't work. How should I proceed ? 

Thanks for your help.
```powershell
Add-PodeRoute -Method Get -Path '/api/:AccountID/:RessourceType/:Action/:Value' -Middleware (Get-PodeAuthMiddleware -Name 'Login' -Sessionless) -ArgumentList $auth_check  -Verbose -ScriptBlock {
        param($e,$auth_check)
 
        #Not able to get the user like that
        $auth_check.Auth.User.Name
}

```

**Comment by Badgerati** [comment]
Hey @ClissonFlorian,

The authenticated user will be within the first `$e` parameter. So the following should work for you: `$e.Auth.User.Name`.

The `$auth_check` is purely middleware - effectively a scriptblock - that is invoked to authenticate the user. The `$e` is the main event object for the whole request flow.

Hope that helps!

**Comment by ClissonFlorian** [comment]
Thanks a lot! It's working well. I was looking for something complex when it was simple :)
