### ISSUE TITLE
Cron expressions not working to the expected schedule

### ISSUE THREAD

**Issue by Fraham** [Badgerati/Pode#414]
### Describe the Bug
Cron expressions not working to the expected schedule.

Having an expression of `*/2 * * * *` should run every two minutes but only runs once an hour.

### Steps To Reproduce
1. Have a server which has a schedule set to '*/2 * * * *'
2. Have the schedule output the current time to the console

### Expected Behavior
The log output should be every 2 minutes. As shown on [here](https://cron.help/#*/2_*_*_*_*)

### Platform
 - OS: Windows

**Comment by Badgerati** [comment]
@Fraham 

For now you can use `0/2 * * * *` which does the exact same thing, Do you want the `*/2` support?
