### ISSUE TITLE
Allow to invoke a schedule

### ISSUE THREAD

**Issue by Fraham** [Badgerati/Pode#415]
### Describe the Change
Being able to run the code inside a schedule outside of the scheduled time.

For example, having a schedule that collects some data from an external source which only runs once an hour but having the ability to request for the schedule to run, maybe through a rest API so the user could ask for the data to be updated in the background outside of the normal schedule

**Comment by Badgerati** [comment]
Ooo, yes, can probably do this for timers as well and have something like:

```powershell
Invoke-PodeSchedule -Name '<name>'
Invoke-PodeTimer -Name '<name>'
```

Each of which will invoke that schedule/timer's logic adhoc.
