### ISSUE TITLE
Use-PodeScript with psm1 file opens Notepad

### ISSUE THREAD

**Issue by majkinetor** [Badgerati/Pode#418]
### Describe the Bug

Use-PodeScript with psm1 file opens Notepad. On my system `.psm1`  is associated with Notepad so the line `. <psm1_path>` that is used within `Use-PodeScript` opens it.

### Steps To Reproduce

- Associate Notepad to psm1 files
- Run `examples\external-funcs.ps1`
- Notepad is shown and script doesn't work
   - Interestingly, doing it all over with ps1 script doesn't trigger Notepad, but `Get-Gretting` is still not found

### Expected Behavior

Function gets included and can be called

### Platform
 - OS: Windows 10
 - Version: PS 5.1.18362.145

**Comment by Badgerati** [comment]
Hey,

After finding [this link](https://stackoverflow.com/questions/45406653/powershell-dot-sourcing-opens-up-file-in-notepad) I'm now very sure that in the `external-funcs.ps1` example it's a typo - it should say `Import-PodeModule` and not `Use-PodeScript`. It also makes far more sense, as `Import-PodeModule` loads the module into all runspaces - where as `Use-PodeScript` is a one time fire-and-forget.

I'll fix the typo, and I think I'll fix the other minor documentation typos from Gitter as well here, so:

* https://badgerati.github.io/Pode/Tutorials/SharedState/#full-example using `$hash['value']` and not `$hash.value` and,
* https://badgerati.github.io/Pode/Tutorials/ImportingModules/ referencing `Import-PodeModule` twice, and not `Import-PodeSnapIn` the second time

**Comment by majkinetor** [comment]
Great. 

What is the use case for `Use-PodeScript` then ? T

**Comment by Badgerati** [comment]
So using normal dot-sourcing works perfectly fine, as long as the server's root isn't altered. If however you set the `-RootPath` of the server, and your scripts are also stored there, then dot-sourcing won't find them. This is where `Use-PodeScript` comes in handy, as if the path supplied is relative it will look for the script to dot-source at the server's root.
