### ISSUE TITLE
Ability to list all of the routes

### ISSUE THREAD

**Issue by Fraham** [Badgerati/Pode#425]
### Describe the Feature
Ability to list all of the routes

**Comment by Badgerati** [comment]
Re-opening the issue to add an `-EndpointName` filter to the new `Get-PodeRoute` and `Get-PodeStaticRoute` functions (as mentioned in #426).

**Comment by ArieHein** [comment]
https://github.com/Badgerati/Pode/pull/426#issuecomment-592448519

**Comment by Badgerati** [comment]
Added in support to filter by EndpointName:

```powershell
# all routes
Get-PodeRoute

# all routes for method
Get-PodeRoute -Method Get

# all routes for a Path
Get-PodeRoute -Path '/users'

# all routes for an Endpoint
Get-PodeRoute -Endpoint 127.0.0.1:8080

# all routes for an Endpoint by name
Get-PodeRoute -EndpointName Admin
```

If you assign one route to multiple endpoints:
```powershell
Add-PodeRoute -Method Get -Path '/users' -EndpointName User, Admin -ScriptBlock {}
```

then doing `Get-PodeRoute -Path '/users'` will return two routes - one for each endpoint name. I've also changed `EndpointName` on the returned Route to be literally the name of the endpoint that Route is assigned to - not the array of all.

**Comment by ArieHein** [comment]
This will be very beneficial for my unit testing !
