### ISSUE TITLE
pode CLI cmd does not work as expected. Causes `The term './Server.ps1' is not recognized as the name of a cmdlet, function, script or operable program`

### ISSUE THREAD

**Issue by larssb** [Badgerati/Pode#429]
### Describe the Bug
pode cli cmd start does throws. `The term './Server.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

### Steps To Reproduce
0. Execute `pode init`
1. Go to the root of your project using pode
2. Execute `pode start`
3. See error

### Expected Behavior
I expected `pode start` to work by starting the Pode server.

### Platform
 - OS: Win10 build 1809
 - PS Version: v5.1
 - Pode version: v1.2.1

### Additional Context
In my troubleshooting I went through the Pode code used to start the server. Here I see that on the Windows platform, the server is initiated by executing `powershell /c "$($ActionScript)"`. This seems to be the culprit. 

When trying `powershell /?` in e.g. -> WindowsKey+R. I don't see the /c option anywhere. Shouldn't it be the `-Command` parameter that was used here instead?
Anyways PowerShell do not interpret the `$(ActionScript)` part as executable code. I've successfully used the following approact: `powershell -command & { POWERSHELL_CODE_TO_EXECUTE }`

---

I hope I describe myself clearly in the above. If not I'll be happy to further elaborate.

Thank you

**Comment by Badgerati** [comment]
Hey @larssb,

So for `/c` I definitely agree that needs to be `-Command` for `powershelll` and `pwsh` - though I will mention that `powershell /c` does work on my machine (same platform/versions):

```powershell
PS> powershell /c "write-host 'hello'"
hello
PS> powershell -c "write-host 'hello'"
hello
```

I did replace `powershell /c "$($ActionScript)"` with `powershell -Command "$($ActionScript)"` and it works as intended 🤔

The only way I could get the same error was to follow your steps literally:

1. Run `pode init`
2. Run `pode start`

I noticed that between the two you're not creating a `server.ps1` script, and for me this is when the error was thrown:

```powershell
C:\Projects\Temp> pode init
name (Temp):
version (1.0.0):
description:
entry point (./server.ps1):
author:
license (MIT):
Success, saved package.json

C:\Projects\Temp> pode start
./server.ps1 : The term './server.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:1 char:1
+ ./server.ps1
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (./server.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Is this the same case for yourself? In which case would you prefer `pode init` create the initial server script if it doesn't already exist?

**Comment by larssb** [comment]
Hi @Badgerati 

Thank you for replying so fast. I did have a Server.ps1 file before executing `pode start`. However, it is in a sub-folder .... so

> Folder hierarchy

- package.json
-- API
--- Server.ps1

However, I do not see why this should not work. Of course I updated the package.json after executing `pode init` so that it has the corrects paths.

I just tried dot invoking. So in `Setup.ps1` on [L17](https://github.com/Badgerati/Pode/blob/cf695db9286314d7a3150232bedb4b72bda9661f/src/Private/Setup.ps1#L17) I did `. "$($ActionScript)"`. And that works without issues.

I also tried moving my Server.ps1 file into my projects root folder. So that is side-by-side the package.json file. Update the package.json file to reflect this.

Same error:
```
The term './Server.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

So maybe dot-invocation is the way to go? What do you think?

**Comment by Badgerati** [comment]
Hi @larssb,

So a sub-folder was what I was missing before, but I've just tried it on my side and it works 😕. This is the folder hierarchy and package.json I have:

* Hierarchy:
```plain
- package.json
- api/
    - server.ps1
```

* package.json:
```json
{
    "version":  "1.0.0",
    "license":  "MIT",
    "name":  "test",
    "scripts":  {
                    "test":  "invoke-pester ./tests/*.ps1",
                    "install":  "yarn install --force --ignore-scripts --modules-folder pode_modules",
                    "build":  "psake",
                    "start":  "./api/server.ps1"
                },
    "description":  "",
    "author":  "",
    "main":  "./api/server.ps1"
}
```

Running `pode start` in the same directory as the package.json works 🤔. Would you be able to share your package.json as well? (assuming the hierarchy is the one you mentioned above)

On the dot-invocation, I was originally using that method! Unfortunately it was causing havoc with the FileWatcher, and using `powershell.exe`/`pwsh.exe` worked. I'll test it again though, that and `Invoke-Expression`, just to make sure I haven't since fixed the issue during the massive refactor 👀

**Comment by Badgerati** [comment]
Hey @larssb,

Good news! Using `Invoke-Expression` works, so I must have fixed whatever the original issue was way-back-when. It's also nice to remove the "pwsh,exe"/"powershell.exe" check!

Let me know if `Invoke-Expression` works for you - I did check dot-invocation as well, just this is a little nicer.

**Comment by larssb** [comment]
Yes that works. I just tested it. Looks great. Hopefully this can get out in the next release of Pode.

Good 1

**Comment by Badgerati** [comment]
Excellent! Yes, I'll get this into the next release.
