### ISSUE TITLE
Re-use or setup Self-Signed Certificates when using HTTPS

### ISSUE THREAD

**Issue by Badgerati** [Badgerati/Pode#43]
Ability for Pode to re-use or create its own self-signed certificates when being used over HTTPS - this will be inbuilt logic to handle certs in the `WebServer`, using the example `web-pages-https.ps1` from @ssugar.

> Note: for now this will only be for Windows environments, and *not* PS-Core/Linux environments. Maybe it's possible to use OpenSSL instead?

Before checking if a cert exists, check to ensure a cert isn't already bound to the IP:Port binding using `netsh http show sslcert` - if there is, skip the other steps.

A new parameter on `Server` called something similar to `-SSLName`, which is the certificate name/domain to look for existing certs at `Cert:/LocalMachine/My` or to create a new self-signed cert. (If no name supplied, use some default name like "Pode SSL Certificate").

Also another parameter for `-NoSelfSignedCert` (or similar), so that if no cert is bound or can be found, then disable creating a self-signed cert and throw an error instead.

If no binding, and no cert, then create a self-signed cert using `New-SelfSignedCertificate`.

Then attach the new/existing cert using `netsh http add sslcert` to bind the cert to the IP:Port config.

**Comment by ssugar** [comment]
Not about self-signed certs, but I've been using a LetsEncrypt issued cert on the public pode server I'm running.  Used the [Posh-ACME](https://github.com/rmbolger/Posh-ACME) powershell module with their AzureDNS plugin to get and install the cert with a single command.

Given that pode is already a web server, it may also be possible to implement the [HTTP-01](http://letsencrypt.readthedocs.io/en/latest/challenges.html) challenge so no external dependencies are added.

**Comment by Badgerati** [comment]
Good shout on LetsEncrypt; I think for now maybe I'll keep signed certs from CAs external to Pode, but so long as the cert is installed and in the Personal store then Pode can use it via this issue. Though if you want to have a crack at it go for it 😄 

I did manage to find out how to potentially install certs in powershell core, via the Posh-ACME module:

```powershell
$pfxBytes = [IO.File]::ReadAllBytes($PfxFile)

$pfx = New-Object Security.Cryptography.X509Certificates.X509Certificate2($pfxBytes,$PfxPass,'Exportable,PersistKeySet')

$store = New-Object Security.Cryptography.X509Certificates.X509Store($StoreLoc,$StoreName)
$store.Open("MaxAllowed")
$store.Add($pfx)
$store.Close()
```

* https://github.com/rmbolger/Posh-ACME/blob/master/Posh-ACME/Private/Import-PfxCertInternal.ps1
* https://stackoverflow.com/questions/47768069/x509certificate2-fails-to-parse-on-linux-but-works-on-windows

So if we can figure out how to make a self-signed cert in powershell core, maybe this could be used to install it on windows (and hopefully linux? 🤔)

**Comment by ssugar** [comment]
Cool, I was able to mash together some code from a few other places to come up with this, which allows me to manage the apple keychain certs via PowerShell (add/remove).

```powershell
$StoreName = 'My'
$StoreLocation = 'LocalMachine'
$StoreNameObject = [System.Security.Cryptography.X509Certificates.StoreName]
$StoreLocationObject = [System.Security.Cryptography.X509Certificates.StoreLocation]
$OpenFlags = [System.Security.Cryptography.X509Certificates.OpenFlags]
$Store = [System.Security.Cryptography.X509Certificates.X509Store]::new($StoreNameObject::$StoreName, $StoreLocationObject::$StoreLocation)

$X509Certificate2 = [System.Security.Cryptography.X509Certificates.X509Certificate2]
$CertPath = (Resolve-Path 'SelfSingedCert.pfx').Path
$Cert = $X509Certificate2::New($CertPath, 'pfxPassword')

$Store.Open($OpenFlags::ReadWrite)
$Store.Certificates
$Store.Add($Cert.RawData)
$Store.Certificates
$Store.Close()
```

That being said, i still haven't figured out how to get the Mac to bind a cert to a port properly.  httpcfg commands seem to run ok, but web browsers don't seem to be able to open up a secure connection still.
