### ISSUE TITLE
Route logic interpreted by Pode contains ASCII characters. These breaks the route logic code.

### ISSUE THREAD

**Issue by larssb** [Badgerati/Pode#437]
### Describe the Bug
I have [this](https://gist.github.com/larssb/5c0e8a93235e43f2f6e7755d6b3bff54) server.ps1 definition for Pode.
When requesting the route the following error occurs:

```
A parameter cannot be found that matches parameter name &#39;OpenTimeout&#39;.
At /usr/src/app/API/Server.ps1:36 char:20
+ ...  $Servers = Get-ActiveScanAndPayServer -Config $Config -System $Syste ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
at CreatePSSession, /usr/src/app/Classes/Helpers/IISSiteManager.ps1: line 24
at IsIISSiteRunning, /usr/src/app/Classes/Helpers/IISSiteManager.ps1: line 57
at Get-ActiveScanAndPayServer&lt;Process&gt;, /usr/src/app/Public/ScanAndPayActions/Get-ActiveScanAndPayServer.ps1: line 61
at &lt;ScriptBlock&gt;, /usr/src/app/API/Server.ps1: line 36
at Invoke-PodeScriptBlock, /usr/local/share/powershell/Modules/Pode/Public/Utilities.ps1: line 638
at &lt;ScriptBlock&gt;, &lt;No file&gt;: line 57
    + InvalidArgument: (:) [Get-ActiveScanAndPayServer], ParameterBindingException
```

The error occurs within this code block in the IISSiteManager.ps1 file:

```
hidden static [PSCustomObject]CreatePSSession([String]$Server, [bool]$InteractiveSession, $DebugLog)
    {
        $SessionTimeout = 10000
        $SessionOpts = New-PSSessionOption -OpenTimeout $SessionTimeout -CancelTimeout $SessionTimeout -IdleTimeout ($SessionTimeout*6)
        try {
            <#
                - HACK TO TEST WITH SB..... directly on New-PSSession
            #>
            $Password = [Environment]::GetEnvironmentVariable("sbfailoversvcpass") | ConvertTo-Securestring
            $Credentials = new-object -typename System.Management.Automation.PSCredential -argumentlist "DOMAIN\sb....",$Password
            #
            $Session = New-PSSession -ComputerName $Server -SessionOption $SessionOpts -Credential $Credentials -ErrorAction Stop
            # Return the instantiated session
            return $Session
.............
```

- IISSiteManager.ps1 contains a class.
- IISSiteManager.ps1 is dot-sourced in the `Begin` block of the `Get-ActiveScanAndPayServer` function.

### Steps To Reproduce
This might be hard to reproduce without the full repository. I'm very open to that. But, maybe it is possible to troubleshoot this without the full repository. If not, we might be able to figure out something.

N.B. It is important to know that this only happens when the workload is executed inside a Docker container.

### Expected Behavior
A routes logic (scriptblock) does not contain odd ASCII characters. And therefore do not break cmdlet's/functions called later.

### Platform
 - OS: Docker Desktop v19.03.5 on Windows 10 build 1809
 - Podman, Invoke-RestMethod used to call the TestBuyFlow route
 - Pode version: v1.2.1
- PowerShell version, v6.2.3 (the version that comes with the Pode container image

### Additional Context
* I consider it rather strange that the `Read-Config` and the `Get-OAuthToken` functions work without issues. But, the `Get-ActiveScanAndPayServer` does not when calls in the `IISSiteManager` class methods are called.

* I did a `docker exec` into the container to do a `cat` of the `IISSiteManager` file. No ASCII characters to be seen.

* The `Get-OAuthToken` function also dot-sources a helper class. Which contains other functions/cmdlets. There is no issues with that.

---

I hope the above sufficiently explains the issue. If not feel free to ask for more. I'll happily provide it.

Have a great day.

**Comment by Badgerati** [comment]
Hey @larssb,

The ASCII characters will be when Pode converts the exception details into an HTTP/JSON safe format.

For the error "`A parameter cannot be found that matches parameter name "OpenTimeout"`", on Linux it would appear that the `New-PSSessionOption` function doesn't have the `-OpenTimeout` parameter 🤔- but on Windows it is present. Since the Pode container runs on Ubuntu, this is likely your issue.

Hope that helps!

**Comment by larssb** [comment]
Ah the ASCII characters makes sense then. Hmmm you might very well be 100% correct. However, this means that the [docs](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/new-pssessionoption?view=powershell-6) are incorrect? As we agree that it PowerShell core that the container runs?
I just bumped my PowerShell version on my Mac to v6.2.3 and yes there is no `OpenTimeout` parameter. Shiiit. Rather strange when the docs says so. As I did read that when I got the error.

What a bummer. However, I'll test if I can just adjust the `$PSSessionOption` pref. variable.

**Comment by Badgerati** [comment]
It is definitely PowerShell Core 6.2.3 in the container. I have seen a couple of other functions like this before, where certain parameters on *nix are missing - normally it's anything that deals with remoting and WinRM 🤔

**Comment by larssb** [comment]
I'll try the `$PSSessionOption` variable. This is definitely not *Pode* being the culprit here. Should I go ahead and close this one. Or get back with what was the solution?

**Comment by Badgerati** [comment]
I feel it should be OK to close the issue; you can comment back with what he solution was afterwards if you want to 😄

**Comment by larssb** [comment]
Sure thang

**Comment by larssb** [comment]
Changing timeout values and so forth, for remote PowerShell sessions, via `$PSSessionOption` was the fix. Actually connecting though. Authenticating via an AD user to a Windows machine via the Pode Linux container, now that was even more challenging.

**Comment by Badgerati** [comment]
I can imagine for AD! I'm actually currently working on an extension module "Pode.Ldap" that uses Novell's library for xplat support.

**Comment by larssb** [comment]
Very interesting. I will be looking forward to that.
