### ISSUE TITLE
routes.ps1 - Get-PodeEndpointByName - not in accordance with contributing guide

### ISSUE THREAD

**Issue by jhainau** [Badgerati/Pode#446]
### Describe the Change
portion of Get-PodeEndopintByName uses forbidden commandlets 
instead of using Where-Object and Select-Object -First 1,
```PowerShell
    $found = $(foreach ($i in $PodeContext.Server.Endpoints) {
            if ($i.name -ieq $EndpointName) {
                $i
                break
            }
        }
    )
```
### Related Issues
https://github.com/Badgerati/Pode/blob/develop/.github/CONTRIBUTING.md#powershell-commandlets

**Comment by jhainau** [comment]
also in same Routes.ps1, the function Convert-PodeFunctionVerToHttpMethod can be simplified:
```PowerShell
function Convert-PodeFunctionVerbToHttpMethod {
    param (
        [Parameter()]
        [string]
        $Verb
    )
    # if empty, just return default
    switch ($Verb) {
        { $_ -in @('Find', 'Format', 'Get', 'Join', 'Search', 'Select', 'Split', 'Measure', 'Ping', 'Test', 'Trace') } { 'GET' }
        { $_ -in @('Set') } { 'PUT' }
        { $_ -in @('Rename', 'Edit', 'Update') } { 'PATCH' }
        { $_ -in @('Clear', 'Close', 'Exit', 'Hide', 'Remove', 'Undo', 'Dismount', 'Unpublish', 'Disable', 'Uninstall', 'Unregister') } { 'DELETE' }
        Default { 'POST' }
    }
}
```

**Comment by Badgerati** [comment]
Hahah, yes. So the first one is safe to change, but is also safe to leave. I appear to have missed out a small part about not using them 😳 

Ideally these cmdlets want to be avoided, but don't have to be. However, they absolutely need to be avoided in functions that are used within a request-flow. The above function is "safe", as it is only invoked once when a route is created, and then never again - so performance wise the cmdlets are negligible.

They're both safe to be changed though! You're proposed changes look good if you want to make them? 😄 One recommendation I'd have is to switch `-in` to `-iin` - just to make sure case doesn't become an issue!

**Comment by jhainau** [comment]
Pull request submitted... my first one ever 😃.

**Comment by Badgerati** [comment]
Congrats on your first pull request! 🎉 I've merged it in, thanks for the contribution! 😃
