### ISSUE TITLE
Swap EndpointName to be an array

### ISSUE THREAD

**Issue by ArieHein** [Badgerati/Pode#448]
### Describe the Change
When creating an Endpoint, we can give it a Name.
When creating a Route you can point it to a matching Endpoint Name.

I would like to be assign a Route to more then one EndpointName, if the action is the same for both so i do not have to create a copy of a Route just to point it to a different EndpointName

Today:

Add-PodeEndpoint -Address localhost -Port 8080 -Name 'User'
Add-PodeEndpoint -Address localhost -Port 9090 -Name 'Admin'

Add-PodeRoute -Method Get -Path '/health -EndPointName 'User' -ScriptBlock { do action }

Add-PodeRoute -Method Get -Path '/health -EndPointName 'Admin' -ScriptBlock {do same action}

Instead:

Add-PodeRoute -Method Get -Path '/health -EndPointName 'User','Admin' -ScriptBlock { do action }

or similar syntax, idea is to allow it to accept arrays.

Main reason for this is that i want to create a web site with user commands and Admin commands. Some of the commands (a.k.a routes) will do the same for both of them, but some are only for admin. Naturally it also saves duplication and decreases the size of server.ps1

**Comment by Badgerati** [comment]
Hi @ArieHein,

Sounds good! I should be able to look into this for the next release

**Comment by Badgerati** [comment]
Updated both `Add-PodeRoute` and `Add-PodeStaticRoute`, so you can now pass an array of EndpointNames:

```powershell
Add-PodeRoute -Method Get -Path '/' -EndpointName 'Admin', 'User' -ScriptBlock {}
```

**Comment by ArieHein** [comment]
Brilliant!

Whats the plan for 1.4 ?

**Comment by Badgerati** [comment]
I try to get a release out every ~2 weeks, so it should be either next week or the week after.
