### ISSUE TITLE
Long URL's

### ISSUE THREAD

**Issue by LLIT** [Badgerati/Pode#45]
I am trying to send a long base64 string as a parameter to the API.
When i reach +260 characters, the server returns a 400 bad request.

Found this, and is testing now.

https://support.microsoft.com/da-dk/help/820129/http-sys-registry-settings-for-windows

**Comment by Badgerati** [comment]
This worked for me:

```powershell
New-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Services\HTTP\Parameters' -Name 'UrlSegmentMaxLength' -Value 0 -PropertyType DWord -Force
```

In Linux it just works out-of-the-box.

**Comment by LLIT** [comment]
Thanks

**Comment by majkinetor** [comment]
Should be documented.

**Comment by Badgerati** [comment]
Agreed, a `Known Issues` page is long overdue for this issue
