### ISSUE TITLE
Forcing a Version of Pode as a Minimum on startup

### ISSUE THREAD

**Issue by ArieHein** [Badgerati/Pode#451]
### Question
Is there a way to force a specific version of Pode, for example in the package.json or server1.psd that will not allow it to continue loading if pode engine is not of version x.y.z as a minimum ?

**Comment by Badgerati** [comment]
Hey @ArieHein,

There's nothing native within Pode for this, but in theory you could have the following just before your `Start-PodeServer` call:

```powershell
Import-Module -Name Pode -MinimumVersion '<version>' -ErrorAction Stop
```

That should fail startup if that version of Pode is missing.

**Comment by ArieHein** [comment]
Hmm that is true.

I want to make sure new devs that dont have it installed on thier machine will (at least the minimum version) will have it when they try to use it the first time.
