### ISSUE TITLE
High CPU/Memory

### ISSUE THREAD

**Issue by awickham10** [Badgerati/Pode#452]
### Describe the Bug
I'm experiencing high CPU and memory usage when running a pretty basic API server. 15-30% CPU ~~and 300-400 MB memory~~ when sitting idle.

### Steps To Reproduce
- Start-PodeServer with DisableTermination
- Custom logging method for errors and requests
- Two endpoints, one for http and one for https
- Two get routes, both server results from Get-ChildItem on pretty small directories (20 items)
- NSSM to run it as a service

### Expected Behavior
Minimal CPU and memory usage.

### Screenshots
N/A

### Platform
 - OS: Windows Server 2012 R2
 - Browser: N/A
 - Version [e.g. PS6.2.1]: PowerShell 5.1, Pode 1.3.0

**Comment by awickham10** [comment]
I've found that a couple external modules contribute a decent amount to the memory usage but CPU still remains an issue.

**Comment by Badgerati** [comment]
Hi @awickham10,

I should be able to take a look at reproducing this later, but I'm wondering if it could be the logging 🤔. What happens to the CPU if you disable the error/request logging?

**Comment by awickham10** [comment]
I commented out the logging and I'm seeing similar CPU usage.

**Comment by Badgerati** [comment]
I put together a server, and started it - letting it run idly. This was both in a pwsh terminal and using nssm, on WS2012 and WS2016.

For all 4 cases the CPU usage was <1-2%.

Below is the server I was using to test.
```powershell
Start-PodeServer -DisableTermination {
    Add-PodeEndpoint -Address 127.0.0.1 -Port 8080 -Protocol Http
    Add-PodeEndpoint -Address 127.0.0.1 -Port 8081 -Protocol Https -SelfSigned

    New-PodeLoggingMethod -Terminal | Enable-PodeErrorLogging
    New-PodeLoggingMethod -Terminal | Enable-PodeRequestLogging

    Add-PodeRoute -Method Get -Path '/test1' -ScriptBlock {
        Get-ChildItem 'C:\' | Out-Null
        Set-PodeResponseStatus -Code 200
    }

    Add-PodeRoute -Method Get -Path '/test2' -ScriptBlock {
        Get-ChildItem 'C:\' | Out-Null
        Set-PodeResponseStatus -Code 200
    }
}
```

Is there anything else in your server, or some other external module your using that could be causing the CPU to idle high?

**Comment by awickham10** [comment]
Turns out it is due to PSFramework. I'll open a ticket with them. Sorry for wasting your time!

**Comment by Badgerati** [comment]
No worries, glad you found it! 😃  I'll close this issue
