### ISSUE TITLE
Inspect HTTP events

### ISSUE THREAD

**Issue by dfinke** [Badgerati/Pode#457]
Can this be accomplished with Pode?

https://requestbin.com/

**Comment by Badgerati** [comment]
Hey @dfinke,

Do you mean can you do something like RequestBin with Pode, where you can send any HTTP request regardless of method/path and inspect the Request?

If so, this should do it:

```powershell
Add-PodeRoute -Method * -Path '/*' -ScriptBlock {
    param($e)
}
```

The `$e` parameter will contain the normal `$e.Data`, `$e.Query`, and others depending on what's sent.

**Comment by ArieHein** [comment]
could probably also create a middleware for more in depth inspection ?
