### ISSUE TITLE
Store the uptime of the server, and the number of restarts

### ISSUE THREAD

**Issue by Badgerati** [Badgerati/Pode#459]
### Describe the Change
The should be 2 new metrics stored within Pode for Uptime and Restart Count. In the case of both, they should be stored on the `$PodeContext` internal object.

#### Uptime
The uptime can be stored as just the start time of the server, and be reset every time the server is restarted.

There should be a new `Get-PodeServerUptime` function which returns the uptime of the server in seconds.

There could also be a separate start time stored, which is the original start time. This remains the same throughout restarts. Then on the above function some `-Total` switch will return the total uptime of the server in seconds regardless of restarts.

#### Restarts
The restart counter will start at 0, and will increment by 1 per server restart. Some `Get-PodeServerRestartCount` will return this count.

**Comment by ArieHein** [comment]
i like the idea. I assume the restart counter goes back to 0 when the machine it runs on restarts ?

**Comment by Badgerati** [comment]
Yeah, if the actual machine/vm gets restarted the counter will reset.

**Comment by Badgerati** [comment]
In line with the new #464, these metrics will be stored in the `$PodeContext` as:

```powershell
Metrics = @{
    Server = @{
        IntialLoadTime = '2020-01-25 00:00:00.000'
        StartTime = '2020-01-30 00:00:00.000'
        RestartCount = 3
    }
}
```

The new functions will remain the same.
