### ISSUE TITLE
Bug in web-rest-openapi-simple.ps1

### ISSUE THREAD

**Issue by haidouks** [Badgerati/Pode#465]
### Post method example in web-rest-openapi-simple.ps1 has a bug.
While route definition expects a lower case 'userId' property, it is defined uppercase as Open API property. Also OA property 'Name' has no effect on route example. 

### Steps To Reproduce
1. Go to 'examples/web-rest-openapi-simple.ps1
2. Check line number 43,48 and 49

### Expected Behavior
Post sample on Swagger, should set Name and userId properties.

### Platform
 - OS: MacOS
 - Browser Safari
 - Version 6.2.3

**Comment by Badgerati** [comment]
Closing now it's been merged; thanks!
