### ISSUE TITLE
API authentication with Certificate

### ISSUE THREAD

**Issue by Manasa-Sathyanarayan** [Badgerati/Pode#472]
HI,

I have a scenario where I want only particular server having certificate can execute this API, kind of authenticating Pode server to do any active if you have Certificate on the serve.

Is that possible?

**Comment by Badgerati** [comment]
On initial investigation this does appear to be possible, if there's a client certificate available on the request. I'll play around a little more, but this could either be a new auth type (using certs), or any available client certs are supplied to the existing auth types - or both 🤔

**Comment by manasa1633** [comment]
Thank You @Badgerati Will be waiting to see your next step
