### ISSUE TITLE
Error using Pode with IIS as Reverse proxy in DotnetCore hosting module

### ISSUE THREAD

**Issue by ehagen** [Badgerati/Pode#475]
When using a Pode Server in IIS like we use Asp.Net Core applications with out of process hosting, I encounter the following error:

In browser
	HTTP Error 502.5 - ANCM Out-Of-Process Startup Failure

In logs
	Exception setting "TreatControlCAsInput": "There is no console."
	At D:\dev\Pode\src\Public\Core.ps1:134 char:13
	+             [Console]::TreatControlCAsInput = $true

When I disable this line everything works okay.

### Steps To Reproduce
- Install IIS or IIS Express
- Install DotnetCore Windows Hosting (choco install dotnetcore-windowshosting -y)
- Create website in IIS and set physical folder to dir with pode server script and add web.config file with contents
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <location path="." inheritInChildApplications="false">
    <system.webServer>
      <handlers>
        <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
      </handlers>
      <aspNetCore processPath="pwsh.exe" arguments=".\webpages.ps1" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" hostingModel="OutOfProcess"/>
    </system.webServer>
  </location>
</configuration>
```
- Update Pode\examples\web-simple-pages.ps1 with detecting ASPNETCORE port and address
```powershell
	$port = 8090
	$address = 'localhost'
	# detect if running in IIS dotnet core app-pool
	if ($env:ASPNETCORE_PORT)
	{
	    $port = $env:ASPNETCORE_PORT
	    $address = '127.0.0.1' # localhost not working
	}
	
	Add-PodeEndpoint -Address $address -Port $port -Protocol Http # replace line
```

Suggested fixes

1: Add to function Start-Server -Type IIS-Hosting and change Core.Ps1 line 132 with checking ServerType and don't set TreatControlCAsInput

```powershell
        # set it so ctrl-c can terminate, unless serverless
        if (!$PodeContext.Server.IsServerless) {
            [Console]::TreatControlCAsInput = $true
        }
```

2: Quick fix ignore error in try/catch or detect no console

**Comment by Badgerati** [comment]
Hey @ehagen,

I've managed to reproduce the same error you're getting, though once commented out the page for me still fails to load - but with no errors. I don't know if there was anything else you also did to make the pages load?

The errors do go away though once `[Console]::TreatControlCAsInput = $true` is removed.

For the fix, I'm thinking of either:

* An `-IIS` switch on `Start-PodeServer`. or
* We could check if `$env:ASPNETCORE_PORT` (or `$env:APP_POOL_CONFIG`) is present internally, and flag the server as being hosted by IIS automatically

There does appear to be a fair few environment variables that only exist when hosted by IIS, so checking for these could be more ideal 🤔 

On another note, having the steps on how to host Pode via IIS is really cool! So if you're ok with it, and we can get this working, I could also use these steps to add into Pode's docs.

**Comment by ehagen** [comment]
I have attached my sample to this comment. Put it into the repo samples folder and change the web.config to point to 'web-static2.ps1'. Don't use a folder inside the c:\inetpub folder (security issues). See the samples\logs folder for issues.
[web-static2.ps1.txt](https://github.com/Badgerati/Pode/files/4203696/web-static2.ps1.txt)

Would be nice if you added this as a standaard option.

**Comment by ehagen** [comment]
Just one more remark: You need to start your site with type **Pode**, a lot of the samples don't do this.
````powershell
Start-PodeServer -Type Pode -Threads 2
````

**Comment by Badgerati** [comment]
Yep, adding `-Type Pode` worked! Interesting, there must be something that HttpListener is doing to block the requests 🤔 

As for the `-Type Pode`, this is Pode's pure powershell web server which allows xplat HTTPS support. If you don't supply the type then HttpListener is used as default - which is why the majority of the samples don't specify the type unless HTTPS is required. But in this case, it would appear to be needed!

As for the fix, I'll make it so Pode checks for the existence of the `$env:ASPNETCORE_PORT` environment variable. If it exists, then `[Console]::TreatControlCAsInput = $true` will be skipped.

**Comment by ehagen** [comment]
Just for the record. A webserver based on http.sys (Like System.Net.HttpListener) is not supported in an ASP.NET Core Module (see https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/aspnet-core-module?view=aspnetcore-3.1)

This is why we can only use Start-PodeServer -Type 'Pode'. 

Did you check the query string handling of PodeServer. Things like 

````powershell
Add-PodeRoute -Method Get -Path '/api/diag' -ScriptBlock {
    param($e)
    if ($e.Query -ne $null)
    {
        if ($e.Query.ContainsKey('id'))
        {
           # do something with id
        }
    }
    Write-PodeJsonResponse -Value "{`"result`" : `"true`"}]"
}
````
are not working anymore

**Comment by Badgerati** [comment]
Aah, that makes sense!

As for the query strings, it seems on the PodeServer it's being left as a NameValueCollection - rather than been converted to a HashTable. The first query anme/value pair is also a little weird at times, where the key could contain the `?`.

I haven't tested everything running from IIS yet - I'll do that as a part of this - but since the query string logic appears to be separately broken, I'm going to move that to it's own issue.

**Comment by Badgerati** [comment]
That above commit works with IIS, I did some extra testing as well and query strings now also appear to be working.

I've also made it so that `Add-PodeEndpoint` will default to using `$env:ASPNETCORE_PORT` as the `-Port` (if not supplied) when Pode detects it's running under IIS. Also, the `-Type` on `Start-PodeServer` is set to `Pode` when under IIS.

So you can now just do the following, and the Server Type and Endpoint Port are defaulted:
```powershell
Start-PodeServer -Threads 2 {
    Add-PodeEndpoint -Address '127.0.0.1' -Protocol Http

   # routes, auth, etc
}
```

**Comment by ehagen** [comment]
I checked the commit and it's working.

Maybe it's nice to modify function Add-PodeEndpoint $Address to '127.0.0.1' when inIIS to prevent required '127.0.0.1' in address. This also prevents the 'Must be running with administrator privileges to listen on non-localhost addresses' error if you changed it before the check.

This would be working when running in IIS and as stand-alone

Add-PodeEndpoint -Protocol Http

and

Add-PodeEndpoint -Address * -Protocol Http

I have still some issues with the PodeServer using Get-PodeSessionMiddleware (Sessions.Store is null or $e.Session is null) / Authentication but this has nothing to do with IIS hosting but more with difference between Webserver and PodeServer

**Comment by Badgerati** [comment]
Something I'm also going to do is force the Port to be ASPNETCORE_PORT regardless, when in IIS and the protocol is HTTP/HTTPS.

One thing I did manage to get working though was it listening on hostnames - so `localhost` or `test.pode.com` etc. For the `test.pode.com` for example, I had to supply `-Force` to `Add-PodeEndpoint`, but I could use SNI in IIS 🤔. One idea could be to check if the Address is local or a hostname and skip the Admin check when running as IIS?

I also got HTTPS working too; IIS deals with all the certs and SSL streams, so we can leave Pode on a normal HTTP endpoint.

On the Authentication and Sessions, I just tried these in IIS, and outside of IIS, and both worked - with both Web/Pode server types as well. I imagine you mean `Enable-PodeSessionMiddleware`, and by the looks of it you're setting a custom Storage? Outside of the two server types, everything else is pretty much identical - the only real difference in the server types is the Request/Response parsing. 

Feel free to raise an issue for it though, in case it is a problem!

**Comment by Badgerati** [comment]
Did a bit more playing and I agree, under IIS:

* the Address will be forced to `127.0.0.1`
* the Port will be forced to `ASPNETCORE_PORT`
* the server Type will be forced to `Pode`
* the endpoint Protocol will be forced to `HTTP` (as IIS deals with all HTTPS)

So even if you had the below to run locally, under IIS it'll still work:

```powershell
Start-PodeServer -Threads 2 {
    Add-PodeEndpoint -Address 127.0.0.2 -Port 8080 -Protocol Http

    # etc
}
```

**Comment by ehagen** [comment]
Top, I give it a try

**Comment by ehagen** [comment]
Maye it's nice to add the IIS Authenticated user from the Request and surface it in Pode

```powershell
$Win32CloseHandle = Add-Type -Name Win32CloseHandle -PassThru -MemberDefinition @'
    [DllImport("kernel32.dll", SetLastError = true)]
    public static extern bool CloseHandle(IntPtr handle);
'@
```
in Invoke-PodeSocketHandler for example
```powershell

        if ($WebEvent.Request.Headers.ContainsKey('MS-ASPNETCORE-WINAUTHTOKEN'))
        {
            $winAuthToken = [System.IntPtr][Int]"0x$($WebEvent.Request.Headers['MS-ASPNETCORE-WINAUTHTOKEN'])"
            $winIdentity = New-Object System.Security.Principal.WindowsIdentity($winAuthToken, 'Windows')
            $Win32CloseHandle::CloseHandle($winAuthToken)
            Write-Host "user: $($winIdentity.Name) type: $($winIdentity.AuthenticationType)"
        }
```
For details see
IIS midlleware
https://github.com/dotnet/aspnetcore/blob/f6c3f9e02ab7c4ae5c395245f2792ba18c33075a/src/Servers/IIS/IISIntegration/src/IISMiddleware.cs line 164

And maybe it's nice to add the email address to the (Windows)User (also in Add-PodeAuthWindowsAd) like
````powershell
$windowsIdentity = [System.Security.Principal.WindowsIdentity]::GetCurrent()
$sidbind = "LDAP://<SID=" + $windowsIdentity.user.Value.ToString() + '>'
$MailAddress = ([ADSI]$sidbind).mail.tostring()
````
Lots of times I need user & email :)

**Comment by Badgerati** [comment]
The first part should be OK, as it'll only be on Windows for IIS. Something like `$WebEvent.IIS.User` with `Name` and `Type` properties?

For the Windows AD and Email, that's definitely possible - I'll make it apart of #474 to include the user's email :)

For the example you've put, is that apart of the IIS user logic? (So get the Name, Type, and Email?)

**Comment by ehagen** [comment]
<<is that apart of the IIS user logic
Standard is getting the WindowsIdentity, which gives you the authenticated User if available. The rest is extra and up to the developer but very nice to have. So you can surface the Identity and the Email for IIS. To keep everything standard in all auth providers surface Name, Type and Email with optionally Identity if in IIS.

**Comment by Badgerati** [comment]
Since this is about authentication, it sounds like it could be best as a new authentication type, something like:

```powershell
New-PodeAuthType -IIS | Add-PodeAuthWindowsAd -Name 'Auth' -IIS
```

The `New-PodeAuthType -IIS` checks for the `MS-ASPNETCORE-WINAUTHTOKEN` header and returns a 401 if not present. Otherwise, it's passed to `Add-PodeAuthWindowsAd` that runs similar logic to yours above, and sets the web event's `Auth.User` to the same as what the current LDAP WindowsAd does:

```powershell
$Win32CloseHandle = Add-Type -Name Win32CloseHandle -PassThru -MemberDefinition @'
    [DllImport("kernel32.dll", SetLastError = true)]
    public static extern bool CloseHandle(IntPtr handle);
'@

try {
    $winAuthToken = [System.IntPtr][Int]"0x$($IISToken)"
    $winIdentity = New-Object System.Security.Principal.WindowsIdentity($winAuthToken, 'Windows')
    $adUser = [ADSI]"LDAP://<SID=$($winIdentity.User.Value.ToString())>"

    return @{
        User = @{
            AuthenticationType = $winIdentity.AuthenticationType
            DistinguishedName = @($adUser.distinguishedname)[0]
            Username = ($winIdentity.Name -split '\\')[-1]
            Name = @($adUser.name)[0]
            Email = @($adUser.mail)[0]
            Fqdn = $Server
            Domain = ($winIdentity.Name -split '\\')[0]
            Groups = $groups
        }
    }
}
finally {
    $Win32CloseHandle::CloseHandle($winAuthToken)
}
```

^ something along these lines could work.

**Comment by Badgerati** [comment]
I've created a new `Add-PodeAuthIIS` function - this is just a standalone function that sets up a custom authentication to parse for the AUTHTOKEN header. It has a similar makeup to `Add-PodeAuthWindowsAd`, and the `User` object in `$e.Auth` is the same.

If the AUTHTOKEN is missing a 401 is returned. I've managed to test it a little for both Local and AD users.

```powershell
Start-PodeServer {
    Add-PodeEndpoint -Address 127.0.0.1 -Protocol Http

    Add-PodeAuthIIS -Name 'IISAuth'

    Add-PodeRoute -Method Get -Path '/test' -Middleware (Get-PodeAuthMiddleware -Name 'IISAuth') -ScriptBlock {
        param($e)
        Write-PodeJsonResponse -Value @{ User = $e.Auth.User }
    }
}
```

(I've also added a `Test-PodeIsIIS` in case you need to switch between logics locally and under IIS)

**Comment by Badgerati** [comment]
Been able to test this a little more today and seems to be working as expected. If it looks good to you I can look to merge this for 1.6.0 😄

**Comment by ehagen** [comment]
Looks very good. I will implement it next week into production and let you know if issues arise. Nice to have IIS integration now.

**Comment by ehagen** [comment]
When testing the Add-PodeAuthIIS -Name 'IISAuth' -NoGroups I noticed that 

 $noGroups = $options.NoGroups
 
 is missing in function Get-PodeAuthWindowsADIISMethod. Now it's always true…
 
Can you also move the vars
                        $localUser = $winIdentity.Name -replace '\\', '/'
                        $ad = [adsi]"WinNT://$($localUser)"
 
Into the (dirty) NoGroups check clause
 
                    if (!$NoGroups) {
                        $localUser = $winIdentity.Name -replace '\\', '/'
                        $ad = [adsi]"WinNT://$($localUser)"
                        $cmd = "`$ad = [adsi]'WinNT://$($localUser)'; @(`$ad.Groups() | Foreach-Object { `$_.GetType().InvokeMember('Name', 'GetProperty', `$null, `$_, `$null) })"
                        $user.Groups = [string[]](powershell -c $cmd)
                    }
 
For the rest everything is working very good.

**Comment by Badgerati** [comment]
Woops on the `$NoGroups`! I can fix  those to be `$options.NoGroups`.

On the following lines:
```powershell
$localUser = $winIdentity.Name -replace '\', '/'
$ad = [adsi]"WinNT://$($localUser)"
```

I can move them, however it would also mean losing (or moving) the following line to get that user's name:
```powershell
$user.Name = @($ad.FullName)[0]
```

What's the reason in wanting those lines moved?

Glad to hear it's working though!

**Comment by ehagen** [comment]
I had issue on workstation with no AD present, call was very slow initially. With AD present it was working okay. Keep the $user.Name from $ad. I missed that.

**Comment by Badgerati** [comment]
Ah yeah, when adsi is done locally using WinNT the first couple of calls go slow; but it normally goes quick after the first couple 🤔 .

Instead of moving it into NoGroups, I could add a new switch (`-NoLocalAD` or `-NoLocalCheck`), and if supplied that stops the local user AD/Groups check?:

```powershell
$user.UserType = 'Local'

if (!$options.NoLocalAD) {
    $localUser = $winIdentity.Name -replace '\\', '/'
    $ad = [adsi]"WinNT://$($localUser)"
    $user.Name = @($ad.FullName)[0]

    if (!$options.NoGroups) {
        $cmd = "`$ad = [adsi]'WinNT://$($localUser)'; @(`$ad.Groups() | Foreach-Object { `$_.GetType().InvokeMember('Name', 'GetProperty', `$null, `$_, `$null) })"
        $user.Groups = [string[]](powershell -c $cmd)
    }
}
```

**Comment by ehagen** [comment]
Top good solution

**Comment by Badgerati** [comment]
Added a new `-NoLocalCheck`, which will stop Pode from doing local user lookups.

**Comment by ehagen** [comment]
Works as expected. Everything working good now.

**Comment by Badgerati** [comment]
Excellent!
