### ISSUE TITLE
write html not working

### ISSUE THREAD

**Issue by phand00** [Badgerati/Pode#479]
Unable to use the Write-PodeHtmlResponse? Seem there is a bug.
Lasted version fetch this morning from PowershellGallery

some simple example fail with blank page or hashtable msg object displayed

/test return:
 blank
/test2 return:
IsReadOnly	IsFixedSize	IsSynchronized	Keys	Values	SyncRoot	Count
False	False	False	System.Collections.Hashtable+KeyCollection	System.Collections.Hashtable+ValueCollection	System.Object	1

Here is to code for the sample to reproduce the error:
`Start-PodeServer -threads 2 {
	Add-PodeEndpoint -address * -port 8080 -protocol Http

	Add-PodeRoute -Method Get -Path '/test' -ContentType 'text/html' -ScriptBlock {
	    '<html><body>Welcome to <b>TEST - Web Service</b> <br><br>Need <a href=help>help</a>?</body></html>'
	}

Add-PodeRoute -Method Get -Path '/test2' -ScriptBlock {
		Write-PodeHtmlResponse -Value @{ Message = 'Hello, all!' }
	}
	
	
	Add-PodeRoute -Method Get -Path '/json' -ScriptBlock {
	    $v = 'Welcome to TEST - Web Service'
		Write-PodeJsonResponse -Value @{ 'value' = $v; }
	}
	
	Add-PodeRoute -Method Get -Path '/about' -ContentType 'text/html' -ScriptBlock {
		Write-PodeHtmlResponse -Path 'c:\util\about.html'
                # Don't forget to create the about.html file with valid content.
	}
}`

**Comment by Badgerati** [comment]
Hey @phand00 

For the first one, `/test`, you'll also need to use `Write-PodeHtmlResponse`:

```powershell
Add-PodeRoute -Method Get -Path '/test' -ContentType 'text/html' -ScriptBlock {
   Write-PodeHtmlResponse -Value  '<html><body>Welcome to <b>TEST - Web Service</b> <br><br>Need <a href=help>help</a>?</body></html>'
}
```

For the `/test2` issue, this is more of the way PowerShell's `ConvertTo-Html` and `ConvertTo-Xml` work. They work best with Classes or PSObjects, with HashTables those functions get a little weird. It'll either be best to build the HTML dynamically, or use a PSObject instead.

For the first one though, that could be an idea for an enhancement to allow returning a value from the Route's scriptblock - with the value being written to the response. 🤔 

Hope that helps!

**Comment by Badgerati** [comment]
Although, I might be able to use a trick I used in XML/CSV to make HashTables output a little nicer, which is to include the following for hashtables:

```powershell
$Value = @(foreach ($v in $Value) {
    New-Object psobject -Property $v
})
```

**Comment by phand00** [comment]
Well, I tried the Write-PodeHtmlResponse -Value '' like you mentionned and it works. Is it possible to correct the documentation accordingly because example 1 and 2 does not work. This is the reason I wrote this /test and /test2 sample. 
Documentation URL I'm referring to: https://badgerati.github.io/Pode/Functions/Responses/Write-PodeHtmlResponse/

thanks

**Comment by Badgerati** [comment]
Shockingly the function's summary actually has it correct!
```powershell
.EXAMPLE
Write-PodeHtmlResponse -Value '<html><body>Hello!</body></html>'
```

This appears to be an issue with mkdocs and markdown 🤔 

I'll see what I can do though!
