### ISSUE TITLE
JSON reply order

### ISSUE THREAD

**Issue by ArieHein** [Badgerati/Pode#489]
Small petty OCD question ;)

When using the PodeJsonResponse, when supplying a json with multiple values, how is the order of the values being displayed ?

Assume I have this in server.ps1

 ```
 # Create route for uptime
  Add-PodeRoute -Method GET -Path '/uptime' -ContentType 'application/json' -ScriptBlock {
    $Current = Get-PodeServerUptime
    $Total = Get-PodeServerUptime -Total
    Write-PodeJsonResponse -Value @{ 'Current' = $Current ; 'Total' = $Total}
  }
```
I would assume the reply would look like this:
```
{
  "Current": 1000,
  "Total": 2000
}
```

Instead I get this:
```
{
  "Total": 2000,
  "Current": 1000
}
```

Normal ? Intended ? Configurable ?

Thanks

**Comment by Badgerati** [comment]
Hey @ArieHein, I've tested the following and it works:

```powershell
Write-PodeJsonResponse -Value ([pscustomobject]@{ 'Current' = $Current ; 'Total' = $Total})
```

Unfortunately this doesn't appear to be something I can put into the function itself. The conversion has to be directly on the raw hashtable, doing it to the variable/parameter and the order reverts back to being unordered again 😕

**Comment by Badgerati** [comment]
You can also use `[ordered]` instead of `[pscustomobject]` as well - but that also has the same issue of only being able to convert a literal hashtable, and not a variable 😞

**Comment by jhainau** [comment]
You can use both PSCustomObject And Ordered on the same object. You can even add them nested inside:
`Write-PodeJsonResponse -Value [pscustomobject][ordered]@{ 'Current' = $Current ; 'Total' = $Total; 'example' = [pscustomobject][ordered]@{'item1'=$something;'item2'=$somethingElse}}`
