### ISSUE TITLE
Default Response 

### ISSUE THREAD

**Issue by ArieHein** [Badgerati/Pode#494]
As I am building multiple routes over multiple endpoints, some exist in all endpoints but not all the routes exist in each endpoint.

When a call is made for a route that doesn't exist in an endpoint, is there away to have a default response (json / other) that will catch all theses occurrences ?

**Comment by Badgerati** [comment]
Would setting up a custom error page work for you: https://badgerati.github.io/Pode/Tutorials/Routes/Utilities/ErrorPages/#error-pages ?

That will let you setup a custom 404 page for routes that aren't found.

**Comment by ArieHein** [comment]
This will work for html but not json (?), I'm more looking into a 'catch all' type of response in json for services that try to consume my api and are reaching the right host and port but wrong path so have to reply with a json response back of some sort.

**Comment by Badgerati** [comment]
They support JSON 😃 even a `.png` if you were crazy enough!

You can create a `404.json` in the `/errors` directory - from the root of the server. Then, if the request's content type isn't already `application/json`, set a Route's `-ContentType` or `-ErrorContentType` to be `application/json` and it'll attempt to use the JSON 404 error.

Or you can set a general default error page type in the `server.psd1`:
```powershell
@{
    Web = @{
        ErrorPages = @{
            Default = "application/json"
        }
    }
}
```

(you can also filter by [route pattern](https://badgerati.github.io/Pode/Tutorials/Routes/Utilities/ErrorPages/#route-patterns))
