### ISSUE TITLE
Authentification and request file logging make the pode application freeze

### ISSUE THREAD

**Issue by PoSam66** [Badgerati/Pode#509]
### Describe the Bug
Activating bearer authentification and request file logging make the api freeze when multiple call to an endpoint are done at the same time. When the api is frozen, you have no choice to restart the pode application to fix the problem.

If you disable either the authentication or the logging file, the problem seem to disappear. Also, this problem doesn't seems to happen when using the terminal logging.

### Steps To Reproduce
1. Create a pode application with bearer authentification, request file logging and a endpoint using the authentification.
2. Make multiple simultaneous call to the created endpoint during more or less 15 seconds
3. At this point, the api should be frozen

### Platform
 - OS: Windows

**Comment by Badgerati** [comment]
Hi @PoSam66,

I've tried to reproduce this but I can't seem to get the freeze to occur. Would you be able to give a minimum script that causes the freeze to happen?

If not, would you be able to give me a bit more info into what your Bearer `Add-PodeAuth` script is doing? And potential how much load you're putting the endpoint under when the freeze triggers?

Under normal circumstances this technically shouldn't ever happen, as the Authentication and the Logging are in two separate runspaces 🤔 

For the API to freeze it could indicate that an error is occurring that causes the main Route runspaces to crash. If you try enabling Error logging to see if an error/stacktrace appears that could be useful.

Hope that helps, and thanks

**Comment by PoSam66** [comment]
Hi @Badgerati,
Thanks for your quick response! I did more testing on my side and it looks like it could be caused by the file monitoring. You can try to reproduce the issue with the Freeze_test.zip that I joined to this message.

[Freeze_Test.zip](https://github.com/Badgerati/Pode/files/4355472/Freeze_Test.zip)

Thank you.

**Comment by Badgerati** [comment]
Hey @PoSam66,

So with that I managed to reproduce it! I've pushed a potential fix, it was being caused when sessions were enabled - if you made the auth sessionless the freeze didn't happen.

The change is to make the ScriptMethods of the InMem PSObject session store be NoteProperty ScriptBlocks instead - which also increases the performance as well!

With the change, I couldn't get the freeze to trigger again.

Would you be able to test with the above commit (Issue-509 branch), see if it resolves the issue?
