### ISSUE TITLE
How to call a custom function from multiple routes

### ISSUE THREAD

**Issue by robertfshort** [Badgerati/Pode#512]
I may be missing the way to do this, or the documented inabilty to do this, but I have a function that I want to run from multiple routes. I know I can put that function within a route definition and it will work for that route. I attempted to put the function into middleware using:

```
add-podemiddleware -name 'whatever' -scriptblock {
function foo {
param($myparam)
return $true
}
```

but that function cannot be called from a route afterward.

Please update the documentation to include the correct process for accomplishing this, or the express inability to do so.

**Comment by Badgerati** [comment]
Hi @robertfshort,

To create shared functions for use in multiple routes, you'll need to put these functions into a custom module and then use `Import-PodeModule`. This way the module is loaded into all runspaces, and functions are usable everywhere.

This is [documented here](https://badgerati.github.io/Pode/Tutorials/ImportingModules/)

So as a quick example you could have a `module.psm1` and your `server.ps1`, and in your module:
```powershell
function foo {
    # do stuff
}
```

and in your server:
```powershell
Start-PodeServer {
    Import-PodeModule -Path './module.psm1'

    Add-PodeRoute -ScriptBlock {
        # call function
        foo
    }
}
```

Hope that helps!

**Comment by ArieHein** [comment]
Donnt forget in your module to export the functions at the end:

`Export-ModuleMember -Function foo`
