### ISSUE TITLE
Variable scope vs Thread/Runspacepool

### ISSUE THREAD

**Issue by phand00** [Badgerati/Pode#513]
### Describe the Bug
Hi,

we got some weird issues when we activate the -Threads parameter with value greater than 1, when starting Pode Server. After searching, we identified the problem to be related to local scope variable use. With runspacepool, the variable goes from initialized to unitialiazed to back to and old value. The issue is explained very well in this article https://learn-powershell.net/2018/01/28/dealing-with-runspacepool-variable-scope-creep-in-powershell/

I search in the pode src code but haven't found how to handle this as of now.

### Steps To Reproduce
1. Import a module
2. In your module, define a function with a local variable in the begin section and assign a value
3. In the process, use this variable and change the value. Write the value to the shell and see how the content of the variable change from initialized to unitialized depending witch thread handle the call... 
4. 

### Expected Behavior
Would like to have the option to respect the UseLocalScope if possible

**Comment by Badgerati** [comment]
I was often concerned this kind of a bug existed, and thanks for the link!

This hopefully looks like something quick to resolve by changing https://github.com/Badgerati/Pode/blob/aa0548338f52104940fe66f76d3ce3a9a9eaaa72/src/Private/Helpers.ps1#L642

to:
```powershell
$ps.AddScript($ScriptBlock, $true) | Out-Null
```

🤔

**Comment by phand00** [comment]
Hi Badgerati,

I tested with your suggestion but it's not working. It's a lot worse. I mean, pode start but nothing works. A simple request just never reach the routes as if the whole server is not listening at all. It looks like Pode code has something not compatible with the uselocalscope = $true parameter.

I dig futher and did a simple test to search for a solution and that's very strange. I use ActiveDirectory cmdlet in one of my route (trying to return a simple user information). The cmdlet Get-Aduser $username -properties mail return the mail property on the first call/thread. The subsequent call return the aduser without the mail property. And when I get back on the first thread (recall until you get back on the first thread), the mail property is filled again. But on all thread the distinguishedname is there and all right.

Thread 1: VERBOSE:  ad user CN=username,OU=OrgUnit,DC=contoso,DC=com [mail= firstname.lastname@contoso.com] found!
Threads X: VERBOSE:  ad user CN=username,OU=OrgUnit,DC=contoso,DC=com [mail=] found!

I also notice you have the -Now parameter on Import-PodeModule function, but I tried to use this parameter with no difference. I see in the Import-PodeModule that you load the module with -Global with that parameter. Thought that maybe it may load the module differently. 

If I try with another module function of our own. The first thread is working but all other threads have no result return... very strange. It behave like ad module. 

If you have some idea, let me know. Thanks

Danny

**Comment by Badgerati** [comment]
Hi Danny,

That might make some sense actually, the UseLocalScope could be blocking variables set within the Session State of the Runspaces - if these variables can be set as global then it could work.

On the `-Now`, that just loads the module into the current scope as well - rather than just the runspace scopes.

As for `Get-Aduser $username -properties mail`, that is a weird one! I can't actually see why that would work on one thread, and then not work on others 🤔 It doesn't seem like it could be the thread-scoping issue, but possibly something else.

Would you be able to put together a simple script that can reproduce that? Something I can test with to try and fix.

Thanks

**Comment by phand00** [comment]
Hi Matthew,

My test pode server with TestDirectory module

the url for the test: 

GET http://server.fqdn.com:8080/api/user/useridentity
Accept: application/json

[pode_bug_513.zip](https://github.com/Badgerati/Pode/files/4395683/pode_bug_513.zip)

output of multiple request:
[PS] ps01->C:\util\psh\danny> cd test
[PS] ps01->C:\util\psh\danny\test> pode start
Listening on the following 1 endpoint(s) [4 thread(s)]:
        - http://localhost:8080/
VERBOSE: Get-AdUser danny9301
VERBOSE:  ad user CN=danny9301,OU=OrgUnit,DC=contoso,DC=com [mail= Danny.X@contoso.com] found!
VERBOSE: Get-LDAPPersonne danny9301
VERBOSE: Get-AdUser danny9301
VERBOSE:  ad user CN=danny9301,OU=OrgUnit,DC=contoso,DC=com [mail=  cip=] found!
VERBOSE:  revert cip to identity [cip:danny9301]
VERBOSE: Get-LDAPPersonne danny9301
VERBOSE: Get-AdUser danny9301
VERBOSE:  ad user CN=danny9301,OU=OrgUnit,DC=contoso,DC=com [mail=  cip=] found!
VERBOSE:  revert cip to identity [cip:danny9301]
VERBOSE: Get-LDAPPersonne danny9301
VERBOSE: Get-AdUser danny9301
VERBOSE:  ad user CN=danny9301,OU=OrgUnit,DC=contoso,DC=com [mail=  cip=] found!
VERBOSE:  revert cip to identity [cip:danny9301]
VERBOSE: Get-LDAPPersonne danny9301
VERBOSE: Get-AdUser danny9301
VERBOSE:  ad user CN=danny9301,OU=OrgUnit,DC=contoso,DC=com [mail= Danny.X@contoso.com] found!
VERBOSE: Get-LDAPPersonne danny9301
VERBOSE: Get-AdUser danny9301
VERBOSE:  ad user CN=danny9301,OU=OrgUnit,DC=contoso,DC=com [mail=  cip=] found!
VERBOSE:  revert cip to identity [cip:danny9301]
VERBOSE: Get-LDAPPersonne danny9301
VERBOSE: Get-AdUser danny9301
VERBOSE:  ad user CN=danny9301,OU=OrgUnit,DC=contoso,DC=com [mail=  cip=] found!
VERBOSE:  revert cip to identity [cip:danny9301]
VERBOSE: Get-LDAPPersonne danny9301
VERBOSE: Get-AdUser danny9301
VERBOSE:  ad user CN=danny9301,OU=OrgUnit,DC=contoso,DC=com [mail=  cip=] found!
VERBOSE:  revert cip to identity [cip:danny9301]
VERBOSE: Get-LDAPPersonne danny9301
VERBOSE: Get-AdUser danny9301
VERBOSE:  ad user CN=danny9301,OU=OrgUnit,DC=contoso,DC=com [mail= Danny.X@contoso.com] found!
VERBOSE: Get-LDAPPersonne danny9301
Terminating... Done

Thanks :-)

**Comment by phand00** [comment]
Oh by the way. I'm running it on Windows Server 2019 with Powershell 5.1

**Comment by Badgerati** [comment]
Thanks!

I had to use `CN` to test, but was able to reproduce. I've a feeling this one could be an AD Module issue, as the second I added the following to your `config.ps1` the issue went away:

```powershell
Import-PodeModule -Name ActiveDirectory
Import-PodeModule -Name TestDirectory
```

Does that do the same for you?

**Comment by phand00** [comment]
Hi,

Yes it's working. So simple solution. I understand that I need to explicitly load built in modules... 
Will continue doing more test tomorrow but sound like it's all fine. 

Thanks for your help.

**Comment by phand00** [comment]
It works Thank again
