### ISSUE TITLE
Maintaining endpoints and routes using external source

### ISSUE THREAD

**Issue by ArieHein** [Badgerati/Pode#514]
I have 2 endpoints with about 30 overall routes. This means my server.ps1 is quite long and bit hard to maintain.

I am trying to create a method of managing by using 2 json files, one for endpoints and one for routes that will be read inside server.ps1 and created.

Do you reckon this sort of abstractions can be something that can be baked in 
with a proper schema ? Something like :

`start-podserver  -endpoints <path to endpoints.json> -routes <path to routes.json> ...`

and treat those the same as -file option ?

I have a short demo code for endpoints as its schema is simple, my problem at the moment is making one for routes as you want to record in that routes.json also an abstraction layer how to deal with same route for multiple endpoints, and how to parameterize the function name, the passed variables for each route , the success / errors messages and the different types of content html/json and file/inline code.

Ideas on how to maintain a complex endpoints / routes structures would be helpful ;)

**Comment by Badgerati** [comment]
Hey @ArieHein,

When I've normally had to deal with a lot of routes, I tend to split them up into different `.ps1` files; importing them back into the `server.ps1` by dot-sourcing or via `Use-PodeScript`. That could help split them up into categories of what the routes do, leaving your server script to just create the endpoints and them import the route scripts.

```
- server.ps1
- /routes
    - users.ps1
    - servers.ps1
    - etc
```

As for a schema of some type, that is a tricky one. I'd suggest using `.psd1` instead, but may need to see an example of the json 🤔 . For supporting it in Pode, I might have to say it could be better as something built on top of Pode - unless we can design a concrete way of doing it, in which case it could be done as something like `Import-PodeRoute`

Hope that helps!

**Comment by ArieHein** [comment]
I think splitting it into multiple .ps1 files and dot sourcing might be the only way with routes.
but a json files following a schema might be the more elegant way, though not an easy one.

For the endpoints I did something like this:

```
{
    "endpoints" : [
        {
            "name" : "user",
            "port" : "8080",
            "protocol" : "http"
        },
        {
            "name" : "admin",
            "port" : "9090",
            "protocol" : "http"
        }
    ]
}
```

and then in server.ps1 just add these lines:

```
# get the list of endpoints to create
$endpoints = Get-Content -Path ./pode/endpoints/endpoints.json -Raw | ConvertFrom-Json

# add the endpoints
for ($i=0; $i -lt $endpoints.endpoints.length; $i++) {
   Add-PodeEndpoint -Address localhost -Port $endpoints.endpoints[$i].port -Protocol 
   $endpoints.endpoints[$i].protocol -Name $endpoints.endpoints[$i].name
}
```

**Comment by Badgerati** [comment]
> Then thinking about potential files , static files, html response, json response, and over all complexity of the content of a script block made it go exponential complex.

Throw Authentication and Middleware in there and it'll be mental! 😂 

Using split files tends to be the normal way - even for tools like Express.js and WebAPI.

That being said, I can see where you're going with it. It could be interesting to have a "routes.json" file that you can update, and a server restart just picks up the new routes 🤔 you could even store it in MongoDB or something!

If this were to happen - taking routes as an example - I see it being something like `ConvertTo-PodeRoute` for modules/functions:

```powershell
Import-PodeRoute -FilePath './routes.json' [-Middleware] [-Path]
```

(Whatever `-Middleware` is supplied is set against all routes)

As for the file, possibly something like:

```json
[
    {
        "method"       : "get",
        "path"         : "/health",
        "endpoints"    : [ "user", "admin" ],
        "response" : {
            "inline": "@{ 'health' = 'OK' }"
        }
    },
    {
        "method"       : "get",
        "path"         : "/project",
        "endpoints"    : [ "user", "admin" ],
        "response" : {
            "function": {
                "name": "Get-Project",
                "parameters": {
                    "Param1": "Value1",
                    "Param2": "Value2"
                }
            }
        }
    }
]
```

Though it is made harder if you want to retrieve values from a the payload or query string 🤔

**Comment by ArieHein** [comment]
Went with splitting it to a few ps1 and dot sourcing it.

Just have to find a nice clean way to pass parameters to those dot-sourced files as i want to pass the endpoint names there were created earlier inside server.ps1.

Appreciate the discussion about this !
