### ISSUE TITLE
IIS Windows Authentication Error HTTP Error 502.5 Issue

### ISSUE THREAD

**Issue by RobinBeismann** [Badgerati/Pode#515]
I finally came to look into this awesome project, I've been using NodePS for different projects before and will definately convert them to Pode! 
However I'm having an Issue as soon as I enabled the IIS Authentication in Pode. I've configured Windows authentication on the IIS Site and according to the logs I'm successfully authenticated, however as soon as I comment the following part in, I'm instantly getting the following error:

> HTTP Error 502.5 - ANCM Out-Of-Process Startup Failure

Code:

> Add-PodeAuthIIS -Name 'IISAuth'
> 
>     Add-PodeRoute -Method Get -Path '/' -Middleware (Get-PodeAuthMiddleware -Name 'IISAuth') -ScriptBlock {
>         param($e)
>         Write-PodeJsonResponse -Value @{ User = $e.Auth.User }
>     }

Checking the event log I can see that IIS fails to start pode:
> Application '/LM/W3SVC/2/ROOT' with physical root 'C:\www-data\approval-t.ad.nightwire.de\' failed to start process with commandline 'pwsh.exe .\server.ps1' with multiple retries. Failed to bind to port '28845'. First 30KB characters of captured stdout and stderr logs from multiple retries:

The log of the webapp itself however is empty.

Am I missing something? I've installed the latest Powershell 7.0 and .NET Core:

> PS C:\Windows\system32> dotnet --list-runtimes
> Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
> Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

I just also tried it with .NET Core 3.1.2 - same error.

Thanks already!

**Comment by RobinBeismann** [comment]
Just as update: I just tried it on a fresh installed Server 2019 using the Guide and packages installed by Choco, however I'm still having the same issue, as soon as I add a Route with the IIS Auth Middleware it goes into a HTTP/502.5 like described above.

**Comment by Badgerati** [comment]
Hi @RobinBeismann,

I'll have a play with this one later, but just so I know, this only happens when you have a Route with IIS Auth? If you have a normal Route with no auth everything is fine?

With IIS failing to start Pode, the first things that jump to mind are the web.config file, and is Pode installed under PSCore for AllUsers? I also sometimes got this error and an iisreset resolved it.

In case Pode is getting a fair bit in and then failing, try adding the following as the first line:
```powershell
Start-PodeServer {
    New-PodeLoggingMethod -File | Enable-PodeErrorLogging
```
and that should hopefully populate some errors in a `./logs` directory. The web.config should also be writing some IIS errors there as well.

**Comment by RobinBeismann** [comment]
Hi @Badgerati ,

thanks for the response!
I've just tried to enable logging, however that results in the same behavior, it generates a log file under logs which is completely empty.
Pode runs fine in IIS as long as I don't add the following as route example:
`    Add-PodeRoute -Method Get -Path '/test' -Middleware (Get-PodeAuthMiddleware -Name 'IISAuth') -ScriptBlock {
        param($e)
        Write-PodeJsonResponse -Value @{ User = $e.Auth.User }
    }`

If I remove it, Pode instantly starts to work again after an iisreset, I can even leave "Add-PodeAuthIIS -Name 'IISAuth'" in without the crash, but as soon as I add the Route it crashes.
IIS unfortunately doesn't log anything either, it only logs that the pwsh instance crashed after App Pool start.

**Comment by Badgerati** [comment]
Hi @RobinBeismann,

Think I got it! Small error in the docs - it's missing sessions.

If you don't want sessions then updating the `-Middleware` to the following should do the trick:
```powershell
Get-PodeAuthMiddleware -Name 'IISAuth' -Sessionless
```

If you want sessions, adding the following line should work:
```powershell
Enable-PodeSessionMiddleware -Secret 'schwifty' -Duration 120 -Extend
```

**Comment by RobinBeismann** [comment]
That fixes it, thanks!
I've created #517 to address this is in the docs.
