### ISSUE TITLE
Add Get-PodeEndpoint functionality

### ISSUE THREAD

**Issue by ArieHein** [Badgerati/Pode#518]
Similar to how you can use Get-PodeRoute to list the routes available and filter then by a few parameters, is it possible to have a Get-PodeEndpoint that will list all the available endpoints, filtered by different parameters.

I am mostly aiming at validation and perhaps unit testing, without having to invoke a specific route as the endpoint might be up but the route/s might not work.

**Comment by Badgerati** [comment]
Hey @ArieHein,

This should be possible! Thinking:

```powershell
Get-PodeEndpoint [-Address] [-Port] [-Protocol] [-EndpointName]
```

**Comment by ArieHein** [comment]
Yes, without necessary any of them being mandatory

**Comment by Badgerati** [comment]
Added the new `Get-PodeEndpoint` as:

```powershell
Get-PodeEndpoint [-Address] [-Port] [-Protocol] [-Name]
```

All parameters are optional, returning all endpoints if nothing is supplied. I kept it as this syntax, just so it's similar to `Get-PodeRoute`.
