### ISSUE TITLE
Add Conditions / Events

### ISSUE THREAD

**Issue by ArieHein** [Badgerati/Pode#519]
How would I implement a route that changes the return value (lets assume json), based on the amount of consecutive requests made to the route ?
so first request will return message A.
If another request arrives within x sec, it will return message B
and if another request arrives within y sec, it will return message C
If the gap between requests gets closer, it will continue returning message C
but if the it gets longer, it gradually falls back to message B and if longer to message A.

I was reading about Add-PodeLimitRule and was thinking it would be nice if we can intervene and change the reply if its higher then 5 times every 10 sec, but make it dynamic in behavior, so once its back to "normal" change the message or if it goes extreme change to a different message.

**Comment by Badgerati** [comment]
This could be an interesting one 🤔 

Just to make sure, in this scenario would message `A` just be the normal Route response, but messages `B` and `C` would both be the 429 responses but with different content? Such as:

* `A` - 200 - Route
* `B` - 429 - "we've hit the limit" (like 5req/s or something)
* `C` - 429 - "okay guys, you're killing us!" like 1000req/s)

**Comment by ArieHein** [comment]
Don't think you need to change the http status, its just a event-based routing system that can change the response.

**Comment by Badgerati** [comment]
Ah right, just you mentioned `Add-PodeLimitRule` which set the status to 429, that's where my thinking came from.

For this I wonder if you could use the `Timestamp` of requests, and keep track of ms since the last request 🤔 something like below perhaps (quickly thrown together):

```powershell
Add-PodeRoute -Method Get -Path '/message' -ScriptBlock {
    param($e)

    $ms = ($e.Timestamp - (Get-PodeState -Name 'LastTimestamp')).TotalMilliseconds
    Set-PodeState -Name 'LastTimestamp' -Value $e.Timestamp

    if ($ms -gt 10000) {
        # Message C
    }
    else if ($ms -gt 3000) {
        # Message B
    }
    else {
        # Message A
    }
}
```

**Comment by ArieHein** [comment]
That's an interesting implementation.
I haven't tested it yet but logically this should work.

I will probably make the name of the state dependent on the path so I can record different timestamps for different path requests.
