### ISSUE TITLE
Pode and letsencrypt

### ISSUE THREAD

**Issue by soulruins** [Badgerati/Pode#520]
### How to bind a letsencrypt certificate in Pode?
I got a certificate using [Posh-ACME](https://github.com/rmbolger/Posh-ACME), but I can't associate it with Pode. If possible, give an example.

**OS:** Windows 10
**Posh-ACME:** v3.12.0
**Pode:** 1.6.1

**Comment by Badgerati** [comment]
Hi @soulruins,

Would you be able to give some examples of what you've tried? The `Add-PodeEndpoint` and the `New-PACertificate` calls mostly.

From looking at their docs, `New-PACertificate` seems to create a `cert.pfx` and ` fullchain.pfx` - both with a default password of `poshacme` (unless you specified `-PfxPass`).

You should be able to use either of those files:
```powershell
Add-PodeEndpoint -Address test.example.com -Port 443 -Protocol Https -CertificateFile ./fullchain.pfx -CertificatePassword poshacme
```

**Comment by soulruins** [comment]
> Hi @soulruins,
> 
> Would you be able to give some examples of what you've tried? The `Add-PodeEndpoint` and the `New-PACertificate` calls mostly.
> 
> From looking at their docs, `New-PACertificate` seems to create a `cert.pfx` and ` fullchain.pfx` - both with a default password of `poshacme` (unless you specified `-PfxPass`).
> 
> You should be able to use either of those files:
> 
> ```powershell
> Add-PodeEndpoint -Address test.example.com -Port 443 -Protocol Https -CertificateFile ./fullchain.pfx -CertificatePassword poshacme
> ```

Oh!!! Many, many thanks! It's working. I didn't study the documentation well enough. Thanks!
