### ISSUE TITLE
Unable to use shared state in Pode Schedule

### ISSUE THREAD

**Issue by haidouks** [Badgerati/Pode#526]
Hi,
Although "Shared State" runs as expected in "Add-PodeTimer", it looks like code does not enter the "Lock-PodeObject" script block in "Add-PodeSchedule". Am I doing something wrong or is this a bug?
### Steps To Reproduce

1. Copy the [Full Example](https://badgerati.github.io/Pode/Tutorials/SharedState/#full-example)
2. Change Timer to Schedule
3. Finally code should be as below. Run it

`

  
    Start-PodeServer {
    
    Add-PodeEndpoint -Address * -Port 8080 -Protocol Http
    
    # create the shared variable
    Set-PodeState -Name 'hash' -Value @{ 'values' = @(); } | Out-Null

    # attempt to re-initialise the state (will do nothing if the file doesn't exist)
    Restore-PodeState -Path './state.json'

    # timer to add a random number to the shared state
    #
    # changed this line to schedule from timer
    Add-PodeSchedule -Name 'forever' -Cron '@minutely' -ScriptBlock {
        param($e)

        # ensure we're thread safe
        Lock-PodeObject -Object $e.Lockable {

            # attempt to get the hashtable from the state
            $hash = (Get-PodeState -Name 'hash')

            # add a random number
            $hash.values += (Get-Random -Minimum 0 -Maximum 10)

            # save the state to file
            Save-PodeState -Path './state.json'
        }
    }

    # route to return the value of the hashtable from shared state
    Add-PodeRoute -Method Get -Path '/' -ScriptBlock {
        param($e)

        # again, ensure we're thread safe
        Lock-PodeObject -Object $e.Lockable {

            # get the hashtable from the state and return it
            $hash = (Get-PodeState -Name 'hash')
            Write-PodeJsonResponse -Value $hash
        }
    }

    # route to remove the hashtable from shared state
    Add-PodeRoute -Method Delete -Path '/' -ScriptBlock {
        param($e)

        # ensure we're thread safe
        Lock-PodeObject -Object $e.Lockable {

            # remove the hashtable from the state
            Remove-PodeState -Name 'hash' | Out-Null
        }
    }
    }

`
 
4. Wait more than 1 min and browse route
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/23384662/78473599-8fad3580-774a-11ea-8117-12b966acf4ee.png">
 
5. There's no numbers in list.

### Expected Behavior
It should return random numbers.
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/23384662/78473681-3db8df80-774b-11ea-97c8-855254645f7f.png">

### Platform
 - OS: MacOS
 - Powershell 7.0

**Comment by Badgerati** [comment]
Hi @haidouks,

This is actually an oddity with schedules, unlike timers, middleware, routes, etc, the parameter names have to be supplied literally ([here](https://badgerati.github.io/Pode/Tutorials/Schedules/#arguments))

Because schedules are run in a new runspace, and not like timers/etc where the ScriptBlock is simply invoked, the runspace forces the parameter names to unfortunately be literally named.

The first parameter to a schedule is the still the event, but it has to be named as `$Event`:

```powershell
Add-PodeSchedule -Name 'forever' -Cron '@minutely' -ScriptBlock {
    param($Event)

    # ensure we're thread safe
    Lock-PodeObject -Object $Event.Lockable {

        # attempt to get the hashtable from the state
        $hash = (Get-PodeState -Name 'hash')

        # add a random number
        $hash.values += (Get-Random -Minimum 0 -Maximum 10)

        # save the state to file
        Save-PodeState -Path './state.json'
    }
}
```

Hope that helps!

**Comment by haidouks** [comment]
Hi @Badgerati,

Sorry, I missed that part. Using $Event parameter fixed the problem and I'm closing the issue. 

Thank you.
