### ISSUE TITLE
Create a Route to return all the available Routes using Get-PodeRoute

### ISSUE THREAD

**Issue by ArieHein** [Badgerati/Pode#532]
Main question is when is Get-PodeRoute available to be used and what dictates the order in which the results return.
It may sounds weird but I am trying to have a route that will allow me to get a list of all active routes  and later all endpoints, now that Get-PodeEndpoint was added(Ver 1.7.0)

I created 2 Endpoints: 
```
  Add-PodeEndpoint -Address * -Name 'user' -Port 8080 -Protocol 'http'
  Add-PodeEndpoint -Address * -Name 'admin' -Port 9090 -Protocol 'http' 
```
I then created the following Routes:

```
# Create route for health
Add-PodeRoute -Method GET -Path '/health' -EndpointName 'user', 'admin' -ContentType 'application/json' -ScriptBlock {
  Write-PodeJsonResponse -Value @{ 'health' = 'I am Healthy!'; }
}
# Create route for uptime
Add-PodeRoute -Method GET -Path '/uptime' -EndpointName 'user', 'admin' -ContentType 'application/json' -ScriptBlock {
  $Current = Get-PodeServerUptime
  $Total = Get-PodeServerUptime -Total
  Write-PodeJsonResponse -Value @{ 'Time' = $Current ; 'Total' = $Total}
}
# Create route for status
Add-PodeRoute -Method GET -Path '/status' -EndpointName 'user', 'admin' -ContentType 'applicaiton/json' -ScriptBlock {
  $UserRoutes = Get-PodeRoute -EndpointName 'user'
  $AdminRoutes = Get-PodeRoute -EndpointName 'admin'

  "User Routes" | Out-PodeHost
  $UserRoutes | Out-PodeHost
  
  "Admin Routes" | Out-PodeHost
   $AdminRoutes | Out-PodeHost

  Write-PodeJsonResponse -Value @{ 'status' = 'Will list endpoints and routes report' }
```
Tried both directly in server.ps1 but also with Use-PodeScript dot sourcing.

Originally I used the 'Use-PodeScript' to dot source 5 additional ps1 files with more routes in them.
For the 'user' endpoint I get empty results.
For the 'admin' endpoint I get a json back.

Now perhaps all the routes are available via Get-PodeRoute AFTER server.ps1 is fully executed, but then I still get values for the 'admin' endpoint.

Perhaps Out-PodeHost is doing something weird to the returned value from the function.

Perhaps I need to place the'/status' route at the very end of server.ps1 or on the last ps1 file i dot source. This is a bit counter intuitive as I think I noticed that routes were already active even before the last route was dot sourced, during debugging.

Just not fully understand how 'user' is blank, and 'admin' isn't, and the results for 'admin' are a random route that originated from one of the files dot sourced.
At least every time I tested it, the results for 'admin' were the same so some consistency.

**Comment by Badgerati** [comment]
Hi @ArieHein,

Since you're calling `Get-PodeRoute` within a route, it will only be run after the server.ps1 has fully run anyway.

Looking at the above, I can't see why 'user' would be empty; but I'll have a look later and see if I can reproduce it.

**Comment by Badgerati** [comment]
Managed to reproduce it, I think I know what's going on but shall investigate further and fix!

**Comment by Badgerati** [comment]
That should fix the issue, when a route had multiple endpoints it was creating a 2D array rather than a flat 1D one.
