### ISSUE TITLE
Non-Permanent States / Save Exclusions

### ISSUE THREAD

**Issue by RobinBeismann** [Badgerati/Pode#533]
### Question
Would it be possible to have non-permanent states? 
By default all states are non-permanent, however to keep them it makes sense to have a Save/Restore Routine implemented.
It would however be great if we could exclude states from being saved or even define which ones are supposed to be saved to the file. 
Background:
States are a great way for caching across runspaces, however it doesn't make sense to save the cache to the file while there are probably states that you'd want to save. 

Thanks!
Robin

**Comment by Badgerati** [comment]
Hey @RobinBeismann,

I like the idea! So you're after something whereby you can exclude certain keys in the pode state?

Perhaps something like?
```powershell
# some numbers state
Set-PodeState -Name 'Numbers' -Value @(1,2,3,4)

# save, but exclude numbers
Save-PodeState -Path './state.json' -Exclude @('Numbers')
```

Could possibly also add an `-Include` on there as well 🤔

**Comment by RobinBeismann** [comment]
Hey @Badgerati ,

yeah, thats basically what I'm looking for, I think using "-Include" might scale better than excluding, having both wouldn't hurt either. :)

Best regards
Robin

**Comment by ArieHein** [comment]
I think it would be better when you use the Set-PodeState to actually declare a scope.
Something like:

```
# some numbers state
Set-PodeState -Name 'Numbers' -Value @(1,2,3,4) -Scope 'File'
Set-PodeState -Name 'Characters' -Value @(a,b,c) -Scope 'something else'

```

Scope can hold an array of scopes
and 'File' would imply that when Save-PodState is used with -File, the stats that have the 'File' scope are written to the file, and those that dont have it, wont be written.

**Comment by Badgerati** [comment]
I actually considered something like `-Scope` at first, over `-Include`/`-Exclude`, but thought people using state might have lots and lots of `Set-PodeState` and it could be tedious to update them all. Where as they would likely only have a couple of `Save-PodeState`

However, both ideas could be implemented: `-Include`/`-Exclude` and `-Scope`, as they could also work together as well!

I was thinking of making `-Scope` free text as well, so:

```powershell
Set-PodeState -Name 'Numbers1' -Value @(1,2,3,4) -Scope 'Numbers'
Set-PodeState -Name 'Numbers2' -Value @(10,20,30,40) -Scope 'Numbers'

# save just scope:
Save-PodeState -Path './state.json' -Scope 'Numbers'

# save scope, but exclude something:
Save-PodeState -Path './state.json' -Scope 'Numbers' -Exclude @('Numbers1')
```

**Comment by ArieHein** [comment]
Even with people having lots of states already in their scripts, you can have a defualt value.
So any existing Set-PodeState that do not have a -scope and you want to preserve backward compatibility, then it will assume a default value that will catch all possibilities.

`Set-PodeState -Name 'Number' -Value @(1,2,3,4)`

is the same as :

`Set-PodeState -Name 'Number' -Value @(1,2,3,4) -Scope 'All'`

Also in you example it doesnt make sense to include Number1 in the Numbers scope. If you dont want to save it to  the file, give it another scope or no scope.

**Comment by Badgerati** [comment]
If scope is free text, then none would be the default, and all current state calls work as per normal. I was more thinking on the lines of someone who has to go back and alter a lot of them to give them different specific scopes.

The Number1 example is a rare but still a plausible use case, some body might have a reason for ever wanting to do it.

In general, having Include, Exclude, and Scope would offer flexibility to people for whatever scenario they may have; so doesn't hurt to have all 3.
