### ISSUE TITLE
Fix an internal naming issue that is causing errors in the SMTP server

### ISSUE THREAD

**Issue by Badgerati** [Badgerati/Pode#543]
### Describe the Bug
Within the SMTP server logic, there is an old `SmtpEvent` variable, this should be `TcpEvent`. Also, the initialisation of the `Email` object in the event should be to `@{}` not `$null`.

Each of these stop emails, and `Send-MailMessage` from being received and hanging.

### Steps To Reproduce
1. Start the `mail-server.ps1` example
2. Run a `Send-MailMessage` with `-SmtpServer` as localhost
3. The call will hang

### Expected Behavior
The `Send-MailMessage` should complete without error, and details of the email output on the server console.

### Screenshots
See gitter channel for gifs.

### Platform
 - OS: Windows 10
 - Version: PS5.1

**Comment by majkinetor** [comment]
https://gitter.im/Badgerati/Pode?at=5ea37a249a04a259f22f0906

**Comment by Badgerati** [comment]
Hey @majkinetor, the commits in the [Issue-543](https://github.com/Badgerati/Pode/tree/Issue-543) branch now allow `Send-MailMessage` to work for me. When you get a free moment, would you be able to test?

**Comment by majkinetor** [comment]
Seems to work now. Good job.

**Comment by Badgerati** [comment]
I'll get this out in a 1.7.2, as SMTP is basically broken.

**Comment by Badgerati** [comment]
Released in v1.7.2
