### ISSUE TITLE
Not all data from the Email is read

### ISSUE THREAD

**Issue by Badgerati** [Badgerati/Pode#547]
### Describe the Bug
At times, an email can be received in multiple parts; meaning the initial `Read` of the TCP stream only gets the first part, but ignores the rest. So at times the data, or some headers, of the email can be dropped.

### Steps To Reproduce
1. Start the `mail-server` example
2. Use `Send-MailMessage` to send an email (single or multi line body)
3. Sometimes the body isn't received

### Expected Behavior
The whole stream should be read, and all headers/data available for constructing the SMTP event.

### Platform
 - OS: Windows 10
 - Version: PS5.1

**Comment by majkinetor** [comment]
Doesn't seem to block any more.

**Comment by Badgerati** [comment]
Do you need this as a 1.7.3?

**Comment by majkinetor** [comment]
I can wait for release.
