### ISSUE TITLE
Azure AD support

### ISSUE THREAD

**Issue by ArieHein** [Badgerati/Pode#551]
I am looking into including AD authentication into my API via Pode.
I know there is Add-PodeAuthWindowsAd and in the tutorials there is a section about AD but I'm having trouble understanding if this is the same way I would use it with Azure AD ?

Are there more examples or a guide into how to do this one correctly. It sure would help to also address the concerns of some sec departments.

**Comment by RobinBeismann** [comment]
Unfortunately Azure AD is something completely different, Pode would need to support the modern Auth / OAuth2 Standard, also the ADSI Searcher Class won't work for Azure AD.
Azure AD doesn't offer an LDAP Interface so I guess I'd require something completely new.

Are you using IIS below Pode?

**Comment by ArieHein** [comment]
Was thinking of using a web app so it is IIS underneath but its not visible as normal iis server would. PerhPד something with Bearer token or using an external azure function most likely

**Comment by Badgerati** [comment]
It would be interesting to see if we could implement OAuth2, that could make a lot more things possible!

On AAD itself, where I work we created an AADDS on top of AAD so the inbuilt WindowsAD in Pode could work. But it would be cool to have the support to use the AAD directly 🤔

**Comment by RobinBeismann** [comment]
Ah yeah, with AADDS this should work as it offers a native LDAPS Interface and probably ADSI for Member Systems. I've never seen Azure AD Domain Services in production yet through.
