### ISSUE TITLE
how to pass query string in Add-PodeRoute -path 'script'  ... -FilePath './modules/someScript.ps1'

### ISSUE THREAD

**Issue by jhainau** [Badgerati/Pode#559]
How do I pass the query string to the script? for example:
https://podeserver.domain/script?item=value

pode route:
Add-PodeRoute -path '/script'  -FilePath './modules/someScript.ps1'

someScript.ps1:
param($e)
return { Write-PodeJsonResponse -Value $($e.Query)}

---
this will result in an empty JSON object.

**Comment by jhainau** [comment]
most examples make use of the script block, but not of the -filepath option. I was thinking that if I give file system access to the script to a person tasked with maintaining that script, that I wouldn't necessarily need to give them the keys to the kingdom. I would maintain the main server script, but an individual could maintain a specific script.  

of course, there is likely a much better or easier way to accomplish this already... in which case I would  love to learn!

**Comment by RobinBeismann** [comment]
Just keep in mind that whatever he puts into that subscript will be executed as the user which runs Pode.

Back to the main question:
You can access the GET / POST Values via the Parameters which Pode pushes to the route like this:
Add-PodeRoute -Method Get -Path '/' -Middleware $IISAuth -ScriptBlock {

param($Data) 

Write-PodeViewResponse -Path 'index' -Data $Data

}

For your above example $data.item would hold "value"

**Comment by RobinBeismann** [comment]
Sorry, the issue with your above script block is probably that the value you supply is not a hashtable and thus Pode is not able to convert it to JSON.

**Comment by RobinBeismann** [comment]
Now that I'm at my desktop, this is what you want:
Main File:
```
Import-Module -Name "Pode"
Start-PodeServer -Threads (Get-CimInstance -ClassName "Win32_Processor" | Select-Object -ExpandProperty NumberOfLogicalProcessors) -ScriptBlock {
    Add-PodeEndpoint -Address 127.0.0.1 -Protocol Http
    
    Add-PodeRoute -Method Get -Path '/script' -FilePath "./test.ps1"
}
```
Test.ps1:
```
{
    param($Data)
    Write-PodeJsonResponse -Value $Data.Query
}
```

Return:
```
{
"test": "value"
}
```

**Comment by Badgerati** [comment]
What @RobinBeismann said!

In your `someScript.ps1`, the whole content needs to be wrapped as a scriptblock - this is then treated as the script for the route. For yours, only the `Write-PodeJsonResponse -Value $($e.Query)` part is being used, so the `$e` isn't present 😄 

On another note! Seeing this:

```powershell
-Threads (Get-CimInstance -ClassName "Win32_Processor" | Select-Object -ExpandProperty NumberOfLogicalProcessors)
```

has given me an idea of adding a `-MaxThreads` switch! Could potentially use something like `grep -c '^processor' /proc/cpuinfo` on *nix to get the cpus 🤔

**Comment by jhainau** [comment]
thanks! had to remove  "return" and moved the bracket so that it included the entire script per your suggestion. this is going to work out quite nicely :-D
somescript.ps1:
{
param($e)
Write-PodeJsonResponse -Value $($e.Query)
}
