### ISSUE TITLE
Alternative storage of Request Queues

### ISSUE THREAD

**Issue by ArieHein** [Badgerati/Pode#574]
Was there ever a thought about adding an option of recording request queues in a DB ?

I am trying to incorporate an approval system.
So i have 2 endpoints, one for User and one for Admin.
I have created a route in both endpoints for an action.
This action when it comes from the User endpoint, will create a request for approval
that will call a third endpoint notifying admins of the request.
They will then use the admin endpoint and same route to get the original request for approval, verify the details and approve the execution of the request.

Now i can store the request in a json/yaml file with a unique identifier or alternatively in a DB like redis for simple key-value pairs as I don't have access to the original runspace where the request was done .

I was thinking if there is a native support for an external DB to record the requests and its parameters and making the schema public or extensible to allow this kind of scenario.

**Comment by jhainau** [comment]
@ArieHein  I use odbc calls to sybase from powershell.  But if you have the drivers,  you can connect to any db.

**Comment by ArieHein** [comment]
Yes i am using the redis driver as i find it more suitable for the type of data i want to store, but having discussion with @Badgerati on another discussion he mentioned that the requests that arrived are queued in a runspace and then picked so there is a queue of sorts, and my idea here was to also allow it to be saved to a db of our liking to a base schema that will allow repeated access to the data even after the request has been picked from the queue

**Comment by Badgerati** [comment]
Ah right, this could be terribly wording on my part; the queues I speak of are Lists that (using HttpListener for example) contain the Context objects for the Request and Response. In Pode each runspace can get the next Context available, process the Request and then set the Response.

In the case of HttpListener, it deals with sending back the Response, and only it can add new Contexts to its internal "queue". So if we stuck to HttpListener, then this pretty much becomes impossible. (using Kestrel, or other third parties would also exhibit the same issues) - unless you completely rebuild the Request and Pode fires of an `Invoke-RestMethod`.

Now, if we moved completely to a Pode controlled listener then we have control over this "queue", so we could add extra Contexts to it. The only issue is that there would be no Response object - so this would need to be managed.

It is theoretically possible, and it's also eerily similar to a module concept I've been thinking about!! If Pode does get support for this it would probably have to follow:

1. It could only happen if we have a listener completely controlled by Pode
2. I wouldn't put storage into Pode, but instead some `Export-PodeRequest` and `Import-PodeRequest`. These would let people store the Request where they want, and then import would add the Request to the queue. (This would run a Request through normal routing, so need to think about authentication and passwords)
3. If we *do* put storage into it, then it'll either be to flat json files, or to some internal state.

**Comment by Badgerati** [comment]
Oh also, on storing the entire queue elsewhere, I don't think it would be feasible. Once the sockets open, the streams for Request/Response are created at that point, and those are something I don't believe you'd be able to store externally.

**Comment by ArieHein** [comment]
Other then the timestamp from the webevent, is there anything in the details of the request that are unique ? If you have one endpoint with 2 routes and with murphy blessing both arrive same second, what would be a way to record the requests in an external db ?

**Comment by ArieHein** [comment]
This context you mentioned, how do you know which to take next for example ?

**Comment by Badgerati** [comment]
Hey @ArieHein,

If it were two different routes, then the Path on the event would be enough to distinguish them.

If it's 2 requests for the same endpoint/route at the same second, then nothing would uniquely identify them - unless something in the query string/payload were different. You could assign each event an ID, like a GUID or similar - then use that as your unique identifier.

In some global middleware: `$e.ID = New-Guid`

It is something I can just add into Pode as well, could help with debugging purposes 🤔 

In terms of the internal context queue, it's purely FIFO. Pode doesn't care what the endpoint/route the next request is for, it just processes them as they come in. Internally there's no need to unique identify each of the requests.

**Comment by ArieHein** [comment]
How did you solve it then to know what request to take in what runspace ?

**Comment by ArieHein** [comment]
As part of the original request, when a request arrives from a "user" endpoint, i need to give it a unique id and record the details of the request (either in a local file or a local db) and then the admins could see the list of the all existing waiting requests and through the ID can then fetch the request data and call the real action that is called when the request comes from the "admin" endpoint. A Queue for activities thus the ID has to be unique even for cases when a request for the same route happened at the same time else i might approve the wrong request for exmaple)
I am looking for that uniqness

**Comment by Badgerati** [comment]
> How did you solve it then to know what request to take in what runspace

Even then it's first-come-first-serve. The socket listener simply adds all inbound requests to a single "static" queue, and the runspaces just grab the next object from the queue - which ever runspace gets there first gets the request.

The only uniqueness at this point is the .NET ClassID for each Context class being added to some BlockingCollection data structure; for requests that come in at the same time, they would be on different sockets.

For Pode, even if you have 3 runspaces and each of them started handling a different request each, at the same time - same route, same endpoint, same everything. The information in the context might "be the same", but each of them are being handled in their own scope, in a different runspace. The only level of uniqueness Pode really cares about is the URI Path and Host values, to figure out the Route and Endpoint, but that's about as unique as Pode needs.

If Pode started storing these contexts in, say, MongoDB. The contexts would be stored as in array, with no unique identifier - with Pode just getting `array[0]` each time.

---

Back on getting a unique ID, there is the option to add in middleware to assign a GUID to each web event - this is likely the easiest.

Another way could be to generate a hash of the following combined values on the event:

* Path
* Endpoint
* Timestamp
* Auth.User.Name ?
* Request.UserAgent
* Request.RemoteEndPoint

Those last two should help with different browsers and different machines.
The auth could be useful if end users are having to authenticate first.

And another way, if you control the source of the incoming requests, you could add some `X_MY_UNIQUE_ID` header to the requests, and use that to identify them. (could be a guid or equivalent)

**Comment by ArieHein** [comment]
Thanks for the added discussion.

I thought about creating a hash but still was bothered with uniqueness as there will be a system that will call my apis frequently but i don't control how frequent and if I want to create a workflow as mentioned above i do require a unique key in a queue so I can reference it when handling the original request. Not sure the Auth.User.Name or Request. UserAgent would help there. 
So i thought about just a simple json file / table in a db that saves the webevent data and also handles the unique id.

The question then is If I create a route and a function that processes the request, the runspace is alive as long as the it takes the function to handle the request. So i can have in my function a call to some functionality that keeps a "latest id" in a file or a db and just increments it, records the WebEvent Data and later reads it in another route. The only problem here is that I cant treat it as a transaction because if anything later in the function breaks (say i wrote a bad code or other) I would have to create code to remove the data that was entered in the json/db and decrement the id so next request could get it but here it gets complicated as in the mean time another request from the same endpoint/route can arrive and handled by the same function (In a different runspace) that now needs to read the latest ID to increment it..
Obviously value of the unique id should be saved in a "global" variable available to all the runspaces, but as there is no 'failure event' to register to, managing the decrement becomes very complex.

Originally I though some unique id could be given by pode, which would make it easier to create such functionality but as you mentioned there's no uniquness and the .net  ClassID that I don't know how unique it is between calls from same endpoint/route and if there is real usage to record it in pode request object.

**Comment by ArieHein** [comment]
I do admit that I have only thought about managing the uniqueness in the function but didn't think of adding my own header in the request which sounds actually like an interesting way to achieve this but as I don't control the requests coming from my users how can I actually use this ?

So a request comes through pode to my route and function, and then my function will create a new request to another route but inject this header with a unique id and that will save it to a file/db ?
I would still have to deal with the "non transactional" aspect of it ?

**Comment by RobinBeismann** [comment]
Is there a reason you are that scared about the Deincrementing of the ID? Does it really hurt if there's a "dead" ID in the table?
I'm not sure if Pode supports it, but you could add the thread id to the hash, making the request definitely unique for this Pode instance, could however be a potential issue with a load balancer in front of multiple Pode instances.
You could also include the client ip of the caller plus the thread ID, this should make it quite unique.

I'd avoid any file based table in your case for performance reasons.
I tried writing it to Pode states and synchronize save the states to the file, but that's just too slow as it adds to many IO Operations on a request.

**Comment by Badgerati** [comment]
If the initial request is something you don't control, adding the ID Header will be a little tricky. One thought I just had is to enable sessions (if not already enabled), and use `Get-PodeSessionId`. That SessionId will be unique for each request.

If you're using an incrementing key then I'd agree with @RobinBeismann, is there something that would break if you didn't decrement the key? So long as the row/entry is removed from the file, I can't see any harm in constantly incrementing 🤔 

> I'm not sure if Pode supports it, but you could add the thread id to the hash

Yep, there is! You can use `$ThreadId` in Routes/Middleware an it'll tell you the ID of the current thread/runspace 😄
