### ISSUE TITLE
Rogue "=" causes OpenApi rendering to fail

### ISSUE THREAD

**Issue by jackvaughanjr** [Badgerati/Pode#578]
https://github.com/Badgerati/Pode/blob/7134d806e7fa746517719413fa39abeddaf68689/src/Public/OpenApi.ps1#L578

When trying to use
`Add-PodeOAComponentRequestBody` and then `New-PodeOARequestBody`, `Start-PodeServer` fails with the following error caused by the "=":

`= : The term '=' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the
name, or if a path was included, verify that the path is correct and try again.
At C:\Program Files\WindowsPowerShell\Modules\Pode\1.8.0\Public\OpenApi.ps1:578 char:20`
`+             return = @{`
`+                    ~`
`    + CategoryInfo          : ObjectNotFound: (=:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException
`

**Comment by jackvaughanjr** [comment]
Additionally, after adding in reusable responses/parameters, reloading the server using Ctrl-R no longer works. When I start the server at the command line using 'Start-PodeServer' it works as expected.

**Comment by Badgerati** [comment]
That is a very rogue `=`! Seems there's another one as well in `ConvertTo-PodeOAParameter`.

I can also reproduce restarting the server crashing as well, so I shall look into this.

**Comment by Badgerati** [comment]
That commit should resolve the issue, are you able to verify on your end?

**Comment by jackvaughanjr** [comment]
It does resolve the restarting issue. Thanks!
I am not able to use a reusable Parameter though.

*Build Parameter*
`New-PodeOAIntProperty -Name 'nodeId' -Required | ConvertTo-PodeOAParameter -In Path | Add-PodeOAComponentParameter -Name 'NodeId'`

*Use Parameter*
`Add-PodeRoute ... {
    } -PassThru | `
`        Set-PodeOARequest -Parameters @(ConvertTo-PodeOAParameter -Reference 'UserId') -PassThru | `
`        Set-PodeOARouteInfo -Tags 'SolarWinds'`

*Error Received*
`The OpenApi component request parameter doesn't exist: userId`
`At C:\Program Files\WindowsPowerShell\Modules\pode\1.8.0\Private\Server.ps1:101 char:9`
`+         throw $_.Exception`
`+         ~~~~~~~~~~~~~~~~~~`
`    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException`
`    + FullyQualifiedErrorId : RuntimeException`

**Comment by Badgerati** [comment]
@jackvaughanjr That one should fix the parameters for you! I've tested and it worked on my end - it was referencing the responses components rather than the ones for parameters 👀

**Comment by jackvaughanjr** [comment]
Excellent! Thanks for the rapid response! <3

**Comment by Badgerati** [comment]
😄 if it's all working for you, I can get this out as a v1.8.1

**Comment by KuenzelIT** [comment]
I also just encountered this rogue "=" :smile: 

Is a v1.8.1 going to be released soon?

Thank you for this awesome framework! :+1:

**Comment by Badgerati** [comment]
Released in v1.8.1
