### ISSUE TITLE
Get back IP address of Client

### ISSUE THREAD

**Issue by ClissonFlorian** [Badgerati/Pode#593]
### Question

From Pode Server, there is any way to get back the IPaddress of the client which request API ?

**Comment by Badgerati** [comment]
Hey @ClissonFlorian,

There is a way to get it, using the event object Pode supplies you can get the IPAddress from the Request property:

```powershell
$e.Request.RemoteEndPoint.Address.IPAddressToString
```

Ie, in a Route:

```powershell
Add-PodeRoute -Method Get -Path '/ip' -ScriptBlock {
    param($e)

    # this will be the ip of the client
    $e.Request.RemoteEndPoint.Address.IPAddressToString
}
```

You can do the same in middleware as well 😃

**Comment by ClissonFlorian** [comment]
It's perfect :), thank you very much.

**Comment by Badgerati** [comment]
You're very welcome! 😄

**Comment by TechnicallyJoe** [comment]
Hi @Badgerati 

Sorry for reopening this. Inspired by the above, I'm trying this and getting InputObject is null

```
    Add-PodeRoute -Method Get -Path '/ip' -ScriptBlock {
        param($e)

        # this will be the ip of the client
        $e.Request.RemoteEndPoint.Address.IPAddressToString
    }
```

The above shows nothing. 
$e | get-member doesnt show anything

and 

```
    Add-PodeRoute -Method Get -Path '/ip' -ScriptBlock {
        param($e)

        if ($null -eq $e)
        {
            Write-Host "NULL"
        }
        else
        {
            Write-Host "Not NULL"
        }
    }
```

Also outputs null. Any helps appreciated :)

**Comment by Badgerati** [comment]
Hey @TechnicallyJoe,

Aaah, are you using Pode 2.0? There were changes in there that removed the `$e`.

If you are, then this should do it:
```powershell
Add-PodeRoute -Method Get -Path '/ip' -ScriptBlock {
    # this will be the ip of the client
    $WebEvent.Request.RemoteEndPoint.Address.IPAddressToString
}
```

If you don't mean to use Pode 2.0, you can force the module version to 1.X via `Import-Module Pode -MaximumVersion 1.99.99 -Force` in your main server script :)

**Comment by TechnicallyJoe** [comment]
Thanks @Badgerati 

$WebEvent solved my issue. Thanks for the great work with Pode! 👍
