### ISSUE TITLE
Add-poderoute - error with the regex deleting my path.

### ISSUE THREAD

**Issue by ThomasPerezBlanco** [Badgerati/Pode#597]
Hello,
I am trying to create a route containing a directory path variable.

Except when the server starts, a regex removes backslash and antislash.
I can't manage my folder path, can you tell me how I could do it?

![image](https://user-images.githubusercontent.com/44971529/89426371-645b4700-d73a-11ea-904e-30bfb9ff8170.png)

![image](https://user-images.githubusercontent.com/44971529/89426403-6de4af00-d73a-11ea-9e23-404b40663694.png)

![image](https://user-images.githubusercontent.com/44971529/89426513-89e85080-d73a-11ea-91b3-c35b40158094.png)

Thank you.

cordially

Thomas.

**Comment by Badgerati** [comment]
Hi @ThomasPerezBlanco,

When it comes to using directory paths in URL's, I'd advise caution. Although Windows does normally use `\`, you can also use `/` - especially on *nix - and that would cause havoc with URL paths and routing.

In this case, I would advise using a query string parameter for the path:

```powershell
Add-PodeRoute -Method Get -Path '/api/newFolder' -ScriptBlock {
    param($e)
    $filePath = $e.Query['filePath']
}
```

and call it via: `http://localhost:8080/api/newFolder?filePath=c:\temp`.

If you need to use the route parameter, then what you could do - albeit a little dirty - is replace the slashes on the client end with another character; say a `|`. Then on the server, re-replace the `|` characters with slashes again.

Hope that helps,
Matt

**Comment by ThomasPerezBlanco** [comment]
hello matt,
Thank you for your feedback, it's working great now.
Thank you so much.
Thomas.
