### ISSUE TITLE
Add OpenAPI "enum" for Parameters

### ISSUE THREAD

**Issue by jackvaughanjr** [Badgerati/Pode#603]
### Describe the Change
Allow an -Enum option on New-PodeOA###Property commands to allow for a definite set of allowed values.

### Additional Context
This functionality is described in the OpenAPI specs as follows:
"The enum keyword allows you to restrict a parameter value to a fixed set of values. The enum values must be of the same type as the parameter type."
https://swagger.io/docs/specification/2-0/describing-parameters/

**Comment by Badgerati** [comment]
😨 can't believe I missed enums! This looks to be relatively simple enough to add in though.
