### ISSUE TITLE
Quick start template or/and Cmdlets for PowerShell users

### ISSUE THREAD

**Issue by ili101** [Badgerati/Pode#614]
I assume a popular use case for this module is PowerShell users that want to make some of their functions accessible from a web interface in some sort.
It will be awesome if there was an easy and fast way to do this that is friendly to PowerShell users that are not very familiar with web development.
For example adding a guide and/or template and/or cmdlets that can get you started and pointed in the right direction.

This can be done for example with the PowerShell module UniversalDashboard with 30 lines of PS code but I prefer if possible to do the same thing in Pode as it's an open source project.

Here is a UD example of something that include:
* Some default general styling for all the elements (CSS?).
* Login page.
* Side menu to navigate between pages.  
* A few input fields that are passed to some command (Get-Process).
* Grid view to show the output.
* Output Excel/CSV download button.
```powershell
Install-Module UniversalDashboard
Get-UDDashboard | Stop-UDDashboard

$AuthenticationMethod = New-UDAuthenticationMethod -Endpoint {
    param([PSCredential]$Credentials)

    New-UDAuthenticationResult -Success -UserName "Adam"
    New-UDAuthenticationResult -ErrorMessage "You aren't Adam!!!"
}
$LoginPage = New-UDLoginPage -AuthenticationMethod $AuthenticationMethod -WelcomeText 'LOL'

$Page1 = New-UDPage -Name 'Process' -Icon home -Content {
    New-UDHeading -Text 'Get-Process' -Size 4
    New-UDInput -Title "User Data" -Endpoint {
        param($Name, [Bool]$Something)
        $Process = Get-Process -Name $Name
        New-UDInputAction -Toast "Found $($Process.Count) Processes"
        Set-UDElement -Id "results" -Content {
            New-UdGrid -Title "Processes" -Endpoint {
                $Process | Select-Object Name, ID, WorkingSet, CPU | Out-UDGridData
            }
        }
    }
    New-UDElement -Tag "div" -Id "results"
}
$Page2 = New-UDPage -Name 'Services' -Icon link -Content {}

$Dashboard = New-UDDashboard -Title Test -Pages ($Page1, $Page2) -LoginPage $LoginPage
Start-UDDashboard -Dashboard $Dashboard -Port 5001 -AllowHttpForLogin
```
![ud](https://user-images.githubusercontent.com/6960531/95886420-3c661080-0d87-11eb-88ac-038bf202183c.gif)

Honestly I don't know where to begin and what to use.
Are there some ready made HTML templates with styles and page menus? or should I use .pode files or PSHTML or EPS? how to make the Data Grid?

Probably wishful thinking but I can see that you have a cool way to make an API from a cmdlet `ConvertTo-PodeRoute`. This is obviously more complicated but in concept for example a similar command that produce a base for a human Pode website code instead of an API.

Thank you

**Comment by Badgerati** [comment]
Hey @ili101,

I really like the idea, and it's definitely possible! The difference between doing something like this and `ConvertTo-PodeRoute` is that this will be a lot more involved - I'm thinking it might be best to have this in a new wrapper module (like Pode.Dashboard or something), just so all of the frontend js/css doesn't bulk-up the main module.

There aren't currently any ready made templates like what you're after - the closest would be PSHTML which does have cmdlets for some charts and navs inbuilt. Pode/EPS are more like powershell templating to help dynamically build a file.

I'll have think; there could possibly be a very simplified `ConvertTo-PodePage`, in the main module, that works like the Route equivalent, but it builds simple templated/stylised pages. 🤔  This would be very simple though, like the Route one it would have an input box for almost all of a function's parameters.

For a more full-fledged version, a new wrapper module is probably the better way to go.

**Comment by Badgerati** [comment]
Hey @ili101,

I started work on [`Pode.Web`](https://github.com/Badgerati/Pode.Web), which lets you build sites via PowerShell + Pode. I've pushed v0.1.0 for people to play with, but it's still a work in progress.

You can do your example code in Pode + Pode.Web as:

```powershell
Import-Module Pode
Import-Module Pode.Web

Start-PodeServer {
    # endpoint
    Add-PodeEndpoint -Port 5001 -Protocol Http

    # login/auth
    Enable-PodeSessionMiddleware -Secret 'schwifty' -Duration (10 * 60) -Extend
    New-PodeAuthScheme -Form | Add-PodeAuth -Name Example -ScriptBlock {
        param($username, $password)

        if ($username -eq 'morty' -and $password -eq 'pickle') {
            return @{
                User = @{ ID ='M0R7Y302'; Name = 'Morty'; Type = 'Human' }
            }
        }

        return @{ Message = 'Invalid details supplied' }
    }

    # templates / login page
    Use-PodeWebTemplates -Title Test -DarkMode
    Set-PodeWebLoginPage -Authentication Example

    # processes - table for results, and a form to search
    $table = New-PodeWebTable -Name 'Results' -Id 'tbl_process_results' -Filter
    $form = New-PodeWebForm -Name 'Search' -ScriptBlock {
        $processes = Get-Process -Name $InputData.Name -ErrorAction Ignore | Select-Object Name, ID, WorkingSet, CPU
        $processes | Out-PodeWebTable -Id 'tbl_process_results'
        Show-PodeWebToast -Message "Found $($processes.Length) processes"
    } -Elements @(
        New-PodeWebTextbox -Name 'Name'
    )

    Add-PodeWebPage -Name Processes -Icon Activity -Components $form, $table

    # services
    Add-PodeWebPage -Name Services -Icon Settings
}
```

**Comment by ili101** [comment]
Wow that's amazing!
Didn't noticed you actually started running with this a month ago.
I started to play with it today and so far it looks very promising :smile:
Thank you @Badgerati!
