### ISSUE TITLE
Windows AD authentication using Username, UPN, or NetBIOS name

### ISSUE THREAD

**Issue by ericpritchett** [Badgerati/Pode#631]
### Question
I have successfully setup AD auth using a person's username (e.g. marty.mcfly), but how could I auth against their UPN (marty.mcfly@domain.com) and/or NetBIOS name (netbiosname\marty.mcfly) as well? This is for both Pode 1.8.4 and Pode 2.0 that I've experienced this where the username will work, but the upn or domain\username format will give me a Pode 500 error. To make things simple we can stick with Pode 2.0 that I'm using:

```
New-PodeAuthScheme -Form | Add-PodeAuthWindowsAd -Name 'Login' -Fqdn 'domain.local' -Groups "app_group" -SuccessUrl '/' -FailureUrl '/login' #I've replaced domain.local with my domain
Add-PodeRoute -Method Get -Path '/login' -Authentication 'Login' -login -ScriptBlock {
    Write-PodeViewResponse -Path 'auth-login' -FlashMessages
}
Add-PodeRoute -Method Post -Path '/login' -Authentication 'Login' -login
```

I'm using the [html PatternFly Login Component](https://www.patternfly.org/v4/components/login-page/html) for the login. If the only auth variable allowed is the username (and password), would I then need to parse the username field in the Add-PodeRoute -Method Post somehow? Thanks in advance!

**Comment by Badgerati** [comment]
Hey @ericpritchett,

This is definitely something Pode should be handling, and I can get that fixed in a 2.0.1 - using parsing on `\` and `@`.

As for how to get around it at the moment, it should be possible in both 1.8.4 and 2.0.0; both requires setting up a global middleware to parse the username first. If you want to limit either to just `/login` then supply `-Route '/login'` onto either.

### 1.8.4
```powershell
Add-PodeMiddleware -Name 'ParseFormUsername' -ScriptBlock {
    param($e)

    if ($e.Data.Username) {
        $e.Data.Username = (($e.Data.Username -split '@')[0] -split '\\')[-1]
    }

    return $true
}
```

### 2.0.0
```powershell
Add-PodeMiddleware -Name 'ParseFormUsername' -ScriptBlock {
    if ($WebEvent.Data.Username) {
        $WebEvent.Data.Username = (($WebEvent.Data.Username -split '@')[0] -split '\\')[-1]
    }

    return $true
}
```
