### ISSUE TITLE
CurrentUser instead of LocalMachine listed in Pode Tutorial Docs

### ISSUE THREAD

**Issue by ericpritchett** [Badgerati/Pode#642]
### Describe the Bug
In the following links its said and referenced to store the certs in CurrentUser instead of LocalMachine

https://badgerati.github.io/Pode/Tutorials/Certificates/
https://badgerati.github.io/Pode/Tutorials/Endpoints/Basics/#certificates

### Steps To Reproduce
1. Go to https://badgerati.github.io/Pode/Tutorials/Certificates/ and https://badgerati.github.io/Pode/Tutorials/Endpoints/Basics/#certificates
2. Find 'CurrentUser' to see the misplaced cert store references.

### Expected Behavior
After speaking with @Badgerati it should be listed in LocalMachine instead of CurrentUser

### Platform
 - Tutorial Documentation

**Comment by Badgerati** [comment]
Mentioned in Gitter, but I was wrong and the docs are right - been playing in IIS too much of recent. The certificates are meant to be in `Cert:\CurrentUser\My`; the bug is that PowerShell is now treating an enum value as a literal string (including the class name) for some bizarre reason.

**Comment by ericpritchett** [comment]
@Badgerati, I've tested this and it works for me. Thanks again!
