### ISSUE TITLE
OpenAPI Authentication

### ISSUE THREAD

**Issue by joachimBurket** [Badgerati/Pode#648]
### Question
I'm using a BearerAuthentication on all API routes 
```powershell
New-PodeAuthScheme -Bearer | Add-PodeAuth -Name 'BearerAuth' -Sessionless -ScriptBlock {
    ...
}
Add-PodeAuthMiddleware -Name "GloablAuthMiddleware" -Route "/api/*" -Authentication "BearerAuth"
```

And the OpenApi doc like this: 
```powershell
Enable-PodeOpenApi -Path "/docs/openapi" -Title "My API" -Version "1.0" -Description "API Description" -RouteFilter "/api/*"
Enable-PodeOpenApiViewer -Type Swagger -Path "/docs/api"
```

I'd like to be able to give a BearerToken into the Swagger UI for all the routes needing it, but I can't see it on the page. Is there something I'm missing? 

Thanks!

**Comment by Badgerati** [comment]
Swagger does usually just add the textbox at the top of the page 🤔 Interesting, I'll have a look this weekend/next week once the holidays finish; but this could be either a bug in Pode and I'm not flagging something, or in Swagger.

Thanks! 😄

**Comment by Badgerati** [comment]
Turns out it was a bug in Pode! In the security section it should have been `securitySchemes`, not `securitySchemas`; with that, a new global Authorize button appears at the top of the swagger page.

The above commit contains the change, if you're able to test on your end?

**Comment by joachimBurket** [comment]
Nice! 
I could make it work, but I needed to add the `-Authentication` to the `Add-PodeRoute` to have the authentication header added on the route test in Swagger (even with the global authentication method). Is it the normal behavior or is something missing?

**Comment by joachimBurket** [comment]
Just for precision, this is the OpenApi generated when I add or not the `-Authentication` :
```json
{
    "info": {
        "title": "Test API",
        "description": "testestestest",
        "version": "1.0"
    },
    "security": [
        {
            "BearerAuth": []
        }
    ],
    "openapi": "3.0.2",
    "components": {
        "securitySchemes": {
            "BearerAuth": {
                "scheme": "bearer",
                "type": "http"
            }
        },
        "schemas": {}
    },
    "paths": {
        // Without -Authentication in the route definition
        "/api/test1": {
            "get": {
                "summary": "Test route",
                "description": "",
                "requestBody": {},
                "security": [],
                "tags": [],
                "deprecated": false,
                "responses": {
                    "default": {
                        "description": "Internal server error"
                    },
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        // With -Authentication in the route definition
        "/api/test2": {
            "get": {
                "summary": "Test route 2",
                "description": "",
                "requestBody": {},
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [],
                "deprecated": false,
                "responses": {
                    "default": {
                        "description": "Internal server error"
                    },
                    "200": {
                        "description": "OK"
                    }
                }
            }
        }
    }
}
```

**Comment by Badgerati** [comment]
Aah, yes, I know what's missing - I'll look into it!

Thanks!

**Comment by Badgerati** [comment]
That should fix it, when the OpenAPI definition was being built, routes weren't checking if any global authentication applied to them - now they do.

**Comment by joachimBurket** [comment]
The authentication is working for all routes, thanks :) 
Also there is a strange behavior. In Swagger, each time I open the card of a request, the page is doing a `GET /docs/[object Module]` (my api doc is in `/docs/api`), getting a 404 not found.

**Comment by Badgerati** [comment]
Appears to be a bug within Swagger itself, v3.38.0 doesn't have the problem but the latest, v3.39.0, does 🤔

**Comment by joachimBurket** [comment]
Okay, so I think I can close this issue
