### ISSUE TITLE
Azure AD Authentication from within Powershell Invoke-RestMethod

### ISSUE THREAD

**Issue by breento** [Badgerati/Pode#649]
Hi,

First of all I really like Pode.
I just configured Azure AD authentication and that's working fine.
Now I want to load a Pode page from Powershell, that will give a Microsoft Login HTML page. Do you know if it's possible to use OAuth2/Azure AD authentication from without Powershell with Invoke-RestMethod ?

**Comment by Badgerati** [comment]
Hey @breento,

If you're using Azure AD with all the redirecting to Azure and back again, then I'm afraid doing this via Invoke-RestMethod isn't possible.

If however you're using it without the redirecting, and having users enter their credentials in for login (the Password version of Azure AD, [here](https://badgerati.github.io/Pode/Tutorials/Authentication/Methods/AzureAD/#password)), then this is possible, and you have to use the WebSession and SessionVariable parameters of IRM. It's been a while, but something like:

```powershell
$res = Invoke-RestMethod -Url 'http://etc' -SessionVariable session
$res.Form[0].username = 'username'
$res.Form[0].password = 'password'
Invoke-RestMethod -Url 'http://etc' -WebSession $session -Body $res.Form[0]
```

If this is for a REST API of you site, then you can use basic authentication with Azure AD (and have both form and basic active at once):

```powershell
$form  = New-PodeAuthScheme -Form
$schemeForm = New-PodeAuthAzureADScheme -ClientID '<clientId>' -ClientSecret '<clientSecret>' -Tenant '<tenant>' -InnerScheme $form

$basic = New-PodeAuthSceme -Basic
$schemeBasic = New-PodeAuthAzureADScheme -ClientID '<clientId>' -ClientSecret '<clientSecret>' -Tenant '<tenant>' -InnerScheme $basic

$authLogin = {
    param($user, $accessToken, $refreshToken)
    # check user
}

$schemeForm | Add-PodeAuth -Name 'LoginForm' -FailureUrl '/login' -SuccessUrl '/' -ScriptBlock $authLogic
$schemeBasic | Add-PodeAuth -Name 'LoginBasic' -ScriptBlock $authLogic
```

^ then you can use `LoginForm` on your web page routes, and `LoginBasic` on your REST API routes.

**Comment by RobinBeismann** [comment]
Just as note, pretty sure this only works if you either use Pass-through Authentication, Password Hash Sync or are Azure AD only (without on prem AD).
If you're authenticating your Azure AD against another IdP as ADFS then Azure AD does not know the credentials and can only authenticate you via your IdP.

**Comment by breento** [comment]
Hey @Badgerati,

Thanks for the tip, that's working great! 👍 
I'm now using the redirect method for the webpage routes and the LoginBasic for the REST API routes.

@RobinBeismann  You're right, I'm using Pass-through Authentication and that's working fine, but when I test it against an other Azure AD tenant with ADFS then it's not working.

**Comment by RobinBeismann** [comment]
@breento thanks for confirming, one more question before I raise a pull request to update the docs, do you got Password Hash Sync also enabled or just Pass-through Authentication?
To my understanding it should work with both.

**Comment by breento** [comment]
I’m just using Pass-through Authentication. I have no environment with Password Hash Sync, so I can’t test that scenario right now.

**Comment by breento** [comment]
@RobinBeismann I’m just using Pass-through Authentication. I have no environment with Password Hash Sync, so I can’t test that scenario right now.
