### ISSUE TITLE
Redirect http to https

### ISSUE THREAD

**Issue by ili101** [Badgerati/Pode#650]
### Describe the Bug
Trying to use example [web-route-protocols.ps1](https://github.com/Badgerati/Pode/blob/3f7fd9f68d5fc8707b34db825538c7cc930cd0d5/examples/web-route-protocols.ps1) to redirect http to https.

1. `Add-PodeRoute -Method * -Path * -EndpointName Endpoint1 {`
Need to be changed to this as it can't be resolved:
`Add-PodeRoute -Method * -Path * -EndpointName Endpoint1 -ScriptBlock {`
2. `Add-PodeEndpoint -Address localhost -Port 8443 -Protocol Https -Name Endpoint2`
Need to be changed to this because when browsing to it you get "Secure Connection Failed":
`Add-PodeEndpoint -Address localhost -Port 8443 -Protocol Https -Name Endpoint2 -SelfSigned`
3. If I change the ports to 80 and 443 I get 404 error on both URLs
Looks like it happens when using 80/443 with `Add-PodeRoute -EndpointName foo`

### Workaround
For now I just start a separate PS session to redirect:
```powershell
Start-PodeServer {
    # listen on 80 (set your listening address).
    Add-PodeEndpoint -Address 192.168.0.1 -Port 80 -Protocol Http

    # Redirect http to https.
    Add-PodeRoute -Method * -Path * -ScriptBlock {
        Move-PodeResponseUrl -Protocol Https -Port 443
    }
}
```

### Platform
```
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by Badgerati** [comment]
Fixed the example, cheers!

Also, I found and fixed the reason for 80/443 redirects - and in general - were failing. Should all be OK in the `Issue-650` branch.

**Comment by Badgerati** [comment]
Hey @ili101, are you able to test if this fixes the redirecting for you?

**Comment by ili101** [comment]
Yep, looks like it's working correctly 👍
