### ISSUE TITLE
Investigate adding ScriptBlock parameters to inbuilt Authentication methods

### ISSUE THREAD

**Issue by Badgerati** [Badgerati/Pode#657]
### Describe the Change
When adding authentication, you normally use `Add-PodeAuth` which allows full control of user validation/detail retrieval.

However, for the inbuilt methods: IIS, WindowsAD, WindowsLocal, and UserFile; these validate and retrieval the user object as is, without the option for additional custom logic - such as getting a Windows AD user, and then mapping this to a custom SQLite storage for additional configuration via the user email.

To potentially allow this, could a new `-ScriptBlock` parameter be added to the following functions:

* `Add-PodeAuthWindowsAd`
* `Add-PodeAuthWindowsLocal`
* `Add-PodeAuthUserFile`
* `Add-PodeAuthIIS`

If supplied, and if the methods find a user, then the user object is supplied to this scriptblock as a parameter. The same rules apply as they would in `Add-PodeAuth`: you can either return the user, or an error code/message.

```powershell
New-PodeAuthScheme -Form | Add-PodeAuthWindowsAd -Name 'Login' -FailureUrl '/login' -SuccessUrl '/' -ScriptBlock {
    param($user)

    # check user, retrieve further data from another storage, ie:
    $theme = Get-UserDataFromSql -Email $user.email
    $user.theme = $theme

    return @( User = $user }
}
```

### Related Issues
https://github.com/Badgerati/Pode.Web/issues/13

**Comment by ili101** [comment]
Hi. looks like there is a problem with the argument passed/return from the script block.
The scriptblock get "$User", if you return it login fails as on Private\Authentication.ps1 1005 it expects `Test-PodeIsEmpty $result.User`

So I tested this
```powershell
Add-PodeAuthUserFile -Name 'MainAuth' -FilePath '.\Example\Users.json' -ScriptBlock {
            param($User)
            return  @{ User = $User }
}
```
and it logged in successfully so I assume the code expects "Auth" object returned with "User" in it and not "User"

Full example https://github.com/ili101/ExchangeMessageTrackingLogWeb/blob/I675/Config.Example.ps1#L73-L78

**Comment by Badgerati** [comment]
Yes, the return should be `return  @{ User = $User }`, or if you want to fail:

```powershell
return @{ Message = 'error message' }
```

basically like the normal `Add-PodeAuth` scriptblocks 😃 

I just finished and pushed what I had before going sleep last night 😂 but I realised it would be simpler to have the returns the same as normal `Add-PodeAuth`s

**Comment by ili101** [comment]
Cool so no problem, It was just copying example from this ticket.
