### ISSUE TITLE
Removing cookies in AJAX response fails

### ISSUE THREAD

**Issue by Badgerati** [Badgerati/Pode#660]
### Describe the Bug
When attempting to remove a cookie using `Remove-PodeCookie`, but from an AJAX request, the `Set-Cookie` is set but AJAX doesn't update the cookie on the frontend. This is due to `Remove-PodeCookie` not setting the cookie's Path; A browser will ignore this and treat it as `/`, but AJAX requires it to be set.

### Related Issue
https://github.com/Badgerati/Pode.Web/issues/13

### Steps To Reproduce
1. Set a cookie on the frontend
2. Wire up a button to use AJAX
3. In the request's route use `Remove-PodeCookie`
4. Note the cookie isn't remove in dev tools

### Expected Behavior
The cookie should be expired/removed

### Platform
 - OS: Windows
 - Browser: Chrome
 - Versions:
   - Pode: v2.0.3
   - PowerShell: v5.1

**Comment by ili101** [comment]
LGTM
