### ISSUE TITLE
AD Validation from a machine not joined to Active Directory

### ISSUE THREAD

**Issue by IBera** [Badgerati/Pode#666]
### Question
Hi everybody, Is it possible validate authentication request in Pode, from a container that is not joined to Active Directory?

Thanks and regards

**Comment by ili101** [comment]
Yes, for example `New-PodeAuthScheme -Form | Add-PodeAuthWindowsAd -Name 'MainAuth' -Groups 'IT' -Fqdn MyDomain.local`

**Comment by IBera** [comment]
Is it valid for Basic authentication too?

New-PodeAuthScheme -Basic | Add-PodeAuthWindowsAd -Name 'Login' -Groups @('ITCSL', 'devops') -Fqdn 'MyDomain.local'

We want to use it with a Dockerfile. As you said, i understand that we have to install the ldapsearch package too:

FROM mcr.microsoft.com/powershell:7.0.1-ubuntu-16.04
LABEL maintainer="Matthew Kelly (Badgerati)"
RUN mkdir -p /usr/local/share/powershell/Modules/Pode
COPY ./pkg/ /usr/local/share/powershell/Modules/Pode

**Comment by ili101** [comment]
Yes. Should work, I tried it on WSL Ubuntu successfully

**Comment by IBera** [comment]
Ok thanks, we are going to find info about install and configure ldapsearch and then we will try the authentication. I will keep you updated.

regards.

**Comment by IBera** [comment]
Hi ili101 we've tested AD Authentication from a docker and woks great!!

Thanks a lot
Regards
