### ISSUE TITLE
PodeEndpoint * Address gives 404 if endpoint have name

### ISSUE THREAD

**Issue by ili101** [Badgerati/Pode#669]
1. Give your server a DNS name or put something in the hostfile that point to your IP.
2. If you remove `-Name 'Main'` and `-EndpointName 'Main'` and browse to the name it works.
3. with `-Name 'Main'` and `-EndpointName 'Main'` you get 404 error with the name or with IP. only "localhost" works.
4. Same problem if you put the IP in the `-Address ` and browse to the name.

```powershell
Start-PodeServer {
    Add-PodeEndpoint -Address * -Protocol Http -Name 'Main'

    Add-PodeRoute -Method Get -Path '/' -ScriptBlock {
        Write-PodeJsonResponse -Value @{ 'value' = 'Hello, world!' }
    } -EndpointName 'Main'
}
```

**Comment by Badgerati** [comment]
This is similar to #663, if you try the `Issue-663` branch that should cover most cases.

The commit above is some extra changes I'm toying with to help match a Request to an Endpoint for more use cases - like someone host filing via a different name, etc. So that should also work for your point 4.

**Comment by ili101** [comment]
Tested, with IPs and "*" localy and remotly. looks like it works correctly.
question regarding named endpoints
```powershell
Start-PodeServer {
    # Https Self Signed
    Add-PodeEndpoint -Address * -Port 443 -Protocol Https -SelfSigned -Name 'Main'

    # Redirect http to https
    Add-PodeEndpoint -Address * -Port 80 -Protocol Http -Name 'Redirect'
    Add-PodeRoute -Method * -Path * -EndpointName 'Redirect' -ScriptBlock { Move-PodeResponseUrl -Protocol Https -Port 443 }

    # Theme & Title
    Use-PodeWebTemplates -Title Tools -Theme Auto
    Add-PodeWebPage -Name P1 -Title T1 -Layouts @()
}
```
This code works after this fix. http redirect to https and site is on https.
Note that `Use-PodeWebTemplates -Title Tools -Theme Auto` don't have `-EndpointName 'Main'` on it.
So in this case the redirect PodeRoute have priority over the PodeWeb I presume? Can I rely on that that it will always have higher priority and that it will work? Or is it just luck and it's needed to restrict PodeWeb to the 'Main' PodeEndpoint to prevent unpredictable behavior?
Thank you

**Comment by Badgerati** [comment]
Yes, named routes have a higher priority.

That said, we could add an `-EndpointName` to `Use-PodeWebTemplates` for that extra reassurance 😃
