### ISSUE TITLE
How do I use PODE behind a (NGINX) Reverse Proxy with SSL?

### ISSUE THREAD

**Issue by jhochwald** [Badgerati/Pode#677]
I try to use PODE behind an NGINX Reverse Proxy and struggle to get this scenario working as expected.
When I use HTTP (port 80) on the Proxy, everything works fine, as soon as I use HTTPS (port 443) the behaviour changes and stuff is not working as expected.

In this case, I try to use a login (relative simple, based on some of the examples).

Accesslog on NGINX:
```
192.168.112.16 - - [31/Jan/2021:00:31:12 +0100] "POST /login HTTP/2.0" 302 0 "https://test.hochwald.net/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
192.168.112.16 - - [31/Jan/2021:00:31:12 +0100] "GET /login HTTP/2.0" 200 1024 "https://test.hochwald.net/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
```

When access via http
```
127.0.0.1 - - [31/Jan/2021:00:30:56 +01:00] "POST /login HTTP/1.1" 302 - "http://test.hochwald.net/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
127.0.0.1 - - [31/Jan/2021:00:30:56 +01:00] "GET /login HTTP/1.1" 200 1073 "http://test.hochwald.net/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
```
This request works fine!

When access via https
```
127.0.0.1 - - [31/Jan/2021:00:31:12 +01:00] "POST /login HTTP/1.0" 302 - "-" "-"
127.0.0.1 - - [31/Jan/2021:00:31:12 +01:00] "GET /login HTTP/1.0" 200 3572 "-" "-"
```
This request not, it will simply reload the login (/login) page.

The reverse Proxy config is simple:
```
server {
   listen 80;
   listen [::]:80;
   listen 443 ssl http2;
   listen [::]:443 ssl http2;

   server_name test.hochwald.net;

   location / {
      add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;
      add_header Referrer-Policy "no-referrer, strict-origin-when-cross-origin";
      add_header X-Frame-Options SAMEORIGIN always;
      add_header X-Content-Type-Options nosniff always;
      add_header X-XSS-Protection "1; mode=block" always;
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Server $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_hide_header 'Cache-Control';
      proxy_pass http://127.0.0.1:8080;
      proxy_redirect http://127.0.0.1:8080 https://test.hochwald.net;
   }
}
```
I also removed the `proxy_redirect`, that doesn't change the issue I have. PODE is running on port 8080 in both cases. I also reused a working SSL configuration (different port and Https as Protocol), with "-SelfSigned" and a trusted certificate, no difference.

I also tried to terminate SSL on the NGINX, makes no difference. I also removed most of the security stuff above (add_header), same result.
In general the NGINX setup works fine for several other scenarios and backends, with and without SSL. And it also works fine with plain HTTP traffic.

Any idea how to set this up, or what I did wrong?

**Comment by jhochwald** [comment]
Just to describe my setup a bit more detailed:
The reverse Proxy runs on a Debit 10 system, I use PowerShell (Core) 7.1.1 on the same system (for this test), and Pode from the Gallery.
I also tried a Remote Pode (on Windows 10, with the same PowerShell version), that didn't change.
Pode runs as Daemon, but I also tried to run it as user (in the console).

The basic example I use for this test is `web-auth-form.ps1` (`New-PodeAuthScheme -Form`), with a simple HTML Form served by Pode.

**Comment by ili101** [comment]
Try building the Issue-655 branch and using it.
I tested NGINX with the same configuration on it and it works for me.

**Comment by jhochwald** [comment]
> Try building the Issue-655 branch and using it.
> I tested NGINX with the same configuration on it and it works for me.
Hi @ili101,

thanks for the hint, the build was fine, but it didn't change the behaviour:

Pode Console:
```
Listening on the following 1 endpoint(s) [1 thread(s)]:
	- http://localhost:8080/
127.0.0.1 - - [31/Jan/2021:16:09:13 +01:00] "GET /login HTTP/1.1" 200 3572 "-" "-"
127.0.0.1 - - [31/Jan/2021:16:09:40 +01:00] "POST /login HTTP/1.1" 302 - "-" "-"
127.0.0.1 - - [31/Jan/2021:16:09:40 +01:00] "GET /login HTTP/1.1" 200 3572 "-" "-"
```
The request will still not work as it should (the forma data seems to be missing and the request data (header) is marked as "-". With HTTP (instead if HTTPS) it still works just fine.

I have the latest NET SDK installed in that system:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     debian
 OS Version:  10
 OS Platform: Linux
 RID:         debian.10-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.102/

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  5.0.102 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```
And the build was easy:
```
Build Build /home/josh/Pode-Issue-655/pode.build.ps1
Task /Build/BuildDeps
Done /Build/BuildDeps 00:00:00.0076283
Task /Build
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  Pode -> /home/josh/Pode-Issue-655/src/Listener/bin/Release/netstandard2.0/Pode.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.91
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  Pode -> /home/josh/Pode-Issue-655/src/Listener/bin/Release/netstandard2.0/Pode.dll
  Pode -> /home/josh/Pode-Issue-655/src/Libs/
Done /Build 00:00:02.7843523
Build succeeded. 2 tasks, 0 errors, 0 warnings 00:00:02.8146155
```

**Comment by jhochwald** [comment]
Did another Build with **.NET SDK Version 3.1.405**, that didn't change it.
Just to ensure its not related to the latest .NET

**Comment by ili101** [comment]
Tested again, looks like the specific fix is actually in develop branch and Issue-655 branch is a little out of date, it worked for me on Issue-655 because I updated it before using it:
``` powershell
git fetch origin
git checkout Issue-655
git merge origin/develop
Invoke-Build Build
```

**Comment by jhochwald** [comment]
@ili101 and you did that with .NET core 3.1, right?

**Comment by ili101** [comment]
Yes

**Comment by jhochwald** [comment]
After following the steps that @ili101 provided, it woks as expected:
```
127.0.0.1 - - [31/Jan/2021:21:05:55 +01:00] "GET /login HTTP/1.1" 200 3572 "https://test.hochwald.net/login" "Mozilla/5.0 (iPhone; CPU iPhone OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1"
127.0.0.1 - - [31/Jan/2021:21:06:08 +01:00] "POST /login HTTP/1.1" 302 - "https://test.hochwald.net/login" "Mozilla/5.0 (iPhone; CPU iPhone OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1"
127.0.0.1 - - [31/Jan/2021:21:06:08 +01:00] "GET /login HTTP/1.1" 200 3675 "https://test.hochwald.net/login" "Mozilla/5.0 (iPhone; CPU iPhone OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1"
```
I also see the complete headers in the request and the login works just fine!

Interesting... I tried `Issue-655` and `develop` before, but never merged it ;-)

Thanks you @ili101
