### ISSUE TITLE
Remove server.psd1 static import restrictions 

### ISSUE THREAD

**Issue by ili101** [Badgerati/Pode#679]
I saw that Pode have a config file system (server.psd1)  so I started to move my [Config.Example.ps1](https://github.com/ili101/ExchangeMessageTrackingLogWeb/blob/main/Config.Example.ps1) to it.
Unforgettably I found out that it is mach harder to work with because it's loaded with `Import-PowerShellDataFile`  which make it very restrictive.

for example configs like:
```powershell
@{
    Path       = Join-Path (Get-PodeServerPath) '\Components\SQLite\SqlHelper.psm1'
    Credential = [Management.Automation.PSCredential]::new('User', (ConvertTo-SecureString 'Test' -AsPlainText -Force))
    Script     = {
        Get-Date
    }
}
```
"Path" and "Credential" will make it throw an error on import.
"Script" will import but is annoying to use because of this bug https://github.com/PowerShell/PowerShell/issues/12789.

Suggestion is to either use `server.ps1` instead or in addition and just load it like `& server.ps1` or alternatively keep it the same as it is now and load it with something like `& ([ScriptBlock]::Create((Get-Content Server.psd1 | Out-String)))` instead of `Import-PowerShellDataFile`

**Comment by ili101** [comment]
After some testing replacing `Import-PowerShellDataFile` with `& ([ScriptBlock]::Create((Get-Content Server.psd1 | Out-String)))` in Pode works but as it's loaded in the Pode module scope it have the side effect that if you configured stuff in your main server script file you can't accesses them from server.psd1.
So I implemented the PODE_ENVIRONMENT for my `Config.<environment>.ps1`, loaded it manually then added it to `Get-PodeConfig`.
So it's a little bit extra code and extra config file but I'm not restricted in my `Config.ps1` file and it's loaded in my main script scope.
[Home.ps1](https://github.com/ili101/ExchangeMessageTrackingLogWeb/blob/6b72b26e8ecb836a85d9f1bb15b526b78d3b36fe/Home.ps1#L12-L33)
So maybe leaving it as is is best?

**Comment by Badgerati** [comment]
That is the weirdest of bugs with the ScriptBlock!

Agreed it's probably best to leave it as is, with .psd1. That being said, we could add some helper functions perhaps, for other people that have custom configs scripts 🤔 

Something like a `Find-PodeConfig` to find the config file and path for the PODE_ENVIROMENT.
And an `Update-PodeConfig` that takes a hashtable, and does something like your GetEnumerator.

**Comment by ili101** [comment]
Actually one of the configuration is where the Pode module path is. So I couldn't use `Find-PodeConfig` if I want to keep this config option.
I think that because of the potential scope problems when loading server.psd1 as is unrestricted maybe it's not worth pursuing. As users will implement their custom config files/implementation anyway.
I didn't find a nice way to invoke something from a module in the caller scope except something like the user dot sourcing a function `. Invoke-Configuration` that is not very intuitive.
You can close this issue in my opinion unless you see some value here or other alternative.

**Comment by ili101** [comment]
Just sharing some interesting experiment that actually worked 😀.
https://github.com/ili101/Pode/commit/265b85dc0c6ec9154fb3a73707b22b854d6ef469 It invokes the config in the scope that called `Start-PodeServer` So you have accesses for everything configured before `Start-PodeServer` from the config file.
But you don't have accesses to `Get-PodeServerPath` (maybe other things?) as it's loaded after loading the config, so first auto load of static file then costume loading of dynamic file maybe still better.

Shout out to @seeminglyscience for this awesome article on how to run in other scope 👍 https://seeminglyscience.github.io/powershell/2017/09/30/invocation-operators-states-and-scopes

**Comment by Badgerati** [comment]
Aaah interesting, it's a similar trick as to what I used for `$using:` and local function importing.
