### ISSUE TITLE
Download from PodeStaticRoute with EndpointName 404

### ISSUE THREAD

**Issue by ili101** [Badgerati/Pode#686]
Similar to https://github.com/Badgerati/Pode/issues/669?
`Add-PodeStaticRoute -EndpointName Foo` then use `-DownloadOnly` or `Set-PodeResponseAttachment` you get 404
``` powershell
Start-PodeServer {
    Add-PodeEndpoint -Address localhost -Protocol Http -Name 'Main'
    Set-PodeViewEngine -Type Pode
    
    Add-PodeStaticRoute -Path '/assets' -Source './assets' -EndpointName 'Main' -DownloadOnly

    # GET request to download a file from static route
    Add-PodeRoute -Method Get -Path '/download' -ScriptBlock {
        Set-PodeResponseAttachment -Path '/assets/file.txt'
    }
}
```

**Comment by ili101** [comment]
Thank you! Works for me 👍
I should have read the documentation, didn't know you can use `Set-PodeResponseAttachment` without a Static Route. Probably better for security in case of not public files because it's well... not a static route 😅

**Comment by Badgerati** [comment]
Aye, it's legacy from 0.X, I might actually look at removing it come 3.0 so it's only static routes.

**Comment by ili101** [comment]
In that case I will keep using static routes. Why remove it? Dose it have some big disadvantage?

**Comment by Badgerati** [comment]
No disadvantages, and there are a few other functions that have the same Literal/Static path logic, so it'll probably stick unless other people flag security concerns

**Comment by ili101** [comment]
OK
So I set the Download caching folder to use static route as the files there has GUID folders that can't be guessed, I can maybe provide a direct download URL if needed and it restricted to the static route.

And for the Drive I use absolute path without static route as a user can guess the paths and if I will add permission logic in the future it will be a problem. also the delete/show/list files are already using absolute paths so if my logic have security holes it's compromised already anyway ¯\\\_(ツ)_/¯
https://github.com/ili101/PWT

**Comment by Badgerati** [comment]
Under the hood a static route's source path setup as a temp drive, which can be retrieved via `(Get-PodeStaticRoute -Path '/download').Source` - this is another path you could use 🤔 

Only thing you really need to worry about is if someone put a path into `?value=` manually like `?value=../../../etc`. Using the temp drive, or the static path would prevent backwards traversal - otherwise a user guessing a path within the downloads folder isn't too much of an issue I would've thought, as you're letting them traverse it anyway.

**Comment by ili101** [comment]
I know you can do `?value=../../../etc` this is allowed as long as you don't get out of the base path.
I was checking the option of using a temp drive yesterday evening. didn't knew that this is what you already use 😊. With it you would be able to also do `?value=Drive:/etc` so you can have direct links.

**Comment by ili101** [comment]
I switched to using a PSDrive for the [Drive](https://github.com/ili101/PWT/commit/4062a26448ee97ec3e44d778255a3c89353016d1) but I create it manually and not from Pode because:
1. I want to select the name.
2. I don't need it to be static.
3. I don't need it on all runspaces.

A few problems I encountered:
1. In PowerShell as far as I can find you can't normalize a non existing path with a drive https://github.com/PowerShell/PowerShell/issues/5730 and https://github.com/PowerShell/PowerShell/issues/2993 so I needed to use some regex replacement to work around it ([Workaround](https://github.com/ili101/PWT/blob/4062a26448ee97ec3e44d778255a3c89353016d1/Components/Core/Pwt.Core.Helper.psm1#L19-L31)).
2. `Save-PodeRequestFile` don't work on PSDrives (like in the point above native .Net (in this case `[System.IO.File]::WriteAllBytes`) doesn't know what a PSDrive is, so I converted it before sending the path as a [workaround](https://github.com/ili101/PWT/blob/4062a26448ee97ec3e44d778255a3c89353016d1/Tools/Drive/DrivePages.ps1#L81) for now.
