### ISSUE TITLE
After upgrade to 2.1.0 from 1.6x cannot start pode server

### ISSUE THREAD

**Issue by robertfshort** [Badgerati/Pode#691]
### Describe the Bug
Unable to find type [PodeListenerType].
At C:\Program Files\WindowsPowerShell\Modules\Pode\2.1.0\Private\PodeServer.ps1:256 char:9
+         [PodeListenerType]
+         ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (PodeListenerType:TypeName) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TypeNotFound

### Steps To Reproduce
Start-PodeServer {
    #New-PodeLoggingMethod -Terminal | Enable-PodeErrorLogging
    Add-PodeEndpoint -Address localhost -Port 8080 -protocol http

    Add-PodeRoute -Method Get -Path '/config' -ScriptBlock {

        Write-PodexmlResponse -value 'test'
    }
}

### Expected Behavior
I'm not expecting that error. pode server will not start

### Platform
 - OS: [e.g. iOS, Windows] Windows 2012r2
 - Browser: [e.g. Chrome, Safari]
 - Versions:
   - Pode: 2.1.0
   - PowerShell: 5.1

### Additional Context
this machine was running pode 1.6.x but was upgraded to 2.1.0, after which it no longer functions.

**Comment by robertfshort** [comment]
![image](https://user-images.githubusercontent.com/6556995/107692256-851cd000-6c7a-11eb-8cb2-bf411b70fa90.png)

**Comment by robertfshort** [comment]
if I disable termination when I start the pode server I get this:
![image](https://user-images.githubusercontent.com/6556995/107693950-c615e400-6c7c-11eb-98af-1e7e2058866a.png)

**Comment by Badgerati** [comment]
I've had someone report this once before, and it was resolved by updating .NET to 4.7.2 - does this work for you as well?

**Comment by Badgerati** [comment]
I'm closing this on the assumption the above worked; if not, feel free to re-open.
