### ISSUE TITLE
File upload high CPU extremely slow

### ISSUE THREAD

**Issue by ili101** [Badgerati/Pode#696]
Uploading a 2MB zip takes 5 minutes. (also tested with Pode.Kestrel)
Thank you 🙏
```powershell
Start-PodeServer {
    Add-PodeEndpoint -Address localhost -Protocol Http
    Use-PodeWebTemplates -Title Tools -Theme Dark

    Add-PodeWebPage -Name P1 -Title T1 -Layouts @(
         New-PodeWebForm -Name 'Form' -AsCard -Content @(
            New-PodeWebFileUpload -Name 'Upload File'
            New-PodeWebTextbox -Name 'New Folder'
            New-PodeWebTextbox -Name 'New File'
        ) -ScriptBlock {
            Write-Warning 'OK'
        }
    )
}
```

**Comment by ili101** [comment]
Fix for Pode.Kestrel:
Kestrel - [Expose Kestrel Form to Pode](https://github.com/ili101/Pode.Kestrel/commit/1e846fdde31224751a0414e2c2f4e45ae409150a)
Pode - [Use Kestrel Form](https://github.com/ili101/Pode/commit/86992c023895f6d999a2d5ad95b9eea1bc2c332c)

**Comment by ili101** [comment]
It works up to 30MB because there is a limit https://khalidabuhakmeh.com/increase-file-upload-limit-for-aspdotnet#:~:text=0%2C%20both%20Kestrel%20and%20HttpSys,ReadAsync%20will%20throw%20an%20IOException%20.
I set it to unlimited as it instruct and it worked for 160MB file but for 1.6GB file Kestrel doesn't returns any form data, I don't know why.

**Comment by Badgerati** [comment]
Yeah, because we have to use Kestrel not as a server but more of a parser, Pode uses it in a slightly weird way.

I'll have a look at this, and with Pode's listener as well to speed that up - taking it's multipart parser into .NET and doing it like Kestrel is probably the better approach 🤔

**Comment by ili101** [comment]
Yes so do the encoding in .Net, then give to Pode the encoded result with .Form and .Files properties. 
Pode with custom .Net multipart parser.
Pode.Kestrel with the inbuilt parser.
But regardless of the presser as I see we still need to configure the limit in Kestrel somehow as it will not accept big files anyway, maybe you can find how to override the second 120MB limit.

**Comment by ili101** [comment]
I don't know if you like to use other projects or write it by yourself but if you do there is [HttpMultipartParser](https://github.com/Http-Multipart-Data-Parser/Http-Multipart-Data-Parser).
This replaces the code with the parser https://github.com/ili101/Pode/commit/38b0aab2118c81c613534a55a7cb22ddb9067c31.
To add the dlls (75KB) (probably should be added to the build procedure):
```powershell
Install-Package -Name HttpMultipartParser -Destination 'C:\Temp\' -SkipDependencies
Install-Package -Name Microsoft.IO.RecyclableMemoryStream  -Destination 'C:\Temp\' -SkipDependencies
# Copy "Microsoft.IO.RecyclableMemoryStream.dll" (dependency) and "HttpMultipartParser.dll" to "Pode\src\Libs\"
```

It works with regular Pode and Kestrel but Kestrel is faster. When uploading files with Kestrel there are some limits unlike regular Pode, so https://github.com/ili101/Pode.Kestrel/commit/6b8d55d6b58c8c4e472d26dd146fe31ead66ee87:
* Removes the 30MB limit.
* Increase timeout limit from 30 Sec to 5 Minutes, this doesn't actually limit the upload itself but the time the form will wait for response. Maybe should be increased more for big uploads over the internet or other long operations?

This doesn't use the Kestrel parser, but it doesn't seems to matter anyway as this is very fast as is (don't know if it's faster or slower because I don't know how to remove the Kestrel 120MB form limit to test).

**Comment by Badgerati** [comment]
At present I prefer to avoid third party dependencies, but I'm open to using them if there's no other solution.

I already have logic for parsing form data, it just needs .NET-ifying for the main Pode listener, but I can use the ttpMultipartParser as a reference for any possible improvements I could make 😃 

I'll be taking a look at this one soon, and I'll see if I can find a way to remove that 120MB limit 🕵️

**Comment by Badgerati** [comment]
Hey @ili101,

I've overhauled the upload logic in Pode, and when testing managed to upload a 130MB file a couple of seconds (bit better than 2MB in 5mins! 😄)

I've also updated Pode.Kestrel as well (https://github.com/Badgerati/Pode.Kestrel/issues/2), and I think I've managed to remove the 120MB limit (as I tested it with a 130MB file) - the limit is no 256MB, but can be altered.

**Comment by ili101** [comment]
Thank you for the update 😀
I was so close with the `MultipartBodyLengthLimit`, I think my syntax was wrong or something, nice to see the solution. 

I did some tests uploading large files with Pode and with Pode.Kestrel .
For the usual use case of uploading Excel and Image files that probably go up to 20MB max, both options are practically instantaneous.

I also tested with 1.9GB file. Pode uploaded it in ~100 seconds and Pode.Kestrel took 17 seconds, so both are usable but at this point it probably recommended to use Kestrel.

Over 2GB Pode get Int32 limit error which is probably good as practically it's pushing it to far already .
Kestrel also can't pass 2GB even with `options.MultipartBodyLengthLimit = 1099511627776;`, not entirely understand why.

Kestrel limit should probably best set to `options.MultipartBodyLengthLimit = int.MaxValue;` to be the same as without Kestrel or alternatively see if it can be made higher in case someone will like to upload bigger things like for example ISO files that are usually 4GB-8GB.
But at least for me this already solves the problem for what I need 🎉

**Comment by Badgerati** [comment]
Seems Kestrel might have the same `int` issue, which is what causes the 2GB limit there as well: https://github.com/dotnet/aspnetcore/issues/2711 - still it an issue today it looks like.

I'll set the Kestrel MultipartLength to `int.MaxValue`, which'll set the limits for both at 2GB.

I could probably fix that int32 error in main Pode, depending on what's throwing it 🤔 have you got the error/stacktrace for it?

**Comment by ili101** [comment]
Dinging into https://github.com/dotnet/aspnetcore/issues/2711 it seems like most of the problems reported where fixed by now.
So I did some test here https://github.com/ili101/Pode.Kestrel/commits/Issue-2-Test

First I updated Kestrel to target net5.0 and use the newer builtin Microsoft.AspNetCore.App https://github.com/ili101/Pode.Kestrel/commit/684d40c61e619a11be5a1f88dee22d005c9971e8 following [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-5.0&tabs=visual-studio).
Unflinchingly after testing with it I didn't see any different behavior relevant to the limit.

I saw in the issue that someone linked to a helpful document that was written/updated as response to the questions [Upload files in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-5.0).
In the end it revels what is the problem, basically `byte[]` and `MemoryStream` are limited to 2GB:
> Stream was too long
The examples in this topic rely upon MemoryStream to hold the uploaded file's content. The size limit of a MemoryStream is int.MaxValue. If the app's file upload scenario requires holding file content larger than 50 MB, use an alternative approach that doesn't rely upon a single MemoryStream for holding an uploaded file's content.

It also explains [Buffering vs Streaming](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-5.0#file-upload-scenarios) and show how to [Upload large files with streaming](https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads?view=aspnetcore-5.0#upload-large-files-with-streaming) but it requires client and server side support.

I also found this helpful question [Uploading and Downloading large files in ASP.NET Core 3.1](https://stackoverflow.com/a/62555240/7886965).
So to see if this indeed the problem I just saved it immediately with `FileStream` and it worked https://github.com/ili101/Pode.Kestrel/commit/f48591d614184216dc0956d2098302a0b7196ab4.
It successfully uploaded and saved 8GB in 2 minutes.
He also shows there how you can save to `FileStream` then create `StreamContent` from it to pass it to the next step.
So maybe `class PodeFormFile ... public byte[] Bytes` should be of a type that supports > 2GB like `StreamContent`? 🤔

**Comment by Badgerati** [comment]
I think we leave the limit at 2GB for the time being - it should be pretty rare I'd imagine for anyone to need higher 🤔 I've updated both main Pode and Pode.Kestrel to have a new Save method on PodeFormFile; while this doesn't really do anything for Pode, it should let you do >2GB files in Pode.Kestrel.

We then raise a separate issue to look at how we could increase this beyond 2GB in Pode - refactoring the code to remove `byte[]` and `MemoryStream`. The `StreamContent` seems to only be for files, so not much help; and in most cases people were writing their own steams.

I've an idea of what could be done, but it might end up refactoring the code so much it'd have to be a v3.0! 😂

**Comment by ili101** [comment]
Ohh `Save()`, that's a good idea 👍
Maybe instead of trying to guess what limits/timeouts are most suitable it will be better to use something like the default/conservative limits and add the option to configure them in [server.psd1](https://badgerati.github.io/Pode/Tutorials/Configuration/)?
In this context we have `MultipartBodyLengthLimit`, `MaxRequestBodySize` and this timeout `var _task = Task.Delay(300000, ContextCancellationToken.Token);`, maybe other ones you think of from Pode/Pode.Kestrel.

**Comment by Badgerati** [comment]
I have thought about this before; it's easy for Kestrel, for Pode's listener both MaxSize and Timeout will need implementing.

Defaults I was thinking of 100MB and 30secs, they should be comfortable enough not to break anyone else. Then you can alter them in server.psd1, in bytes and seconds. 0 bytes is just int.Max, and 0 seconds goes back to 30secs.

**Comment by Badgerati** [comment]
There's now support for Request Timeout and BodySize in server.psd1:

```powershell
@{
    Server = @{
        Request = @{
            Timeout = 30
            BodySize = 100MB
        }
    }
}
```

(30secs and 100MB are the default values if not supplied)

**Comment by ili101** [comment]
Tested the 2 limits with Pode and Pode.Kestrel
Looks like all combinations are working.
One difference I found it that with Kestrel the submit spinner will stop and without it it just keep going although it was aborted. Not a big deal just an observation.

**Comment by Badgerati** [comment]
I'm guessing the spinner is Pode.Web? I just tried myself, but the spinner would hide each time 🤔  

If it's Pode.Web, probably one for raising there and I'll work on getting this merged.

**Comment by ili101** [comment]
Those are the tests I did, this time without Pode.Web
Modified `examples\web-upload.ps1`:
```powershell
param (
    [int]
    $Port = 8085,
    [switch]$Kestrel
)
$Params = $Kestrel ? @{ ListenerType = 'Kestrel' } : @{}

$path = Split-Path -Parent -Path (Split-Path -Parent -Path $MyInvocation.MyCommand.Path)
Import-Module "$($path)/src/Pode.psm1" -Force -ErrorAction Stop
Import-Module "$path\..\Pode.Kestrel\src\Pode.Kestrel.psd1"

# or just:
# Import-Module Pode

# create a server, and start listening on port 8085
Start-PodeServer @Params {

    # listen on localhost:8085
    Add-PodeEndpoint -Address LOCALHOST -Port $port -Protocol Http

    Set-PodeViewEngine -Type HTML

    # GET request for web page on "localhost:8085/"
    Add-PodeRoute -Method Get -Path '/' -ScriptBlock {
        Write-PodeViewResponse -Path 'web-upload'
    }

    # POST request to upload a file
    Add-PodeRoute -Method Post -Path '/upload' -ScriptBlock {
        write-warning 'In'
        if ($WebEvent.Data.'username' -eq 's') {
            write-warning 'Sleep'
            sleep 10
        }
        # Save-PodeRequestFile -Key 'avatar'
        # Move-PodeResponseUrl -Url '/'
    }

}
```

Set `examples\server.psd1` for Timeout test:
```powershell
@{
    Server = @{
        Request = @{
            Timeout = 3
            BodySize = 1.99GB
        }
    }
}
```
1. Run: `.\examples\web-upload.ps1` and submit: "Username: s"
Result is good:
```
WARNING: In
WARNING: Sleep
# Browser: HTTP 408
```
2. Ctrl+C then `.\examples\web-upload.ps1 -Kestrel`
Result is good:
```
WARNING: In
WARNING: Sleep
# Browser: HTTP 408
```
3. Ctrl+C then `.\examples\web-upload.ps1` and submit a big file that hit timeout
Result waiting:
```
# Browser: keep waiting for post response
```
4. Ctrl+C then `.\examples\web-upload.ps1` and submit: "Username: s", go back and submit a big file that hit timeout
Result 2 runs then 408: (sometimes can't reproduce and it will just wait like in "3.")
```
WARNING: In
WARNING: Sleep
WARNING: In
WARNING: In
# Browser: HTTP 408
```
5. Ctrl+C then `.\examples\web-upload.ps1 -Kestrel` and submit a big file that hit timeout
Result 3 runs then 408:
```
WARNING: In
WARNING: In
WARNING: In
# Browser: HTTP 408
```

Set `examples\server.psd1` for BodySize test:
```powershell
@{
    Server = @{
        Request = @{
            Timeout = 300
            BodySize = 5MB
        }
    }
}
```
6. Ctrl+C then: `.\examples\web-upload.ps1` and submit a file that hit size limit
Result waiting:
```
# Browser: keep waiting for post response
```
7. Ctrl+C then: `.\examples\web-upload.ps1 -Kestrel` and submit a file that hit size limit
Result 3 runs then Connection reset:
```
WARNING: In
WARNING: In
WARNING: In
# Browser: Connection reset
```

**Comment by Badgerati** [comment]
Hey @ili101,

Thanks for the test examples! Does that commit above work for you now? Each of the test cases passed for me.

**Comment by ili101** [comment]
It's better now with Pode.
Kestrel is the same (did you make an update? didn't see a new commit there)

Set `examples\server.psd1` for Timeout test:
```powershell
@{
    Server = @{
        Request = @{
            Timeout = 3
            BodySize = 1.99GB
        }
    }
}
```
1. Run: `.\examples\web-upload.ps1` and submit: "Username: s"
Result is good:
```
WARNING: In
WARNING: Sleep
# Browser: HTTP 408
```
2. Ctrl+C then `.\examples\web-upload.ps1 -Kestrel`
Result is good:
```
WARNING: In
WARNING: Sleep
# Browser: HTTP 408
```
3. Ctrl+C then `.\examples\web-upload.ps1` and submit a big file that hit timeout
Result reset on timeout
```
# Browser: Connection reset
```

5. Ctrl+C then `.\examples\web-upload.ps1 -Kestrel` and submit a big file that hit timeout
Result 3 runs then 408:
```
WARNING: In
WARNING: In
WARNING: In
# Browser: HTTP 408
```

Set `examples\server.psd1` for BodySize test:
```powershell
@{
    Server = @{
        Request = @{
            Timeout = 300
            BodySize = 5MB
        }
    }
}
```
6. Ctrl+C then: `.\examples\web-upload.ps1` and submit a file that hit size limit
Result 403:
```
# Browser: HTTP 403
```
7. Ctrl+C then: `.\examples\web-upload.ps1 -Kestrel` and submit a file that hit size limit
Result 3 runs then Connection reset:
```
WARNING: In
WARNING: In
WARNING: In
# Browser: Connection reset
```

**Comment by Badgerati** [comment]
That one was just Pode, I've just updated Kestrel and Pode. Should hopefully do the trick on both now 😄

**Comment by ili101** [comment]
LGTM 👍 fast and consistent behavior
Thank you!
