### ISSUE TITLE
Certificates from Computer store

### ISSUE THREAD

**Issue by Juanito99** [Badgerati/Pode#698]
Currently Pode can leverage certificates that are stored in the personal certificate store. - When running Pode as a Windows Service however, I would like to use a certificate from the computer store. 

Could you please consider this for a future release?

**Comment by Badgerati** [comment]
That commit should do the trick; on `Add-PodeEndpoint` there's a new `-CertificateStoreName` and `-CertificateStoreLocation`, each are defaulted to `My` and `CurrentUser` respectively.

They can only be used if trying to use a certificate via Name or Thumbprint

**Comment by Juanito99** [comment]
Thanks for the quick feedback . - A n00p question; I ran **update-module pode -force** 
That is not enough it seems?

**Comment by Badgerati** [comment]
This hasn't been released yet :)

If you want to test you'll have to checkout the code from git, or manually apply the changes your locally installed version. If you're not able to, I have tested locally myself.

**Comment by Juanito99** [comment]
Missed that testing part (facepalm) ...

No problem, I will bare until the next release than 👍 :-)
