### ISSUE TITLE
Get-ADUser with extra properties

### ISSUE THREAD

**Issue by breento** [Badgerati/Pode#702]
If I use "Get-ADUser -identity $username" in a pode route I get the default properties back as expected.
If I run for example "Get-ADUser -identity $username -Properties EmployeeID,Title,Department" sometimes I get the properties back as expected, but most of the time I only get back the default properties like you get with "Get-ADUser -identity $username". 
I got this behavior in Pode 2 but also in 1.x.

If I run this code instead of Get-ADUser
$filter = "(&(objectCategory=User)(samAccountName=$Username))"
$searcher = New-Object System.DirectoryServices.DirectorySearcher
$searcher.Filter = $filter
$ADUserPath = $searcher.FindOne()
$ADUser = $ADUserPath.GetDirectoryEntry()

It's working as expected

Do you have any idea how to fix this with Get-ADUser?

**Comment by Badgerati** [comment]
Hey @breento,

Based on other people who've faced similar, you need to `Import-Module ActiveDirectory` before `Start-PodeServer`, so the module is loaded properly in the other runspaces 😃

**Comment by breento** [comment]
Hey @Badgerati,
Thanks that's working great! 😄

**Comment by breento** [comment]
I tried to put the Get-ADUser command in a Start-Job command like this with multiple threads.
$UserInfo = Start-Job -ScriptBlock {
            get-aduser -Identity 4FlexIT_D.Grayson -Properties EmployeeID, Title, Department
        } | Wait-Job | Receive-Job

That's a little slower of course but that's giving all the properties each time.

**Comment by Badgerati** [comment]
Found this: https://github.com/PowerShell/PowerShell/issues/14604 which explains why this happens.

Why it doesn't work when you bump the threads up is weird, but from that issue link adding `Import-Module ActiveDirectory` to the route's scriptblock could work.

Or, something like this might do it:

```powershell
$user = Get-ADUser -identity $username -Properties EmployeeID,Title,Department

# this should contain the above properties
$user.PSObject.Properties
```

**Comment by breento** [comment]
Interesting article, I didn't found that yet.
I tried both, Import-Module ActiveDirectory in the route doesn't work.
The second option $user.PSObject.Properties does contain all properties but most of the times the value of those custom properties is null. 

I tried to load the PoshRSJob module before Start-PodeServer and use the following code:
$UserInfo = Start-RSJob  -ScriptBlock {
            get-aduser -Identity username -Properties EmployeeID, Title, Department | Select-Object GivenName, Surname, UserPrincipalName, Enabled, SamAccountName, EmployeeID, Title, Department
        } | Wait-RSJob | Receive-RSJob

In this case $UserInfo always contains all variables and it's almost as fast as just Get-ADUser. I think it's workable that way, do you see any issues with this approach?

**Comment by Badgerati** [comment]
If it works, it should be fine :)

However, I've just potentially found a bug that stops the AD module importing properly into the other threads! I'll have a play later, see if what I've found could resolve it. 🤞

**Comment by Badgerati** [comment]
Hey @breento,

Would you be able to test the fix in the above commit? I've tested locally, and if you have `Import-Module ActiveDirectory` before `Start-PodeServer`, the AD module properly imports into all threads now - and `Get-ADUser` returned the extra properties each time.

**Comment by breento** [comment]
Hey @Badgerati,
I tried the commit and it seems to work, now all the times I get the extra properties returned.
Thank you! 😃

**Comment by breento** [comment]
I tried it about 100 times today and all 100 times all properties getting returned 😄 . Great thanks for your quick fix!
