### ISSUE TITLE
Bug on scriptblock

### ISSUE THREAD

**Issue by timttran** [Badgerati/Pode#708]
### Describe the Bug
When I do a GET method with URL ex. http://localhost:8080/exe/notepad.exe,
the scriptblock is being run twice.  I believe it is caused by the period in the parameter "notepad.exe"
If the parameter is just "notepad" then it runs OK (only once).
Please see output on screenshot attached

### Screenshots
![image](https://user-images.githubusercontent.com/25288383/110534508-c622cb80-80e4-11eb-96af-d564ff90cf82.png)

### Platform
 - OS: [e.g. iOS, Windows]
 - Browser: [e.g. Chrome, Safari]
 - Versions:
   - Pode: [e.g. Pode v1.7.3]
   - PowerShell: [e.g. PS6.2.1]

**Comment by Badgerati** [comment]
Hey @timttran,

Which version of Pode/PowerShell are you using? I've just tried on the lastest, v2.1.1, and the scriptblock only runs once as expected for me 🤔

**Comment by timttran** [comment]
hi Badgerati,

I am new and just started to play with Pode, how do I check for the version number?
I just install Pode 2 days ago, should it be the latest?

**Comment by Badgerati** [comment]
Hey @timttran ,

Yeah I'd expect that would be the latest; if you run the following and dump the outputs here:

```powershell
Import-Module Pode -Force
Get-Module Pode
$PSVersionTable
```

Also, which OS are you running this on?
How was the endpoint being hit? Just via a browser, or using `Invoke-WebRequest`/`Invoke-RestMethod`?

Thanks 😃

**Comment by timttran** [comment]
hi Badgerati,

You're right.  It works fine.

I ran it again outside of VSCode, on its own separate Powershell instance, and it ran fine.
For some reason, when running in VSCode's terminal instance, the output shows the scriptblock ran twice, unless I take out the period, then it runs only once

FYI....I am running on Windows 10 Prof (64Bit).  And I just confirm it with your instructions, I am on v2.1.1

Thank you and keep it the good work!

**Comment by Badgerati** [comment]
Glad to hear it works outside VSCode 😄 

I just tried myself in VSCode, and it worked normally for me - I think it may have to be chalked down to some VSCode quirkiness.

Where it would invoke the scriptblock twice doesn't really make much sense, unless somehow two requests were being received. You should be able to check this by adding the following with the other `Write-PodeHost`:

```powershell
Write-PodeHost "Reqs: $(Get-PodeServerRequestMetric -Total)"
```

If the "Reqs" goes 0 > 1, then the server is getting two requests somehow :) if both say 0, then something weird is happening. But so long as it's only in VSCode then it's not toooo bad

**Comment by timttran** [comment]
Thanks Badgerati.

I'll try your suggestion and see what's going on with VSCode.

**Comment by Badgerati** [comment]
I'm closing this issue, but if it's still causing problems please feel free to re-open 😃
