### ISSUE TITLE
Exception setting "TreatControlCAsInput": "The handle is invalid.

### ISSUE THREAD

**Issue by sureshkrishnan83** [Badgerati/Pode#720]
I am facing below error while trying to start the pode web server.  
PS C:\> Start-PodeServer {
    Add-PodeEndpoint -Address localhost -Port 8080 -Protocol Http

    Add-PodeRoute -Method Get -Path '/ping' -ScriptBlock {
        Write-PodeJsonResponse -Value @{ 'value' = 'pong' }
    }
}
Exception setting "TreatControlCAsInput": "The handle is invalid.
"
At \\vmware-host\Shared Folders\Documents\WindowsPowerShell\Modules\pode\Public\Core.ps1:157 char:13
+             [Console]::TreatControlCAsInput = $true
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ExceptionWhenSetting
 

========================================================================================
I have to manually download the pode from psgallery using details mentioned below as the system does not have access to internet. :)  .. Thanks in advance... 
https://docs.microsoft.com/en-us/powershell/scripting/gallery/how-to/working-with-packages/manual-download?view=powershell-7#using-manual-download-to-acquire-a-package
==========================================================

**Comment by Badgerati** [comment]
Hey @sureshkrishnan83,

Are you perhaps running this in PSISE? If not, have you got the details on OS / PS version / IDE ?

You can also supply `-DisableTermination` to `Start-PodeServer` which will skip binding Ctrl+C :)

**Comment by sureshkrishnan83** [comment]
Yes i am running in pse 
Os windows 2016 standard
Ps version 5.1 
Ide ps ise 

i am on mobile now . Will test -disabletermnination once back home . Thanks for your support 😀

**Comment by AlfiCode** [comment]
I get the same exception when starting the script (PS 7.1.3) in an azure pipeline (not ISE, in VScode I have no problem).
As I'm running the script also manually for test I would like to keep it.
Did you see it in other environment as well?
Do you know a fix?

**Comment by Badgerati** [comment]
Hey @AlfiCode,

I'd recommend creating a new issue, and referencing this one 😄 

That said, how are you running Pode in an Azure Pipeline (I've never actually tried, intrigued to know!). `Start-PodeServer` has a `-DisableTermination` switch, so if you have a way of telling if your server is running in the scope of an Azure Pipeline you can set this as `-DisableTermination:$true`, and locally have `-DisableTermination:$false`

Hope that helps!
