### ISSUE TITLE
Docker image based on alpine

### ISSUE THREAD

**Issue by ArieHein** [Badgerati/Pode#726]
To restrict attack surface and known vulnerabilities, can we have a docker image based on the alpine,
possibly using the latest - 7.1.3-alpine-3.12-20210316  or appropriate ps version

**Comment by Badgerati** [comment]
Yep! I can look at setting one up - been meaning to bump the main image to 7.1.3 as well 😃

**Comment by Badgerati** [comment]
That bumps the main images to 7.1.3, an also adds a new `<version>-alpine` image.
