### ISSUE TITLE
Server does not start

### ISSUE THREAD

**Issue by kort3x** [Badgerati/Pode#736]
### Describe the Bug
Pode WebServer does not start

### Reproduce
Follow the my-first-pode-app example: https://badgerati.github.io/Pode/Getting-Started/FirstApp/

### Error
Resolve-PodeValue: C:\Users\berfelde\Documents\PowerShell\Modules\Pode\2.2.2\Private\WebServer.ps1:24
Line |
  24 |          $_protocol = (Resolve-PodeValue -Check $_.Ssl -TrueValue 'htt …
     |                                                 ~~~~~~
     | Cannot process argument transformation on parameter 'Check'. Cannot convert value "" to type
     | "System.Boolean". Boolean parameters accept only Boolean values and numbers, such as $True, $False, 1
     | or 0.

### Platform
 - OS: Windows
 - Versions:
   - Pode: 2,2.2
   - PowerShell: 7.1.3 and 5.1

**Comment by Badgerati** [comment]
Seems like something went wrong with the 2.2.2 packaging 🤔 some how it's bundled 2.2.1 in there as well. 

For now, drop back to 2.2.1 and I'll look to fix this ASAP. 

Thanks for reporting!

**Comment by kort3x** [comment]
Thanks for the quick response

**Comment by Badgerati** [comment]
Hey @kort3x ,

This is now fixed in v2.2.3 😃

**Comment by kort3x** [comment]
Awesome, thank you!
