### ISSUE TITLE
JSON web token (JWT) via the authorisation token in the header

### ISSUE THREAD

**Issue by berki7867** [Badgerati/Pode#744]
Hi,

I’m trying to write a REST API that takes a JSON web token (JWT) via the authorisation token in the header.
I have a function to decrypt the JWT, but I keep getting invalid authorisation header.

The script I have so far is:

Start-PodeServer {
    Add-PodeEndpoint -Address * -Port 8080 -Protocol Http

    # setup bearer authentication to validate a user
    New-PodeAuthScheme -Bearer | Add-PodeAuth -Name 'Authenticate' -Sessionless -ScriptBlock {
        param($token)

        function ConvertFrom-Jwt {

            [cmdletbinding()]
            param(
            [Parameter(Mandatory = $true)]
            [string]$Token,
            
            [Alias('ih')]
            [switch]$IncludeHeader
            )
            
            # Validate as per https://tools.ietf.org/html/rfc7519
            # Access and ID tokens are fine, Refresh tokens will not work
            if (!$Token.Contains(".") -or !$Token.StartsWith("eyJ")) { Write-Error "Invalid token" -ErrorAction Stop }
            
            # Extract header and payload
            $tokenheader, $tokenPayload = $Token.Split(".").Replace('-', '+').Replace('_', '/')[0..1]
            
            # Fix padding as needed, keep adding "=" until string length modulus 4 reaches 0
            while ($tokenheader.Length % 4) { Write-Debug "Invalid length for a Base-64 char array or string, adding ="; $tokenheader += "=" }
            while ($tokenPayload.Length % 4) { Write-Debug "Invalid length for a Base-64 char array or string, adding ="; $tokenPayload += "=" }
            
            Write-Debug "Base64 encoded (padded) header:`n$tokenheader"
            Write-Debug "Base64 encoded (padded) payoad:`n$tokenPayload"
            
            # Convert header from Base64 encoded string to PSObject all at once
            $header = [System.Text.Encoding]::ASCII.GetString([system.convert]::FromBase64String($tokenheader)) | ConvertFrom-Json
            Write-Debug "Decoded header:`n$header"
            
            # Convert payload to string array
            $tokenArray = [System.Text.Encoding]::ASCII.GetString([System.Convert]::FromBase64String($tokenPayload))
            Write-Debug "Decoded array in JSON format:`n$tokenArray"
            
            # Convert from JSON to PSObject
            $tokobj = $tokenArray | ConvertFrom-Json
            Write-Debug "Decoded Payload:"
            
            if($IncludeHeader) {$header}
            return $tokobj
            }
        $JWTDetails = ConvertFrom-Jwt $JWT
        $name = $JWTDetails.name
        
        
        # here you'd check a real storage, this is just for example
        if ($name -eq 'John Doe') {
            return @{ User = $name }
        }

        # authentication failed
        return $null
    }

    # check the request on this route against the authentication
    Add-PodeRoute -Method Get -Path '/cpu' -Authentication 'Authenticate' -ScriptBlock {
        Write-PodeJsonResponse -Value @{ 'cpu' = 82 }
    }

    # this route will not be validated against the authentication
    Add-PodeRoute -Method Get -Path '/memory' -ScriptBlock {
        Write-PodeJsonResponse -Value @{ 'memory' = 14 }
    }
}
 
But when I call it using below:
$JWT = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c'
Invoke-RestMethod 'localhost:8080/cpu' -Headers @{ Authorization = "$JWT" } 

I get “Invalid Authorization header".
The JWT is valid, it’s the example used on the site https://jwt.io/
And the function decrypts it just fine:

$JWT = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c'

function ConvertFrom-Jwt {

    [cmdletbinding()]
    param(
    [Parameter(Mandatory = $true)]
    [string]$Token,
    
    [Alias('ih')]
    [switch]$IncludeHeader
    )
    
    # Validate as per https://tools.ietf.org/html/rfc7519
    # Access and ID tokens are fine, Refresh tokens will not work
    if (!$Token.Contains(".") -or !$Token.StartsWith("eyJ")) { Write-Error "Invalid token" -ErrorAction Stop }
    
    # Extract header and payload
    $tokenheader, $tokenPayload = $Token.Split(".").Replace('-', '+').Replace('_', '/')[0..1]
    
    # Fix padding as needed, keep adding "=" until string length modulus 4 reaches 0
    while ($tokenheader.Length % 4) { Write-Debug "Invalid length for a Base-64 char array or string, adding ="; $tokenheader += "=" }
    while ($tokenPayload.Length % 4) { Write-Debug "Invalid length for a Base-64 char array or string, adding ="; $tokenPayload += "=" }
    
    Write-Debug "Base64 encoded (padded) header:`n$tokenheader"
    Write-Debug "Base64 encoded (padded) payoad:`n$tokenPayload"
    
    # Convert header from Base64 encoded string to PSObject all at once
    $header = [System.Text.Encoding]::ASCII.GetString([system.convert]::FromBase64String($tokenheader)) | ConvertFrom-Json
    Write-Debug "Decoded header:`n$header"
    
    # Convert payload to string array
    $tokenArray = [System.Text.Encoding]::ASCII.GetString([System.Convert]::FromBase64String($tokenPayload))
    Write-Debug "Decoded array in JSON format:`n$tokenArray"
    
    # Convert from JSON to PSObject
    $tokobj = $tokenArray | ConvertFrom-Json
    Write-Debug "Decoded Payload:"
    
    if($IncludeHeader) {$header}
    return $tokobj
    }

$JWTDetails = ConvertFrom-Jwt $JWT
$name = $JWTDetails.name
 
Any ideas?

**Comment by Badgerati** [comment]
Hey @berki7867,

Add `Bearer` to the front of the JWT token 😃:
```powershell
Invoke-RestMethod 'http://swpapp-nichprc.swp-rest.police.int:8080/cpu' -Headers @{ Authorization = "Bearer $JWT" }
```

I was surprised to see this wasn't in the docs; so I'll get that added!

**Comment by berki7867** [comment]
Many thanks, its working now, but I can't process the JWT to get the username out. 
I just get an empty field. This is what I have:

# bearer auth works using John Doe
Start-PodeServer {
    Add-PodeEndpoint -Address * -Port 8080 -Protocol Http

    # setup bearer authentication to validate a user
    New-PodeAuthScheme -Bearer | Add-PodeAuth -Name 'Authenticate' -Sessionless -ScriptBlock {
        param($token)

        function ConvertFrom-Jwt {

            [cmdletbinding()]
            param(
            [Parameter(Mandatory = $true)]
            [string]$Token,
            
            [Alias('ih')]
            [switch]$IncludeHeader
            )
            
            # Validate as per https://tools.ietf.org/html/rfc7519
            # Access and ID tokens are fine, Refresh tokens will not work
            if (!$Token.Contains(".") -or !$Token.StartsWith("eyJ")) { Write-Error "Invalid token" -ErrorAction Stop }
            
            # Extract header and payload
            $tokenheader, $tokenPayload = $Token.Split(".").Replace('-', '+').Replace('_', '/')[0..1]
            
            # Fix padding as needed, keep adding "=" until string length modulus 4 reaches 0
            while ($tokenheader.Length % 4) { Write-Debug "Invalid length for a Base-64 char array or string, adding ="; $tokenheader += "=" }
            while ($tokenPayload.Length % 4) { Write-Debug "Invalid length for a Base-64 char array or string, adding ="; $tokenPayload += "=" }
            
            Write-Debug "Base64 encoded (padded) header:`n$tokenheader"
            Write-Debug "Base64 encoded (padded) payoad:`n$tokenPayload"
            
            # Convert header from Base64 encoded string to PSObject all at once
            $header = [System.Text.Encoding]::ASCII.GetString([system.convert]::FromBase64String($tokenheader)) | ConvertFrom-Json
            Write-Debug "Decoded header:`n$header"
            
            # Convert payload to string array
            $tokenArray = [System.Text.Encoding]::ASCII.GetString([System.Convert]::FromBase64String($tokenPayload))
            Write-Debug "Decoded array in JSON format:`n$tokenArray"
            
            # Convert from JSON to PSObject
            $tokobj = $tokenArray | ConvertFrom-Json
            Write-Debug "Decoded Payload:"
            
            if($IncludeHeader) {$header}
            return $tokobj
            }
        $JWTDetails = ConvertFrom-Jwt $token
        $name = $JWTDetails.name
        $name | Out-Default
        
        # here you'd check a real storage, this is just for example
        if ($name -eq 'John Doe') {
            return @{ User = $name }
        }

        # authentication failed
        return $null
    }

    # check the request on this route against the authentication
    Add-PodeRoute -Method Get -Path '/cpu' -Authentication 'Authenticate' -ScriptBlock {
        Write-PodeJsonResponse -Value @{ 'User' = User }
    }

    # this route will not be validated against the authentication
    Add-PodeRoute -Method Get -Path '/memory' -ScriptBlock {
        Write-PodeJsonResponse -Value @{ 'memory' = 14 }
    }
}

So when I call it using:

$JWT = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c'

Invoke-RestMethod 'http://localhost:8080/cpu' -Headers @{ Authorization = "Bearer $JWT" }

I get:

User
----


How can I pass the username from the authentication to the route?

**Comment by Badgerati** [comment]
Hey @berki7867,

In the `/cpu` route, it should be:
```powershell
Write-PodeJsonResponse -Value @{ 'User' = $WebEvent.Auth.User }
```

**Comment by berki7867** [comment]
Thanks again for your assistance, I've almost got it working, but I'm having to hard code the username:

If ($name -eq 'John Doe')

If I try 

If ($name -ne '')
or 

If ($name)

Then I get the error "User not found"

I just want it to process a JWT and if there is a value for the for the name use other say "user not found".

**Comment by Badgerati** [comment]
That is strange, `if ($name)` should work 🤔 I just tried my self, and it worked as expected. Have you got a snippet of the code?

**Comment by berki7867** [comment]
Hi,

Many thanks for your assistance with your help I managed to get it working.
Thank you
