### ISSUE TITLE
Javascript in Pode Files

### ISSUE THREAD

**Issue by datenschieber** [Badgerati/Pode#745]
My views are based on pode files. Now I want to use DataTables (https://datatables.net/) in my views. You need to use JavaScript for some initialization tasks:

```
    <script type="text/javascript">
        $(document).ready(function () {
            $('#example').DataTable();
        });
    </script>
```

When I add this fragment to my pode files, start the pode server, and load the page (Write-PodeViewResponse) I get an Internal Server Error 500. Error message is 

```
The term 'document' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

It seems that $(document) is processed as powershell code. 

Any idea how to embed this kind of JavaScript code in pode files?

**Comment by RobinBeismann** [comment]
You can escape the $ by adding a ` in front of it. That's how I do it for Javascript in Pode Files.

**Comment by datenschieber** [comment]
@RobinBeismann Thanks for the hint. I will try!

I found another solution: Just add a space between $ and (. The following worked for me:

```
    <script type="text/javascript">
        $ (document).ready(function () {
            $ ('#example').DataTable();
        });
    </script>
````

**Comment by RobinBeismann** [comment]
Yeah, that's because Pode Files interpreters $() as Powershell Code, however I'd suggest to escape it instead, who knows if all browser Javascript engines support a space in between.
