### ISSUE TITLE
How long is startup supposed to take?

### ISSUE THREAD

**Issue by krokofant** [Badgerati/Pode#756]
### Question
I've executed a small example and the server takes 2m30s before this text is visible:

```powershell
Listening on the following 1 endpoint(s) [1 thread(s)]:
    - http://localhost:8080/
```

I'm thinking it should not take this long. Any idea on what I can troubleshoot? If the antivirus is blocking, what executables or paths might impact this slowness?

```powershell
Import-Module -Name Pode -MaximumVersion 2.99.99

Start-PodeServer {
    Add-PodeEndpoint -Address localhost -Port 8080 -Protocol Http

    Add-PodeRoute -Method Get -Path '/' -ScriptBlock {
        Write-PodeJsonResponse -Value @{ 'value' = 'Hello, world!' }
    }
}
```

Environment:
```powershell
Pode                           2.3.0
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by krokofant** [comment]
It's fast when executed in a pwsh process started with `-NoProfile` option.

**Comment by Badgerati** [comment]
Hey @krokofant,

It sounds like you might have a lot of module importing in your profile? Pode will automatically load all currently imported modules into its runspaces, so if there's a lot, it will slow down the start-up.

Does disabling the module loading make it go faster as well? You can do this by adding the following to a `server.psd1`:

```powershell
@{
    Server = @{
        AutoImport = @{
            Modules = @{
                Enable = $false
            }
        }
    }
}
```

[see more here](https://badgerati.github.io/Pode/Tutorials/Scoping/)

**Comment by krokofant** [comment]
@Badgerati That works great thank you.

I'm also wondering, how would I trigger a schedule (`Invoke-PodeSchedule`) directly after the server is started?

I've tried this but it doesn't seem to trigger. Are there some server event hooks where they should be placed?
If it's a real issue it'll create another one to track it.
```powershell
Start-PodeServer {
    Add-PodeEndpoint -Address localhost -Port 8080 -Protocol Http

    Add-PodeRoute -Method Get -Path '/' -ScriptBlock {
        $ips = Get-PodeState vmIps
        Write-PodeJsonResponse -Value @{ 'value' = "$ips" }
    }

    Add-PodeSchedule -Name 'RunEveryMinute' -Cron '@minutely' -ScriptBlock {
        Write-Host "Fetching new VMs"
        Set-PodeState vmIps -Value $((Get-AzpVm) -join ',')
    }

    Invoke-PodeSchedule -Name RunEveryMinute
}
```

**Comment by Badgerati** [comment]
Hey @krokofant,

At the point `Invoke-PodeSchedule` is called here, the runspaces haven't been started yet, which is why it doesn't run.

However, `Add-PodeSchedule` has an `-OnStart` switch that will trigger it straight away, once everything has started 😃

**Comment by krokofant** [comment]
Thank you @Badgerati . Very exciting project 🎉
