### ISSUE TITLE
Must be running with administrator priviledges to listen on non-localhost addresses

### ISSUE THREAD

**Issue by berki7867** [Badgerati/Pode#757]
### Question
A clear and concise description of your question.

Hi,

I have a pode script installed as a windows service, but I want to be able to run it under a service account that has non-admin privileges. Currently if I run it as local system, it work fine, but when I run it as a non-admin account I get the error

"Must be running with administrator priviledges to listen on non-localhost addresses"

Is there any way to run the script as non-admin windows service account?

**Comment by Badgerati** [comment]
Hi @berki7867,

Is your script listening on localhost, or a non-localhost address?

If it's the former, let me know, because there could be a bug. If it's the latter, I'm afraid it's a Windows restriction that to listen on non-local addresses the account running the script has to be admin :(

**Comment by berki7867** [comment]
Thanks Badgerati,

If I set the address to be localhost and hostname the FQDN of the server, it starts under the service account, but I can't access it remotely. I get
"Invoke-RestMethod : Unable to connect to the remote server"

Is there anyway to have the address as localhost and be able to access it remotely?

**Comment by Badgerati** [comment]
Hey @berki7867,

Unfortunately not, the address has to be all (*) or the IP of the machine if you want to access the script remotely.

You can run it using localhost and access remotely, but you'll need to use a tool like IIS or NGINX to proxy traffic for you. For NGINX I'm not too sure, but with IIS your script will have to be run via IIS and not as a Windows Service.

**Comment by RobinBeismann** [comment]
Do you have temporary admin access?
You could possibly NAT a port on the local windows firewall to a high port that your user account can run.

@Badgerati, wouldn't using netsh http add urlacl as admin be an option too?

**Comment by Badgerati** [comment]
@RobinBeismann I did consider `netsh http`, but thought that only works for tools using HTTP.SYS?

**Comment by RobinBeismann** [comment]
Ah correct yeah - that won't work for PodeListener.

This would work through:
https://docs.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh-interface-portproxy#add-v4tov4
We had to use a local portproxy to tunnel an application which did not support IPv6 over an IPv6 based VPN - works pretty reliable. However it requires the user to atleast have admin rights once in order to create the portproxy.

**Comment by Badgerati** [comment]
@RobinBeismann Oh wow, yeah that works!

```powershell
netsh interface portproxy add v4tov4 listenport=<external-port> connectaddress=127.0.0.1 connectport=<pode-port>

#ie:
netsh interface portproxy add v4tov4 listenport=8085 connectaddress=127.0.0.1 connectport=8086
```

As you said it requires admin initially, but after that you can run pode on localhost as non-admin. I'll have to get that into the [External](https://badgerati.github.io/Pode/Tutorials/Endpoints/External/) docs 😮 thanks!

@berki7867 the above should work for you, to access externally but running Pode as non-admin on localhost 😄

**Comment by berki7867** [comment]
Thanks both this worked.
Thanks again 😊
