### ISSUE TITLE
env setup

### ISSUE THREAD

**Issue by ericxin1982** [Badgerati/Pode#758]
### Question
A clear and concise description of your question.
I have powershell 7 installed, and the windows has two powershell versions, normally how I should start?
I install-module through powershell 7 or 5, or I download the zip package and decompress and get into that folder to run code?

I am a bit confused, and there is no answer from doc, sorry to bother.

Thanks
Eric Xin

**Comment by Badgerati** [comment]
Hi @ericxin1982,

It depends really on which version of PowerShell you'd like to run Pode from. If from PowerShell 7, then `Install-Module Pode` in pwsh, or if PowerShell 5, then `Install-Module Pode` under Windows PowerShell. Pode does support 5 and 7, so you could install it under both versions to make it easier :)

Once installed, you can start to write your script, and then run it under which ever version of PowerShell you installed Pode on.

Hope that helps 😃

**Comment by ericxin1982** [comment]
ok, thanks.
