### ISSUE TITLE
smtp server attachment saveas or manipulation

### ISSUE THREAD

**Issue by ericxin1982** [Badgerati/Pode#759]
### Question
A clear and concise description of your question.

Hi,

I saw smtp server has many attributes there, but I found there is no attachment attribute, if I have csv or xlsx file attached, and how I can manipulate it or save it somewhere.

thanks
Eric Xin

**Comment by Badgerati** [comment]
Hi @ericxin1982,

Honestly, I've never tried it with an attachment! When I get chance, I'll investigate and let you know :)

**Comment by ericxin1982** [comment]
Thanks.
