### ISSUE TITLE
smtp server issue

### ISSUE THREAD

**Issue by ericxin1982** [Badgerati/Pode#760]
![image](https://user-images.githubusercontent.com/9047436/122343397-3ceb2280-cf78-11eb-8b66-fdfa12a42cff.png)
![image](https://user-images.githubusercontent.com/9047436/122343450-4aa0a800-cf78-11eb-980c-2035fe6ec06f.png)

Hi,

I tried smtp server, I set it up, and telnet the ip and 25, and continued keying in from xxx.xxx, once I keyed in f, then the connection get lost, what did I do wrong?

Thanks
Eric Xin

**Comment by ericxin1982** [comment]
![image](https://user-images.githubusercontent.com/9047436/122348082-58a4f780-cf7d-11eb-8f48-22898aa6f3c2.png)
I used smtp test tool, does not work also.

**Comment by Badgerati** [comment]
Hey @ericxin1982,

The first one with the `f` makes sense, as it's an invalid SMTP command so the connection is being closed.

As for the second one, that looks like it worked all right; what makes you think it didn't work?

**Comment by ericxin1982** [comment]
![image](https://user-images.githubusercontent.com/9047436/122488270-b4b85c00-d00f-11eb-930f-8d26a7f95e77.png)
Hi @Badgerati 

At least I should see the value output to the console, right?
I did not see anything output from here.
I am wondering whether it is right, or how do I know it works or not.
Please advise!

Thanks
Eric Xin

**Comment by ericxin1982** [comment]
@Badgerati 

Do you have any comment for this, anything may be helpful, I can keep trying.

Thanks
Eric Xin

**Comment by Badgerati** [comment]
Hey @ericxin1982,

Sorry for the late response, yes I've an idea. From the SMTP test tool it looks like it's definitely talking to Pode (with the `250 OK` responses), so it's likely due to the `Write-Host`s; if you use `Out-Default` instead do you get any output?

```powershell
$SmtpEvent | Out-Default
$SmtpEvent.Email.From | Out-Default
$SmtpEvent.Email.To | Out-Default
$SmtpEvent.Email.Body | Out-Default
```

Other ideas are:
* The test tool looks to be connecting to 127.0.0.1 rather than 10.121.148.148 - if you make the test tool connect to the 10. address does that work?
* Try setting up the Pode endpoint to be on localhost, and use the test tool then.

I've just tried on my machine, and the mail is received and outputted but if it was on localhost I had to send to localhost; likewise for my machine's IP, if Pode was listening on my 10. address I had to send to the same address, localhost failed.

Are you sending the mail from the same machine, or an external one? If it's external, try setting the `-Address` on the endpoint to `*` (same for local as well if you're still having issues).

**Comment by ericxin1982** [comment]
Thanks very much!

**Comment by ericxin1982** [comment]
![image](https://user-images.githubusercontent.com/9047436/123185994-c1362c00-d4c9-11eb-972b-1c1d3802f833.png)
Hi @Badgerati 

The out-default has nothing output still, so I am using out-file, and it did not record anything also.
But smtp-console has response from pode proxy server, and why it looks like this?

Thanks
Eric Xin

**Comment by ericxin1982** [comment]
![image](https://user-images.githubusercontent.com/9047436/123213179-49332a80-d4f8-11eb-8e80-9de3ed7b65ce.png)
![image](https://user-images.githubusercontent.com/9047436/123213220-53edbf80-d4f8-11eb-967d-88a0b45e55f5.png)
I ran in both ps env, all do not work.

**Comment by Badgerati** [comment]
Very strange 🤔 

If you add `New-PodeLoggingMethod -Terminal | Enable-PodeErrorLogging` just under `Add-PodeEndpoint` do you get any error output? (could take up to 10secs to appear).

What happens if you use `Send-MailMessage`, does that work? 

Out of interest, what is the smtp test tool, is it something I could test with and see if I get the same issue?

**Comment by ericxin1982** [comment]
send-mailmessage I tried also. Let me try to capture the error first.

**Comment by ericxin1982** [comment]
![image](https://user-images.githubusercontent.com/9047436/123352564-20f80a00-d592-11eb-9376-7a7c61d55473.png)
[SMTPConsole.zip](https://github.com/Badgerati/Pode/files/6712801/SMTPConsole.zip)
I used this tool to try. You can try.

**Comment by Badgerati** [comment]
Hey @ericxin1982,

I've had a play, and think I can see the issue 😃 

In the test tool you're passing the `DATA` command with the message body, where as it should be the `DATA` command on its own, then the message body - also, the message body should end with a `.` (or more precisely `<CR><LF>.<CR><LF>` as the `354` response says):

```plain
(Connected with 127.0.0.1)
220  -- Pode Proxy Server
HELO 
250 OK
MAIL FROM:<test@test.com>
250 OK
RCPT TO:<me@me.com>
250 OK
DATA
354 Start mail input; end with <CR><LF>.<CR><LF>
From: "From Name" <scomp@domain.com>
To: "To Name" <fbl@domain.com>
Subject: This is the subject

This is the body of the message.

.
250 OK
QUIT
```

^ that works for me. I tested with the image you posted further up (DATA with body in one line), and there is a very very quick `501: Error` from the server and the tool disconnects immediately.

**Comment by ericxin1982** [comment]
Hi @Badgerati 

Thanks for the testing, but I still have no luck.
So I tried powershell send-mailmessage command, 
![image](https://user-images.githubusercontent.com/9047436/123723892-ef4ab000-d8bd-11eb-816f-10b90ce7d389.png)
It works, but it seems it sometimes would not capture what I sent, sometimes it would throw an error from client, do you know why, and how to solve?

Thanks
Eric Xin

**Comment by ericxin1982** [comment]
Hi @Badgerati 

Sorry, when I did for powershell 5.x version, it works perfectly.
But how come powershell 7 does not work like powershell 5.x?
Do you know why? Sorry, it may be far away from the topic.

![image](https://user-images.githubusercontent.com/9047436/123780310-a74f7b80-d905-11eb-9be1-4c91e5a5e6e3.png)

**Comment by ericxin1982** [comment]
Hi @Badgerati 

I tested these features, actually I prefer it can be used as email received smtp server, if it is used as email being sent smtp server, what is the user case?
Normally if it can be smtp received listener would be better.
Not sure whether it supports.

Thanks
Eric Xin

![image](https://user-images.githubusercontent.com/9047436/123784755-58581500-d90a-11eb-8234-597e0e0f023b.png)

**Comment by ericxin1982** [comment]
![image](https://user-images.githubusercontent.com/9047436/123785577-45921000-d90b-11eb-9d23-8a3edd4c998a.png)
![image](https://user-images.githubusercontent.com/9047436/123785696-6bb7b000-d90b-11eb-9243-b2464ad735f8.png)
![image](https://user-images.githubusercontent.com/9047436/123785719-74a88180-d90b-11eb-8b6a-a55a2ef15fbb.png)

I expected to show this email content, from and to. But there is no output for this. It's set up as email received smtp server.

**Comment by Badgerati** [comment]
Hey @ericxin1982,

If it's `Send-MailMessage` from PS6/7 then this make some sense; other than it now being deprecated, for some reason it no longer sends the QUIT command which causes timeout/disconnect errors on the client side.

As for the type, I'm not too sure what you mean by "email being sent", but I can see the way that Pode's works as definitely being email received. The original use case for it was for a test framework to send emails to a mock/fake smtp server to test email sending logic - but have a handler in Pode that logs the email from/to/body into a SQLite DB for later viewing.

**Comment by ericxin1982** [comment]
Thanks!
