### ISSUE TITLE
Cannot work with https

### ISSUE THREAD

**Issue by nchurkin** [Badgerati/Pode#778]
I created simple server and generated certificate via letsencrypt (certbot):

```
Import-Module Pode
Start-PodeServer -Threads 2 {
    Add-PodeEndpoint -Address * -Hostname 'test.xxxxxx.xxx' -Port 443 -Protocol Https -CertificateName 'test.xxxxxx.xxx'

    New-PodeLoggingMethod -Terminal | Enable-PodeRequestLogging

    Add-PodeRoute -Method Get -Path '/' -ScriptBlock {
        'Opening...' | Out-Default
        Write-PodeTextResponse -Value 'Good!'
    }
}
```
I tried use different parameters: certificate name, thumbprint, file name -- same result. Server starts with no errors.

It doesn't work, browser cannot open a page. If I switch to http -- it works perfectly. I tried to run Invoke-WebRequest -- The operation has timed out.

I use Powershell 7.1.3 on Windows 10.

**Comment by Badgerati** [comment]
Hey @nchurkin,

I've just tested this myself, and HTTPS/Certificates does work for me. The fact it starts without errors says it's definitely finding the certificate and binding 🤔 

Just a couple of questions/ideas:
* Have you got an example of the `Invoke-WebRequest` call you're making? (is this also on 7.1.3 as well?)
    * If on 7.1.3, what happens if you try with the `-SkipCertificateCheck` switch?
* What happens if you try a different `-Port`, say 8443, etc?
* Are you running Pode as an admin?
* Try adding `New-PodeLoggingMethod -Terminal | Enable-PodeErrorLogging` and then use `Invoke-WebRequest`; wait a few seconds (~10secs), is there any errors in the terminal?

This being on Windows, I'm guessing the certificate is a PFX installed to `Cert:\CurrentUser\My`?

**Comment by nchurkin** [comment]
Hi! Sorry for delay.

I run Pode as admin, use Powershell 7.1.3 and certificate is a PFX and installed to Cert:\CurrentUser\My. I tried use port 8443 -- the same situation.

I added Enable-PodeErrorLogging to the script:
```
Import-Module Pode

Start-PodeServer -Threads 2 {
    New-PodeLoggingMethod -Terminal | Enable-PodeRequestLogging
    New-PodeLoggingMethod -Terminal | Enable-PodeErrorLogging

    Add-PodeEndpoint -Address * -Hostname api.kb.ru -Port 80 -Protocol Http
    Add-PodeEndpoint -Address * -Hostname api.kb.ru -Port 8443 -Protocol Https -CertificateName 'api.kb.ru'

    Add-PodeRoute -Method Get -Path '/' -ScriptBlock {
        Write-PodeTextResponse -Value 'Good!'
    }
}
```

I tested port 8443 via telnet -- it is opened.

```
PS C:\Users\n.churkin> $PSVersionTable.PSVersion

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      1      3

PS C:\Dev\krs-site-export> iwr api.kb.ru

StatusCode        : 200
StatusDescription : OK
Content           : Good!
RawContent        : HTTP/1.1 200 OK
                    Date: Wed, 21 Jul 2021 07:40:23 GMT
                    Server: Pode
                    X-Pode-ContextId: 014bee3f-08c7-70a8-135f-ebff9d320d26
                    Connection: close
                    Content-Type: text/plain; charset=utf-8
                    Content-Length: …
Headers           : {[Date, System.String[]], [Server, System.String[]], [X-Pode-ContextId, System.Str
                    ing[]], [Connection, System.String[]]…}
Images            : {}
InputFields       : {}
Links             : {}
RawContentLength  : 5
RelationLink      : {}


PS C:\Dev\krs-site-export> iwr https://api.kb.ru:8443
Invoke-RestMethod : Unable to read data from the transport connection: An existing connection was forcibly closed by
 the remote host.
PS C:\Dev\krs-site-export> iwr https://api.kb.ru:8443 -SkipCertificateCheck
Invoke-RestMethod : Unable to read data from the transport connection: An existing connection was forcibly closed by
 the remote host.
PS C:\Dev\krs-site-export>
```

Server output (no errors):
```
PS C:\Dev\krs-site-export\corex> .\pode-server.ps1
Listening on the following 2 endpoint(s) [2 thread(s)]:
        - http://api.kb.ru:80/
        - https://api.kb.ru:8443/
192.168.3.220 - - [21.июл..2021:09:39:04 +02:00] "GET / HTTP/1.1" 200 5 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36"
192.168.3.220 - - [21.июл..2021:09:40:23 +02:00] "GET / HTTP/1.1" 200 5 "-" "Mozilla/5.0 (Windows NT 10.0; Microsoft Windows 10.0.19043; ru-RU) PowerShell/7.1.3"
192.168.3.23 - - [21.июл..2021:10:05:25 +02:00] "GET / HTTP/1.1" 200 5 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0"
```

**Comment by Badgerati** [comment]
Hey @nchurkin, no worries! 😄

Thanks for the further information! This is a very strange one; locally for me it's still okay 🤔 One idea I have is what if you run the following line before doing `Invoke-WebRequest`?

```poweshell
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
```

I'm guessing those lines from FireFox/Chrome have the same problem, only working for HTTP and not HTTPS?

If that TLS change above doesn't work, I'll look at adding in a proper verbosity mode for Pode. Around where Pode closes the connection most of the errors are swallowed up for things like requests with invalid hostnames/ssl/tls/etc.

I think there could be an error being thrown here: https://github.com/Badgerati/Pode/blob/e880ca0e321302d99884646204e972812379d614/src/Listener/PodeContext.cs#L153-L163

And making the `catch` a `catch (Exception ex)` with a `Console.WriteLine(ex.Message)` will probably give us some clues 🤔

**Comment by nchurkin** [comment]
Hi!

I tried to change security protocol -- the same result.

**Comment by Badgerati** [comment]
Hi @nchurkin,

In the above commit I've added in some debug logging; just before that though, from #791 I've had a thought. The default SSL protocols Pode allows are SSL3 and TLS12, but you can alter these [as seen here](https://badgerati.github.io/Pode/Tutorials/Certificates/#ssl-protocols) - one to have a play with just in case! You can allow just TLS12, allow everything, try TLS13, etc.

If that still fails, then the commit above does have some extra logging, however to test you'll have to clone and build the repository locally. Once cloned, you'll need the InvokeBuild module, and then from the root of the repo run `Invoke-Build Build`. You can then directly import the module file found at `./src/pode.psm1` (don't do the psd1, it'll fail).

Then, add `New-PodeLoggingMethod -Terminal | Enable-PodeErrorLogging -Levels Error, Debug` to enable error and debug logging. Hopefully you should get something! 🤞

**Comment by nchurkin** [comment]
Hi @Badgerati, thank you!

I pulled repository and built it. I added New-PodeLoggingMethod to the script:
```
Import-Module C:\Dev\Pode\src\Pode.psm1 -Force

Start-PodeServer -Threads 2 {
    New-PodeLoggingMethod -Terminal | Enable-PodeRequestLogging
    New-PodeLoggingMethod -Terminal | Enable-PodeErrorLogging -Levels Error, Debug
    Get-PodeConfig | ConvertTo-Json | Out-Default

    Add-PodeEndpoint -Address * -Hostname api.kb.ru -Protocol Https -CertificateName 'api.kb.ru' -Port 8443

    Add-PodeRoute -Method Get -Path '/' -ScriptBlock {
        Write-PodeTextResponse -Value 'Good!'
    }
}
```

It is sad, but no errors or debug messages in console. I tried to change server.psd1 file, tried all protocols. It doesn't work...

Client output:
```
PS C:\Users\n.churkin> ping api.kb.ru

Pinging api.kb.ru [192.168.3.220] with 32 bytes of data:
Reply from 192.168.3.220: bytes=32 time<1ms TTL=128
Reply from 192.168.3.220: bytes=32 time<1ms TTL=128
Reply from 192.168.3.220: bytes=32 time<1ms TTL=128
Reply from 192.168.3.220: bytes=32 time<1ms TTL=128

Ping statistics for 192.168.3.220:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 0ms, Average = 0ms
PS C:\Users\n.churkin> iwr https://api.kb.ru:8443
Invoke-WebRequest: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
```

**Comment by Badgerati** [comment]
Hey @nchurkin,

This is a bizarre one. I've added in some extra debug logging around closing socket connection if you want to give that a try?

I also had a friend quickly trying Pode using LetsEncrypt, and for him it worked as expected. When doing it though, we spotted a couple things:

* First one was: is there a chance it's firewall related, even locally on Windows Firewall? Maybe briefly disable it and try then.
* Second one was the generation of the PFX. When he did it certbot gave back PEM file that has to be merged into a PFX via openssl. Was this the same for you, and could the merger have gone wrong? He suggested that the PFX could be missing it's private key - basically in mmc.exe on the certificate's properties do you see the following? 
![image](https://user-images.githubusercontent.com/1483395/128085689-fdb70efe-3936-40cd-9a56-6987bdc17cc5.png)
* Finally, are you able to try the cert in IIS? Just to prove it isn't the cert at fault.

Do you have the certbot/openssl commands you used?

**Comment by Badgerati** [comment]
I'm closing this issue, but if it's still causing problems please feel free to re-open 😃
