### ISSUE TITLE
PodeListener RequestTimeout Attribute not found

### ISSUE THREAD

**Issue by RobinBeismann** [Badgerati/Pode#784]
### Describe the Bug
I'm trying to run Pode 2.3.0 as standalone on Windows 10 20H2 with PowerShell 5.1 (latest CU) and am getting the following error (sorry - it's in german):
It translates to something like "RequestTimeout" Attribute was not found on $listener.
```
Die Eigenschaft "RequestTimeout" wurde für dieses Objekt nicht gefunden. Vergewissern Sie sich, dass die Eigenschaft vorhanden ist und festgelegt werden kann.
In Zeile:1 Zeichen:1
+ $listener.RequestTimeout = $PodeContext.Server.Request.Timeout
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException
```
I get this error even if I define one basic route and fire the listener up with: 
```
$podePort = 7788
Add-PodeEndpoint -Address 127.0.0.1 -Protocol Http -Port $podePort
```

### Platform
 - OS: Windows 10 20H2
 - Browser: Unrelated
 - Versions:
   - Pode: v2.3.0
   - PowerShell: 5.1.19041.1023

### Additional Context
If I set a breakpoint in private/PodeServer.ps1 on line 46, I can see that PodeListener indeed does not have those attributes it tries to set:
```
$listener.PSObject.Properties

MemberType      : Property
Value           : {}
IsSettable      : False
IsGettable      : True
TypeNameOfValue : System.Collections.Generic.IDictionary`2[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Pode.PodeWebSocket, Pode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]
Name            : WebSockets
IsInstance      : True

MemberType      : Property
Value           : False
IsSettable      : False
IsGettable      : True
TypeNameOfValue : System.Boolean
Name            : IsListening
IsInstance      : True

MemberType      : Property
Value           : False
IsSettable      : False
IsGettable      : True
TypeNameOfValue : System.Boolean
Name            : IsDisposed
IsInstance      : True

MemberType      : Property
Value           : True
IsSettable      : True
IsGettable      : True
TypeNameOfValue : System.Boolean
Name            : ErrorLoggingEnabled
IsInstance      : True

MemberType      : Property
Value           : System.Threading.CancellationToken
IsSettable      : False
IsGettable      : True
TypeNameOfValue : System.Threading.CancellationToken
Name            : CancellationToken
IsInstance      : True

MemberType      : Property
Value           : Http
IsSettable      : False
IsGettable      : True
TypeNameOfValue : Pode.PodeListenerType
Name            : Type
IsInstance      : True
```

**Comment by RobinBeismann** [comment]
Updated: I just compiled the latest listener version from develop and that one has the Attributes and starts without issues - is the listener version in the 2.3.0 Release maybe not the one that should have shipped with it?

**Comment by Badgerati** [comment]
Hey @RobinBeismann,

I've a feeling something may have gotten confused/wrongly cached on your end?

I just tested 2.3.0 on a fresh VM, and works fine; I've also been used 2.3.0 at work for the last month with issue 👀 For RequestTimeout to not be there is like it's cached a 2.1.0 dll somehow (RequestTimeout was added in 2.2.0).

Where did you install the module from? I've been using the Gallery one, so I know that's good; I just checked Choco and that also seems fine, and someone I know is using Docker so should be OK as well 🤔

**Comment by RobinBeismann** [comment]
Hey @Badgerati ,

I used the one from Github Releases, I'll try it on a fresh machine later today just to be sure.

**Comment by Badgerati** [comment]
@RobinBeismann, Oh I see! I just tried the `2.3.0-Binaries.zip` from the Releases and that worked also 😄

**Comment by RobinBeismann** [comment]
Just to add, this was indeed an issue on my side due to multiple Pode versions being installed.
I'll close the issue, thanks.
