### ISSUE TITLE
IIS Required Features

### ISSUE THREAD

**Issue by PrzemyslawKlys** [Badgerati/Pode#790]
### Question

Could you let me know which features exactly are required on IIS to be enabled for Pode to work?

I've been checking documentation (https://pode.readthedocs.io/en/latest/Hosting/IIS/) but it's just too wide.

```powershell
Install-WindowsFeature -Name Web-Server -IncludeManagementTools -IncludeAllSubFeature
```

Can you be a bit more specific so I don't have to install 50 features that will never be used?

**Comment by RobinBeismann** [comment]
I can't name the roles at the moment as I'm not near a PC, but you basically only need the basic functions which the Server Manager suggests plus the .NET Core Hosting Bundle and Powershell 7.
If you want to use Windows Authentication on Pode, you'll also need to install the IIS Windows Authentication Feature also.

You now owe me (and Badgerati) a cuddle with that fluffy Samoyed. 😂

**Comment by PrzemyslawKlys** [comment]
I see, well I am getting an error - thought this might be related - but if not I'll search some

![image](https://user-images.githubusercontent.com/15063294/126799508-e1a2a3aa-e096-4011-9705-096e157e6408.png)

I guess it may be that Microsoft .NET 5.0.8 Windows Server Hosting is not what I should have installed :) 

![image](https://user-images.githubusercontent.com/15063294/126799745-2bb9f37a-5830-47a9-a3b3-8c82e1ae6c3d.png)

I don't keep choco on my server so I would appreciate links to proper software :)

**Comment by Badgerati** [comment]
So far as I'm also aware you should be able to get away with just the default features Server Manager suggests - though I've never tested it without everything!

For dotnetcore hosting I've only personally used v3.1 myself, I really need to test with v5.0 - I know some people have been using it here, so it does work. You can find a direct install for v5.0 [here](https://dotnet.microsoft.com/permalink/dotnetcore-current-windows-runtime-bundle-installer) and for v3.1 I believe it's this one [here](https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-aspnetcore-3.1.17-windows-hosting-bundle-installer)

If I get chance this weekend I'll checkout the minimum features required, as well as test with v5.0 as there's something else on Windows Server 2019 I need to test as well for IIS 😄 

Also, I'm loving that Instagram! 🐶

**Comment by PrzemyslawKlys** [comment]
The links don't work if you try to click them - most likely because those are valid for your session only. But I believe I have them - if you can let me know the minimum requirements that would be great.

**Comment by Badgerati** [comment]
Hey @PrzemyslawKlys, this is the minimum I was able to get down to:

```powershell
$features = @(
    'Web-Default-Doc',
    'Web-Dir-Browsing',
    'Web-Http-Errors',
    'Web-Static-Content',
    'Web-Http-Redirect',
    'Web-DAV-Publishing',
    'Web-Http-Logging',
    'Web-Stat-Compression',
    'Web-Filtering',
    'Web-Net-Ext',
    'Web-Net-Ext45',
    'Web-Asp-Net',
    'Web-Asp-Net45',
    'Web-CGI',
    'Web-ISAPI-Ext',
    'Web-ISAPI-Filter',
    'Web-Mgmt-Console'
)

$features | % { Install-WindowsFeature -Name $_ }
```

If you don't need the IIS Manager then you can remove `Web-Mgmt-Console`. And as  @RobinBeismann suggested, if you need to use Basic/Windows auth then `Web-Basic-Auth` or `Web-Windows-Auth` are needed respectively.

I've also just tested with windowshosting 5.0.8 and can confirm it works 😄 if just those features above also work for you, I'll use this issue to update the IIS docs (+non-session specific install links 😂).

**Comment by PrzemyslawKlys** [comment]
Hi,

For the visual representation that's what I have enabled and things work

![image](https://user-images.githubusercontent.com/15063294/126881899-d0da6756-afa5-4867-b6ff-ca91dea3114e.png)

I installed WebSocket protocol because I found it on UD IIS settings - thought it may be the same requirement. But if you're saying it's not - it's not :)

**Comment by Badgerati** [comment]
Yeah, I believe UD runs on WebSockets where as Pode doesn't :)

If you need to use Pode's WebSockets then you might have to install that feature as well; but it'll be like the auth ones and optional.
