### ISSUE TITLE
How to run https endpoint on MacOS?

### ISSUE THREAD

**Issue by phatmandrake** [Badgerati/Pode#791]
### Question

I'm getting a "ERR_SSL_VERSION_OR_CIPHER_MISMATCH" on **MacOS** when attempting to use https. It works as expected when the server is hosted from Centos. Not sure what to fiddle with for MacOS to do this properly

**Comment by Badgerati** [comment]
Hey @phatmandrake,

MacOS seems to be an oddball when it comes to using HTTPS. I've only known one other person try it, and I believe for him it was a broken chain in the end 🤔 Although Pode doesn't really care, MacOS fails cert validation regardless.

I'd recommended ensuring the chain is valid. Also, try doing the following before something like `Invoke-WebRequest` as the error seems to suggest it could be TLS related:

```powershell
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
```

I believe MacOS can also sometimes be weird with self-signed certificates, so if possible try and use a properly signed certificate.

Hope this helps! I don't personally own a macbook so can't test probably 😅

**Comment by phatmandrake** [comment]
The default security protocol is tls12 at least PS7 MacOS, I did also try explicitly setting it. I only tested it with the -selfsigned cert flag, presumably that's the issue all other things being the same, I've seen similar issues elsewhere.

**Comment by Badgerati** [comment]
In PS7 I think it is the default, I'm too use Windows where it can never make it's mind up 😂 I always recommend it, because sometimes it could be the answer :)

It could work if you import it into the local cert store, though I'm not too sure how to do that from powershell on a mac 🤔 It could even be that the self signed cert needs something setting specifically on a mac to work.

What happens if you manually create a self signed cert via openssl and use that on the endpoint, does that work?  Does it work if you import it into the local cert store?

**Comment by phatmandrake** [comment]
`openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 365`

Tried generating a cert and it says:

`The certificate 'CN=localhost' has expired`

When starting Pode. It's definitely not expired.

Looking at https://badgerati.github.io/Pode/Functions/Core/Add-PodeEndpoint/#-x509certificate I didn't know which parameter I was supposed to use for specifying the key so it could be that.

**Comment by phatmandrake** [comment]
mmmkay the same certificate works with https://github.com/http-party/http-server.

So I don't think it's the certificate that is the issue.

**Comment by Badgerati** [comment]
I think I may have the answer, .NET it seems doesn't play ball with PEM cert/key files for SSL - it requires a PFX and password.

On Windows/Linux I could get the cert.pem to load, but then requests would just fail or hang. Once I converted the cert and key to a PFX it worked as expected (again, on windows/nix):

```bash
openssl pkcs12 -inkey ./key.pem -in ./cert.pem -export -out ./cert.pfx
```

```powershell
Start-PodeServer {
    Add-PodeEndpoint -address * -Port 443 -Protocol Https -Name QRCode -certificate "./cert.pfx" -CertificatePassword '<password>'
    Add-PodeRoute -Method GET -Path "/" -ScriptBlock { 
        Write-PodeTextResponse -Value "Hello World!" 
    }
}
```

I may have found something that people on Kestrel use to trick cert/key PEMs to work over there, so I'll take a look at that and see if I can do the same here 🤔 

(Also, `-Certificate` is the right parameter - `-X509Certificate` is if you load the certificate yourself via .NET and want to pass that to Pode)

**Comment by phatmandrake** [comment]
I converted it to a PFX and the server now starts, but now I'm back to the original issue. 

In chrome:
`"ERR_SSL_VERSION_OR_CIPHER_MISMATCH"` 

Error from Invoke-RestMethod
```
System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
                  ---> Interop+AppleCrypto+SslException: bad protocol version
```
I've tried importing the certificate into the MacOS keychain and explicitly trusting it. 

Not sure what the special sauce is for this.

**Comment by Badgerati** [comment]
That does suggest something with TLS doesn't it, hmm 🤔 

The only thing Pode sets by default is to allow just SSL3 and TLS1.2. You could test by allowing them all ([see here](https://badgerati.github.io/Pode/Tutorials/Certificates/#ssl-protocols)) and see what happens.

**Comment by phatmandrake** [comment]
Holy Toledo that worked. Y'know I'm ashamed I saw that was probably the first thing I found a day or 2 ago and thought to myself "that looks to complicated...." *click* 😅

It works when either TLS,TLS11,TLS12 are specified, it does not work if TLS13 is the only one specified. If it is as you say then it should be working out of box.

**Comment by Badgerati** [comment]
Ooo, OK! So on MacOS instead of both SSL3/TLS12 being the default, just TLS12 on it's own should be the default and that should work 🤔 It could be that Mac doesn't play ball with SSL3, and that's what's causing the issue; if we bin it on Mac, should be OK?

**Comment by phatmandrake** [comment]
To clarify it works if anything below TLS13 is specified. It only fails if if TLS13 is the only one specified. It's a little perplexing.

**Comment by Badgerati** [comment]
That commit should do it :)

I don't know if you're able to test the changes locally? I have setup HTTPS integration tests that use `-SelfSigned` and it passed on Windows, Linux and MacOS - so it's hopeful!

**Comment by phatmandrake** [comment]
It's working for me 

This confuses me though:

```
function ConvertTo-PodeSslProtocols
{
    param(
        [Parameter()]
        [ValidateSet('Ssl2', 'Ssl3', 'Tls', 'Tls11', 'Tls12', 'Tls13')]
        [string[]]
        $Protocols
    )

    $protos = 0
    foreach ($protocol in $Protocols) {
        $protos = [int]($protos -bor [System.Security.Authentication.SslProtocols]::$protocol)
    }

    return [System.Security.Authentication.SslProtocols]($protos)
}
```

What's going on here? Protos is set to 0, then becomes the value of the bor and then uses that same value for the next bor. Is it supposed to overwrite? Is `$protos = 0` supposed to be inside the loop?

If it does it seems to  work with the existing ssl3,tls12 configuration. Just curious about how this works.

**Comment by Badgerati** [comment]
`-bor` is a binary or on the two or more protocols, so the finally protocol value is like a form of all the protocols aggregated together :)

If the `$protos = 0` was inside the for-loop, then this wuld appear to work as it's the same as only passing Tls12. But what we want is the binary value of all the protocols together, so the `$protos` gets reused for the next `-bor` operator.
