### ISSUE TITLE
Cannot get sql query result to create a new table? 

### ISSUE THREAD

**Issue by qy2009** [Badgerati/Pode#792]
Hi,

I have tried to get the sql query result to create a new table, however when I run it, it outputs empty result? 
here is the code:

    Start-PodeServer {
    Add-PodeEndpoint -Address localhost -Port 8080 -Protocol Http

    Use-PodeWebTemplates -Title 'SCCM' -Theme Dark
    Add-PodeWebPage -Name 'Component Status' -Icon 'Settings' -ScriptBlock {
        New-PodeWebCard -Content @(
            New-PodeWebTable -Name 'Component Status' -ScriptBlock {
                Invoke-DbaQuery -SqlInstance $sqlserver -Database $database -Query $query | ForEach-Object {
    @{ 
        MachineName = $_.MachineName 
        ComponentName = $_.ComponentName
        Status = $_.Status
        Infos = $_.Infos
        Warnings = $_.Warnings
        Errors = $_.Errors
    } 
    } }
        )
    
    }}

I have also tried just using " Invoke-DbaQuery -SqlInstance $sqlserver -Database $database -Query $query" inside the script block. same result.

thanks!

**Comment by RobinBeismann** [comment]
Where are you defining those variables?
Are you sure that they're accessible within the PodeWeb Function?

Btw, this should go into the PodeWeb Issue Tracker, not directly into the Pode one.

**Comment by qy2009** [comment]
those variables are defined on the beginning of the script. you mean I need to put them inside the "Start-PodeServer {"?

oh. I am really sorry about that. should I close this ticket and open there? 

thanks!
