### ISSUE TITLE
Windows Authentication from CentOS 8

### ISSUE THREAD

**Issue by phatmandrake** [Badgerati/Pode#793]
### Question

Trying to get AD Auth working.

```
Start-PodeServer {
    
    Add-PodeEndpoint -address * -Port 8080 -Protocol Https -Name QRCode -selfsigned
   
    Enable-PodeSessionMiddleware -Duration 120 -Extend

    New-PodeAuthScheme -Basic | Add-PodeAuthWindowsAd -Name 'Auth' -server "server.ad.domain.com" -domain 'ad.domain.com'

    Add-PodeRoute -Method GET -Path "/QR/Users" -EndpointName "QRCode" -Authentication 'Auth' -Scriptblock {
            
        Write-PodeTextResponse -Value "Hello World!"
    }

}
```

User credentials are being rejected 401. https://github.com/Badgerati/Pode/issues/666 references needing ldapsearch, which is installed.

**Comment by Badgerati** [comment]
Hey @phatmandrake,

What format are you supplying the username in? Internally Pode will split the username on `\` and `@`, and then prepend that with the `-Domain` you supplied (ie: `ad.domain.com`).

For example:
* You pass `domain\username`
* Pode splits on `\` to get just `username`
* Then it adds the domain: `ad.domain.com\username`

and that last one is what's sent to LDAP for authentication. Are you using a different initial format, or is the last format sent to LDAP not valid for your server? Also, are your users stored somewhere non-standard, and needs a custom LDAP query to find them?

**Comment by phatmandrake** [comment]
The user objects aren't stored in the default `CN=Users` container of AD if that's what you mean by non-standard. They're located in a different beneath a different OU. Is there a way to specify a search base and scope if that's required? I didn't see a way to do this if so. 

I am supplying just the username portion not the domain portion for basic auth. so 

first.last is all that is being supplied. I also tried:

Dom-AD\first.last - NetBIOS
first.last@ad.domain.com - UPN

If Pode automatically preprends the value of -domain that would actually fail in my environment if I were using the DNS name ad.domain.com (like I am), it would need to be the NetBIOS domain name that would need to be appended which is limited to 15 characters and can't contain dots.

So I tried it with the NetBIOS name, assuming it is what is appended, and it still failed.

**Comment by Badgerati** [comment]
Yes, the `-Domain` is the NetBIOS domain name.

That could be the reason, if Users is under a different OU 🤔 Currently there's no way to specify a different path but I can look into it.

Just to make sure it's not that, this is the ldap query used:

```powershell
(&(objectCategory=person)(samaccountname=$($Username)))
```

Where `$Username` here would just be `first.last` - is that valid for your `samaccountname`? The ldapsearch call looks like it should be OK and search all person objects from the root -so in theory shouldn't matter about the OU.

**Comment by RobinBeismann** [comment]
Just to add, many Linux LDAP Directories do not have a sAMAccountName Attribute, I think that's basically just Active Directory.

**Comment by phatmandrake** [comment]
Great Googley Moogley, I got it!

```
Start-PodeServer {
    
    Add-PodeEndpoint -address * -Port 8080 -Protocol Http -Name QRCode
    Enable-PodeSessionMiddleware -Duration 120 -Extend
    New-PodeAuthScheme -Basic | Add-PodeAuthWindowsAd -Name 'UnixAuth' -server "ad.domain.com" -domain 'DOM-AD'
    Add-PodeRoute -Method GET -Path "/QR/Users" -EndpointName "QRCode" -Authentication 'UnixAuth' -Scriptblock {
            
        Write-PodeTextResponse -Value "Hello World!"

    }

}
```

1. FQDN/SERVER needed to be just the DNS domain not the name of the FQDN of the domain controller. The other option was to leave the parameter out entirely.

2. Domain needed to be the NetBIOS domain name.

But this is confusing since:

```
    # set the domain if not passed
    if ([string]::IsNullOrWhiteSpace($Domain)) {
        $Domain = ($Fqdn -split '\.')[0]
    }
```
   
Sets "Domain" to the value of -fqdn split on periods, but the Domain needs to be the NetBIOS name not the DNS name...or so I thought....

So looking at this string from `Open-PodeAuthADConnection`

`ldapsearch -x -LLL -H "$($hostname)" -D "$($user)" -w "$($Password)" -b "$($dcName)" "$($query)" dn)`

**Hostname** can be a uri string that contains only the DNS name. (ldap://ad.domain.com)
-D (binddn) Can be in UPN format (samacountname@ad.domain.com)
-b Is the search base so exposing that to a simple parameter would be beneficial for systems with large LDAP structures.

In total though this mean the NetBIOS name is not needed at all for this to work correctly, I think it would be simpler to just have the DNS domain be used. 

```
        $user = $Username
        if (!$Username.StartsWith($Domain)) {
            $user = "$($Domain)\$($Username)"
        }

```

It looks like NetBIOS is only being taken for the username to supply to ldapsearch

```
    if ([string]::IsNullOrWhiteSpace($Fqdn)) {
        $Fqdn = Get-PodeAuthDomainName
```

Pulls the domain DNS Name from `Get-PodeAuthDomainName` if unspecified. So Pode already has all the information it needs to make this work without the NetBIOS Domain.

Also for what it's worth your code is SUPER easy to read I love it. I usually have so much trouble, but everything make sense.

**Comment by phatmandrake** [comment]
Also this:

```
    # set the domain if not passed
    if ([string]::IsNullOrWhiteSpace($Domain)) {
        $Domain = ($Fqdn -split '\.')[0]
    }
```

Only works if your NetBIOS domain is the same as the value of the first index of the split so:
ad.domain.com would process to just "ad" for $Domain, which may or may not be correct.
 

  ```
        $user = $Username
        if (!$Username.StartsWith($Domain)) {
            $user = "$($Domain)\$($Username)"
        }

Would become "ad\samccoutname", which in our environment would be incorrect. So the logic to try and determine the "NetBIOS" domain name for the purpose of creating the username for the ldapsearch is failing for people like me.

**Comment by Badgerati** [comment]
Aah OK, so in the second scenario with `ad\samaccountname`, if that was `sam@ad.domain.com` that would work.

So dropping `-Domain` is something I can't do for Pode 2, but is definitely something I can flag to be gone in Pode 3 (that or make UPN the default instead). Here though, we could have a `-UseUPN` switch on `Add-PodeAuthWindowsAd` and that uses `sam@ad.domain.com` instead - ignoring `-Domain`.

For `-b`, we could have an `-OUPath` that, if specified, gets prepended to the DC Path Pode builds from the DNS domain name.

---
> Also for what it's worth your code is SUPER easy to read I love it. I usually have so much trouble, but everything makes sense.

Thanks you! 😊

**Comment by phatmandrake** [comment]
I don't think the `-UseUPN` switch is necessary if the documentation is clear that for the time being that you need the NetBIOS name. UPN is definitely more intuitive though.

For `-b` It might be more intuitive to just use the term "searchbase" since that's the standard and would increase discoverability. People know that searchbase means a DN to an OU. There's no ambiguity there.

**Comment by Badgerati** [comment]
Added a `-SearchBase` onto `Add-PodeAuthWindowsAd`, and fleshed out the Windows AD docs to better mention the `-Domain` should be the NetBIOS.

For searchbase, if you set it to say `OU=CustomUsers`, internally that becomes something like `OU=CustomUsers,DC=test,DC=example,DC=com`.

**Comment by phatmandrake** [comment]
It might be more clear if you can supply the Full DN rather than the relative DN, I've seen other systems use relative DN for this so it's not unheard of, but you could make the behavior be if a search base is manually specified take the whole DN. 

This would simplify documentation.

**Comment by Badgerati** [comment]
Tweaked it so that `-SearchBase` should be the full DN.
