### ISSUE TITLE
Windows AD Authenticaton with Groups failing

### ISSUE THREAD

**Issue by phatmandrake** [Badgerati/Pode#795]
### Describe the Bug

WindowsAD auth from a server using `ldapsearch` for binding fails when valid groups are set as values in `Add-PodeAuthWindowsAd`

### Steps To Reproduce

Using `Add-PodeAuthWindowsAd` set groups restrictions and a user account will not validate against it correctly. 

### Platform

**Pode Server**
 - OS: Centos8
 - Versions:
   - Pode: 2.4
   - PowerShell: 7.1
   
I have a Pull Request open with a fix related to text wrapping. https://github.com/Badgerati/Pode/pull/796

**Comment by Badgerati** [comment]
#796 merged.
