### ISSUE TITLE
General Performance

### ISSUE THREAD

**Issue by phatmandrake** [Badgerati/Pode#799]
### Question

I have a function that runs in 2 seconds when run directly on the server, and takes 6 seconds when the same function is initiated by a pode route. The route isn't being called multiple times it's just invoking the same function that would be invoked from command line. My understanding is that outside of the overhead for initiating the connection and returning the response, the function itself should run at the same speed, but it's happening at 1/3 the rate.

I can't really think of an explanation for this so I am wondering if anyone else might be able to help.

Function run via terminal = 2 Seconds
Function run by pode route = 6 seconds

(time stamping iterations of the loop)

**Comment by Badgerati** [comment]
Hey @phatmandrake,

You're right that it should be close-ish to the 2secs mark, plus a bit of connection overhead; though it also depends what the function is doing and any output/response being returned from the request. ie: large amount of data + json serialisation will add some overhead too.

Are you able to give an example of the function, and how you're using it in Pode?

**Comment by phatmandrake** [comment]
ugh it was a `sudo` I had in my code that was causing the delay. Not sure why this had such a significant affect when it was triggered by Pode specifically. Times are back down to what makes sense after removing sudo.
