### ISSUE TITLE
Schedule from file failures

### ISSUE THREAD

**Issue by tysimo** [Badgerati/Pode#806]
### Describe the Bug
Schedule from file fails after first successful run.

### Steps To Reproduce
1. Create a Pode schedule from file.
  Add-PodeSchedule -Name 'from-file' -Cron '@minutely' -FilePath './Schedules/File.ps1'
2. The first run will succeed as expected.  
3. Every subsequent run fails with below error. 

### Error
InvalidOperation: (:) [], RuntimeException
Message: You cannot call a method on a null-valued expression.
StackTrace: at Invoke-PodeInternalScheduleLogic, C:\Program Files\WindowsPowerShell\Modules\Pode\2.4.1\Private\Schedules.ps1: line 141
at Invoke-PodeInternalSchedule, C:\Program Files\WindowsPowerShell\Modules\Pode\2.4.1\Private\Schedules.ps1: line 102
at <ScriptBlock>, <No file>: line 30
at <ScriptBlock>, <No file>: line 23

### Expected Behavior
Schedule continues to run successfully on given internal after initial successfully run.  

### Platform
 - OS: Windows
 - Browser: Chrome
 - Versions:
   - Pode: Pode v2.4.1
   - PowerShell: 5.1.14393.4467

### Additional Context
Pode is installed as a windows service.

**Comment by tysimo** [comment]
It looks like I was able to resolve the issue by wrapping the code in the ./Schedules/File.ps1 file in brackets {}.

**Comment by Badgerati** [comment]
Hi @tysimo,

Yes, the file needs to return a scriptblock as [seen here](https://badgerati.github.io/Pode/Tutorials/Schedules/#script-from-file).

Glad you were able to resolve it! 😄
