### ISSUE TITLE
Query property of WebEvent string should be a Hashtable

### ISSUE THREAD

**Issue by phatmandrake** [Badgerati/Pode#809]
### Describe the Change

A few of the data types in the WebEvent object appear to be slightly wrong such as the Query property, which stores the query parameters as an `HttpQSCollection`. The documentation list it as a Hashtable and while it is a name/value collection it isn't of the Hashtable type and its values are not accessible using the property dereference operator, nor does it display it's values directly. So it doesn't really work in an expected manner.

I think the default behavior should be modified to convert the `HttpQSCollection` to a Hashtable so its behavior is more consistent with a typical powershell experience.
```powershell
$Hashtable = @{} ; $WebEvent.Request.QueryString | ForEach-Object { $Hashtable.add($_ ,$QuerString[$_]) } # Happy Hashtable 🎉
```

A change like this could break things for someone though.

**Comment by Badgerati** [comment]
Hey @phatmandrake,

Which property are you using?

The `$WebEvent.Query` property is converted to a HashTable, here 🤔 : https://github.com/Badgerati/Pode/blob/60cfe364ee0a4cd753ce462628fccf0faaa909f8/src/Private/Middleware.ps1#L302-L315 

Running `$WebEvent.Query.GetType()` from a Route also gives me:
```
IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Hashtable                                System.Object
```

**Comment by phatmandrake** [comment]
Well this is weird.

$WebEvent shows that query has values, but they were inaccesible:

![image](https://user-images.githubusercontent.com/24230425/130071165-5b6b25f2-d200-4560-b86a-06ca55b1db71.png)

So I restarted the server and now I'm finding that Query doesn't exist, only QueryString:

![image](https://user-images.githubusercontent.com/24230425/130072519-2a754cc0-1497-4984-8113-9bad8552b3c0.png)

Something is up I haven't gone spelunking yet.

**Comment by phatmandrake** [comment]
Doh I was looking at the `$Query.Request` nevermind 😅
