### ISSUE TITLE
Is there a way to stop the server programmatically?

### ISSUE THREAD

**Issue by phatmandrake** [Badgerati/Pode#813]
### Question

I am using Pode to listen on localhost for an OAuth response, but I haven't figured out how to store the response in a powershell session variable and stop Pode when it is received. Is that currently possible?

**Comment by Badgerati** [comment]
Ooo, so you want the response to be available in a variable to use outside of Pode, then close the server?

For closing Pode, there's [`Close-PodeServer`](https://badgerati.github.io/Pode/Functions/Core/Close-PodeServer/), call this from within the server itself - like a route, middleware, endware, etc. - and the server will terminate

**Comment by phatmandrake** [comment]
`Ooo, so you want the response to be available in a variable to use outside of Pode, then close the server?`

Yes Exactly! A special short lived server for an important use. If there were any easy way to integrate this into a powershell module then enabling OAuth based Authentication for Powershell modules would be made trivial.

Right now I'm using Flask to bridge the gap, there I am able to assign the request input from a route to a global variable.

**Comment by phatmandrake** [comment]
I'd support that :D

**Comment by Badgerati** [comment]
Those commits add a new `Out-PodeVariable`, which auto-creates variables when the server stops :)

used as: `Out-PodeVariable -Name 'VariableName' -Value <SomeValue>`
