### ISSUE TITLE
Order of API routes on swagger page

### ISSUE THREAD

**Issue by s-dobson** [Badgerati/Pode#814]
### Question
Not sure if this is a question, bug or I'm just missing something.

I have the following routes (as an example):
'/api/users/'
'/api/users/user/:userId'

In a basic setup using 'Enable-Pode-OpenApi' these stay in the above order. However when using a  "-RouteFilter '/api/*'" the order switches to:
'/api/users/user/:userId'
'/api/users/'

Obviously I would prefer the first example as the second route is a child of the first so this flows better and makes more sense to an end user.

I just wanted to see if I'm missing anything obvious, if this is intended or is a bug.

Thanks

**Comment by s-dobson** [comment]
Just as a follow up here is what I mean with screenshots.

Using `Enable-PodeOpenApi -Path '/docs/openapi' -Title 'Lorem ipsum API' -Version 0.0.0.1` 

![Screenshot-NoRouteFilter](https://user-images.githubusercontent.com/84972828/130800241-c91d00e5-731f-4095-923f-cc09ab593ce5.png)

Using `Enable-PodeOpenApi -Path '/docs/openapi' -Title 'Lorem ipsum API' -RouteFilter '/api/*' -Version 0.0.0.1`
![Screenshot-WithRouteFilter](https://user-images.githubusercontent.com/84972828/130800320-200fe2a0-13f4-4161-a34f-793bc965e829.png)

**Comment by Badgerati** [comment]
Hey @s-dobson,

I managed to reproduce the issue, and the changes in the above commit fixes the ordering so it's more consistent. Are you able to make the same couple of changes in the above commit to your Pode module locally and test?

Thanks :)

**Comment by Badgerati** [comment]
I've merged the fix for this as testing shows the correct order now, but if it's still occurring please feel free to re-open :)

**Comment by s-dobson** [comment]
Hey @Badgerati ,

Sorry about the delay getting back to you.

I've just tested this and its working on v2.4.2,.

Thanks 👍
