### ISSUE TITLE
OAuth - User, Access_Token and Refresh_Token with Google - some thoughts.

### ISSUE THREAD

**Issue by phatmandrake** [Badgerati/Pode#830]
### Question

So with Google the `refresh_token` is only returned if the `access_type` query parameter is set to `offline` in the `auth_uri`.  It doesn't look like it's possible to set additional vendor specific parameters to accomplish this. 

Being able to supply a hashtable to `New-PodeAuthScheme` with these optional parameters would be clutch, but I'm not seeing a means to accomplish this. Is it possible?

Something like `-AdditionalAuthURIParams @{access_type = "offline"}` that could just be appended to the URI since order doesn't matter.

Also is there a way to control the parsing of the value returned from the token URL? Google returns an id_token (JWS), that can be used to validate claims/identity without an extra call to the `userinfo_endpoint`, but it doesn't look like the auth_code response is accessible.

The OAuth auth scheme in Pode looks like it rigidly defines what values are passed to the validator `($User,$AccessToken,$RefreshToken)`, but there could be other information returned when the auth_code is exchanged. So if there were a way to get all information returned that would be great.

I'm gonna spelunk this a bit harder, but wanted to started a convo.

All these behaviors are defined under `Get-PodeAuthOAuth2Type`. 

P.S Thanks for making the best Powershell Module ever :D

**Comment by Badgerati** [comment]
Hey @phatmandrake,

Adding a couple parameters in for custom query parameters for `-AuthoriseUrl` and `-TokenUrl` should be simple enough. Have you got any links to the Google docs for the second part, with the id_token? Wouldn't mind a read myself to better understand 😃

**Comment by phatmandrake** [comment]
Right here: https://developers.google.com/identity/protocols/oauth2/openid-connect It's apart of the OpenID Connect spec I believe. Which is I supposed makes it slightly different that pure OAuth.

Here's a stackoverflow answer about it: https://stackoverflow.com/questions/32175174/is-it-possible-to-get-profile-information-in-an-id-token-from-google/32406589#32406589

**Comment by phatmandrake** [comment]
Not to overload this question, but I didn't wanna necessarily open another issue. Is it possible to access the $Webevent object before the OAuth redirect? Like if data is passed along in the initial request is it possible to access it? 

Say I wanted a client to send a symmetric key, or some other data to use, during the initial request before the OAuth redirect takes place, then Pode could then use that client-specific data after the callback is received. 

In my case I want to redirect the user-agent to a desktop application listening on localhost so that the desktop app can receive an access token, but I want to reasonably prevent a 3rd party app from being able to use the easily intercepted token.

**Comment by Badgerati** [comment]
To get to the `$WebEvent` before the authentication you could use middleware, but then it would run all the time even when authentication isn't needed. Sounds more like how `New-PodeAuthScheme` has a `-PostValidator` script, you need a `-Pre` script of some kind to run once before the scheme's actual logic 🤔 

Reading the code, OAuth looks like it should work as an InnerScheme for Custom, have you got an example of roughly how you've got that setup?

For `Move-PodeResponseUrl`, it's undocumented, but if you `return @{ IsRedirected = $true }` from `New-PodeScheme` or `Add-PodeAuth` after doing `Move-PodeResponseUrl` it'll work 😃

**Comment by phatmandrake** [comment]
A pre-validator is a good idea. I'll have to try and make an example for the OAuth as an innerscheme, but the error I was getting was that it wasn't creating the Auth_URI correctly, didn't dig into what exactly was missing other than the redirect_uri.

Oooooh that's what I like to hear. More testing to do yet thanks for the tip.

**Comment by phatmandrake** [comment]
Okay I figured out what it was, if you don't specify a `-RedirectUrl` OAuth2 as an `-innerscheme` fails. That `return @{ IsRedirected = $true }` worked great thanks!

Still really need the ability to specify a custom parameters for the Redirect though to really use the built-in stuff for my needs. Should also explore PKCE since that seems to be standard now for all flows 🤔.

**Comment by Badgerati** [comment]
I've just had a glance at PKCE, it seems pretty simple to implement. What I'll do it move PKCE to its own issue, as my aim is to get v2.5.0 this week and get some work on Pode.Web under way; this way if it takes a little longer than expected I'll do it for 2.6.0
