### ISSUE TITLE
Failure to export functions.

### ISSUE THREAD

**Issue by opustecnica** [Badgerati/Pode#846]
### Describe the Bug
When importing the Pode module, no functions are exported.  The behavior is consistent in both PowerShell 5.1 and Powershell 7.1.4 on Win32 systems. (Will test on LInux ASAP).

___Apologies in advance if the issue I am experiencing was documented previously and I failed in properly research past comments___

### Steps To Reproduce
1. Open Powershell or Pwsh console
2. Import-Module Pode -Force -Verbose 
3. Get-Module (OR)
4. Get-Command -Module Pode

### Expected Behavior
A list of the exported functions should be displayed rather than a $null.

### Platform
 - OS: Windows 10
 - Browser: Not relevant
 - Versions:
   - Pode: v2.4.0, 2.4.1, 2.4.2
   - PowerShell: pwsh 7.1.4 & powershell 5.1.19041.1237

### Additional Context
Workaround: Edit last line in .psm1 file from:
```Export-ModuleMember -Function ($funcs.Name)```
to:
```Export-ModuleMember -Function * # ($funcs.Name)```

While attempting to debug the issue, the psm1 file was renamed ps1 and the __Export-ModuleMember__ call commented out.  Dot-sourcing the file did not show any issue loading libraries and/or functions.  Moreover, the __$sysfuncs__ and __$funcs__ were properly populated.

**Comment by Badgerati** [comment]
Hey @opustecnica,

By Win32 do you mean Windows that's solely 32bit? I just tried on mine, Windows 10 but x64and also tried in x86 PowerShell, but in each the Functions were populated after import 🤔

**Comment by opustecnica** [comment]
@Badgerati,

for win32 I meant run-of-the-mill Intel/windows 10/64. I have used the modules on three other computers without issue. The puzzling thing is that the [string[]] is exactly what the export cmd let expects. I suppose it is something specific to the configuration of this particular computer … just can’t understand what :-).

**Comment by Badgerati** [comment]
I'm closing this issue, but if it's still causing problems please feel free to re-open 😃
