### ISSUE TITLE
PassThru

### ISSUE THREAD

**Issue by ericxin1982** [Badgerati/Pode#858]
### Question
A clear and concise description of your question.

I kept reading doc.
I am not sure how to use this switch, would you please give me some idea, sorry for this.

Thanks
Eric Xin

**Comment by Badgerati** [comment]
Hey @ericxin1982,

The two are independent of each other; `Write-PodeJsonResponse` lets you return JSON responses from `Add-PodeRoute`, and OpenAPI lets you define how to use your REST API and Routes via Swagger.

You would only really use OpenAPI if you want to support Swagger. If you don't need to, then you won't need to use any of the OpenAPI functions.

**Comment by ericxin1982** [comment]
@Badgerati 

Thanks for reply, I got it.
