### ISSUE TITLE
Issue using AWS.Tools and AWSPowerShell.NetCore modules

### ISSUE THREAD

**Issue by tomgrice** [Badgerati/Pode#861]
### Describe the Bug
Whenever I use Import-Module with AWS PowerShell modules, it throws an error:
`     | Exception calling "Open" with "0" argument(s): "Module AWS.Tools.Common version 4.1.15.0 failed importing.
     | AWS.Tools.Common version 4.1.15.0 is currently imported. Only a single version of a single variant of AWS Tools for
     | PowerShell (AWSPowerShell, AWSPowerShell.NetCore or AWS.Tools.Common) can be imported at any time."`

I think it is related to some code in the AWS module, [ImportGuard.ps1](https://www.powershellgallery.com/packages/AWS.Tools.Common/3.3.618.0/Content/ImportGuard.ps1) - preventing the module from being imported more than once, which Pode seems to be doing (something to do with being able to handle multiple requests at a time etc I'm guessing?) Long story short I am unable to interact with my AWS services through Pode.

Hoping there is a way to get round this?

### Steps To Reproduce
Here is an example of code which will throw the error - it will also continue to throw the error even when the server.ps1 file is edited and the Import-Module for AWS is removed, until the system is restarted.

```
Import-Module Pode
Import-Module AWS.Tools.Common
Import-Module AWS.Tools.EC2
Import-Module SimplySql

Start-PodeServer {

    Add-PodeEndpoint -Address * -Port 8086 -Protocol Http

    Add-PodeRoute -Method Get -Path '/ServerManager/startInstance/:ServerKey' -ScriptBlock {
        Write-PodeJsonResponse -Value @{ 'hello' = 'world'; }
    }

}
```

### Expected Behavior
Should be able to import the AWS.Tools.EC2 module and manage AWS services as normal.

### Platform
 - OS: Ubuntu 20.04 LTS
 - Versions:
   - Pode: v2.4.2
   - PowerShell Core: v7.1.5

**Comment by Badgerati** [comment]
Hey @tomgrice,

That's some crazy logic there AWS 😂 I usually stick to the aws/az cli tools, mostly for things like this!

What I think is happening though seems to stem from `AWS.Tools.EC2`; the `AWS.Tools.Common` module is set as a [required module](https://www.powershellgallery.com/packages/AWS.Tools.EC2/4.1.14.0/Content/AWS.Tools.EC2.psd1) for EC2 so is likely forcing PowerShell to re-import the Common module, triggering the error.

To get around this, you'll probably have to explicitly tell Pode which modules to import - rather than relying on Pode to auto-import everything from the current session.

You can see an example of it [here](https://badgerati.github.io/Pode/Tutorials/Scoping/#export), but in general you'll need to have the following in the `server.psd1` file:
```powershell
@{
    Server = @{
        AutoImport = @{
            Modules = @{
                Enable = $true
                ExportOnly = $true
            }
        }
    }
}
```

and then import your modules as normal (possibly minus the common module, and let EC2 deal with it), and then "export" the modules to tell Pode which to import:
```powershell
Import-Module AWS.Tools.EC2
Import-Module SimplySql

Start-PodeServer {
    Export-PodeModule AWS.Tools.EC2, SimplySql

    Add-PodeEndpoint -Address * -Port 8086 -Protocol Http

    Add-PodeRoute -Method Get -Path '/ServerManager/startInstance/:ServerKey' -ScriptBlock {
        Write-PodeJsonResponse -Value @{ 'hello' = 'world'; }
    }
}
```

If AWS starts throwing the errors again, try adding `Remove-Module AWS.*` at the top of the server.ps1.

Hope this helps 😃

**Comment by tomgrice** [comment]
Thanks so much for your response. In the end I did end up just using the AWS CLI instead. I will probably look at it again as the code isn't much to look at, even with trying to pretty it up with backticks etc. I will look at this again.

Thanks for your work on Pode by the way, I have been able to quite easily migrate my messy Lambda/AWS API Gateway function to a clean and elegant self-hosted way of deploying my cloud gaming instances. Will definitely be working on more in the future!

```
Import-Module Pode
Import-Module SimplySql

# create a server, and start listening on port 8086
Start-PodeServer {

    Add-PodeEndpoint -Address * -Port 8086 -Protocol Http

    Add-PodeRoute -Method Get -Path '/ServerManager/startInstance/:ServerKey' -ScriptBlock {
        Open-MySqlConnection -Server "ionobeam.com" -UserName "xxxxxxxxxx" -Password "xxxxxxxxx" -Database "xxxxxxxx"
        $ServerKey = $WebEvent.Parameters['ServerKey']
        $result = Invoke-SqlQuery -Query "SELECT * FROM instance_config WHERE ServerKey='$ServerKey'"

        $running_instances = (aws ec2 describe-instances `
        --filter Name=tag:Name,Values=$($result.InstanceName) Name=instance-state-name,Values=pending,running,shutting-down,stopping,stopped `
        | ConvertFrom-Json).Reservations.Instances


        $pending_snapshots = (aws ec2 describe-snapshots `
        --filter Name=tag:Name,Values=$($result.InstanceName) Name=state,Values=pending `
        | ConvertFrom-Json).Snapshots

        if ($running_instances.Count -gt 0) {
            Write-PodeTextResponse -Value "Instance is already running on IP: $($running_instances[0].PublicIpAddress)"
        } elseif ($pending_snapshots.Count -gt 0) {
            Write-PodeTextResponse -Value"Snapshot from previous instance is still pending."
        } else {
            $ami_imageid = (aws ec2 describe-images --filter Name=name,Values=tom-cloud | ConvertFrom-Json).Images[0].ImageId
            $user_data = $result | Select-Object -Property AdminPassword,ComputerName,DNSHost,DNSToken,InstanceName,Owner,TimeUpdated | ConvertTo-Json -Compress

            $newinstance = (aws ec2 run-instances `
            --launch-template LaunchTemplateName=trmg-cloud-1-template `
            --iam-instance-profile Name=CloudGamingInstanceRole `
            --image-id $ami_imageid `
            --user-data $user_data `
            --tag-specifications `
            "ResourceType=instance,Tags=[{Key=Name,Value=$($result.InstanceName)},{Key=SnapAndDelete,Value=True},{Key=CostId,Value=$($result.CostId)}]" `
            "ResourceType=volume,Tags=[{Key=Name,Value=$($result.InstanceName)},{Key=SnapAndDelete,Value=True},{Key=CostId,Value=$($result.CostId)}]" `
            --count 1 | ConvertFrom-Json).Instances

            aws ec2 wait instance-status-ok --instance-ids $newinstance[0].InstanceId
            Write-PodeTextResponse -Value "Instance created with IP: $($newinstance[0].PublicIpAddress)"
        }
    }

}
```

**Comment by pcgeek86** [comment]
@Badgerati I can confirm that your solution works fine.
