### ISSUE TITLE
Get the number active requests

### ISSUE THREAD

**Issue by mikaelkrief** [Badgerati/Pode#869]
On my company, we are using Pode for expose API, but for deliver new versions of the PowerShell code, we need to wait that there are no outstanding API request.

Does its possible to get the number of current request active ?

**Comment by Badgerati** [comment]
Hey @mikaelkrief,

It's not directly supported at the moment, and having some metrics functions for this is actually a good idea. I'll look into it, but it should be possible.

**Comment by mikaelkrief** [comment]
thank you

**Comment by mikaelkrief** [comment]
Hi @Badgerati 
Hi tested this method Get-PodeServerActiveRequestMetric it's working fine, but it's only for get the number of requests that is in queue or ready to be proceded.
Does it's possible to get the number of requests which are currently running ?

thanks

**Comment by Badgerati** [comment]
Hi @mikaelkrief,

I have a possible idea on how to implement this, so I'll have a look soon - just updating Pode.Web at the moment :)
