### ISSUE TITLE
ConvertFrom-PodeJwt expecting -secret to be System.Byte[]

### ISSUE THREAD

**Issue by scorbisiero** [Badgerati/Pode#877]
### Describe the Bug
ConvertFrom-PodeJwt expecting -secret to be System.Byte[]. As per the documentation (https://badgerati.github.io/Pode/Tutorials/Authentication/Methods/JWT/) you can run:
`ConvertFrom-PodeJwt -Token 'eyJ0eXAiOiJKV1QiLCJhbGciOiJoczI1NiJ9.eyJleHAiOjE2MjI1NTMyMTQsIm5hbWUiOiJKb2huIERvZSIsInN1YiI6IjEyMyJ9.LP-O8OKwix91a-SZwVK35gEClLZQmsORbW0un2Z4RkY' -Secret 'abc'`

However, the function requires a System.Byte[] instead:
https://github.com/Badgerati/Pode/blob/285df043ff6faa0a7df6faf07b1700b4feb654d2/src/Public/Authentication.ps1#L1569-L1571

It works when ran like this:
`ConvertFrom-PodeJwt -Token 'eyJ0eXAiOiJKV1QiLCJhbGciOiJoczI1NiJ9.eyJleHAiOjE2MjI1NTMyMTQsIm5hbWUiOiJKb2huIERvZSIsInN1YiI6IjEyMyJ9.LP-O8OKwix91a-SZwVK35gEClLZQmsORbW0un2Z4RkY' -Secret ([System.Text.Encoding]::UTF8.GetBytes('abc'))`

### Steps To Reproduce
1. Run `ConvertFrom-PodeJwt -Token 'eyJ0eXAiOiJKV1QiLCJhbGciOiJoczI1NiJ9.eyJleHAiOjE2MjI1NTMyMTQsIm5hbWUiOiJKb2huIERvZSIsInN1YiI6IjEyMyJ9.LP-O8OKwix91a-SZwVK35gEClLZQmsORbW0un2Z4RkY' -Secret 'abc'`

### Expected Behavior
Return the converted JWT as an object.

### Platform
 - OS: Any
 - Versions:
   - Pode: 2.5
   - PowerShell: 5.1/7.2

### Additional Context
It depends how you want to tackle this, you could implement an extra parameter called -SecretAsString and use a new ParameterSet for it, or accept anything for Secret and check whether it's a string or a byte[] in the function or, update the documentation to pass Secret as byte[].

**Comment by Badgerati** [comment]
😳 Oops!

I might do the second choice, and allow `-Secret` to be a byte[] or a string. I might do the same on `ConvertTo-PodeJwt` as well. At the moment they're both different types on `-Secret`, which is going to be confusing (it clearly caught me out 😂).
