### ISSUE TITLE
AllowClientCertificate doesn't work when hosting on IIS with certificate authentication enabled

### ISSUE THREAD

**Issue by MaxFalcone** [Badgerati/Pode#879]
### Describe the Bug
I have a Pode server hosted on IIS. Client certificate authentication is enabled on IIS and I tested that for IIS it work and requires correct certificate. But inside Pode there is no way to get the certificate client provided. I supposed that enabling `AllowClientCertificate` would help and I'd get access to `$WebEvent.Request.ClientCertificate` but instedad server can't even start.

### Steps To Reproduce
1. Host Pode server on IIS as described [here](https://badgerati.github.io/Pode/Hosting/IIS)
2. Setup IIS certificate auth as described [here](https://joji.me/en-us/blog/how-to-create-an-iis-website-that-requires-client-certificate-using-self-signed-certificates/)
3. Enable HTTPS on IIS (I used Let's Encrypt)
4. At this point server works well. It is on HTTPS and requires client certificate.
2. Enable `AllowClientCertificate`
3. Try open a page. It fails.
4. Check log for errors

### Code Sample
```
Add-PodeEndpoint -Address localhost -Port 8090 -Protocol HTTPS -AllowClientCertificate
New-PodeLoggingMethod -File -Path "C:\Temp\" -Name "request.pode.log" | Enable-PodeRequestLogging
New-PodeLoggingMethod -File -Path "C:\Temp\" -Name "error.pode.log" | Enable-PodeErrorLogging
New-PodeLoggingMethod -File -Path "C:\Temp\" -Name "Log.pode.log" | Add-PodeLogger -Name 'Log' -ScriptBlock { param($item) "$(Get-Date) $item" }

New-PodeAuthScheme -ClientCertificate | Add-PodeAuth -Name 'Login' -Sessionless -ScriptBlock {
	param($cert, $errors)
	return @{ User = @{ ID ='M0R7Y302' } }
}

# Healthcheck route
Add-PodeRoute -Method Get -Path '/awake' -Authentication 'Login' -ScriptBlock {
   $s = $WebEvent.Request.ClientCertificate | gm | Out-String
   Write-PodeTextResponse -Value $s -StatusCode 200
}
```

### Expected Behavior
Server should start and `$WebEvent.Request.ClientCertificate` should be populated with client certificate provided in request.

### Screenshots
Page opened in Firefox
![image](https://user-images.githubusercontent.com/72614595/145366504-47af8797-8e1f-45f9-a3c7-0248a7a1f83e.png)
Log says
![image](https://user-images.githubusercontent.com/72614595/145366686-7fed3b19-3ae3-48b1-9c3e-05bd8514645c.png)

### Platform
 - OS: Windows Server 2019
 - Browser: Firefox
 - Versions:
   - Pode: 2.5.0
   - PowerShell: 7

### Additional Context
I went a bit beyond that error and disabled the error popped in log because I do have `-Protocol` set to `HTTPS `, so error is misleading.
![image](https://user-images.githubusercontent.com/72614595/145367535-fa249d9e-c29e-4ed5-b699-7d44edde72db.png)
This allows server to start but `$WebEvent.Request.ClientCertificate` is still empty.
If I try to open the page Pode will return 401 as if there is no client certificate.
![image](https://user-images.githubusercontent.com/72614595/145369982-7b3e0ccc-456d-43ce-b907-d5e9ff62b5c6.png)

**Comment by MaxFalcone** [comment]
Well yes it's kind of makes sense. I didn't know about that restriction for out-of-process apps. So if you'd look at it that would be nice.
Even if the certificate is not available, the user is authenticated so there should be a way to get at least his name probably. But all other auth methods is disabled in the case on IIS, hence if I use `-IISAuth` it will also return 401.
So if certificate authentication is used when hosting on IIS there is now way to inedtify the user in Pode app. This is probably the general issue here.

**Comment by Badgerati** [comment]
Hi @MaxFalcone,

Looks like IIS passes the client certificate base64 encoded as headers to Pode 😃. The commit above includes extra logic, when the `-AllowClientCertificate` switch is passed, to attempt to retrieve the cert from the headers.

The code sample you have above should work with these changes. Would you be able to checkout that commit, build and test it locally? To build you'll need the InvokeBuild module, and run `Invoke-Build Build` at the root of the repo (it'll install other softwares like dotnet). Then in your scripts you'll need to `Import-Module` the `./src/Pode.psm1` directly.

I've tested it on my end, and the certificate is set on `$WebEvent.Request.ClientCertificate` now.

**Comment by MaxFalcone** [comment]
Sounds great! Will test it today or tomorrow.

**Comment by MaxFalcone** [comment]
Can't build it. Seems like I'm missing some prerequisites. It is a Windows Server 2019 with .Net5 installed. Powershell 7.2.
![image](https://user-images.githubusercontent.com/72614595/146911822-725d5329-0339-4266-8ba9-3700d53a58a1.png)

**Comment by Badgerati** [comment]
Hey @MaxFalcone,

That's bizarre 🤔, are you running it in PS7.2 or 5? Both should be enough for netstandard2 regardless; what's returned from `dotnet --version`?

I just tried 7.2 locally, and it builds - haven't tested building in 7.2 yet, just running. I'll have to try on a WS2019 server later.

I've attached a zip ([pode.zip](https://github.com/Badgerati/Pode/files/7755187/pode.zip)) of the commit compiled for you 😃

**Comment by MaxFalcone** [comment]
I've tried it from both Powershell 5 and pwsh 7.2. Same result.
Dotnet version in both is
```Powershell
PS C:\Temp\Pode> dotnet --version
5.0.404
```

Tried your build. It works as described!
I'm able to get the certificate from WebEvent.
Thanks!

**Comment by Badgerati** [comment]
Excellent! I'll get hat merged now then 😄 

I'll make a note to test building on WS2019 and investigate what it could be. I'm thinking it might be because only the dotnet runtime is installed, and not the SDK 🤔 

Thanks for testing!

**Comment by MaxFalcone** [comment]
One thing slipped my mind here. We've just forwarded client certificate to be able to access it from route code. But I think IIS does more than that, it actually maps certificate to a user in this setting here:
![image](https://user-images.githubusercontent.com/72614595/148779418-8522fe70-fa4d-446e-b519-348a6855a047.png)

Should this user name be available via `$WebEvent.Auth.User`? Right now it is `$null`.
Maybe it should work when `Add-PodeAuthIIS` is used.

**Comment by Badgerati** [comment]
Hi @MaxFalcone,

Are you able to add the following to one of your routes, and then inspect the log files (logs folder in your app's folder), what `MS-ASPNETCORE*` headers are present?

```powershell
Get-PodeHeader | Out-Default
```

That should output the `MS-ASPNETCORE-CLIENTCERT` header, but I'm wondering if they pass anything else. For Windows Auth they pass a token header as a reference to the user. If using `Add-PodeAuthIIS` is failing then this token won't be being set.

**Comment by Badgerati** [comment]
I've just tried this on my end, and there's nothing that could be used to identify the user passed from IIS to Pode.

We'll see if you get anything different, in case of setup differences.

**Comment by Badgerati** [comment]
I got pretty much the same headers as well, and couldn't find anything on the web about it. If IIS doesn't forward anything, there's a chance it might not be possible, and another mapping needs to be done in Pode auth 😕
