### ISSUE TITLE
Route matching

### ISSUE THREAD

**Issue by MaxFalcone** [Badgerati/Pode#905]
### Describe the Bug
I'm pretty confident that it was working befor.

If i have two routed defined
1. `/:first`
2. `/(:second)`

Then only first route will be hit with both of the requests `http://localhost:8090/param` and `http://localhost:8090/(param)`

### Steps To Reproduce
1. Have the routes defined as per code below
2. GET `http://localhost:8090/param` see response `first`
3. GET `http://localhost:8090/(param)` see the same response `first`

### Expected Behavior
Response for second request should be `second`

### Screenshots
![image](https://user-images.githubusercontent.com/72614595/149903489-b599a44e-ba3e-4ac3-bf0a-7fb9c1ef351d.png)
![image](https://user-images.githubusercontent.com/72614595/149913362-44a5cf54-3789-41ef-91e4-b175d967a7d3.png)

### Platform
 - OS: Windows Server 2019
 - Browser: Firefox
 - Versions:
   - Pode: 2.5.2
   - PowerShell: 7.2

### Sample code
```powershell
[cmdletbinding()]
param(
   [int] $port = 8090,
   [switch] $debugging
)

$PodeServerParams = @{"Quiet" = !$debugging; "DisableTermination" = !$debugging } # -DisableTermination is very important to run as a service

Start-PodeServer @PodeServerParams {
   Add-PodeEndpoint -Address localhost -Port $port -Protocol Http

Add-PodeRoute -Method Get -Path '/:first' -ScriptBlock {
   "first" | Write-PodeTextResponse -StatusCode 200
}

Add-PodeRoute -Method Get -Path '/(:second)' -ScriptBlock {
   "second" | Write-PodeTextResponse -StatusCode 200
}

}

```

**Comment by MaxFalcone** [comment]
I've made a few tests installing/reinstalling different versions of Pode and now it doesn't work anyhow. Looks like it depends on something random.

**Comment by Badgerati** [comment]
Hi @MaxFalcone,

The route chosen is the first one found that matches, usually the order is determined by the order the routes are created - though it does just do a `.Keys` on a hashtable, so can also depend on the hashtable's mood!

The code-block above I would expect to always match `:first`, though the image is a little strange as I would have thought `(:second)` should try to match first 🤔 

There could be something going on with regex under the hood, so I'll take a look later. Could probably do with changing the route hashtables to be `[ordered]` as well.

You would always need the `(:second)` to be created before the `:first` though, as the `:first` one would always match `(param)` before the second.

**Comment by Badgerati** [comment]
In typical fashion, I went to test and having the `:second` route created before the `:first` route worked 😂 

```powershell
Start-PodeServer {
    Add-PodeEndpoint -Address localhost -Port 8090 -Protocol Http

    Add-PodeRoute -Method Get -Path '/(:second)' -ScriptBlock {
        "second" | Write-PodeTextResponse -StatusCode 200
    }

    Add-PodeRoute -Method Get -Path '/:first' -ScriptBlock {
        "first" | Write-PodeTextResponse -StatusCode 200
    }
}
```

![image](https://user-images.githubusercontent.com/1483395/150020085-44c8de29-6fa9-4e30-805f-70dcec11208c.png)
(the first/first is when the order was first then second, then the second/first is when it was the code above)

Tried it in 5.1 and 7.2.1 🤔

**Comment by MaxFalcone** [comment]
That thing I can't understand either. It was working all the time up until two days ago. I performed tons of tests and my functionality was working. Now it hits wrong routes.

And you can see on my screenshot that I have second route before the first. It was the opposite all the time and was working. I had to change it yesterday for testing purposes because my first assumption was that maybe order of routes now matters.

Could you point out the place in the code where routes are matched? Maybe I could debug it...

**Comment by Badgerati** [comment]
Sure! The route finding logic you can find here: https://github.com/Badgerati/Pode/blob/f9d6548f2fc89c1ea1f34ae44819ae88cb1a04f8/src/Private/Routes.ps1#L26

mostly at this part: https://github.com/Badgerati/Pode/blob/f9d6548f2fc89c1ea1f34ae44819ae88cb1a04f8/src/Private/Routes.ps1#L73-L78

I'm also wondering what would happen if you changed the following: https://github.com/Badgerati/Pode/blob/f9d6548f2fc89c1ea1f34ae44819ae88cb1a04f8/src/Private/Context.ps1#L241-L254

to be:
```powershell
$ctx.Server.Routes = @{
    'delete'    = [ordered]@{}
    'get'       = [ordered]@{}
    'head'      = [ordered]@{}
    'merge'     = [ordered]@{}
    'options'   = [ordered]@{}
    'patch'     = [ordered]@{}
    'post'      = [ordered]@{}
    'put'       = [ordered]@{}
    'trace'     = [ordered]@{}
    'static'    = [ordered]@{}
    'signal'    = [ordered]@{}
    '*'         = [ordered]@{}
}
```

**Comment by MaxFalcone** [comment]
Well damn it. Today it's working again. Might happen because I reinstalled it again. But I did test it with ordered. Here is what i got.

Order of routes in the Server.ps1 in all steps will be `second` then `first`. So the general assumption that `second` should always be tried first to match.

I added the following output to `Routes.ps1`
```powershell
# match the path to routes on regex (first match only)
$_method.Keys | Write-Host #debug output
$valid = @(foreach ($key in $_method.Keys) {
    if ($Path -imatch "^$($key)$") {
        $key
        break
    }
})[0]
```

1. Initial state. Works as intended. See additional output. Order of routes matches the Server file. _Even though it wasn't yesterday._
![image](https://user-images.githubusercontent.com/72614595/150309551-d740f67a-050f-456a-9bea-d8957f394e4f.png)
2. Now change `second` route to `/a/(:second)`. Obviously `first` should be mathes in this case, but matching order shouldn't change. But it does. Even though in Server file routes are defined as `second` then `first`, they are matched in reverse order.
![image](https://user-images.githubusercontent.com/72614595/150309780-c112306e-50fa-4e90-b9bf-870c4092dea4.png)
3. Now change `Context.p1` to make routes ordered lists. Now the order of matching is preserved and according to Server file.
![image](https://user-images.githubusercontent.com/72614595/150310306-e64909fa-29cf-4844-9840-3fa661d7a9c9.png)

What's your opinion on this?

**Comment by Badgerati** [comment]
This matches what I'd expect. Because the lists currently aren't ordered, we're at the mercy of the key hashing a hashtable uses to "order" the keys. If you ran it enough times I bet eventually `/a/(:second)` will appear before `/:first` (though it could take a long time!).

To make sure the order of routes is always preserved in the order they're created, I'd say adding `[ordered]` is the way to go - to prevent unexpected occurrences like you've had.
