### ISSUE TITLE
auto restart does not work

### ISSUE THREAD

**Issue by ericxin1982** [Badgerati/Pode#920]
### Question
![image](https://user-images.githubusercontent.com/9047436/152500900-18aced88-c9f1-4fd8-b04d-12c9c6025a09.png)
![image](https://user-images.githubusercontent.com/9047436/152500927-c1623d45-287a-438d-9470-85d4d230ebb5.png)
![image](https://user-images.githubusercontent.com/9047436/152500948-b0a4967b-3e8a-4a07-926e-4b632e776172.png)
![image](https://user-images.githubusercontent.com/9047436/152500970-4ecf6397-8636-4577-8da1-2ccaf17037b6.png)
![image](https://user-images.githubusercontent.com/9047436/152501000-5e6f4662-a102-4418-8d8f-8ee61903baa6.png)

Hi,

I tried the auto restart, it seems does not work, what am I missing from the configuration?
What I changed is the number behind my name, I tried changing the rendering, it has not triggered the auto restart.

Thanks
Eric Xin

**Comment by ericxin1982** [comment]
works fine, I have to shut it down and start again.

**Comment by Badgerati** [comment]
Hi @ericxin1982,

Yes, this is expected. When Pode restarts automatically it's only an "internal" restart, and this restart just re-invokes the scriptblock that `Start-PodeServer` was initially given. Any changes in this scriptblock won't be recognised, however if you dot-source other files in the scriptblock then these will be re-dot sourced, and changes recognised.

**Comment by ericxin1982** [comment]
-Filepath './File.ps1'
Is it dot-source format?
Or what is the right way for the dot-source file you meant, thanks

**Comment by ericxin1982** [comment]
I really consider the stronger way to make sure I do not need to restart the code, I need the code can be hot reloaded, so need to understand better in the beginning. Thanks

**Comment by Badgerati** [comment]
Hi @ericxin1982,

You're correct, `-FilePath` on `Start-PodeSever` is recognised during a restart and will be re-imported. I just set the same as you above, and the server is restarted automatically when I change the file used for `-FilePath`, and the new code (number) is used:

![image](https://user-images.githubusercontent.com/1483395/152693865-eadeea4b-58d0-4279-90ad-d57706f5a2c3.png)

Which OS are you on, and which version of Pode and PowerShell are you using that exhibits the issue?

**Comment by ericxin1982** [comment]
Pode 2.5.2
Powershell 7.1.3
Windows10 1909
Your answer is fast and helpful, I think it is solved now.
Just double confirmed what you meant I understood right.
