### ISSUE TITLE
json serialization limitation

### ISSUE THREAD

**Issue by ericxin1982** [Badgerati/Pode#921]
### Question

![image](https://user-images.githubusercontent.com/9047436/152672231-6cf8d2d7-24ad-4598-86ca-6c88342c0aeb.png)
![image](https://user-images.githubusercontent.com/9047436/152672235-4e38f52f-5ddb-465e-b0a2-1a6c9281d281.png)

Hi,
If I rendering a object and met the json limitation, how to solve?

Thanks
Eric Xin

**Comment by ericxin1982** [comment]
write-byeresponse is Write-PodeJsonResponse

**Comment by ericxin1982** [comment]
![image](https://user-images.githubusercontent.com/9047436/152672410-c5e056e7-d564-4049-a696-0174b6525744.png)

**Comment by RobinBeismann** [comment]
You'll need to add the "-depth" parameter, however I'm not sure where the underlying limitations of ConvertTo-Json are.

**Comment by Badgerati** [comment]
Hi @ericxin1982,

As @RobinBeismann mentioned, the `-Depth` parameter on `Write-PodeJsonResponse` can control the depth of the JSON serialisation. As per `ConvertTo-Json` the max depth is 100 and the default is 2 - in Pode, `Write-PodeJsonResponse` sets this default to 10.

I wouldn't convert the whole `$WebEvent` to JSON, and just select the properties you're after. The `$WebEvent` contains references to the Context and the Listener, plus Sockets - the class depth gets quite large, as you can see by it displaying the warning even at a depth of 100. If you're after the properties available: you can see them [here](https://badgerati.github.io/Pode/Tutorials/WebEvent/#properties), or by using the following to see them on the CLI within a Route:

```powershell
$WebEvent | Get-Member | Out-Default
```

**Comment by ericxin1982** [comment]
Got it. Thanks
