### ISSUE TITLE
add-podeaccessrule in one individual file

### ISSUE THREAD

**Issue by ericxin1982** [Badgerati/Pode#923]
Add-PodeAccessRule -Access Deny -Type IP -Values @('127.0.0.1', '[::1]')

Hi,

I am reading doc, and I suddenly come up a question, if I want to keep add-podeaccessrule individually inside one file, how I should do it?

Thanks
Eric Xin

**Comment by Badgerati** [comment]
Hi @ericxin1982,

If you have some file, say `rule.ps1` in the same directory as your seever, with the content as:
```powershell
Add-PodeAccessRule -Access Deny -Type IP -Values @('127.0.0.1', '[::1]')
```

You can then dot-source the file in `Start-PodeServer`:
```powershell
Start-PodeServer {
    . ./rule.ps1
}
```

**Comment by ericxin1982** [comment]
That is great, I know this way, just don't know it works for pode or not.

**Comment by ericxin1982** [comment]
BTW
Use-PodeScript -Path './function.ps1'
and . ./xxx.ps1, what is the difference, or actually I also can use use-podescript this way, just understand pode better.

Thanks
Eric Xin

**Comment by ericxin1982** [comment]
ok, got it.
