### ISSUE TITLE
pode cors

### ISSUE THREAD

**Issue by ericxin1982** [Badgerati/Pode#924]
Hi,

Pode CORS,  should I do something for it, or it is supported by default?

Thanks
Eric Xin

**Comment by Badgerati** [comment]
Hi @ericxin1982,

By itself Pode doesn't do anything with CORS, and you'll need to use middleware and headers to configure CORS.

However, in v2.6.0 which I'm hoping to release soon this week, Pode will have helper functions to assist setting the CORS (and other security) headers: [docs here](https://github.com/Badgerati/Pode/blob/develop/docs/Tutorials/Middleware/Types/Security.md#cross-origin). Pode still won't do anything with CORS automatically, but this will help with setting them. If you use Pode.Web, this will be getting changes to set CORS automatically at some point.

**Comment by ericxin1982** [comment]
Thanks.
