### ISSUE TITLE
powershell for pode

### ISSUE THREAD

**Issue by ericxin1982** [Badgerati/Pode#925]
Sorry for the dump question:

I have built-in powershell 5 installed coming with windows10, and I have installed powershell 7.x for latest feature, and I want pode startup running through windows 7.x, what should I do?

Is there a good example I can follow?

Thanks
Eric Xin

**Comment by RobinBeismann** [comment]
It is as easy as specifying another binary you run your Pode instance with.
Windows Powershell is "powershell.exe" while Powershell 7 is "pwsh.exe".

If you want to execute it with Powershell 7 simply run `pwsh -File .\server.ps1`.

**Comment by ericxin1982** [comment]
Thanks
