### ISSUE TITLE
-Bearer -Scope, how to use scope

### ISSUE THREAD

**Issue by ericxin1982** [Badgerati/Pode#927]
![image](https://user-images.githubusercontent.com/9047436/152942915-33fba364-069e-4c4b-827c-c5bd1ae67f92.png)

Sorry for the dump question again, how to use the scope here?

Thanks
Eric Xin

**Comment by Badgerati** [comment]
Hi @ericxin1982,

Don't worry about it! :)

The `-Scope` on `New-PodeAuthScheme` is the scopes that are required to authenticate and use the API - in the above example, it expects valid users to have the `write` scope.

In the `Add-PodeAuth` scriptblock, the `Scope = 'read'` returned is an example of a user who's trying to authenticate; but they only have the `read` scope.

The Bearer authentication has an inbuilt scope validator, and if the required scopes aren't in the user's scope, then then authentication fails 😃

**Comment by ericxin1982** [comment]
Thanks.
