### ISSUE TITLE
user file, password field value, how to generate?

### ISSUE THREAD

**Issue by ericxin1982** [Badgerati/Pode#928]
![image](https://user-images.githubusercontent.com/9047436/152956048-f4ba1a70-6867-4603-b37f-fc9a76e7783d.png)

Hi,

I read this chapter, and as it stated, the users.json should be existed and data inside should be ready for authenticated, and how to generated each users' password, there is no mention in this chapter.

Thanks
Eric Xin

**Comment by Badgerati** [comment]
Hi @ericxin1982,

It comes down to personal preference on what tool you'd like to use to generate the SHA256s, but if you're opting for PowerShell:
```powershell
$password = 'Passw0rd'
$crypto = [System.Security.Cryptography.SHA256]::Create()
[System.Convert]::ToBase64String($crypto.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($password)))
```

or for HMAC SHA256:
```powershell
$password = 'Passw0rd'
$secret = [System.Text.Encoding]::UTF8.GetBytes('secret_salt')
$crypto = [System.Security.Cryptography.HMACSHA256]::new($secret)
[System.Convert]::ToBase64String($crypto.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($password)))
```

**Comment by ericxin1982** [comment]
Thanks!
