### ISSUE TITLE
service mode won't work after upgrade to 2.6

### ISSUE THREAD

**Issue by ericxin1982** [Badgerati/Pode#935]
Powershell 7.2.1
Pode 2.6

service mode won't work, it is starting and stopped, and repeating again, but it never running.

**Comment by ericxin1982** [comment]
I downgraded to 2.5.2, it works fine.

**Comment by ericxin1982** [comment]
Is there any way I can hardcode the response header to accept CORS first, since 2.6 I have tried, and it has bug I roll back to 2.5.2 and add response header to accept CORS to continue my trial?

Thanks
Eric Xin

**Comment by pcgeek86** [comment]
I think you're interested in the "pre-flight" OPTION request that's made by the browser. Have you tried adding an OPTION route on your Pode server, and append the CORS header there, as a Middleware?

Browser pre-flight check: https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request

Middleware: https://pode.readthedocs.io/en/latest/Tutorials/Middleware/Overview/

**Comment by Badgerati** [comment]
Hi @ericxin1982,

As @pcgeek86 points out, in v2.5.2 you'll have to use a combo of an OPTION route with global middleware in Pode.

For you issue with v2.6.0, when you say service mode, are you talking about Windows Services? I've just tested myself and the service starts and runs ok 🤔 If it's another type of service, have you got a sample script that causes the issue, as well as the type of service and how you're configuring it?

You can also send error logs to a file using:
```powershell
New-PodeLoggingMethod -File -Name 'errors' -Path '/some/path/logs' | Enable-PodeErrorLogging
```

Or if that doesn't show anything, then you might have to wrap the whole `Start-PodeServer` in `try {} cacth {}`:
```powershell
try {
    Start-PodeServer {
        # logic
    }
}
catch {
    $_.Exception.Message | Out-File -Path '/some/path/file.log' -Append
    $_.Exception.StackTrace | Out-File -Path '/some/path/file.log' -Append
    $_.ScriptStackTrace | Out-File -Path '/some/path/file.log' -Append
}
```

If those have any errors, that'd be great to see :)

**Comment by ericxin1982** [comment]
My bad.
I found the reason is I use pwsh to install new module, but where it locates is not in PSmodulepath varaible, and I used to install Pode2.3 before, so the error is 2.3 does not recognize the new cmdlet like set-podesecurity, so I re-installed the pode in powershell and run pode script through pwsh again, it works.

**Comment by ericxin1982** [comment]
Thanks for debug instruction.
