### ISSUE TITLE
converto-podejwt -secret is not optional

### ISSUE THREAD

**Issue by ericxin1982** [Badgerati/Pode#936]
![image](https://user-images.githubusercontent.com/9047436/153551052-7fe5bf95-e1d5-4995-810f-d72d14fd4233.png)

As I tried, this command, -secret is not optional, it is a must parameter.

Thanks
Eric Xin

**Comment by Badgerati** [comment]
Hi @ericxin1982,

When the Header `alg` property is set to `hs256`, this requires a secret to be supplied for an HMAC SHA256 signed signature. For no secret/signature, then an `alg` of `none` will work:

```powershell
$header = @{
    alg = 'none'
    typ = 'JWT'
}
```

**Comment by ericxin1982** [comment]
ah, got it, thanks so much!
