### ISSUE TITLE
[Doc Bug] Broken link to Restart-PodeServer in Pode docs

### ISSUE THREAD

**Issue by pcgeek86** [Badgerati/Pode#937]
### Describe the Change

The link to `Restart-PodeServer` is broken on this page.

https://pode.readthedocs.io/en/latest/Tutorials/Restarting/Overview/

Actually, the link is not really "broken" per se, but the page for `Restart-PodeServer` renders very oddly and is unusable.

https://pode.readthedocs.io/en/latest/Functions/Core/Restart-PodeServer

![Screen Shot 2022-02-11 at 10 41 28 AM](https://user-images.githubusercontent.com/466713/153641582-42c9063b-873c-45d3-bbb4-c5f96aab9db6.png)

**Comment by Badgerati** [comment]
hey @pcgeek86,

As the message on the page says, the docs are properly hosted at https://badgerati.github.io/Pode/ where all the Function URLs work :)

I wasn't aware the readthedocs ones existed until a couple months back. I've had an idea to make the Function URLs work there, which I might try for 2.6.1, but I still official host the docs on GitHub's pages.

**Comment by pcgeek86** [comment]
Cool, sorry for the noise. When I Google for Pode docs, RTD usually comes up first, so that's why I kinda expected it to "just work." Not a priority at all though. Maybe better to just remove it from RTD altogether?
