### ISSUE TITLE
Load my own ps1 and pode said function is not recognized, why?

### ISSUE THREAD

**Issue by ericxin1982** [Badgerati/Pode#938]
![image](https://user-images.githubusercontent.com/9047436/153702323-d797825c-352b-42e0-bdf7-1c704ea6b161.png)
![image](https://user-images.githubusercontent.com/9047436/153702344-b6fad35f-0ae4-4769-848e-49e29e540244.png)
![image](https://user-images.githubusercontent.com/9047436/153702351-b0f5a9ab-a80a-49bf-8bd1-0a8d3c391949.png)
![image](https://user-images.githubusercontent.com/9047436/153702383-1c7a931d-b2e3-4bc8-918b-1132843ff3a8.png)

Why it is like this?

But something I copied from your instruction, it does run ok, it is more puzzled.
![image](https://user-images.githubusercontent.com/9047436/153702434-9f38fceb-2a1d-4dbf-b244-4699d2d1550b.png)
![image](https://user-images.githubusercontent.com/9047436/153702440-d9193026-b477-4573-982e-d47ada4cf059.png)

What should I do?
Thanks
Eric Xin

**Comment by ericxin1982** [comment]
Hi @Badgerati ,

![image](https://user-images.githubusercontent.com/9047436/153702862-63709bf8-754a-460e-b7f9-6df6425fa926.png)
I found it work like this, is it right?
I need to create a global db connection and I can reuse this db connection for each route, would you please share me the proper way to do it?

Thanks
Eric Xin

**Comment by ericxin1982** [comment]
![image](https://user-images.githubusercontent.com/9047436/153711933-9e83c92a-e528-4e04-837c-2bd2ae16dd50.png)
What I meant is this does not work, not sure why.

**Comment by ericxin1982** [comment]
I also tried this.
![image](https://user-images.githubusercontent.com/9047436/153738757-afac133b-6fc7-4f8a-9325-7000f3b59399.png)
![image](https://user-images.githubusercontent.com/9047436/153738766-eead181e-7b17-4f38-b62d-59f245861dbe.png)
![image](https://user-images.githubusercontent.com/9047436/153738774-aa527987-c20b-4cdb-b42d-1776bcf079af.png)


I still got nothing.

Thanks
Eric Xin

**Comment by ericxin1982** [comment]
![image](https://user-images.githubusercontent.com/9047436/153745548-e24f0276-9e1e-4053-a37d-c92fff41f31e.png)
I used the import-module in the beginning, and use the function inside event, it works fine, so I used the function further inside specific route,  like this:
![image](https://user-images.githubusercontent.com/9047436/153745575-a577ba23-1f76-477e-8ac6-77672804dc14.png)
It does not work.
So I imported two module again inside the specific route, then it works?
![image](https://user-images.githubusercontent.com/9047436/153745594-781d0372-81bc-4f5f-b160-b80de4ca9ca3.png)

Why it is like that?
We cannot import module once, and it can be used globally inside the same project?

Thanks
Eric Xin

**Comment by ericxin1982** [comment]
I also tried this way, it does not work also.
![image](https://user-images.githubusercontent.com/9047436/153746205-77407ecf-0f47-439b-a504-a83dd6a8362e.png)

**Comment by ericxin1982** [comment]
![image](https://user-images.githubusercontent.com/9047436/153746429-fae6617f-a42b-4127-83db-df8a63b95131.png)

**Comment by Badgerati** [comment]
Hi @ericxin1982,

You can find a description of scoping in Pode [here](https://badgerati.github.io/Pode/Tutorials/Scoping/). The Events will work, as they run in the main parent scope - where as Routes/Auth/Middleware/etc all run in separate runspaces.

Pode does automatically import modules found in the parent scope, into each runspace's scope.

However. This won't occur if there are certain settings defined to stop Pode from automatically doing this. Do you have a `server.psd1` file? If so, check the `AutoImport` section, the `Enabled` should be true, and `ExportOnly` should be false (unless you need it to be true, in which case you'll need to use `Export-PodeModule` after importing, so Pode knows to only import specific modules).

**Comment by ericxin1982** [comment]
Got it, thanks.
