### ISSUE TITLE
 server.psd1 all option list

### ISSUE THREAD

**Issue by ericxin1982** [Badgerati/Pode#940]
Hi @Badgerati 

Is there a link I can read for all server.psd1 option, so I can review and see whether I should add them totally in the beginning, right now which shows up in different chapter, and I would go through different pages for different server option, it is a bit messy for long term learning.

Thanks
Eric Xin

**Comment by Badgerati** [comment]
Hi @ericxin1982,

There isn't, but I like the idea!
