### ISSUE TITLE
oauth2 and sessionless

### ISSUE THREAD

**Issue by ericxin1982** [Badgerati/Pode#944]
https://github.com/Badgerati/Pode/blob/develop/examples/web-auth-oauth2.ps1

Hi @Badgerati 

I used to ask you I would have a form/basic login to return a JWT or API KEY, something.
I read oauth2, it is much better than form/basic or windows AD.
And I am wondering why the sessionmiddleware must exist, can I use oauth2 without sessionmiddleware.

Since I prefer to develop SPA application, and once I login successfully, I would just need JWT or API Key for REST API resource.

Thanks.
Eric Xin

**Comment by ericxin1982** [comment]
![image](https://user-images.githubusercontent.com/9047436/154411383-32d5c717-9372-42c0-a606-0c4a2b276233.png)
By the way, if I need the refresh token, and the access token, can I put them into $webevent, auth this object, if yes, how I can extend this auth object properly?

Thanks
Eric Xin

**Comment by Badgerati** [comment]
Hi @ericxin1982,

You can use OAuth2 without the session middleware and pass `-Sessionless` to `Add-PodeAuth`. 

The best way to add access/refresh token would be to bundle them with the User object:
```powershell
param($user, $accessToken, $refreshToken)
return @{
    User = @{
        <# needed properties from $user #>
        Tokens = @{
            Access = $accessToken
            Refresh = $refreshToken
        }
    }
}
```

Or, if you only need the tokens, then just:
```powershell
param($user, $accessToken, $refreshToken)
return @{
    User = @{
        Tokens = @{
            Access = $accessToken
            Refresh = $refreshToken
        }
    }
}
```

**Comment by ericxin1982** [comment]
Thanks so much!

**Comment by ericxin1982** [comment]
Sorry to ask this question thread further:

-login and -logout these two switches, which are all serving for session middleware right? If I am using sessionless switch, then I do not need to use -login and -logout switch for form user/passwd authentication webpage.

![image](https://user-images.githubusercontent.com/9047436/154601012-31d9b385-b9d4-4fe6-ae3b-38e079dd9907.png)

**Comment by Badgerati** [comment]
Hi @ericxin1982,

Yes that's correct, those switches are specifically for sessions and easier Login pages/Logout buttons with routes. In this case, you won't need either, nor a logout route.
