### ISSUE TITLE
The function Set-PodeSecurityAccessControl doesn't work 

### ISSUE THREAD

**Issue by Landris18** [Badgerati/Pode#950]
I tried to use Set-PodeSecurityAccessControl  but it doesn't work, not recognized.

**Comment by Badgerati** [comment]
Hi @Landris18,

Which version of Pode are you using? The security functions were released with v2.6.0.

If you're on v2.6.0, have you got a sample script that throws the error?

**Comment by Landris18** [comment]
hi @Badgerati 

How to know the version of pode i'm using ??
This error happens when I try to use this line: 

`Set-PodeSecurityAccessControl -Origin '*' -Methods '*' -Headers '*' -Duration 7200`

**Comment by RobinBeismann** [comment]
Hi @Landris18,

could you post the actual error message? Without the error message we can only guess the cause.

However as @Badgerati already mentioned it is probably not the v2.6.0 that you're using.

**Comment by Landris18** [comment]
hi @RobinBeismann 

The problem was i'm currently using pode 2.5.0, i've just upgraded and it works fine now.

But i'm facing other problem about Cors from the request of a client

Thanks

**Comment by RobinBeismann** [comment]
It would probably be good if you close this issue and raise a new one with the actual CORS error you're facing.

**Comment by Landris18** [comment]
@RobinBeismann 

Yeah, thanks , i'll open à New issue
