### ISSUE TITLE
CORS problem when request from web app

### ISSUE THREAD

**Issue by Landris18** [Badgerati/Pode#953]
### Describe the Bug

I use pode as a backend api, and angular as the client.

But i'm facing a problem.

### Steps To Reproduce

1. On my pode api i set this :   ` Set-PodeSecurityAccessControl -Origin '*' -Methods '*' -Headers '*' -Duration 7200`

2. On my angular app i send this request : `return this.http.post("http://192.168.28.88:6010/api"+ '/login', user);`

3. But i got this error on my browser: `Access to XMLHttpRequest at 'http://192.168.88.28:6010/api/login' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.`

### Expected Behavior

I want to have no CORS problem after setting: ` Set-PodeSecurityAccessControl -Origin '*' -Methods '*' -Headers '*' -Duration 7200`

Is my way of using  ` Set-PodeSecurityAccessControl` is wrong or should I use other pode cmdlet to resolve this ??

### Platform
 - OS: winserver 2012 r2
 - Browser: opera 
 - Versions:
   - Pode: 2.6.1
   - PowerShell: 5.1

### Additional Context

I know the problem is from the backend and not from the web app because when I try with another backend api like django or flask it works fine with no problem.

Thanks for your helps, and sorry for my bad english.

**Comment by Badgerati** [comment]
Hi @Landris18,

I think I may have found the issue; since the request you're making looks like it might contain an Authorization header, the browser it likely making an OPTIONS preflight call.

If you add the following route to accept OPTIONS on all paths, does this allow the calls to work?
```powershell
Add-PodeRoute -Method Options -Path * -ScriptBlock {
    Set-PodeResponseStatus -Code 200
}
```

Hope that helps :)

**Comment by Landris18** [comment]
Hi @Badgerati 

Sorry but this trick doesn't work. The same problem persist and I still don't know what to do.

Thanks

**Comment by Landris18** [comment]
Hi @Badgerati, 

I found the solution : 

This : 

`Add-PodeMiddleware -name 'Headers' -ScriptBlock{`
     `Add-PodeHeader -Name "Acces-Control-Allow-Origin" -Value "*" `
     `Add-PodeHeader -Name "Acces-Control-Allow-Methods" -Value "*" `
    ` Add-PodeHeader -Name "Acces-Control-Allow-Headers" -Value "*" `
`}`

Plus this (your solution):

`Add-PodeRoute -Method Options -Path * -ScriptBlock {`
          `Set-PodeResponseStatus -Code 200`
`}`

I works fine now, thank you very much @Badgerati
