### ISSUE TITLE
Issue with "$using:" vars after upgrade to 2.6.2

### ISSUE THREAD

**Issue by dillardd** [Badgerati/Pode#955]
### Question
After an upgrade to 2.6.2, which I am not sure caused the issue, I am getting an error when trying to get values from $using: vars.

The issue is inside of the function ConvertTo-PodeUsingVariables:2488 and happens because $varName is null.

Code Section:
```powershell
foreach ($usingVar in $UsingVariables) {
        # var name
        $varName = $usingVar.SubExpression.VariablePath.UserPath

        # only retrieve value if new var
       # this is where my issue happens
        if (!$mapped.ContainsKey($varName)) {
            # get value, or get __using_ value for child scripts
            $value = $PSSession.PSVariable.Get($varName)
            if ([string]::IsNullOrEmpty($value)) {
                $value = $PSSession.PSVariable.Get("__using_$($varName)")
            }

            if ([string]::IsNullOrEmpty($value)) {
                throw "Value for `$using:$($varName) could not be found"
            }

            # add to mapped
            $mapped[$varName] = @{
                OldName = $usingVar.SubExpression.Extent.Text
                NewName = "__using_$($varName)"
                NewNameWithDollar = "`$__using_$($varName)"
                SubExpressions = @()
                Value = $value.Value
            }
        }

        # add the vars sub-expression for replacing later
        $mapped[$varName].SubExpressions += $usingVar.SubExpression
    }
```

I have attached a clixml file with the contents of `$usingVar` at this point right before the error is thrown, as well as the error object.

[pode-usingvar-issue.zip](https://github.com/Badgerati/Pode/files/8391941/pode-usingvar-issue.zip)

From what I can tell, this key (`$usingVar.SubExpression.VariablePath`) doesn't exist in the `$usingVar` object. 

Hopefully you can help me to understand better what is going on.

Please let me know if I can provide any additional info.

Thanks!

**Comment by Badgerati** [comment]
Hi @dillardd,

Thanks for the clixml! I think I can see what's causing the issue, but just to be sure, are you able to give an example snippet of your script with a `$using:` that throws the error?

Also, what version of PowerShell and which OS are you on?

**Comment by dillardd** [comment]
@Badgerati,

Thank you for the quick response!!

Operating System: Windows 11

```powershell
$PSVersionTable

Name                                     Value
----                                         -----
PSVersion                               7.2.2
PSEdition                                Core
GitCommitId                           7.2.2
OS                                            Microsoft Windows 10.0.22000
Platform                                   Win32NT
PSCompatibleVersions             {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion    2.3
SerializationVersion                  1.1.0.1
WSManStackVersion                 3.0
```

Here is the contents (modified to remove identifying info) of the file loaded be the `-FilePath` parameter when I call the `Add-PodeRoute` function:

```powershell
{
    function Get-RouteDataFromSql {
        param (
            # Sql Parameters
            [Parameter(Mandatory)]
            [object]
            $SqlParams,
            
            # Fields
            [Parameter()]
            [ValidateSet('Field','Field2','Field3')]
            [string[]]
            $Fields = @('Field1','Field2')
        )
        $query = "SELECT $($fields -join ',') FROM TableName"
    
        Invoke-Sqlcmd @SqlParams -Query $query | Select-Object -Property $Fields
    }

    Try {
        $result = If ($WebEvent.Data.fields) {
            Get-RouteDataFromSql -SqlParams $using:params.cams.ro -Fields @($WebEvent.Data.fields)
        } Else { Get-RouteDataFromSql -SqlParams $using:params.cams.ro }
    
        Write-PodeJsonResponse -Value $result
    }
    Catch {
    
        Write-PodeJsonResponse -Value @{'error'=$_.Exception.Message}
    
    }
}
```

The `$using:` var that I am referencing  (`$using:params.cams.ro) has a structure like this:

```powershell
@{

    cams = @{

        ro = @{

            ServerInstance = 'servername'
            Database = 'databasename'
            Credential = New-Object System.Management.Automation.PSCredential(
                'username',
                $($env:CRED_CAMS_RO | ConvertTo-SecureString -AsPlainText)
            )

        }

    }

}
```

**Comment by Badgerati** [comment]
Hi @dillardd,

Try with `($using:params).cams.ro` and that should work. The Ast is detecting the whole `$using:params.cams.ro` as being one part, rather than `$using.params` and `.cams.ro` as two separate parts.

I think I can see a possible extension to the logic to make `$using:params.cams.ro` work - which is more obvious than `($using:params).cams.ro`! 😂 

Hope that helps :)

**Comment by dillardd** [comment]
Thank you @Badgerati that absolutely worked!!

I'm not sure if it is something that needs changed, I think if I remember right other functions that implement a scriptblock and support `$using:` parameters might also behave in the same way. Might have been more of a bad assumption on my part to think it would work when feeding it properties like I did. 

I do agree that it seems more obvious to be able to specify them similarly to how you would if you were just using (no pun intended) the variables in a normal fashion.

Appreciate the quick reply and all the help you have given me!
