### ISSUE TITLE
Calling top level functions from other top level functions drop parameters

### ISSUE THREAD

**Issue by jamesgecargo** [Badgerati/Pode#956]
### Describe the Bug
When using Pode from a file, with a route which calls a top level function from the same file, calls from that top level function to other top level functions appear to lose some/all of the parameters but the call succeeds otherwise.

### Steps To Reproduce
1. Run Test.ps1 from [Test.zip](https://github.com/Badgerati/Pode/files/8393182/Test.zip)
2. Execute a web request to each endpoint and view the response: `(iwr http://localhost:8080/test1).Content` and `(iwr http://localhost:8080/test2).Content`.

### Expected Behavior
I would expect to see the same response from both requests, i.e. `{"Third":"And one more","First":"This is the first parameter","Second":"This is the second parameter"}`

What actually happens is the first route executes successfully with a 200 response, but the response shows null values from the function parameters: `{"Third":null,"First":null,"Second":null}`

### Platform
 - OS: both Windows 11 and Ubuntu 20.04.4 LTS
 - Browser: n/a
 - Versions:
   - Pode 2.6.2
   - PowerShell:  5.1.22000.282 on Windows 11, PowerShell Core 7.2.2 on Ubuntu 20.04.4 LTS

**Comment by Badgerati** [comment]
Hi @jamesgecargo,

This could be a quirk of PowerShell, though I'll dig through the Pode's code, just to make sure defining parameters inline aren't been dropped somewhere.

If I change `SomeOtherFunctionWithParameters1` to the below, and use a `param` block instead, it works for me:

```powershell
function SomeOtherFunctionWithParameters1
{
    param($First, $Second, $Third)
    @{ First= $First; Second = $Second; Third = $Third }
}
```

Do you get the same?

**Comment by jamesgecargo** [comment]
Hi @Badgerati, thanks for your response. 

If I include an explicit `param` block with the parameters in it, it does indeed work. I always thought those two styles were equivalent but perhaps internally that is not the case.

If you could point me in the right direction I'm happy to (try) dig into to the code myself.

**Comment by Badgerati** [comment]
Sure! :)

From quickly scanning the code I think it could be in this function:
https://github.com/Badgerati/Pode/blob/be795716cc14f51bd9379333cfb2df3bc157543f/src/Private/Helpers.ps1#L2669

Or possibly more specifically, this one:
https://github.com/Badgerati/Pode/blob/be795716cc14f51bd9379333cfb2df3bc157543f/src/Private/Helpers.ps1#L2640

In the latter it builds hashtable with just the function Name and Body (scriptblock). I'm wondering if the inline parameters are in a different property. This would make sense as to why the explicit param block works, as it's a part of the Body property - being within the scriptblock - where as inline ones aren't.

If that is the case, as to how to fix it I'm not sure. It could be that we need to prepend an explicit param block onto the Body, built using the inline ones 🤔 (similar to how Pode's `.pode.` files work), or tweak the properties from the created `[System.Management.Automation.Runspaces.SessionStateFunctionEntry]` from where `Get-PodeFunctionsFromScriptBlock` is called.
