### ISSUE TITLE
Open Api Request Parameter Enumeration question.

### ISSUE THREAD

**Issue by dillardd** [Badgerati/Pode#957]
### Question
I am looking to be able to enumerate the valid values for a request parameter, and would hope that I can get that to show the available values on the openapi spec. In my case the parameter is called 'fields' and I have a list of field names. I want to be able to show those field names on my Open API documentation so that a user of the API knows what fields are available.

I see that there is a parameter for the Function `New-PodeOAStringProperty` called `-Enum`, and it looks like you would be able to pass it an array of string values, like shown here:

https://badgerati.github.io/Pode/Tutorials/OpenAPI/#:~:text=%23%20a%20string%20with%20a%20default%20value%2C%20and%20enum%20of%20options%0ANew%2DPodeOAStringProperty%20%2DName%20%27type%27%20%2DDefault%20%27admin%27%20%2DEnum%20%40(%27admin%27%2C%20%27user%27)

But I am unable to get it to work out for me. A couple of extra details, I am splatting the parameters for `New-PodeOAStringProperty` and my abridged code looks like this:

```powershell
$propertyParams = @{    
    request = @{
        parameters = @(

            @{
                            name = 'fields' # parameter name as provided in path definition or request query/body
                            type = 'string' # 'string' or 'int' or 'number' or 'bool' or 'object' or 'schema'
                            enum = @('Field1','Field2','Field3','Field4')
                            required = $false # $true or $false (value required)
                            paramLocation = 'query' # either 'path' or 'query'. Query = Body, Path = Uri
             }

        )
    }
}

# set route open api request definition
    [array]$requestParameters = $Properties.request.parameters | Foreach-Object -Process {
        $propertyParams = @{
            Name = $_.name
            Required = $_.required
        }
        If ( $_.enum ) { $propertyParams.Add('Enum',@($_.enum)) }
        If ($_.type -eq 'string') {                 
                New-PodeOAStringProperty @propertyParams | 
                    ConvertTo-PodeOAParameter -In "$($_.paramLocation)"
        }
        ElseIf ($_.type -eq 'int') { 
            New-PodeOAIntProperty -Name @propertyParams | 
                ConvertTo-PodeOAParameter -In "$($_.paramLocation)"
        }
        ElseIf ($_.type -eq 'bool') { 
            New-PodeOABoolProperty -Name @propertyParams | 
                ConvertTo-PodeOAParameter -In "$($_.paramLocation)"
        }
        ElseIf ($_.type -eq 'number') { 
            New-PodeOANumberProperty -Name @propertyParams | 
                ConvertTo-PodeOAParameter -In "$($_.paramLocation)"
        }
        ElseIf ($_.type -eq 'object') { 
            New-PodeOAObjectProperty -Name @propertyParams | 
                ConvertTo-PodeOAParameter -In "$($_.paramLocation)"
        }
        ElseIf ($_.type -eq 'schema') { 
            New-PodeOASchemaProperty -Name @propertyParams | 
                ConvertTo-PodeOAParameter -In "$($_.paramLocation)"
        }
    }
    
    # $route represents the Pode Route Object
    $route | Set-PodeOARequest -Parameters $requestParameters
```

Is the `-Emun` parameter on `New-PodeOAStringProperty` meant to behave in the way I described above?

Or, even more of a possibility, am I just doing something slightly wrong?

Also, I know I have gone at this from a different way than described in the docs, but I didn't want to have all the `-Passthru` piped functions muddying up my code in my route definition file. Also I am implementing a method to auto-generate routes that I designed. I saw that their seems to be a way to do it based on functions, but I didn't think it met my requirements.

Thank you for your help as always @Badgerati !

**Comment by Badgerati** [comment]
From what I can see above it looks all right 🤔 I'll try and test on my side soon

**Comment by Badgerati** [comment]
Turns out it's a bug :)

Some properties were being dropped in `ConvertTo-PodeOAParameter`, the above commits fix that.
