### ISSUE TITLE
Write-PodeTextResponse silently fails if the -Value parameter is not specified

### ISSUE THREAD

**Issue by pcgeek86** [Badgerati/Pode#974]
### Describe the Bug

Write-PodeTextResponse silently fails if the -Value parameter is not specified.
Pode throws an HTTP error 500.

### Steps To Reproduce

```
Start-PodeServer -ScriptBlock {
 Add-PodeEndpoint -Address 0.0.0.0 -Protocol Http -Port 15002
 New-PodeLoggingMethod -Terminal | Enable-PodeRequestLogging
 Add-PodeRoute -Method Get -Path / -ScriptBlock { Write-PodeTextResponse 'Hello Pode' }
}
```

```
Invoke-WebRequest -Uri http://localhost:15002/
```

### Expected Behavior

If possible, Pode should reject the invalid route configuration, due to the missing parameter.
Errors from the runspace handling the HTTP request should be surfaced to the parent runspace.

### Platform
 - OS: Windows 11
 - Browser: n/a
 - Versions:
   - Pode: 2.5.2
   - PowerShell: 7.2.1

**Comment by Badgerati** [comment]
Hi @pcgeek86,

If you add `New-PodeLoggingMethod -Terminal | Enable-PodeErrorLogging` the error is shown on the terminal :)

Hooowever, it does highlight something that could be added though: if I add the `Position=0` property to the `-Value` parameter then `Write-PodeTextResponse 'Hello Pode'` works.
