### ISSUE TITLE
Subsequent HTTPS Requests Timeout with ClientCertificate AuthScheme

### ISSUE THREAD

**Issue by Viajaz** [Badgerati/Pode#977]
### Describe the Bug
Subsequent (2nd, 3rd etc.) HTTPS Requests Timeout when using a ClientCertificate-based AuthScheme after PodeServer start.

### Steps To Reproduce
**Server.ps1**
```powershell
#requires -Version 7.2
#requires -Modules Pode

Start-PodeServer -Threads 8 {
    New-PodeLoggingMethod -File -Name 'Pode_Requests' -Path "C:\ProgramData\Pode" -MaxDays 4 | Enable-PodeRequestLogging

    Add-PodeEndpoint -Address '10.123.123.123' -Port 443 -Protocol Https -CertificateName '*.example.com' -CertificateStoreLocation 'LocalMachine' -CertificateStoreName 'My' -Hostname 'api.example.com' -AllowClientCertificate

    New-PodeAuthScheme -ClientCertificate | Add-PodeAuth -Name 'CertLogin' -Sessionless -ScriptBlock {
        Param(
            $Certificate,
            $Errors
        )
        return @{
            User = 'test@pode'
        }
    }

    Add-PodeRoute -Method Get -Path '/api/v1.0/test' -Authentication 'CertLogin' -ScriptBlock {
        Write-PodeJsonResponse -Value @{
            Result = $true
            User = $WebEvent.Auth.User
        }
    }
}
```

**Server.psd1**
```powershell
@{
    Server = @{
        Ssl= @{
            Protocols = @('TLS12')
        }
    }
    Web = @{
        ErrorPages = @{
            ShowExceptions = $true
            Default = "application/json"
            StrictContentTyping = $true
        }
    }
}
```

**Test Case**
_Let `$Certificate` be a valid X509Certificate_
```powershell
$Response1 = Invoke-WebRequest -Uri 'https://api.example.com/api/v1.0/test' -Certificate $Certificate # This will work correctly
$Response2 = Invoke-WebRequest -Uri 'https://api.example.com/api/v1.0/test' -Certificate $Certificate # This will not get a response and time out
```
### Expected Behavior
All requests to be handled and responses given.

### Screenshots
N/A

### Platform
 - OS: Windows Server 2019 [10.0.17763]
 - Browser: WindowsPowerShell/5.1.19041.1645
 - Versions:
   - Pode: 2.6.2
   - PowerShell: 7.2.0 (Running Pode Server)

### Additional Context

- Valid Certificates issued by Trusted Certificate Authorities (by both Server and Client for all purposes) are used by the Server and the Client.
- Pode PowerShell Host is run as Windows Service, under SYSTEM context, using NSSM Wrapper.

**Comment by Badgerati** [comment]
Hi @Viajaz,

If you add the following line, do you get any errors outputted? (could take up to 10s to appear)
```powershell
New-PodeLoggingMethod -File -Name 'Pode_Errors' -Path "C:\ProgramData\Pode" -MaxDays 4 | Enable-PodeErrorLogging
```

Out of interest, if you change `-Threads` to 1 and do multiple responses do they all work? And if they do, and you set it back to 8, if you do 9 requests does the first work, then the next 7 fail, and the last one work?

Thanks!

**Comment by Viajaz** [comment]
- No Pode Errors Log are produced when enabled and code tested, nothing on stderr or relevant on stdout either.
- Changing Thread Pool to a single thread does not mitigate the issue.
- With a Thread Pool of N, performing N+1 requests sequentially will still result in only the first request being served.
That said, during one of the restarts of Pode, it started working fine across 8 threads with no explanation or change, it then stopped working shortly afterwards; confusing.
@Badgerati

**Comment by Viajaz** [comment]
@Badgerati 
I can't reproduce the issue when I use `Invoke-WebRequest` in a PowerShell 7.2 instance, the issue only seems to present itself on Windows PowerShell 5.1 when using `Invoke-WebRequest`, even during the same session of a Pode instance.

**Comment by Viajaz** [comment]
I tried using `mitmproxy` to inspect what was going on, the behaviour doesn't occur in PowerShell 5.1 when a local mitmproxy instance is specified via `Proxy` parameter to `Invoke-WebRequest`.

**Comment by Viajaz** [comment]
Neither restoring the SChannel configuration to default on the Windows Server instance nor removing Client Certificate authentication from the Pode Endpoint and Route has changed the behaviour...

**Comment by Badgerati** [comment]
Just had a thought, for the error logged try with Verbose and Debug enabled - be interesting to see if the request actually hits the Pode server, and/or where it's getting to:

```powershell
New-PodeLoggingMethod -File -Name 'Pode_Errors' -Path "C:\ProgramData\Pode" -MaxDays 4 | Enable-PodeErrorLogging -Level Error, Debug, Verbose
```

**Comment by Viajaz** [comment]
@Badgerati 
For some reason, I'm not getting any Pode_Errors log file generation with:
```powershell
New-PodeLoggingMethod -File -Name 'Pode_Errors' -Path "C:\ProgramData\Pode" -MaxDays 4 | Enable-PodeErrorLogging -Level Error, Debug, Verbose
```
I am getting Request log file generation though.

---

> Are you saying that with no Client Cert auth, AllowClientCert the endpoint, and route auth it still occurs? Are you still passing the client cert on the `Invoke-WebRequest` ?

When I remove all Client Certificate functionality from the Pode server:
**Server.ps1**
```powershell
#requires -Version 7.2
#requires -Modules Pode

Start-PodeServer -Threads 8 {
    New-PodeLoggingMethod -File -Name 'Pode_Requests' -Path "C:\ProgramData\Pode" -MaxDays 4 | Enable-PodeRequestLogging
    New-PodeLoggingMethod -File -Name 'Pode_Errors' -Path "C:\ProgramData\Pode" -MaxDays 4 | Enable-PodeErrorLogging -Level Error, Debug, Verbose

    Add-PodeEndpoint -Address '10.123.123.123' -Port 443 -Protocol Https -CertificateName '*.example.com' -CertificateStoreLocation 'LocalMachine' -CertificateStoreName 'My' -Hostname 'api.example.com'

    Add-PodeRoute -Method Get -Path '/api/v1.0/testnoauth' -ScriptBlock {
        Write-PodeJsonResponse -Value @{
            Result = $true
            User = $WebEvent.Auth.User
        }
    }
}
```

I still get issues with `Invoke-WebRequest`
```powershell
Invoke-WebRequest -Uri 'https://api.example.com/api/v1.0/testnoauth' -TimeoutSec 10
```

**Comment by Viajaz** [comment]
I got the logging working with the Pode Server instance without Client Certificate.

I did two requests with:
```powershell
Invoke-WebRequest -Uri 'https://api.example.com/api/v1.0/testnoauth' -TimeoutSec 20
```

-the first (`ffffffff-ffff-ffff-fffffffffffffffff`) succeeded and the second (`eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee` ) timed out.
```
Listening on the following 1 endpoint(s) [8 thread(s)]:
        - https://api.example.com:443/
[Verbose]: [ContextId: ffffffff-ffff-ffff-fffffffffffffffff] Received request
[Verbose]: [ContextId: ffffffff-ffff-ffff-fffffffffffffffff] Sending response
[Verbose]: [ContextId: ffffffff-ffff-ffff-fffffffffffffffff] Response sent
[Verbose]: [ContextId: ffffffff-ffff-ffff-fffffffffffffffff] Request disposed
[Verbose]: [ContextId: ffffffff-ffff-ffff-fffffffffffffffff] Response disposed
[Verbose]: [ContextId: eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee] Received request
[Verbose]: [ContextId: eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee] Sending response
[Verbose]: [ContextId: eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee] Response sent
[Verbose]: [ContextId: eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee] Request disposed
[Verbose]: [ContextId: eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee] Response disposed
```

I should note that all the `eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee` log entries occurred immediately _after_ `Invoke-WebRequest` timed out, this matches the timeline of behaviour in the packet capture.

**Comment by Viajaz** [comment]
> Do the requests also work normally from any browser as well, or other tools?

Yes.

**Comment by Badgerati** [comment]
Hi @Viajaz,

So the good news is I managed to reproduce the issue. I get the exact same as you, where having the server run in any PS version, but specifically doing `Invoke-WebRequest` from PS5.1, the first request works and the rest hang - and that anything else, be it browser, curl, PS7.2, etc. all work fine.

What's weird is that you can just close the PS5.1 window, open it again, and it works once then hangs - and repeat. Which would point to it being a PS5.1 issue and not Pode (plus the fact that every browser, and PS7.2 works with issue). **BUT**, if you stop the server, close the window, open it again and start the server, low-and-behold the same PS5.1 window that was hanging now works. Which would mean an issue with Pode and not PS5.1. 😖 (plus the fact that HTTPS calls work fine to the likes of google.com, etc.)

I did some extra debugging around the accept/receive sockets, and when the hanging occurs the socket goes into async receive and then never completes until the timeout occurs. Almost as if PS5.1 is connecting but just not sending data. I made Pode forcibly complete the request and it actually works, meaning there is data being sent! (but this isn't a fix, just a hack to test). It's as if PS5.1 is sending data for the receiving socket, but not completing it somehow, or maybe trying to re-use an already completed socket 🤔 

I'll continue debugging; least I've [found the line](https://github.com/Badgerati/Pode/blob/f85d39caa8c3beeb39a9390a22a6011339195b96/src/Listener/PodeSocket.cs#L139) where it "occurs". Just need to find out why 😕

**Comment by Viajaz** [comment]
@Badgerati 
Your experience mirrors mine, the behaviour only lasts the lifetime of the PS5.1 client instance or the server instance.

> meaning there is data being sent!
That's right, refer to the second Wireshark screenshot.

I've sent you an email, let me know if you want troubleshoot together some time.

**Comment by Badgerati** [comment]
Done a bit more testing.

If I force connections in Pode to KeepAlive then `Invoke-Request` in PS5.1 works without hanging. The moment you pass one with `-DisableKeepAlive` then the next request hangs like before. If you cancel, or timeout, that request and then do a POST request with any `-Body`, and then do other requests they all work again.

So it looks like keeping the connections alive "fixes" PS5.1, until you specifically tell Pode to close the connection. It's almost as if PS5.1 doesn't like new connections each time on HTTPS requests 🤔

**Comment by Viajaz** [comment]
Unfortunately, I also occurs without ever using `DisableKeepAlive` with a request within the duration of the Pode server instance lifetime.

**Comment by Viajaz** [comment]
@Badgerati  how'd your fix attempt go?

**Comment by Badgerati** [comment]
Hi @Viajaz, I've not had chance to investigate further. Big events have occurred in my personal life at the moment, but hopefully I'll get time again soon.

**Comment by Badgerati** [comment]
There's a high chance that the changes being made in #1291 will resolve this.
