### ISSUE TITLE
Roadmap - Publish Roadmap and Time-Frame until next release

### ISSUE THREAD

**Issue by jbaechtelMT** [Badgerati/Pode#987]
Roadmap about what new features are being worked on.  And an expected time-frame of next release would also be very helpful so us consumers could get ideas about what is coming and how we could incorporate it into our sites/projects.

Currently it is tedious to see that last releases have been approximately two month apart.  When we come back two months later and find no no release (eagerly waiting), we have to revisit site daily to see if a new release has arrived.

Not criticism, really like the product and it would be great to know when we could have more!

**Comment by Badgerati** [comment]
HI @jbaechtelKoala9126,

To be honest, there isn't really a "roadmap". I work on bugs/suggestions from the community, as well as features I'm playing with on the side - these features do get written up as issues for people to see/comment (like #980) once I have the design down, or know the idea works in general/practice. Plus anything the community contributes as well.

I have a private kanban board full to the brim of ideas I've thought about over the years, and I could write them all up for people to see and comment (maybe even tackle themselves!). But so far as to see what's coming in the next releases, there's never normally a "plan" per say, other than issues labelled with the next milestone.

As for the release schedule: I do try 1 release every 2 months (tossing to-and-fro with Pode.Web). *However*, as per my status update on Twitter/Discord (and my status on GitHub), I've a lot going on in my personal life at the moment that's eating away at my free time. So for a while, releases will be adhoc with no "~2 month schedule".
