### ISSUE TITLE
True User Space for us to Share Projects; Coding; Community Based Help

### ISSUE THREAD

**Issue by jbaechtelMT** [Badgerati/Pode#989]
Would like to share with others and see what they are doing as well as offer my work to help others.

**Comment by RobinBeismann** [comment]
I don't think such thing exists so far. @Badgerati and many other Pode Users are mainly hanging around in slack.
However I can hardly imagine such a platform being utilized actively..

**Comment by Badgerati** [comment]
Hi @jbaechtelKoala9126,

Pode does have a Discord server [here](https://discord.gg/fRqeGcbF6h), where some of the community ask/answer questions and show what they've done. (a `#projects` channel could be cool actually - but I imagine most people build internal tools with Pode that they can't showcase/share).

There's channels for Pode/Pode.Web help specifically, plus an `#ideas` channel for anyone who has a large feature suggestion, but wants to toss the idea out there without raising an issue first.
