### ISSUE TITLE
swagger enabled globally

### ISSUE THREAD

**Issue by ericxin1982** [Badgerati/Pode#991]
### Question
A clear and concise description of your question.
HI @Badgerati 

My coworker asked me to provide swagger definition for api, I have the api written by pode, but I do not know how to enable it globally?

Not sure how to do is best.

Thanks
Eric Xin

**Comment by Badgerati** [comment]
Hi @ericxin1982,

You'll find documentation for Pode's Swagger/OpenAPI support here: https://badgerati.github.io/Pode/Tutorials/OpenAPI/

First you need to enable OpenAPI via:
```powershell
Enable-PodeOpenApi -Title 'My Awesome API' -Version 9.0.0.1
```

And then enable the Swagger OpenAPI viewer:
```powershell
Enable-PodeOpenApiViewer -Type Swagger -Path '/docs/swagger'
```

Going to `http://localhost:8080/docs/swagger` will load a Swagger page (replace localhost:8080 with what ever your endpoint is).

For Route definitions, you'll need to define them on the Routes themselves (as per the docs above).

Hope that helps!

**Comment by ericxin1982** [comment]
Ok, thanks. Let me take a look at the doc, the definition I read before, but not sure whether I need it.
Sorry to ask further, do you have almost real case I can see, if not, I just read example doc to try understanding better.

**Comment by Badgerati** [comment]
There are some examples OpenAPI examples in the `/examples` folder, this might be the better one [here](https://github.com/Badgerati/Pode/blob/develop/examples/web-rest-openapi.ps1).

**Comment by ericxin1982** [comment]
Thanks so much!
