### ISSUE TITLE
Better WebEvent Documentation

### ISSUE THREAD

**Issue by Viajaz** [Badgerati/Pode#993]
### Describe the Change
The documentation for [WebEvent](https://github.com/Badgerati/Pode/blob/master/docs/Tutorials/WebEvent.md) should be more extensive and cover more than just the first depth of the object (Eg: how are those hashtables, like `Route`, structured?)

WebEvent is difficult to debug (https://github.com/Badgerati/Pode/discussions/783) and it's contents can recurse making it difficult to dump.

**Comment by Badgerati** [comment]
Hi @Viajaz,

For objects like the Route, their structure is defined on the [Routes](https://badgerati.github.io/Pode/Tutorials/Routes/Overview/#route-object) page. To prevent duplicating definitions in multiple places, I could add links from the [WebEvent](https://badgerati.github.io/Pode/Tutorials/WebEvent/) page to the relevant pages where the object is defined. Then where possible, for the likes of Request/Response say, we can update the page with their properties.

**Comment by Viajaz** [comment]
Seems like all that might need to be done then is some links to those pages/anchors.
